### ISSUE TITLE
GitHub Pages for Documentation

### ISSUE THREAD

**Issue by jacobherrington** [rbenv/rbenv#1000]
It looks like the gh-pages branch was abandoned. Is this something that should be created going forward? As a user, it feels like the documentation could be presented better and building a page for documentation might be the best way to do that

**Comment by jacob-on-github** [comment]
You can see the abandoned site at rbenv.org.

**Comment by jacob-on-github** [comment]
I will work on this unless I hear otherwise.

**Comment by mislav** [comment]
You're welcome to suggest some documentation. How did you plan to document things?

We would probably want to have said documentation in a separate repo named `rbenv.github.io`. But you're welcome to send a PR for the gh-pages branch in this repo first.

**Comment by jacob-on-github** [comment]
@mislav I plan on porting the readme into an easy to follow "getting started," then look at expanding it to cover rbenv's features.

I'm thinking something Jekyll based, but I'll be sure to get your feedback on the PR.

**Comment by Grizel2202** [comment]
Thanks
