### ISSUE TITLE
Uninstalling rbenv

### ISSUE THREAD

**Issue by deadman2000** [rbenv/rbenv#1007]
I can't uninstall `rbenv` from Debian 8 server.
Readme says "simply remove the `rbenv init` line from your shell startup configuration"
I can't found `rbenv init`. Where is `shell startup configuration`?

**Comment by mislav** [comment]
The "shell startup configuration" files are typically named like this and are in your home directory: `.profile`, `.bashrc`, `.bash_profile`, `.zshrc`, `.zshenv` (depending on the shell that you use). Check them for any mention of "rbenv" and delete only those lines that mention it. After that, and restarting your shell, running `ruby` or any Ruby-related command will not go through rbenv anymore.

Additionally, to eliminate any remains of rbenv installation on your system, you should remove the directory listed by `rbenv root` command (typically this is `~/.rbenv`), and then remove the rbenv package itself if it was installed by a package manager.

I hope all this helps!
