### ISSUE TITLE
Issue getting rbenv to work on MacOS

### ISSUE THREAD

**Issue by chrisoshea** [rbenv/rbenv#1008]
Hi

I have macOS 10.12.4 and having issues getting started with rbenv via homebrew...

`ruby -v`

> ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]

Installed homebrew:
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

`brew -v`

> Homebrew 1.2.3
> Homebrew/homebrew-core (git revision c88f; last commit 2017-06-13)

```
brew install rbenv
rbenv init
rbenv -v
```

> rbenv 1.1.0

```
rbenv install 1.9.3-p551
rbenv versions
```

> system (set by /Users/chrisoshea/.rbenv/version)
>   1.9.3-p551

```
rbenv local 1.9.3-p551
rbenv versions
```

>   system
> * 1.9.3-p551 (set by /Users/chrisoshea/Documents/jekyltest/.ruby-version)

So far so good, this is where the trouble starts...

`gem install bundler`

> ERROR:  While executing gem ... (Gem::FilePermissionError)
>     You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

`which gem`

> /usr/bin/gem

I tried rbenv rehash.

Something weird about my path?
`echo $PATH`

> /Users/chrisoshea/Developer/android-sdk-macosx/platform-tools:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

No mention of rbenv in there. What else should I be trying? Thanks!

**Comment by chrisoshea** [comment]
also

`rbenv init -`

> export PATH="/Users/chrisoshea/.rbenv/shims:${PATH}"
> export RBENV_SHELL=bash
> source '/usr/local/Cellar/rbenv/1.1.0/libexec/../completions/rbenv.bash'
> command rbenv rehash 2>/dev/null
> rbenv() {
>   local command
>   command="$1"
>   if [ "$#" -gt 0 ]; then
>     shift
>   fi
> 
>   case "$command" in
>   rehash|shell)
>     eval "$(rbenv "sh-$command" "$@")";;
>   *)
>     command rbenv "$command" "$@";;
>   esac
> }

**Comment by mislav** [comment]
You're almost there! `rbenv init` gives you instructions about what you should do to configure rbenv for your shell. It doesn't do anything if you just run it and ignore what it says. If you read its output and follow its instructions, you should be good.

**Comment by chrisoshea** [comment]
In the install notes it says: "You'll only ever have to run rbenv init once." Is that once per session, or once ever?

It still isn't working.
```
rbenv init
cd /Users/chrisoshea/Documents/work/jekyltest 
rbenv local 1.9.3-p551
gem install bundler
```

> ERROR:  While executing gem ... (Gem::FilePermissionError)
>     You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

When I run rbenv init, output is:

> # Load rbenv automatically by appending
> # the following to ~/.bash_profile:
> 
> eval "$(rbenv init -)"

So even if I call init each time, or add to bashprofile i'm still going to get the above permission error.

Confused by the instructions, thanks.

**Comment by chrisoshea** [comment]
Looks like they had the same issue, it isnt clear that you need to add this to your bash_profile, maybe update the readme?

https://github.com/rbenv/rbenv/issues/815

by adding that line to bash_profile, rbenv is now in my PATH and installing gem works.

**Comment by mislav** [comment]
I'm glad you got it solved. The output of `rbenv init` says:

> Load rbenv automatically by appending the following to `~/.bash_profile`

and the line to put in your `.bash_profile` is the following:

```sh
eval "$(rbenv init -)"
```

and by doing exactly that, and restarting the shell, your shell is now configured for rbenv.

What should be made clearer in this process?

**Comment by chrisoshea** [comment]
I think my confusion (and that other post) is that the [docs](https://github.com/rbenv/rbenv#homebrew-on-mac-os-x) say: "You'll only ever have to run rbenv init once."

Does that mean each time on terminal, or only once during install? That was the confusion. Maybe it should say a requirement is to add it to your bash_profile or something.

Thanks

**Comment by jeremy** [comment]
@chrisoshea, updated docs @ #1009

**Comment by fotocell7** [comment]
> and the line to put in your .bash_profile is the following:

How do you do that?

**Comment by edamamegreen** [comment]
I was quite stuck for a while until I realized that `rbenv init` simply prints instructions and will always print the same instructions. (Please correct me if that's not true.)

I mistakenly expected the output of `rbenv init` to change after I had correctly added `eval "$(rbenv init -)"` to the `.bash_profile`.

Instead of trying `rbenv init` again, I needed to move on to the next steps in the readme instructions to confirm that I had completed the `rbenv init` step correctly.

I'm adding this note in case someone else reads above and is still stuck for the same reason.

**Comment by thomasabishop** [comment]
@edamamegreen thank you for taking the trouble to record the above, I was stuck until I read it.  To reiterate for future readers, `rbenv init` will always output the same thing even once it is fully functional and the problem above is solved. You can check that it has worked by running the following command in terminal:

`curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash`

Once you have added rbenv to your path, the above command will confirm with the following output:

`Checking for `rbenv' in PATH: /usr/local/bin/rbenv
Checking for rbenv shims in PATH: OK`

**Comment by hernamesbarbara** [comment]
> I'm adding this note in case someone else reads above and is still stuck for the same reason.

Thank you
