### ISSUE TITLE
fish 2.6.0, setenv: Too many arguments

### ISSUE THREAD

**Issue by therealmarv** [rbenv/rbenv#1010]
Getting following error since 3-4 days in my fish shell 2.6.0 when opening a terminal (macOS Sierra 10.12.5)

```
setenv: Too many arguments
```

rbenv does not work anymore. My config.fish rbenv line:
```
status --is-interactive; and . (rbenv init -|psub)
```

Workaround I use right now is a fisherman plugin https://github.com/fisherman/rbenv which seems to work but would be better if fixed in rbenv itself too.

**Comment by anateus** [comment]
The fix I applied locally is convert usage of `setenv` to `set -gx` (which it previously was presented as a wrapper for, but is actually meant to replicate `setenv` from `csh`.

**Comment by mislav** [comment]
This was fixed in https://github.com/rbenv/rbenv/pull/986/files and will be available through Homebrew when https://github.com/Homebrew/homebrew-core/pull/14627 gets merged.

Meanwhile, you can use `brew install rbenv --HEAD` to install the latest version of rbenv through git.
