### ISSUE TITLE
Fish shell 2.6.0 causes rbenv init to say: env too many args

### ISSUE THREAD

**Issue by sunapi386** [rbenv/rbenv#1012]
For fish shell 2.6.0 users, when `source (rbenv init -|psub)` is used, as part of `status --is-interactive; and source (rbenv init -|psub)`, fish shell says `setenv: Too many arguments`.

I updated fish shell from 2.5.0 to 2.6.0, and it was fine before.

```
jason@jmbp15-nvidia ~ > source (rbenv init -|psub)
setenv: Too many arguments
jason@jmbp15-nvidia ~> fish -v
fish, version 2.6.0
```

**Comment by mislav** [comment]
Sorry for the trouble! This was fixed in the latest release of rbenv. https://github.com/rbenv/rbenv/releases/tag/v1.1.1
