### ISSUE TITLE
Bundler not seeing rbenv installed ruby.

### ISSUE THREAD

**Issue by ENG618** [rbenv/rbenv#1014]
`rbenv version` returns:
`2.4.1 (set by /Users/engarcia/.rbenv/version)`

Running `bundle install` gets the following error:
```
Gem::InstallError: nokogiri requires Ruby version >= 2.1.0.
An error occurred while installing nokogiri (1.8.0), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.8.0'` succeeds before bundling.
```

**Comment by ENG618** [comment]
I've looked at #831 also and tried those suggestions (blow out shims) and had no success.

**Comment by ivanm376** [comment]
Fix for Linux:
https://github.com/flapjack/omnibus-flapjack/issues/72#issuecomment-157908599

**Comment by mislav** [comment]
Sorry, this doesn't sound like a bug with rbenv. Rbenv merely switches between Ruby versions. Gem installation issues are their own problem and not something rbenv affects at all.
