### ISSUE TITLE
Issue with - rbenv: rails: command not found

### ISSUE THREAD

**Issue by nguyenhuuphuc83** [rbenv/rbenv#1023]
Hi all,

I tried to update Ruby 2.4.1 and Rails 5.1.3 but the terminal showed the following message:

Nguyens-MacBook-Pro:~ nhp$ rails --version
rbenv: rails: command not found

The `rails' command exists in these Ruby versions:
  2.2.1

Could you please explain what is this and how to fix it?

Thanks,

**Comment by voloyev** [comment]
Hi, have you tried to install rails gem?  ```gem install rails```?

**Comment by shrmnlt** [comment]
Hi @nguyenhuuphuc83 , have you tried to `rbenv rehash` after installing `rails` gem?

**Comment by mislav** [comment]
The above comments should have helped to solve the issue. 👍
