### ISSUE TITLE
Request: command for executing gem with Ruby version specified inline

### ISSUE THREAD

**Issue by henrebotha** [rbenv/rbenv#1025]
I recently installed tmuxinator, which is a command line utility. It's meant to be usable from anywhere. However, due to how rbenv works, I can't execute tmuxinator when my current rbenv version doesn't match the version tmuxinator was installed under.

What I want is a command that will let me execute tmuxinator under any Ruby version, by specifying the version inline:

```
rbenv exec-with 2.3.4 tmuxinator
```

Something like that.

**Comment by mislav** [comment]
This will do the trick: `RBENV_VERSION=2.3.4 tmuxinator`
