### ISSUE TITLE
Have optoins for finetuning rbenv init

### ISSUE THREAD

**Issue by marcthe12** [rbenv/rbenv#1026]
A rbenv init does for 4 different things. Can it be possible to do all 4 seperately. For example some people like me want set up path only once, so .profile should be used. But rbenv shell functions have to be in .*rc file.

**Comment by mislav** [comment]
You don't have to use `rbenv init` at all; it's entirely optional. You only need to manually prepend `~/.rbenv/shims` to the PATH if you're going to skip the `rbenv init` step.
