### ISSUE TITLE
Error installing Ruby 2.4.1 in Ubuntu 16.04

### ISSUE THREAD

**Issue by egroJ97** [rbenv/rbenv#1029]
egroj97@SmallFootIV:~$ rbenv install 2.4.1 
Downloading ruby-2.4.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.1.tar.bz2
error: failed to download ruby-2.4.1.tar.bz2

BUILD FAILED (Ubuntu 16.04 using ruby-build 20170726-7-g16aa672)

Inspect or clean up the working tree at /tmp/ruby-build.20170824222614.7964
Results logged to /tmp/ruby-build.20170824222614.7964.log

Last 10 log lines:
/tmp/ruby-build.20170824222614.7964 ~
curl: (56) GnuTLS recv error (-9): A TLS packet with unexpected length was received.

**Comment by hsbt** [comment]
It seems network or your environment issue. Please check your laptop or network.
