### ISSUE TITLE
Error exec $SHELL on elementaryos

### ISSUE THREAD

**Issue by sgnd** [rbenv/rbenv#1031]
![screenshot from 2017-08-28 14-24-29](https://user-images.githubusercontent.com/15070585/29763305-c7698d84-8bfc-11e7-9185-7c49ac05f0b6.png)

i am elementary user, i want to install rbenv with this tutorial https://gorails.com/setup/ubuntu/16.04
but if i run exec $SHELL, error like this:
suganda@toshiba:~$ exec $SHELL
bash: /home/suganda/.bashrc: line 171: syntax error near unexpected token `PATH="$HOME/.rbenv/bin:$PATH"'
bash: /home/suganda/.bashrc: line 171: `esacexport PATH="$HOME/.rbenv/bin:$PATH"'

how to fix this?

**Comment by znz** [comment]
Add a newline between `asac` and `export`.
I think your `.bashrc` did not have final newline before `echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc`.

**Comment by sugandaaa** [comment]
ok, thank you. works!

**Comment by blueyed** [comment]
This can be closed.

**Comment by davide-guerra** [comment]
Sorry, I've the same problem but I don't understand which modification should I make in the .bashrc file.
