### ISSUE TITLE
Path error with spacemacs and ruby

### ISSUE THREAD

**Issue by abhi18av** [rbenv/rbenv#1032]
Hi everyone,

I was trying to use the `spacemacs` distribution with `ruby layer` installed but it doesn't seem to be able to sense the path.

However, within the `bash` shell it seems to work fine.

```sh
eklavya@neanderthal:~$ rbenv versions
* 2.3.3 (set by /home/eklavya/.rbenv/version)
  jruby-9.1.12.0
```

The `spacemacs` settings of the `ruby-layer` are 

```elisp
     (ruby :variables
           ruby-version-manager 'rbenv
           ruby-enable-enh-ruby-mode t
           ruby-test-runner 'rspec)
```

But when I try to open any ruby fiile it does nothing, 

![screenshot from 2017-08-29 15-55-06](https://user-images.githubusercontent.com/12799326/29816667-90ec91c6-8cd2-11e7-9e58-750948b07ff4.png)

Perhaps, it might be important to know what `eshell` says about it all

```sh
Welcome to the Emacs shell

~ λ rbenv
rbenv: command not found
~ λ rbenv --version
rbenv: command not found
~ λ rbenv-use-global 
[rbenv] using 2.3.3
~ λ 

```

**Comment by abhi18av** [comment]
The error that's displayed in the mini-buffer is 

```

File mode specification error: (file-error Searching for program No such file or directory ruby)

```

**Comment by mislav** [comment]
`rbenv: command not found` indicates to me that the PATH isn't properly set up within Emacs. The PATH should include `$HOME/.rbenv/bin` so that rbenv is properly discovered. It already seems set up properly in your shell.
