### ISSUE TITLE
There is no way to change the active version of Ruby

### ISSUE THREAD

**Issue by jameshfisher** [rbenv/rbenv#1037]
```
$ rbenv versions
* system (set by /Users/jim/.rbenv/version)
  2.0.0
  2.0.0-p648
  2.2
  2.2.4
  2.3
  2.3.0
  2.3.3
```

I want to set the active (asterisked) version to `2.3.3`. However nothing in https://github.com/rbenv/rbenv tells me how to do that

**Comment by jeremy** [comment]
[rbenv global](https://github.com/rbenv/rbenv#rbenv-global) has your back:
```bash
$ rbenv global 2.3.3
```

https://github.com/rbenv/rbenv#choosing-the-ruby-version
> The global ~/.rbenv/version file. You can modify this file using the rbenv global command. If the global version file is not present, rbenv assumes you want to use the "system" Ruby—i.e. whatever version would be run if rbenv weren't in your path.
