### ISSUE TITLE
Ruby 2.4.2 on rbenv? 

### ISSUE THREAD

**Issue by ankitrg** [rbenv/rbenv#1039]
I am not able to see Ruby 2.4.2 when doing `rbenv install 2.4.2` does it takes some time to be available via rbenv?

**Comment by hsbt** [comment]
Can you confirm to use latest version of ruby-build? It's different project from rbenv.

**Comment by janklimo** [comment]
I can confirm that solved my problem. 

Error message before:

```
ruby-build: definition not found: 2.4.2

See all available versions with `rbenv install --list'.

If the version you need is missing, try upgrading ruby-build:

  cd /Users/Admin/.rbenv/plugins/ruby-build && git pull && cd -
```

Running the suggested command did the trick 👍

**Comment by jobwat** [comment]
MacOS / brew:
```
brew upgrade ruby-build && rbenv install 2.4.2
```
