### ISSUE TITLE
Can't install older ruby versions (ie 1.8.7) 

### ISSUE THREAD

**Issue by cmendla** [rbenv/rbenv#1040]
I am trying to install ruby 1.8.7 on an ubuntu 16.04 LTS machine. I can install newer versions such as 2.4.2. However, when I tried to install an older version such as 1.8.7 (which I need), I get 
------------------------------------------------------------------------------
```
chris@chris-VirtualBox:~/.ssh$ rbenv install 1.8.7
Downloading ruby-1.8.7.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/1.8/ruby-1.8.7.tar.bz2
Installing ruby-1.8.7...

WARNING: ruby-1.8.7 is past its end of life and is now unsupported.
It no longer receives bug fixes or critical security updates.


BUILD FAILED (Ubuntu 16.04 using ruby-build 20170914-2-ge40cd1f)

Inspect or clean up the working tree at /tmp/ruby-build.20170929125827.4276
Results logged to /tmp/ruby-build.20170929125827.4276.log

Last 10 log lines:
                      ^
ossl.c:119:1: note: in expansion of macro ‘OSSL_IMPL_SK2ARY’
 OSSL_IMPL_SK2ARY(x509crl, X509_CRL)
 ^
Makefile:188: recipe for target 'ossl.o' failed
make[1]: *** [ossl.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/tmp/ruby-build.20170929125827.4276/ruby-1.8.7/ext/openssl'
Makefile:285: recipe for target 'all' failed
make: *** [all] Error 1
```
---------------------------------------------------------------------------------------

I understand that there is an issue with openssl not being compatible with RBENV and earlier versions of  ruby. I did install libssl-dev but that didn't help. 

Is there any way to get 1.8.7 installed on my system using rbenv? 

Open ssl version

```
chris@chris-VirtualBox:~/.ssh$ apt-cache policy openssl
openssl:
  Installed: 1.0.2g-1ubuntu4.8
  Candidate: 1.0.2g-1ubuntu4.8
  Version table:
```

Libssl version

```
chris@chris-VirtualBox:~/.ssh$ apt-cache policy openssl
openssl:
  Installed: 1.0.2g-1ubuntu4.8
  Candidate: 1.0.2g-1ubuntu4.8
  Version table:
```

**Comment by mislav** [comment]
This is a question more suitable for https://github.com/sstephenson/ruby-build/issues, since that project is what builds Ruby, not rbenv itself.

However, we can't help you here. Old Ruby versions are usually not installable on newer systems because of a growing number of compatibilities with system dependencies. You might find someone who has patches for Ruby 1.8.7 to install on your system, but we can't provide support for that. Good luck!
