### ISSUE TITLE
Rails generator not working with Ruby v2.4.2 using RBenv

### ISSUE THREAD

**Issue by ltfschoen** [rbenv/rbenv#1043]
When I switch to Ruby version 2.4.2 using RBEnv (i.e. `rbenv global 2.4.2`) and try and use Rails to generate a Controller (i.e. `rails generate controller StaticPages home help`), it does not generate anything, whereas when I use RBEnv to switch back to a previous version of Ruby like 2.4.1 (i.e. `rbenv global 2.4.1`), it will generate the files 

System:
* RubyGems 2.6.11
* RBEnv 1.1.1 with Ruby version 2.4.2

**Comment by hersha** [comment]
Are you on High Sierra? It ships with 2.4.2 and it seems to be causing issues with switching to an rbenv managed 2.4.2. Run `rbenv which ruby` and see what the actual path is. When I run `rbenv global 2.4.2` it just sets it to system ruby even though i have 2.4.2 installed through rbenv.

**Comment by mislav** [comment]
Sorry, this doesn't sound like a bug with rbenv! Rbenv only switches between versions and dispatches the `rails` call to the appropriate Ruby version. What happens after that (and any subsequent failure) is likely not a problem with rbenv, but within the `rails` executable of that Ruby version.
