### ISSUE TITLE
Issue when appending to ~/.bash_profile

### ISSUE THREAD

**Issue by Tjobbe** [rbenv/rbenv#1044]
`rbenv init
Load rbenv automatically by appending
the following to ~/.bash_profile:
eval "$(rbenv init -)"`

ok, so I then do:

`open ~/.bash_profile`

and I then change my existing file:
` [[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*eval "$(rbenv init -)" `

To:
` [[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*eval "$(rbenv init -)" `

But I'm still getting that message on rbenv init? What am I doing wrong?

**Comment by Hikari9** [comment]
In the first place, `rbenv init` simply shows the instructions. It is `eval "$(rbenv init -)"` that actually does the task. I don't think there is any problem related with the issue.
-

**Comment by mislav** [comment]
You seem to be using RVM and rbenv at the same time. Please uninstall one and use just the other, because two at the same time will clash.
