### ISSUE TITLE
Add Ruby 2.3.5 to rbenv list 

### ISSUE THREAD

**Issue by solidstate-tech** [rbenv/rbenv#1046]
Steps to reproduce:
1. rbenv install --list
You'll find that there is no version 2.3.5

**Comment by solidstate-tech** [comment]
Steps to reproduce:
1. rbenv install --list

**Comment by hsbt** [comment]
I couldn't reproduce it.

```
> rbenv install --list | grep 2.3.5
  2.3.5
```

Please update latest version of ruby-build.

**Comment by solidstate-tech** [comment]
Thank you I fixed this by running 
` brew update && brew upgrade ruby-build`
