### ISSUE TITLE
Linked version blocking installation / Permission denied @ unlink_internal

### ISSUE THREAD

**Issue by dreyershelby** [rbenv/rbenv#1050]
_MAC VER: High Sierra 10.13.1_

I am unable to download/upgrade dependencies needed for rbenv, specifically `pkg-config`, which is halting the installation.

Initial installation:

```
$ brew install rbenv
==> Installing dependencies for rbenv: pkg-config, ruby-build
Error: Cannot link pkg-config
Another version is already linked: /usr/local/Cellar/pkg-config/0.29
```

A question: If another version is already linked, then why can I not install rbenv?

Anyways, I tried upgrading pkg-config to see if that was the problem, however it gave me an error, saying `Error: Permission denied @ unlink_internal - /usr/local/share/aclocal/pkg.m4`.

In context:

```
$ brew upgrade pkg-config
==> Upgrading 1 outdated package, with result:
pkg-config 0.29.2
==> Upgrading pkg-config 
Error: Permission denied @ unlink_internal - /usr/local/share/aclocal/pkg.m4
```

What should I do in order to install and use rbenv?

**Comment by mislav** [comment]
Try `sudo rm /usr/local/share/aclocal/pkg.m4`, then repeat the `brew upgrade ...` command.

Future questions about Homebrew should go to their issue tracker, not this one. This is a place for only problems directly related to rbenv.
