### ISSUE TITLE
Confusing ruby dependencies

### ISSUE THREAD

**Issue by hel-ableton** [rbenv/rbenv#1054]
I installed `rbenv` on OSX, installed `ruby 2.4.2` via it, "activated" it, and then tried to `gem install jekyll bundler`. I got notified that `ruby >= 2.1` was required:

```shell
$ rbenv versions
  system
* 2.4.2 (set by /Users/hel/.ruby-version)
 
$ rbenv which gem
/Users/hel/.rbenv/versions/2.4.2/bin/gem
 
$ gem install jekyll bundler
ERROR:  Error installing jekyll:
	public_suffix requires Ruby version >= 2.1.
Successfully installed bundler-1.16.0
Parsing documentation for bundler-1.16.0
1 gem installed
``` 

This was really puzzling, since I thought I was now "shimming" everything to `2.4.2`, and wasn't that the whole point of using `rbenv`? Only after I `brew installed ruby` (which probably installed yet another ruby instance on my machine?) could I successfully run `gem install`.

**Comment by mislav** [comment]
`gem` only gets routed through rbenv if you've completed your rbenv installation and added "shims" to the PATH. What is your `echo $PATH`? Does it include the `/Users/hel/.rbenv/shims` directory? Do you have any rbenv plugins?

**Comment by hel-ableton** [comment]
Hi Mislav, thank you for your quick reply. I was in fact missing the shims directory. What confused me was that after what I described to you, I was able to `gem install jekyll`, and it worked. And hadn't before since I don't have write permissions in my system ruby, which caused me to use rbenv in the first place.

Now I thought I was done, but then it turned out in my next session, jekyll wasn't found. Now I added the shims dir, ran `gem install jekyll` again, and now I have in fact a neat list of executables in that shims directory. I think I'm set now. Maybe in your "Understanding shims" section, you could add a word about the fact that binaries will actually get placed there? I was missing that bit of information.

Anyway, thanks a lot for your help!
Henrik

**Comment by mislav** [comment]
Thanks for the update! Please close your issues after they're no longer issues. 🙇

**Comment by hel-ableton** [comment]
Oh, sorry. My bad. Happy new year!
