### ISSUE TITLE
Rbenv line endings in linux

### ISSUE THREAD

**Issue by augur97** [rbenv/rbenv#1060]
Hi.
I'm having problems with the scripts in a linux system (Linux Mint 18.3) after updating to the latest version due to the Windows line endings.
I have used dos2unix and it solved the problem.
Thank you.
Augur97

**Comment by mislav** [comment]
Thanks for sharing your workaround. See https://github.com/rbenv/rbenv/issues/541#issuecomment-33694270 for more tips how to deal with line endings. Check your configuration to see if by chance your git is configured to clone new repositories using Windows line endings instead of Unix ones.
