### ISSUE TITLE
Should `rbenv version` return failure code when desired version not installed?

### ISSUE THREAD

**Issue by jasonkarns** [rbenv/rbenv#1061]
AFAIK, there isn't a clean way to detect when the desired ruby version is not installed. `rbenv version` prints a warning to STDERR, but I think that's it.

Should rbenv-version be returning a failure status code when the version isn't installed? Or perhaps add this functionality behind an option so as to not be a breaking change?

I could start on a PR if this is acceptable.

**Comment by airtonix** [comment]
two years later...

**Comment by mislav** [comment]
@jasonkarns I'm open to this if you wanted to revisit it! Ref. https://github.com/rbenv/rbenv/issues/1318

**Comment by mislav** [comment]
I'm now in the process of closing stale issues and I want to avoid introducing feature changes to rbenv unless absolutely necessary. This doesn't feel very pressing to me, so I'm going to close this. Thank you for the suggestion!
