### ISSUE TITLE
multiple rbenv in PATH

### ISSUE THREAD

**Issue by cloudyghost** [rbenv/rbenv#1062]
Hi, new to shell.
I get the following when i run the doc script
```
Checking for `rbenv' in PATH: multiple
  You seem to have multiple rbenv installs in the following locations.
  Please pick just one installation and remove the others.
  
  /Users/username/.rbenv/bin/rbenv
  /usr/local/bin/rbenv
```
I ran: `sudo pico /etc/paths`
to add and remove items on PATH on macOS High Sierra, but i don't see neither PATHS on the list.
However, they both show up when I run: `echo $PATH`
Bottom line: how do I pick one install and remove the others as suggested?

**Comment by viclim** [comment]
@cloudyghost 

Can you run the following command and show us the output?
```sh
ls -l /usr/local/bin/rbenv
```

**Comment by idelfonsog2** [comment]
/usr/local/bin/rbenv-install -> ../Cellar/ruby-build/20180224/bin/rbenv-install

**Comment by mislav** [comment]
@cloudyghost @idelfonsog2 You seem have installed rbenv both using direct clone from git method (directly into `~/.rbenv`) and from Homebrew. I recommend that you pick the one from Homebrew and delete the other one.

Here is how to delete the rbenv installation from git located in `~/.rbenv/bin/rbenv`:

```sh
cd ~/.rbenv
git ls-files | xargs rm
find . -type d -depth 2 -empty -delete
rm -rf .git
```

Then, locate where you've configured rbenv in your shell initialization files. This depends on your shell, but is most likely in `~/.bash_profile`. Find it out with:

```sh
grep -i rbenv ~/.* 2>/dev/null
```

You should **keep** the lines that mention `rbenv init`, but delete configurations that adds `~/.rbenv/bin/` to PATH:

```sh
# remove such line:
export PATH=~/.rbenv/bin:"$PATH"
```

**Comment by kapso** [comment]
I am getting the same issue, but this is on a new mac and I just ran `brew install rbenv`

Should this happen for a fresh new installation?

```
$ curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
Checking for `rbenv' in PATH: multiple
  You seem to have multiple rbenv installs in the following locations.
  Please pick just one installation and remove the others.
  
  /usr/local/opt/rbenv/bin/rbenv
  /usr/local/bin/rbenv

Checking for rbenv shims in PATH: OK
Checking `rbenv install' support: /usr/local/bin/rbenv-install (ruby-build 20180618)
Counting installed Ruby versions: 1 versions
Checking RubyGems settings: OK
Auditing installed plugins: OK
```

**Comment by martyro** [comment]
I get this error now after attempting fresh installs multiple times, but whatever I do, I can't escape the multiple paths, leading me to believe I have some sort of plugin like Kapso mentioned over here. However, I use normal terminal and my Ubuntu install is veeery fresh, so I don't see what it could be. 
Here's the output:

Checking for `rbenv' in PATH: multiple
  You seem to have multiple rbenv installs in the following locations.
  Please pick just one installation and remove the others.
  
  /usr/bin/rbenv
  /bin/rbenv

Checking for rbenv shims in PATH: not found
  The directory `/home/martin/.rbenv/shims' must be present in PATH for rbenv to work.
  Please run `rbenv init' and follow the instructions.

Checking `rbenv install' support: not found
Unless you plan to add Ruby versions manually, you should install ruby-build.
Please refer to https://github.com/rbenv/ruby-build#installation

Counting installed Ruby versions: none
  There aren't any Ruby versions installed under `/home/martin/.rbenv/versions'.
  You can install Ruby versions like so: rbenv install 2.2.4
Checking RubyGems settings: OK
Auditing installed plugins: OK

**Comment by manach** [comment]
I got the same error running a fresh install on Ubuntu 20.04.

**Comment by manach** [comment]
@martyro thanks!

**Comment by wbender-wurl** [comment]
For my case with Ubuntu, `/bin` is just a symbolic link to `/usr/bin` where **rbenv** is installed.
```
$ ls -liad /bin /usr/bin
      13 lrwxrwxrwx 1 root root     7 Jun 10 16:54 /bin -> usr/bin
40370178 drwxr-xr-x 2 root root 53248 Jul 27 10:45 /usr/bin
```

**Comment by mislav** [comment]
@wbender-wurl This is being tracked in https://github.com/rbenv/rbenv-installer/issues/35

**Comment by DavitTec** [comment]
I know the issue is closed but ..
I fixed the **"Checking for `rbenv' in PATH: multiple"**

by pointing explicitly to a local **.rbenv/libexec** and not the **.rbenv/bin** 
```
export PATH="$HOME/.rbenv/libexec:$PATH"
export PATH="$HOME/.rbenv/shims:$PATH"
```
the  **rbenv** is a link file in .rbenv/bin  to shellscript(s) in .rbenv/libexec

I also pulled https://github.com/rbenv/rbenv-installer/raw/main/bin/rbenv-doctor script into the
**.rbenv/libexec** 

so I could run

```bash
rbenv doctor
```
_NOTE: no dash_
