### ISSUE TITLE
Add ruby 2.5.0 stable

### ISSUE THREAD

**Issue by calebmeyer** [rbenv/rbenv#1063]
I didn't see any open issues for this when I searched.

Ruby 2.5.0 stable [was released](https://www.ruby-lang.org/en/news/2017/12/25/ruby-2-5-0-released/) 3 weeks ago. I'm not sure what goes into adding a new ruby version, but work has asked that I use 2.5.0 for our rails 5 upgrade.

Please make 2.5.0 stable available so I can use rbenv again. I've had to switch to rvm in the meantime, and it's super slow on WSL.

**Comment by jeremy** [comment]
2.5.0 was [added to ruby-build](https://github.com/rbenv/ruby-build/commit/a97a13859eaff666836c7992e41fbcac36f264c1) as soon as it was released.

**Comment by calebmeyer** [comment]
I did the update instructions for rbenv, do I also need to update ruby-build to see the latest?

**Comment by jeremy** [comment]
Yep: https://github.com/rbenv/ruby-build#upgrading

**Comment by calebmeyer** [comment]
Thanks for the quick response. Installing as we speak.
