### ISSUE TITLE
Feature request: rbenv as a snap

### ISSUE THREAD

**Issue by sahilarora535** [rbenv/rbenv#1064]
It would be great if it is possible to have `rbenv` available as a snap on snapcraft. This would simplify installation, updates, etc. 
This would also make it easier for issues such as https://github.com/rbenv/rbenv/issues/691 and https://github.com/rbenv/rbenv/issues/301 to be resolved.

**Comment by mislav** [comment]
I'm not familiar with snaps. I welcome contributions and pointers how to set up rbenv to be published as a snap automatically via CI on every tagged version.

**Comment by sahilarora535** [comment]
@mislav 
Apologies for the delay. Here is a link which may help with triggering a snap via CI: <https://docs.snapcraft.io/build-snaps/ci-integration> 

Also, though I am not very versed with snaps myself, I am not sure if `rbenv` particularly can be installed as a snap since it sets some variables in the shell. If snap allows this, it would work like a charm and simplify a lot of things.

**Comment by mislav** [comment]
Thanks for the resources! Since then I've learned more about Snap and concluded that containerization is not a good fit for this project.
