### ISSUE TITLE
`rbenv version-name > .ruby-version` write `system` to file instead of current version

### ISSUE THREAD

**Issue by ayqazi** [rbenv/rbenv#1065]
My current global Ruby version is 2.5.0
```
rbenv version
=> 2.5.0 (set by /home/xxxx/.rbenv/version)

rbenv version-name
=> 2.5.0
```

However when I try to redirect that to a file, it outputs `system`!
```
rbenv version-name > .ruby-version
cat .ruby-version
=> system
```

This seems wrong.......

I'm currently on the master branch of rbenv. Commit ID as of now is `b943955dbf10c436a8d4c7c36fd4216a34ef2b33`.

Thanks

**Comment by viclim** [comment]
@ayqazi 

I created a [PR](https://github.com/rbenv/rbenv/pull/1069) to address the issue you're having.

In the meantime, use the builtin method instead.
```sh
rbenv local $(rbenv version-name)
# or simply
rbenv local 2.5.0
```
