### ISSUE TITLE
Debian stretch package out of date

### ISSUE THREAD

**Issue by 0xmachos** [rbenv/rbenv#1068]
The `apt` package for Debian 9 stretch is currently version `1.0.0-1` which was released in December 2015. 

Can you update the `apt` package please?

`apt-cache show rbenv` indicates that the package maintainer is `Debian Ruby Extra Maintainers` contactable at pkg-ruby-extras-maintainers@lists.alioth.debian.org. 

I'm unsure if I should be asking here or emailing the `apt` listed maintainer?

**Comment by 0xmachos** [comment]
I've also just discovered that the `apt` package does not install `ruby-build` which is required to actually install new versions of Ruby. 

Is it possible for this to be bundled with the `apt` package?

**Comment by znz** [comment]
If you say about rbenv package of Debian, you can request as wishlist bug to <https://bugs.debian.org/rbenv>.

**Comment by mislav** [comment]
Sorry, I do not maintain the Debian package for rbenv. You will have to reach out to those who have initially set it up.
