### ISSUE TITLE
Cannot install or update Ruby gems.

### ISSUE THREAD

**Issue by BonnieEllen** [rbenv/rbenv#1070]
I have followed all the instructions that i can find on how to "point" to the version of ruby that I want to update but nothing has worked.  When I type in "ruby -v" I get back version 2.3.3 but when I use rbenv to update the gems or add a gem I get the "do not have permission to write" error.  I am a complete beginner with Max OS and Ruby and I would really appreciate help resolving this issue.  I can't even tell which gems are already installed.  Help!

**Comment by tofifee** [comment]
@BonnieEllen 

Hi there

You need to put `sudo` in front of your command. It is a permission issue. For certain system wide things you need the superuser privileges which you get by prefixing `sudo` aka "superuser do".

You will be asked for your password. Just enter it and hit return.

Think of it like an authentication process by the operating system that the person at the keyboard is still the same user - thus knowing the users password - and not someone else trying to do something they shouldn't with your computer ;)

**Comment by mislav** [comment]
With rbenv, you don't have to ever use `sudo`. In fact, using `sudo` when installing Ruby versions or gems can be harmful.

@BonnieEllen Sorry that your original question didn't get timely attention. I hope that, by now, you've  somehow got up & running? This sounds like an installation issue and not a bug with rbenv. You can use the `rbenv-doctor` tool to help debug your problems: https://github.com/rbenv/rbenv-installer#rbenv-doctor
