### ISSUE TITLE
Ruby 2.3.1 build failed on macOS Sierra 10.12.6

### ISSUE THREAD

**Issue by mulev** [rbenv/rbenv#1071]
Hi,

I'm experiencing some problems with installing ruby 2.3.1 with `rbenv install 2.3.1` on my mac.
Here's what I got:

```
➜ ✗ rbenv install 2.3.1
ruby-build: use openssl from homebrew
Downloading ruby-2.3.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.bz2
Installing ruby-2.3.1...
ruby-build: use readline from homebrew

BUILD FAILED (OS X 10.12.6 using ruby-build 20180224)

Inspect or clean up the working tree at /var/folders/2j/w65h0s153rbb_0sj6dnw819h0000gn/T/ruby-build.20180320125007.29598
Results logged to /var/folders/2j/w65h0s153rbb_0sj6dnw819h0000gn/T/ruby-build.20180320125007.29598.log

Last 10 log lines:
      _main in main.o
  "_ruby_run_node", referenced from:
      _main in main.o
  "_ruby_sysinit", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libruby-static.a] Error 1
make: *** Waiting for unfinished jobs....
transdb.h updated
```

Full log: https://pastebin.com/Hw19EeEK

**Comment by atomhax** [comment]
Same issue here

**Comment by mislav** [comment]
It looks like you're having problems with ruby-build, which is the plugin that provides `rbenv-install`.

1. First, [ensure that ruby-build](https://github.com/rbenv/ruby-build/wiki#updating-ruby-build) is updated to the latest version.
2. If your problem persists, [check existing issues](https://github.com/sstephenson/ruby-build/issues) in the ruby-build repo and open a new one if necessary. When opening a new issue, please attach the full build log.
