### ISSUE TITLE
missing value for RBENV_HO�G�

### ISSUE THREAD

**Issue by sekrett** [rbenv/rbenv#1072]
I am receiving this error message:

`/libexec/ld-elf.so.1: environment corrupt; missing value for RBENV_HO�G�`

when running (for example) `system('sudo id')` from Rails console.

I have FreeBSD 10.4, Rails 4.2.10, Rbenv 1.0.0, Ruby 2.4.2.

It runs without error if I either:

- remove `sudo`
- run on FreeBSD 10.3, Rails 4.2.7.1, Rbenv 1.0.0, Ruby 2.2.5
- run on irb without Rails
- add ENV manually: `system('RBENV_HOOK_PATH=/usr/local/rbenv/rbenv.d && sudo id')`

Sorry, I have no idea of why it happens. Any help?

**Comment by mislav** [comment]
Sorry, I have no idea what `/libexec/ld-elf.so` is. This error is most definitely not coming from rbenv, but from some plugin or script that you have installed on your system.
