### ISSUE TITLE
SublimeREPL cant start ruby with rbenv

### ISSUE THREAD

**Issue by choallin** [rbenv/rbenv#1073]
I'm using Sublime as my editor. 
Recently I found the plugin SublimeREPL that would give me a REPL inside my editor. I have configured it like this:

`
{
  "default_extend_env": {
    "PATH": "{HOME}/.rbenv/shims/:/usr/local/bin:{PATH}"
  }
}
`

After starting it, I get this error message:
`/home/user/.rbenv/libexec/rbenv-exec: Zeile 47: /home/user/.rbenv/shims/ruby: Die Argumentliste ist zu lang (Argumentlist is to long)
`
I did take a look inside the rbenv-exec file to see what the command is and what the arguments are. This is the command
` 
exec -a "$RBENV_COMMAND" "$RBENV_COMMAND_PATH" "$@"
`

where 
$RBENV_COMMAND is `"ruby"`,
$RBENV_COMMAND_PATH is `"/home/user/.rbenv/shims/ruby"` and
$@ is `"/home/user/.config/sublime-text-3/Packages/SublimeREPL/config/Ruby/pry_repl.rb subl -w" `

Now, I'm not 100% sure that it is an rbenv problem, but since the repl crahes before the pry_repl file is called I suppose so.

**Comment by blueyed** [comment]
What OS and shell are you using?

Can you run the command there manually?
How long is your "user" part?

**Comment by mislav** [comment]
Closing due to lack of info and because this is most likely a Sublime configuration issue. It seems like you've correctly configured PATH for executing commands or the REPL from within Sublime, so rbenv should have effect.
