### ISSUE TITLE
I can install only one ruby version

### ISSUE THREAD

**Issue by boyanpn** [rbenv/rbenv#1077]
I have installed rbenv following instructions from github. First thing after that, I did: "rbenv install 2.4.1" ... and it worked. So now, when I do: "rbenv versions" it lists: system, and 2.4.1. However, every attempt to install another version of ruby (2.1.5, 2.2.7, 2.3.4) failed. [Here is the link](https://pastebin.com/7y9g48DV) of failed log of "rbenv install 2.3.4".
Here is the result of rbenv-doctor script:

```
> curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
> Checking for `rbenv' in PATH: /usr/bin/rbenv
> Checking for rbenv shims in PATH: OK
> Checking `rbenv install' support: bash: line 114: : command not found
>  ()
> Counting installed Ruby versions: 1 versions
> Checking RubyGems settings: OK
> Auditing installed plugins: OK
> 
```

I don't understand this 'rbenv install' command not found notice. It worked when I installed 2.4.1, and it also works when I want to list rubies: "rbenv install -l".

PS
Only "hack" I did is adding "eval "$(rbenv init -)" to the end of my .bashrc file.
I'm using Xubuntu but I had same problem on Antergos.
I do "rbenv rehash" every time after I swap between system and 2.4.1 (if that means something).

**Comment by mislav** [comment]
It looks like you're having problems with ruby-build, which is the plugin that provides `rbenv-install`.

1. First, [ensure that ruby-build](https://github.com/rbenv/ruby-build/wiki#updating-ruby-build) is updated to the latest version.
2. If your problem persists, [check existing issues](https://github.com/sstephenson/ruby-build/issues) in the ruby-build repo and open a new one if necessary. When opening a new issue, please attach the full build log.
