### ISSUE TITLE
Unable to install 2.5.1 on macOS

### ISSUE THREAD

**Issue by ghostfreeman** [rbenv/rbenv#1078]
I run `rbenv install 2.5.1` and end up with the following error. It looks like a permissions/file writing issue. I have run `xcode-select --install` to confirm that is setup (it is).

```
$ rbenv install 2.5.1   
ruby-build: use openssl from homebrew
Downloading ruby-2.5.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.1.tar.bz2
Installing ruby-2.5.1...
ruby-build: use readline from homebrew

BUILD FAILED (OS X 10.12.6 using ruby-build 20180424)

Inspect or clean up the working tree at /var/folders/v0/_844prt921gckldxpz303cg00000gn/T/ruby-build.20180508204118.18752
Results logged to /var/folders/v0/_844prt921gckldxpz303cg00000gn/T/ruby-build.20180508204118.18752.log

Last 10 log lines:
compiling dmyext.c
compiling miniprelude.c
translating probes probes.d
compiling bignum.c
error: error reading '/dev/fd/9'
1 error generated.
clang: error: unable to remove file: Operation not permitted
dtrace: failed to compile script probes.d: Preprocessor failed to process input program
make: *** [probes.h] Error 1
make: *** Waiting for unfinished jobs....
```

Apologies for wasting your time with this issue, if its been resolved elsewhere.

**Comment by fotocell7** [comment]
Any updates? I am experiencing the same problem. Thanks

Downloading ruby-2.5.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.1.tar.bz2
Installing ruby-2.5.1...

BUILD FAILED (OS X 10.13.4 using ruby-build 20180424)

Inspect or clean up the working tree at /var/folders/z1/qcpgwxr56dz3rpdx0grgk1200000gn/T/ruby-build.20180519232512.680
Results logged to /var/folders/z1/qcpgwxr56dz3rpdx0grgk1200000gn/T/ruby-build.20180519232512.680.log

Last 10 log lines:
compiling bignum.c
compiling class.c
compiling compar.c
compiling compile.c
error: error reading '/dev/fd/8'
1 error generated.
clang: error: unable to remove file: Operation not permitted
dtrace: failed to compile script probes.d: Preprocessor failed to process input program
make: *** [probes.h] Error 1
make: *** Waiting for unfinished jobs....

**Comment by n00b2pr0** [comment]
Running `RUBY_CONFIGURE_OPTS="--disable-dtrace" rbenv install <version>` worked for me. YMMV.

Source: https://stackoverflow.com/a/48950894

**Comment by mislav** [comment]
See https://github.com/rbenv/ruby-build/issues/1061#issuecomment-366127345

**Comment by sekmo** [comment]
Did you try `brew upgrade ruby-build `?

**Comment by AntonPot** [comment]
Disabling Avira Antivirus (Real-time protection) worked for me.
Same issue was reported on RVM
https://github.com/rvm/rvm/issues/4313
