### ISSUE TITLE
Can't install and use bundler on 2.4.4 after upgrading from 2.4.2

### ISSUE THREAD

**Issue by vfonic** [rbenv/rbenv#1079]
EDIT: After spending some time, I resolved this by uninstalling older ruby version(s).

Here's what happened:
(I started with `brew update && brew upgrade && brew cleanup && brew doctor`)
I had ruby 2.3.0 and 2.4.2 installed (and bundler installed on 2.4.2).

I ran:
```sh
rbenv install 2.4.4
rbenv global 2.4.4
gem install bundler
```

So far so good. Then I ran `bundle --version` but that failed:

> rbenv: bundle: command not found
>
> The `bundle' command exists in these Ruby versions:
  2.3.0
  2.4.2

`gem list bundler

> *** LOCAL GEMS ***
>
> bundler (1.16.1, 1.15.2)

I also tried `rbenv rehash` (I have no idea what this command does), but still no luck.

Here's the set of commands that fixed it (I haven't tried checking if it works "in between"):

```sh
rbenv uninstall 2.4.2
rbenv uninstall 2.3.0
rbenv rehash
bundler --version
```

One thing that I noticed is that, even though I installed ruby 2.4.4 (and earlier  2.4.2), there were a lot of references to 2.4.0. For example:

`gem env`

> RubyGems Environment:
>   - RUBYGEMS VERSION: 2.6.14.1
>   - RUBY VERSION: 2.4.4 (2018-03-28 patchlevel 296) [x86_64-darwin17]
>   - INSTALLATION DIRECTORY: /Users/viktorfonic/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0
>   - USER INSTALLATION DIRECTORY: /Users/viktorfonic/.gem/ruby/2.4.0
>   - RUBY EXECUTABLE: /Users/viktorfonic/.rbenv/versions/2.4.4/bin/ruby
>   - EXECUTABLE DIRECTORY: /Users/viktorfonic/.rbenv/versions/2.4.4/bin
>   - SPEC CACHE DIRECTORY: /Users/viktorfonic/.gem/specs
>   - SYSTEM CONFIGURATION DIRECTORY: /Users/viktorfonic/.rbenv/versions/2.4.4/etc
>   - RUBYGEMS PLATFORMS:
>     - ruby
>     - x86_64-darwin-17
>   - GEM PATHS:
>      - /Users/viktorfonic/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0
>      - /Users/viktorfonic/.gem/ruby/2.4.0
>   - GEM CONFIGURATION:
>      - :update_sources => true
>      - :verbose => true
>      - :backtrace => false
>      - :bulk_threshold => 1000
>      - "gem" => "--no-document"
>      - "install" => "--user-install"
>   - REMOTE SOURCES:
>      - https://rubygems.org/
>   - SHELL PATH:
>      - /Users/viktorfonic/.rbenv/versions/2.4.4/bin
>      - /usr/local/Cellar/rbenv/1.1.1/libexec
>      - /usr/local/heroku/bin
>      - /usr/local/opt/postgresql@9.6/bin
>      - /Users/viktorfonic/.rbenv/shims
>      - /Users/viktorfonic/.gem/ruby/2.4.0/bin
>      - /Users/viktorfonic/scripts
>      - /Users/viktorfonic/go/bin
>      - /Users/viktorfonic/.composer/vendor/bin
>      - /usr/local/sbin
>      - /usr/local/bin
>      - /usr/bin
>      - /bin
>      - /usr/sbin
>      - /sbin
>      - /usr/local/bin
>      - /usr/bin
>      - /bin
>      - /usr/sbin
>      - /sbin
>      - /Users/viktorfonic/.rvm/bin

Some of these were used with ruby 2.4.2 as well. I think that's why, after running `rbenv rehash`, rbenv would not properly switch to ruby 2.4.4.

**Comment by mislav** [comment]
Closing because you've described your issue as solved and there isn't enough here to consider this a bug.

**Comment by vfonic** [comment]
Sure. I left it open in case there is enough info/repro-steps here to be able to pinpoint the bug that happened to me.
<3

**Comment by vfonic** [comment]
I experienced this issue again on a new MacBook. I copied over zsh configuration from the old Mac, so that could be the cause.

Adding this line to `~/.zshrc` solved the issue:
`export PATH="/Users/viktorfonic/.gem/ruby/2.5.0/bin:$PATH"`

Not sure this is the best approach...Actually, I'm not sure this will work when I switch to another ruby version. How does rbenv add bin directory to the PATH?

**Comment by vfonic** [comment]
Here's my `.zshrc` file:

```sh
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="gallois"

plugins=(bundler git history)

source $ZSH/oh-my-zsh.sh

eval "$(hub alias -s)"

export PATH="$HOME/scripts:$PATH"
if [ -f /usr/local/bin/trash ]; then alias rm="/usr/local/bin/trash"; fi

. ~/.aliases
. ~/.git_aliases

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

export BUNDLER_EDITOR='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl -n -w'
export EDITOR='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl -n -w'
eval "$(rbenv init -)"
export PATH="/usr/local/opt/postgresql@9.6/bin:$PATH"

compctl -m npx
```


And my new `$PATH` variable:
`/usr/local/opt/postgresql@9.6/bin:/Users/viktorfonic/.rbenv/shims:/Users/viktorfonic/scripts:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

Expanded:
```
/usr/local/opt/postgresql@9.6/bin
/Users/viktorfonic/.rbenv/shims
/Users/viktorfonic/scripts
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```
