### ISSUE TITLE
not getting the "rbenv: version `x.y.z` is not installed" warning

### ISSUE THREAD

**Issue by tamoyal** [rbenv/rbenv#1080]
I just setup a new computer and after installing `rbenv` successfully according to the `rbenv-doctor` script, I am no longer getting warnings when changing into directories that have a `.ruby-version` file where that version is not installed locally.

I'm on OS X 10.13.4 and rbenv `rbenv 1.1.1-30-gc8ba27f`.

Any idea why this is happening?

**Comment by mislav** [comment]
Simply changing into a directory won't result in any error, even if the version is missing. Try running `ruby -v` in the directory where the `.ruby-version` file references a Ruby version that isn't installed: you will get an error.

Unlike other version managers, rbenv doesn't auto-execute anything when simpy `cd`ing into a new directory.

**Comment by tamoyal** [comment]
Quite possible @mislav but I got to my old computer today and saw that in fact I used to at least have this experience.

![screen shot 2018-06-23 at 5 34 44 pm](https://user-images.githubusercontent.com/46859/41814316-3444e852-770e-11e8-98cc-d466c1f95ed9.png)
