### ISSUE TITLE
Error compiling ruby with Linux Mint 18.3

### ISSUE THREAD

**Issue by hcmarchezi** [rbenv/rbenv#1081]
Hi,

I tried to compile ruby versions 2.5.1, 2.3.7 and 2.4.4 without success. Possibly if I try other versions I will get the same problem.

I got the message below from rbenv:

ERROR: Ruby install aborted due to missing extensions
Try running `apt-get install -y libssl-dev libreadline-dev zlib1g-dev` to fetch missing dependencies.

However even after installing the above libraries I keep receiving the same error message.
Did  anyone have this problem before ?  Is it a Mint specific problem ?

**Comment by hcmarchezi** [comment]
I was able to make it work if I use "sudo rbenv". Is there a reason for this ? thanks

**Comment by mislav** [comment]
It looks like you're having problems with ruby-build, which is the plugin that provides `rbenv-install`.
If your problem persists, please [check existing issues](https://github.com/sstephenson/ruby-build/issues) and open a new one in the ruby-build repo. If you do so, please attach the full build log.
