### ISSUE TITLE
All Ruby builds fail (OS X 10.13.4)

### ISSUE THREAD

**Issue by mcclowes** [rbenv/rbenv#1084]
Trying to install versions of Ruby through rbenv (2.3.4, but have tried various, including 2.4.4, 2.4.2, 2.3.7). None succeed. I can't find any mention of other people encountering thise issue, so I assume its an issue with my setup, but hopefully someone can make more sense of it than I can.

Ran:

`rbenv install  2.3.4`

Terminal log:

```
ruby-build: use openssl from homebrew
Downloading ruby-2.3.4.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.4.tar.bz2
Installing ruby-2.3.4...
ruby-build: use readline from homebrew

BUILD FAILED (OS X 10.13.4 using ruby-build 20180424)

Inspect or clean up the working tree at /var/folders/ml/d6nz6xbj36xdt6qvghzyck800000gn/T/ruby-build.20180531144237.7991
Results logged to /var/folders/ml/d6nz6xbj36xdt6qvghzyck800000gn/T/ruby-build.20180531144237.7991.log
```

Verbose log attached.
[ruby-build.20180531144237.7991.log](https://github.com/rbenv/rbenv/files/2058487/ruby-build.20180531144237.7991.log)

**Comment by mislav** [comment]
It looks like you're having problems with ruby-build, which is the plugin that provides `rbenv-install`.
If your problem persists, please [check existing issues](https://github.com/sstephenson/ruby-build/issues) and open a new one in the ruby-build repo.
