### ISSUE TITLE
Output of `rbenv versions` not semantically sorted

### ISSUE THREAD

**Issue by pvdb** [rbenv/rbenv#1086]
At the moment, the output of `rbenv versions` is nondeterministically _(but most likely lexically)_ sorted, but it would make more sense to have it semantically sorted using the precedence rules defined by [the Semantic Versioning 2.0.0 spec](https://semver.org/).

e.g. in the following example `2.1.10` is listed before `2.1.9` even though semantically it is a later version;  the same for `2.2.10` which is listed before all other `2.2.x` versions I have installed even though it is a newer RMI version.

```shell
$ rbenv versions
  system
  2.0.0-p451
  2.1.10
  2.1.9
  2.2.10
  2.2.3
  2.2.8
  2.2.9
  2.3.3
  2.3.6
  2.3.7
  2.4.0
  2.4.2
  2.4.3
  2.4.4
* 2.5.0 (set by /usr/local/var/rbenv/version)
  2.5.1
$ _
```

A before-and-after diff would be:

```diff
--- rbenv.versions.before	2018-06-04 09:44:10.000000000 +0100
+++ rbenv.versions.after	2018-06-04 09:59:07.000000000 +0100
@@ -1,19 +1,19 @@
 $ rbenv versions
   system
   2.0.0-p451
-  2.1.10
   2.1.9
-  2.2.10
+  2.1.10
   2.2.3
   2.2.8
   2.2.9
+  2.2.10
   2.3.3
   2.3.6
   2.3.7
   2.4.0
   2.4.2
   2.4.3
   2.4.4
 * 2.5.0 (set by /usr/local/var/rbenv/version)
   2.5.1
 $ _
```

**Comment by hsbt** [comment]
The latest version of ruby-build was fixed this issue. Try it.
