### ISSUE TITLE
Should add "Select a ruby version with [$ rbenv global 2.3.0]" to readme

### ISSUE THREAD

**Issue by sunkup** [rbenv/rbenv#1094]
What about adding something along the lines of "Select a ruby version with [$ rbenv global 2.3.0]" to the readme file between the install ruby and install gems sections?

Seems many people needed to do that manually in order to set everything up initially.

**Comment by mislav** [comment]
Maybe a better idea would be to submit a PR to `ruby-build` so that running `rbenv install` for the first time automatically selects that version as global?

**Comment by extremesonic** [comment]
Yes, did not think of that. I opened an issue over there.

**Comment by LeonidKokhnovich** [comment]
Hi! Thanks for supporting this project. 
After running the following command
```
rbenv global 2.5.1
```
I still get the home directory as
```
gem env home
/Library/Ruby/Gems/2.3.0
```
Is there something wrong with the steps I'm doing?

**Comment by darkRaspberry** [comment]
It takes 3 minutes to understand why I can't run any ruby commands. Still I think for the time being. Please add that line as I searched and thought I did something wrong as. I run `rbenv global` it always output `system`.

Then I run `rbenv global 3.1.0` and wohooo it works like a charms.

**Comment by mislav** [comment]
Selecting a global Ruby version is already documented in the README under “Installing Ruby versions” https://github.com/rbenv/rbenv#installing-ruby-versions

> Set a Ruby version to finish installation and start using commands `rbenv global 2.0.0-p247` or `rbenv local 2.0.0-p247`
