### ISSUE TITLE
failed installation of gem

### ISSUE THREAD

**Issue by shahrukhbari99** [rbenv/rbenv#1095]
When I am installing gem bundler using command **gem install bundler**, it gives output **rbenv: gem: command not found
**
What should I do?

**Comment by voloyev** [comment]
Check your config. Is there this command: `eval "$(rbenv init -)"`.
Check your path. Are `~.rbenv/shims` folder there?

**Comment by shahrukhbari99** [comment]
Thanks . Problem has been solved . I had not made the ruby version global . After installing ruby run command **rbenv global <version>** .
