### ISSUE TITLE
Simplfify shims by changing shebang

### ISSUE THREAD

**Issue by marcthe12** [rbenv/rbenv#1100]
Due to how shebangs work, its possible to have an executable file with the shebang 
`#!/usr/bin/env rbenv exec`
This will optimize rbenv

**Comment by mislav** [comment]
I don't understand fully, but no shebang changes are necessary for scripts to work with rbenv. `#!/usr/bin/env ruby` shebang is just fine and doesn't need "optimization". Thanks for suggesting!
