### ISSUE TITLE
UX: Installation progress not visible

### ISSUE THREAD

**Issue by vfonic** [rbenv/rbenv#1103]
I've just run `rbenv install 2.5.1` and, although it's taking substantial time, I don't see any progress. EDIT: Finally, it changed from "Downloading ruby..." to "Installing ruby...". So it's "stuck" (figuratively speaking) there now.

Just sending this over in case anyone wants to tackle this to provide better UX in the future.

Thanks for maintaining this project! ❤️

**Comment by mislav** [comment]
`rbenv install -v` prints compilation progress while it's ongoing. There is [no way right now](https://github.com/rbenv/rbenv/issues/395#issuecomment-18346871) to opt into download progress bars.

PRs to https://github.com/rbenv/ruby-build welcome, but keep in mind that this feature would have to be implemented for curl, wget, and aria2c alike, and that progress bars should only ever go to stderr but not to a log file/other non-terminal output.
