### ISSUE TITLE
Rails is not currently installed on this system - High Sierra

### ISSUE THREAD

**Issue by wonderphil** [rbenv/rbenv#1106]
Hi guys,

To start I follow the exact steps from [Setup Ruby On Rails on
macOS 10.13 High Sierra](https://gorails.com/setup/osx/10.13-high-sierra), just like I have with every other version of mac/ubuntu.

So basically install homebrew, install rbenv ruby-build

add the following to bash profile and source it:

`if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi`

then do

    rbenv install 2.5.1
    rbenv global 2.5.1
    ruby -v

outputs:

    ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

do a which ruby to to make sure:

    /Users/pdavies/.rbenv/shims/ruby

run gem install 

    gem install rails -v 5.2.0

which outputs:

    Successfully installed rails-5.2.0
    Parsing documentation for rails-5.2.0
    Done installing documentation for rails after 0 seconds
    1 gem installed

then a rehash and check version:

    rbenv rehash
    rails -v

outputs:

    

> Rails is not currently installed on this system. To get the latest version, simply type:
>    $ sudo gem install rails
> You can then rerun your "rails" command.

found anther issue that suggested adding:

    export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"
    eval "$(rbenv init -)"

to the bash profile, did that sourced it and tried again still nothing.  to check the output of `echo $PATH` was:

    /Users/pdavies/.rbenv/shims:/Users/pdavies/.rbenv/bin:/Users/pdavies/.rbenv/shims:/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin

Just to make sure i also did which gem incase i wasnt using the right one, output:

    /Users/pdavies/.rbenv/shims/gem

when I do a which rails i get:

    /usr/bin/rails

I found some blog that said to delete that, but I cant seem to do that either, i just get:

    sudo rm -f /usr/bin/rails
    Password:
    rm: /usr/bin/rails: Operation not permitted

This is a fresh install of OSX and the only way I can get it work is to downgrade the version of OSX that is installed, which is a pain in the ass!

Any help would be greatful 

Thanks

**Comment by wonderphil** [comment]
Thanks for getting back to me.  I am sure I tried it without the path, but I removed, reloaded my shell and all seems to be working.

Such a simple little killer :(

**Comment by molfar** [comment]
Have exactly the same issue
~ ❯❯❯ gem env home
/Users/molfar/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0
~ ❯❯❯ rails -v
Rails is not currently installed on this system. To get the latest version, simply type:

    $ sudo gem install rails

You can then rerun your "rails" command.
~ ❯❯❯ gem install rails
Successfully installed rails-5.2.1
1 gem installed
~ ❯❯❯ ls `rbenv prefix`/bin
bundle          gem             rake            ri              update_rubygems
erb             irb             rdoc            ruby
~ ❯❯❯ which -a rails
/usr/bin/rails
~ ❯❯❯

**Comment by mislav** [comment]
> but I removed, reloaded my shell and all seems to be working.

Thanks for updating. It would be nice to close out your issue when you're no longer having an issue!

**Comment by ZacCui** [comment]
> I'm sorry that you're having trouble. Thanks for the detailed information about your setup!
> 
> First of all, you **don't** need this:
> 
> ```
> export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"
> ```
> This is enough if you've installed via Homebrew:
> 
> ```
> if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
> ```
> After you've done `gem install rails -v 5.2.0` while in Ruby 2.5.1 (and ran `rbenv rehash` just in case, but it shouldn't be strictly necessary), it should have generated the `/Users/pdavies/.rbenv/shims/rails` file. The output of `which -a rails` should then be:
> 
> ```
> /Users/pdavies/.rbenv/shims/rails
> /usr/bin/rails
> ```
> The problem on your end seems that the first line is missing. If so, can you check the contents of `` ls `rbenv prefix`/bin `` to see if `rails` is there?

Hi @mislav 
I got the same issue when I installing rails.
There are only one line displayed on my terminal when I ran `which -a rails`
`/Users/pdavies/.rbenv/shims/rails` is missing. How can I get this issue resolved

**Comment by mislav** [comment]
@ZacCui You haven't given us enough information to go on. See https://github.com/rbenv/rbenv-installer#rbenv-doctor for a tool that can help you identify installation problems.

**Comment by kristher1619** [comment]
using the `rbenv rehash` fixed for me

**Comment by mawilmouth** [comment]
using the rbenv rehash fixed for me

**Comment by HariShankarS** [comment]
@mislav I'm having the same issue now. Could you please help me here.
This is the response I got for the `rbenv-doctor`
```
➜  ~ curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash

Checking for `rbenv' in PATH: /usr/local/bin/rbenv
Checking for rbenv shims in PATH: OK
Checking `rbenv install' support: /usr/local/bin/rbenv-install (ruby-build 20200722)
Counting installed Ruby versions: 1 versions
Checking RubyGems settings: OK
Auditing installed plugins: OK

```
`which rails` would only give me this -
```
usr/bin/rails

```

I tried `rbenv rehash` but that doesn't work too.

I have run this so many times now :( 
```gem install rails```

I tried restarting the terminal as many others suggested. Even that doesn't work.

I'm unable to understand what is wrong here.

**Comment by inklin** [comment]
@kristher1619 `rbenv rehash` worked for me, thanks for this tip!

**Comment by pengw00** [comment]
I use ```rbenv rehash```, but got ```rbenv: command not found```

**Comment by Laul0001** [comment]
> I'm sorry that you're having trouble. Thanks for the detailed information about your setup!
> 
> First of all, you **don't** need this:
> 
> ```
> export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"
> ```
> 
> This is enough if you've installed via Homebrew:
> 
> ```
> if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
> ```
> 
> After you've done `gem install rails -v 5.2.0` while in Ruby 2.5.1 (and ran `rbenv rehash` just in case, but it shouldn't be strictly necessary), it should have generated the `/Users/pdavies/.rbenv/shims/rails` file. The output of `which -a rails` should then be:
> 
> ```
> /Users/pdavies/.rbenv/shims/rails
> /usr/bin/rails
> ```
> 
> The problem on your end seems that the first line is missing. If so, can you check the contents of `` ls `rbenv prefix`/bin `` to see if `rails` is there?

Hi, i was having the same issue and tried to run the last command, and it does say that rails is there but, when i run the rails command, I still get the same error as the questioner

**Comment by Allegra9** [comment]
This is what worked for me: 
```gem env home```  (to get your gems path)
Add that path export to your `.zshrc` (yours might look different):
```export PATH="/opt/homebrew/lib/ruby/gems/3.0.0/bin:$PATH"```

And make sure to run install with this flag:
```gem install rails **--user-install`**``

Open new terminal tab and check if it's working with `rails -v`

**Comment by natew8** [comment]
> I'm sorry that you're having trouble. Thanks for the detailed information about your setup!
> 
> First of all, you **don't** need this:
> 
> ```
> export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"
> ```
> 
> This is enough if you've installed via Homebrew:
> 
> ```
> if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
> ```
> 
> After you've done `gem install rails -v 5.2.0` while in Ruby 2.5.1 (and ran `rbenv rehash` just in case, but it shouldn't be strictly necessary), it should have generated the `/Users/pdavies/.rbenv/shims/rails` file. The output of `which -a rails` should then be:
> 
> ```
> /Users/pdavies/.rbenv/shims/rails
> /usr/bin/rails
> ```
> 
> The problem on your end seems that the first line is missing. If so, can you check the contents of `` ls `rbenv prefix`/bin `` to see if `rails` is there?

Thank you for the great info. What is recommended if i DO NOT see `rails` in the contents of the last command.

**Comment by maurovz** [comment]
> I'm sorry that you're having trouble. Thanks for the detailed information about your setup!
> 
> First of all, you **don't** need this:
> 
> ```
> export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"
> ```
> 
> This is enough if you've installed via Homebrew:
> 
> ```
> if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
> ```
> 
> After you've done `gem install rails -v 5.2.0` while in Ruby 2.5.1 (and ran `rbenv rehash` just in case, but it shouldn't be strictly necessary), it should have generated the `/Users/pdavies/.rbenv/shims/rails` file. The output of `which -a rails` should then be:
> 
> ```
> /Users/pdavies/.rbenv/shims/rails
> /usr/bin/rails
> ```
> 
> The problem on your end seems that the first line is missing. If so, can you check the contents of `` ls `rbenv prefix`/bin `` to see if `rails` is there?

Weird. This works but when I close the terminal it doesn't find rails anymore. I have to rerun `if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi`
