### ISSUE TITLE
`rbenv' in PATH: printc:6: bad substitution

### ISSUE THREAD

**Issue by wellington1993** [rbenv/rbenv#1107]
After open `zsh`  and try to run rbenv doctor:
`curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | zsh `
I've got:
`Checking for 'rbenv' in PATH: printc:6: bad substitution`

what is the problem?

**Comment by mislav** [comment]
I'm sorry you're having issues. What is your `bash --version` and your OS?

**Comment by wellington1993** [comment]
Hi @mislav,

I think the problem is related to Zsh because I used:
`...rbenv-doctor | zsh`

with I use:
`...rbenv-doctor | bash`

the problem not occurs.

I think it's a specific bash code inside rbenv-doctor.
Can I test the rbenv with doctor redirecting the script or running the script inside zsh?

I fount this but I can't identify the pattern inside the rbenv doctor code:
https://stackoverflow.com/questions/20323738/echo-syntax-error-bad-substitution
https://unix.stackexchange.com/questions/426458/bad-substitution-running-ls-sed-with-bash
https://www.unix.com/shell-programming-and-scripting/158413-bad-substitution-error.html

Thanks!

**Comment by wellington1993** [comment]
@mislav My bash version is:
```
GNU bash, versão 4.4.19(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
Licença GPLv3+: GNU GPL versão 3 ou posterior <http://gnu.org/licenses/gpl.html>.
```
If I use the bash in:
`rbenv-doctor | bash
`
instead of
`rbenv-doctor | zsh`

The problem not occurs, only if I redirect to zsh.

Maybe bash specific code in rbenv-doctor?

**Comment by mislav** [comment]
Ah I've just realized that you were piping to `zsh` instead of `bash`. You can't do that. rbenv-doctor is a bash script and not a zsh script. The script is not strictly POSIX-compatible.
