### ISSUE TITLE
Expose rbenv-doctor in Debian package

### ISSUE THREAD

**Issue by kwill** [rbenv/rbenv#1114]
**User story:** I am an experienced Debian user. When I install a package I expect utility scripts to be available from the command line. I do not download and run arbitrary scripts, because this is unsafe.

**Suggested solution:** Update the rbenv Debian package such that the following works:

```
$ sudo apt install rbenv
$ rbenv-doctor
```

For Debian users, this would replace the current `curl | bash` instructions in the README.

**Comment by hsbt** [comment]
We didn't touch rbenv and ruby-build packages of Debian. Please ask the package maintainer on Debian project.

**Comment by kwill** [comment]
Thank for the info. I'll submit the issue to Debian.
