### ISSUE TITLE
Cannot execute gem from outside version

### ISSUE THREAD

**Issue by kwill** [rbenv/rbenv#1115]
**Steps to reproduce:**

```
rbenv install 2.4.1
rbenv local 2.4.1 # enter the environment
gem install fpm
rbenv local --unset # leave the environment
rbenv which fpm # still accessible?
fpm --version
```

**What should happen:**

```
$ rbenv which fpm
/home/user/.rbenv/versions/2.4.1/bin/fpm
$ fpm --version                                                                                                                                                 
1.10.2
```

**What happens instead:**

```
$ rbenv which fpm
/home/user/.rbenv/versions/2.4.1/bin/fpm
$ fpm --version                                                                                                                                                 
rbenv: fpm: command not found

The `fpm' command exists in these Ruby versions:
  2.4.1
```

Have I misunderstood the installation instructions, or what I should expect after installation?

**Related link:**

* https://stackoverflow.com/questions/51874821

**Comment by tom-lord** [comment]
> Have I misunderstood the installation instructions

Yes.

> what I should expect after installation?

You install a gem within the current ruby version.

If you switch versions (which is presumably what happened after `rbenv local --unset`), and the gem is not installed within that version, it cannot be accessed.

This is not a bug; it is a feature.

**Comment by tom-lord** [comment]
Note that where you wrote:

> # still accessible?

What's **actually** displayed here is:

```
$ rbenv which fpm
rbenv: fpm: command not found

The `fpm' command exists in these Ruby versions:
  2.4.1
```

So no, it _not_ still accessible.

**Comment by kwill** [comment]
Ok, I checked `~/.rbenv/shims/fpm` and I think I understand now. The shim does not point to the actual gem installed in the actual environment, it points to the relative location of the gem *as if it were installed* in the current environment. It executes the gem if present, and gives a helpful error message if it isn't.

The purpose of the shim is to make the gem executable from the command line, if available. The purpose is not to make the gem executable from any environment (my misunderstanding).

Thanks!
