### ISSUE TITLE
Install script fails when installing rbenv via git

### ISSUE THREAD

**Issue by aarnwri** [rbenv/rbenv#1120]
git pull fails because the new repo doesn't start on any branch...

I get this output:
```
Installing rbenv with git...
Initialized empty Git repository in /root/.rbenv/.git/
fatal: You are on a branch yet to be born
```

I modified this:
```bash
    echo "Installing rbenv with git..."
    mkdir -p ~/.rbenv
    cd ~/.rbenv
    git init
    git remote add origin https://github.com/rbenv/rbenv.git
    git checkout -b master
    git pull origin master
    try_bash_extension
    rbenv=~/.rbenv/bin/rbenv
```

to this:
```bash
    echo "Installing rbenv with git..."
    mkdir -p ~/.rbenv
    cd ~/.rbenv
    git init
    git remote add origin https://github.com/rbenv/rbenv.git
    git fetch
    git checkout master
    git pull origin master
    try_bash_extension
    rbenv=~/.rbenv/bin/rbenv
```

Pretty sure some version of git fetch will work to fix this (probably only want to fetch master)... not sure checking out master is actually necessary. It seems that until the fetch happens, the branch doesn't exist. This was on a centos 6.6 docker image with git version 1.7.1

**Comment by mislav** [comment]
Thank you for reporting. I don't recognize this install script. Which script is this? What do you expect us to fix, exactly? More info would be useful, thank you!

**Comment by aarnwri** [comment]
Sorry! Looks like I created this issue under the wrong repo... Should have been rbenv/rbenv-installer

I was using the curl command found on this page: https://github.com/rbenv/rbenv-installer#rbenv-installer
```bash
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash
```
While pasting the url in my browser the raw link is confusing... It looks to be the same script found here: https://github.com/rbenv/rbenv-installer/blob/master/bin/rbenv-installer
