### ISSUE TITLE
rbenv init and shims

### ISSUE THREAD

**Issue by seitanic-coding** [rbenv/rbenv#1123]
from my understanding`rbenv init` is supposed to create the shims. when i run rbenv init, it tells me to add eval $(rbenv init -) to my ~/.bash_profile. ive done that but it keeps saying it isnt present. where should i go frome here? 
-thanks

**Comment by Banginpadr** [comment]
> from my understanding`rbenv init` is supposed to create the shims. when i run rbenv init, it tells me to add eval $(rbenv init -) to my ~/.bash_profile. ive done that but it keeps saying it isnt present. where should i go frome here?
> -thanks

im having the same problem did you solved it?
