### ISSUE TITLE
Unable to build ruby on ARMv7 architecture 

### ISSUE THREAD

**Issue by abhi18av** [rbenv/rbenv#1124]
Hi rbenv team,

I tried to install ruby on my scaleway C1 instance, ARMv7 architecture but so far I haven't been able to do it. Here's the error log 

```
root@pup:~# rbenv install 2.5.0-dev
Cloning https://github.com/ruby/ruby.git...
Installing ruby-trunk...



BUILD FAILED (Ubuntu 18.04 using ruby-build 20170726)

Inspect or clean up the working tree at /tmp/ruby-build.20181012154306.7388
Results logged to /tmp/ruby-build.20181012154306.7388.log

Last 10 log lines:
making mjit_config.h
generating mjit_compile.inc
compiling node.c
compiling numeric.c
compiling pack.c
generating parse.c
make: bison: Command not found
uncommon.mk:822: recipe for target 'parse.c' failed
make: *** [parse.c] Error 127
make: *** Waiting for unfinished jobs....

```

Could you please help me out here ?

**Comment by abhi18av** [comment]
I'm using this link as my guide 

https://qiita.com/takeru56/items/ab09e239dc38e4da5ea1

**Comment by mislav** [comment]
Hi, the correct project that handles building ruby versions is: https://github.com/rbenv/ruby-build/wiki

Not this one. Your build log suggests that you don't have `bison` installed. Maybe first check that you have all requisite build tools installed (`sudo apt-get install build-essentials`) and only then try to compile Ruby versions?

Thank you

**Comment by abhi18av** [comment]
Ohh, I see!

Thanks Mislav +1
