### ISSUE TITLE
rbenv versions hangs

### ISSUE THREAD

**Issue by gerases** [rbenv/rbenv#1125]
Hi,

I'm giving rbenv a try and after installing it, running `rbenv versions` hangs. Running it like this:

```
RBENV_DEBUG=1 rbenv versions
```

shows that there seems to be an infinite loop? the lines below are executed over and over.

```
...
+ [rbenv-version-file:17] root=.
+ [rbenv-version-file:11] [[ . =~ ^//[^/]*$ ]]
+ [rbenv-version-file:12] '[' -s ./.ruby-version ']'
+ [rbenv-version-file:16] '[' -n . ']'
+ [rbenv-version-file:17] root=.
+ [rbenv-version-file:11] [[ . =~ ^//[^/]*$ ]]
+ [rbenv-version-file:12] '[' -s ./.ruby-version ']'
+ [rbenv-version-file:16] '[' -n . ']'
+ [rbenv-version-file:17] root=.
+ [rbenv-version-file:11] [[ . =~ ^//[^/]*$ ]]
+ [rbenv-version-file:12] '[' -s ./.ruby-version ']'
+ [rbenv-version-file:16] '[' -n . ']'
+ [rbenv-version-file:17] root=.
...
```

Bash profile contains:

```
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"
```

Am I doing something wrong?

Thanks,
  Sergei

**Comment by mislav** [comment]
Thank you for reporting!

1. What `rbenv --version` do you have?
1. What is your OS and bash version?
2. Is the behavior the same when you invoke `rbenv versions` from different directories on your system?

**Comment by gerases** [comment]
Thank you for getting back to me, @mislav.

1. rbenv 1.1.1-39-g59785f6
2. CentOS 7.5
3. When a brand new shell is opened, it hangs, but when I switch to another dir and do it, it works! When switching back to the home dir after that, it works as well.
4. The lines leading up the loop are:

```
+ [rbenv:125] exec /home/sgerasenko/.rbenv/libexec/rbenv-versions
+ [rbenv-versions:10] unset bare
+ [rbenv-versions:11] unset skip_aliases
+ [rbenv-versions:28] versions_dir=/home/sgerasenko/.rbenv/versions
+ [rbenv-versions:30] enable -f /home/sgerasenko/.rbenv/libexec/rbenv-realpath.dylib realpath
+ [rbenv-versions:62] '[' -d /home/sgerasenko/.rbenv/versions ']'
++ [rbenv-versions:63] realpath /home/sgerasenko/.rbenv/versions
+ [rbenv-versions:63] versions_dir=/home/sgerasenko/.rbenv/versions
+ [rbenv-versions:66] '[' -n '' ']'
+ [rbenv-versions:72] hit_prefix='* '
+ [rbenv-versions:73] miss_prefix='  '
++ [rbenv-versions:74] rbenv-version-name
+ [rbenv-version-name:6] '[' -z '' ']'
++ [rbenv-version-name:7] rbenv-version-file
+ [rbenv-version-file:7] target_dir=
+ [rbenv-version-file:22] '[' -n '' ']'
+ [rbenv-version-file:25] find_local_version_file .
+ [rbenv-version-file:10] local root=.
+ [rbenv-version-file:11] [[ . =~ ^//[^/]*$ ]]
+ [rbenv-version-file:12] '[' -s ./.ruby-version ']'
+ [rbenv-version-file:16] '[' -n . ']'
```

Hope this helps.

Thanks,
  Sergei

**Comment by mislav** [comment]
It looks like it was `RBENV_DIR=.` that threw this in a loop. In most cases, RBENV_DIR as assigned like so: `RBENV_DIR="$PWD"`. It might be that the value of `PWD` was `.` when the shell is starting out. 🤔

**Comment by mislav** [comment]
I'm not sure how to act on this, so I'm going to close this until they are more reports. Please reopen if this still bites you!
