### ISSUE TITLE
Add Ruby 2.5.3 stable to rbenv

### ISSUE THREAD

**Issue by karankrizz** [rbenv/rbenv#1128]
I can't find the latest stable version ruby 2.5.3 in the rbenv install list.

**Comment by likeuwill** [comment]
You can use 

`cd /home/{user}/.rbenv/plugins/ruby-build && git pull && cd -`
`rbenv install 2.5.3`

**Comment by mislav** [comment]
https://github.com/rbenv/ruby-build/wiki#updating-ruby-build

**Comment by BKSpurgeon** [comment]
The following splits up the instructions given by @likeuwill  (thank you!) + adds some commentary:

1. `cd ~/.rbenv/plugins/ruby-build/`

(This takes you to the relevant folder). Then pull the git repo:

2. ` git pull`

Then finally you need to install the version you are after. In this case it is:

3. `rbenv install 2.5.3`

And you should be off to the races!

HTH helps.
