### ISSUE TITLE
How to remove the line from terminal that display after uninstalling the rbenv?

### ISSUE THREAD

**Issue by theshashiverma** [rbenv/rbenv#1129]
I have just Uninstalled the rbenv from my ubuntu 16.04 and now when I open my Terminal I am getting this in the top of the terminal  "The program 'rbenv' is currently not installed. You can install it by typing:
sudo apt install rbenv"

**Comment by mislav** [comment]
See https://github.com/rbenv/rbenv#uninstalling-rbenv

The solution is to remove any lines mentioning "rbenv" from your shell initialization files (e.g. `~/.bashrc`, `~/.bash_profile`, `~/.profile`, etc.)
