### ISSUE TITLE
Instructions in README and `rbenv init` are misleading a bit for Ubuntu

### ISSUE THREAD

**Issue by abotalov** [rbenv/rbenv#1130]
I'm on Ubuntu 18.04 and use Bash.

When I followed step 2 of [Basic Github Checkout in README](https://github.com/rbenv/rbenv/blob/master/README.md#basic-github-checkout), I executed both a step for Bash and for Ubuntu Desktop.

That caused the appearance of `~./bash_profile` which isn't sourced by default in the shell.

So when I executed `rbenv init`, I was advised to append a line to [`~./bash_profile`](https://github.com/rbenv/rbenv/blob/1c772d5ff21bbee52e0c6cdf128c5cffaf8feea8/libexec/rbenv-init#L48) because it existed. That didn't help as the file wasn't sourced.

It looks like quite many users also had such issue - https://github.com/rbenv/rbenv/issues/1067#issuecomment-386901944.

Perhaps, step 2 should clarify that appending a line to `~/.bash_profile` on Ubuntu isn't needed. Also it may be good to improve a detection logic in `rbenv init` to check if `~./bash_profile` is sourced.

**Comment by mislav** [comment]
Thank you for reporting! We should definitely fix this case. Does anyone have ideas how to reliably detect when the current shell is set up to execute `~/.bashrc` but not `~/.bash_profile`? I guess that depends on whether or not bash was started in “login” mode or not.

This is our current logic, and it might not be great: https://github.com/rbenv/rbenv/blob/59785f6762e9325982584cdab1a4c988ed062020/libexec/rbenv-init#L47-L52

**Comment by maxim-belkin** [comment]
`~/.bash_profile` should be sourced by Bash by default, see INVOCATION section in `man bash`. However...

`rbenv init -` does the following (on macOS + Homebrew):

```
export PATH="/Users/mbelkin/.rbenv/shims:${PATH}"
export RBENV_SHELL=bash
source '/usr/local/Cellar/rbenv/1.1.1/libexec/../completions/rbenv.bash'
command rbenv rehash 2>/dev/null
rbenv() {
  local command
  command="$1"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "$(rbenv "sh-$command" "$@")";;
  *)
    command rbenv "$command" "$@";;
  esac
}
```
 - Both manipulations with `PATH` and `RBENV_SHELL`can be placed in `~/.bash_profile` because they are exported. Though, they *can* also be placed in `~/.bashrc`...
 - `rbenv.bash` defines a function used for autocompletion. It does not make sense to source it in `~/.bash_profile` because (a) it is not exported (so will be lost in a normal shell) and (b) auto-completion make sense for interactive shells only.
 - `command rbenv rehash ...` applies to interactive shells only so it makes sense to place it in `~/.bashrc`
 - `rbenv()` function is not exported (with `export -f rbenv` after function definition) so it will be lost in a regular shell.

So, I think the problem that @abotalov reports is related to absence of `export -f rbenv` 

Anyways, I would agree that placing `rbenv init -` in `~/.bashrc` makes more sense as most of the commands there apply to the interactive shell.

Notable references: 
 - https://manpages.ubuntu.com/manpages/bionic/en/man1/bash.1.html (INVOCATION section)
 - https://superuser.com/a/147699
- On my Mac I have the following code snippet in my `~/.bash_profile`:
```
[[ "$-" == *i* ]] && . ~/.bashrc
```

**Comment by mislav** [comment]
@maxim-belkin Thank you for the detailed investigation!

**Comment by abotalov** [comment]
By the way, on Ubuntu `.bashrc` is sourced from `.profile` - https://askubuntu.com/questions/432508/why-does-ubuntus-default-profile-source-bashrc

**Comment by sdarwin** [comment]
It almost seems like the Ubuntu instructions on the README page should literally show this code snippet:
```
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
```
Then, in the Advanced section, explain why you might consider modifying this.
The way it stands now in the README, you must go through a series of steps, manually running "rbenv init", to figure out the second step, you can't do a super fast copy-paste from the docs.  
Anyway, just an idea.  Maybe there are reasons it's not as simple as that.

**Comment by orangelynx** [comment]
I would just like to second the opinion that the instructions on initializing rbenv are, if not unclear, at least counter-intuitive. I ran into this problem the first time I set up rbenv and I just now ran into it again.

Step 3 of the github installation process says

> Set up rbenv in your shell.
> 
> $ ~/.rbenv/bin/rbenv init
> 
> Follow the printed instructions to set up rbenv shell integration.

But what I expected was an interactive setup guiding me through the setup of shell integration, like when setting up zsh.

I feel a little more specific printouts in the rbenv init command and a slightly more specific phrase in the README would help. Something like

> The command will automatically generate a static set of instructions for you to follow to set up rbenv shell integration

**Comment by capsulecorplab** [comment]
I've run into this issue on Ubuntu as well and would second something like @sdarwin's [suggestion](https://github.com/rbenv/rbenv/issues/1130#issuecomment-446906104). Also, pyenv has a similar setup with slightly more verbose instructions that might be worth imitating - see step 3 of https://github.com/pyenv/pyenv#basic-github-checkout.

**Comment by sdarwin** [comment]
> issue closed

btw, It seems like a confusing situation still remains. Instead of the README showing full instructions, for example:
```
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
```
and which you also recommended here: https://github.com/rbenv/rbenv/issues/1133

The README continues to provide only partial instructions, and a continued multi-step process:
```
$ rbenv init
**Follow the printed instructions** to set up rbenv shell integration.
```

**Comment by mislav** [comment]
> The README continues to provide only partial instructions, and a continued multi-step process:

You are correct. I don't see this as a problem. If you follow the instructions, you will have installed rbenv correctly.

**Comment by sdarwin** [comment]
> I don't see this as a problem. 

ok, it's your decision. 

From wikipedia:

> The principle of least astonishment (POLA), aka principle of least surprise (alternatively a law or rule),[1][2] applies to user interface and software design.[3] It proposes that a component of a system should behave in a way that most users will expect it to behave.

Usually, you expect instructions to guide you through the steps.  Ideally, until it's all set up.  And you don't expect the instructions to leave off one small step in the end, with a pointer that some people might gloss over.  in this case, the following command:

```
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
```
which is still part of the initial setup, and not mentioned in the readme.

**Comment by sdarwin** [comment]
Further explanation:  Let's say that someone is setting up rbenv, not the first time, but rather the 5th time, and after two years.   They basically understand how rbenv works, and prefer to just copy-and-paste the necessary commands, whether those are .bashrc or shell installation steps.  The natural place to look first, when trying to copy-and-paste a quick setup, is the documentation here.   But by hiding steps, the user is instead compelled to keep their own cheatsheet, so to speak.  Not a major issue or bug.  Ok.

**Comment by mislav** [comment]
> And you don't expect the instructions to leave off one small step in the end, with a pointer that some people might gloss over. in this case, the following command:
> 
> ```
> echo 'eval "$(rbenv init -)"' >> ~/.bashrc
> ```

Fortunately, we don't leave one crucial step in the end undocumented. From our documentation:

> 3\. Set up rbenv in your shell.
>
> ```
> $ ~/.rbenv/bin/rbenv init
> ```
> Follow the printed instructions to set up rbenv shell integration.

So if you read the step 3, run the given command, and follow the printed instructions, you will have set up rbenv shell integration completely. What you are suggesting is to just document step 3 slightly differently. I do not think that's an improvement.
