### ISSUE TITLE
Not able to use older versions of bundler in Ruby 2.6.0-rc1

### ISSUE THREAD

**Issue by everton** [rbenv/rbenv#1132]
Using Ruby 2.6.0-rc1 which now came with bundle  2.0.0 built in I'm not able to use older versions of bundler:

```sh
$ rbenv --version
rbenv 1.1.1-39-g59785f6

$ ruby --version
ruby 2.6.0rc1 (2018-12-06 trunk 66253) [x86_64-linux]

$ bundler --version
Bundler version 2.0.0

$ gem install bundler -v 1.17.1
Fetching bundler-1.17.1.gem
Successfully installed bundler-1.17.1
Parsing documentation for bundler-1.17.1
Installing ri documentation for bundler-1.17.1
Done installing documentation for bundler after 3 seconds
1 gem installed

$ bundle _1.17.1_ --version
Could not find command "_1.17.1_".

$ bundle --version
Bundler version 2.0.0
```

**Comment by everton** [comment]
I have opened this issue because it seems to be related with rbenv... on this post about the release of ruby it seems to be working properly within RVM:

> http://engineering.appfolio.com/appfolio-engineering/2018/11/26/bundler-is-built-into-ruby-260preview3

I don't know enough about the differences between rbenv and RVM to track what could possibly be the problem (but if I need to provide any more information, just say me what is needed).

**Comment by hsbt** [comment]
I couldn't rproduce it.

~ > ruby -v
ruby 2.6.0dev (2018-12-07 trunk 66266) +JIT [x86_64-darwin18]
~ > bundle -v
Bundler version 2.0.0
~ > which -a bundle
/Users/hsbt/.rbenv/shims/bundle
~ > gem i bundler
Fetching bundler-1.17.1.gem
Successfully installed bundler-1.17.1
1 gem installed
~ > bundle -v
Bundler version 2.0.0
~ > gem list | rg default: 
bigdecimal (default: 1.4.0.pre.20181204a)
bundler (default: 2.0.0, 1.17.1)
cmath (default: 1.0.0)
csv (default: 3.0.1)
date (default: 1.0.0)
dbm (default: 1.0.0)
e2mmap (default: 0.1.0)
etc (default: 1.0.1)
fcntl (default: 1.0.0)
fiddle (default: 1.0.0)
fileutils (default: 1.1.0)
forwardable (default: 1.2.0)
gdbm (default: 2.0.0)
io-console (default: 0.4.6)
ipaddr (default: 1.2.0)
irb (default: 0.9.6)
json (default: 2.1.0)
logger (default: 1.2.7)
matrix (default: 0.1.0)
mutex_m (default: 0.1.0)
openssl (default: 2.1.2)
ostruct (default: 0.1.0)
prime (default: 0.1.0)
psych (default: 3.1.0.pre2)
rdoc (default: 6.1.0.beta2)
rexml (default: 3.1.7.3)
rss (default: 0.2.7)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
shell (default: 0.7)
stringio (default: 0.0.2)
strscan (default: 1.0.0)
sync (default: 0.1.0)
thwait (default: 0.1.0)
tracer (default: 0.1.0)
webrick (default: 1.4.2)
zlib (default: 1.0.0)
~ > bundle _1.17.1_ -v
Bundler version 1.17.1
```

**Comment by everton** [comment]
Sorry, I think this was a problem with my "bin stub" of the executable (bin/bundle inside a Rails app).

When I saw your `which -a bundle` I was able to figure it out, really sorry and thanks.
