### ISSUE TITLE
rbenv shims path not set on Ubuntu 18.04

### ISSUE THREAD

**Issue by guangrei** [rbenv/rbenv#1133]
hi, few minutes ago i install rebenv with git and run `rbenv doctor`, all test passed except the shims path

I have follow instruction to run  `echo 'eval "$(rbenv init -)"' >> ~/.bashrc ` and restart the terminal but isn't fix the error

p.s: also installing goenv, phpenv, pyenv, and have no problem

**Comment by mislav** [comment]
Sorry you're having trouble! So far you're doing everything right; I'm not sure why the new line in your `~/.bashrc` isn't sourced. You haven't given us any information on what part of rbenv isn't working for you.

Open your `~/.bashrc` and check for the following lines:

```sh
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
```

Good luck! I'm gonna close this in favor of the related discussion in https://github.com/rbenv/rbenv/issues/1130#issuecomment-446906104.
