### ISSUE TITLE
Problem with /usr/bin/env ruby on Ubuntu 18

### ISSUE THREAD

**Issue by smartb-pair** [rbenv/rbenv#1137]
I'm having trouble getting set up on Ubuntu 18. When trying to execute a script, either with `bundle exec` or not, which starts with:
```
#!/usr/bin/env ruby -w
```
I get:
```
/usr/bin/env: ‘ruby -w’: No such file or directory
```

The result of `which ruby` is `.rbenv/shims/ruby` and both `.rbenv/shims` and `.rbenv/bin` and in my `$PATH`. It seems that in the context of the script `/usr/bin/env` is not working. I use Bash and running `/usr/bin/env ruby` in a terminal works fine.

I have trawled the internet for answers to this but have come up short, so any help would be massively appreciated. It doesn't feel like I am doing anything out of the ordinary and I am fairly sure I have followed the instructions accurately. I also tried this on another Ubuntu 18 machine with the same result, both freshly installed.

Thanks

**Comment by smartb-pair** [comment]
Just discovered that it works without the `-w` flag, so it's having any flags there that throws it off. Does anyone have any idea why this is happening?

**Comment by jasonkarns** [comment]
The `env` utility doesn't accept multiple arguments, just one (the interpreter, which would be `ruby` in this case). For more in-depth on the `env` utility, see https://unix.stackexchange.com/a/29620

I would expect `#!/usr/bin/env ruby -w` to fail for the same reason, even without rbenv installed (just having a ruby in `PATH`)

**Comment by smartb-pair** [comment]
OK found an explanation here https://stackoverflow.com/questions/3306518/cannot-pass-an-argument-to-python-with-usr-bin-env-python. Never mind!

**Comment by smartb-pair** [comment]
thanks @jasonkarns
