### ISSUE TITLE
ruby-build is not automatically installed when using homebrew to install rbenv

### ISSUE THREAD

**Issue by gazeldx** [rbenv/rbenv#1139]
Please check the part of here:

https://github.com/rbenv/rbenv/blob/master/README.md#homebrew-on-macos 

I need to install `ruby-build` manually by `brew install ruby-build` .

`brew install rbenv` will not install `ruby-build` .

FYI: My brew version is brew 0.9.5. It's an old version.

**Comment by hsbt** [comment]
We do only update our documentation. Because we are not the maintainer of formulae of rbenv and ruby-build. You can send a patch for it.

**Comment by jasonkarns** [comment]
@gazeldx Was this the first time you installed rbenv via homebrew on this machine? IIRC, homebrew remembers options, and the ruby-build inclusion used to be optional. So if you had installed it before --without-ruby-build, then it would likely preserve that option and continue to skip ruby-build.

**Comment by gazeldx** [comment]
It's a long time , so I don't remember whether I installed rbenv.
