### ISSUE TITLE
Path to gem binaries is not being updated

### ISSUE THREAD

**Issue by kurko** [rbenv/rbenv#114]
**The problem**

rbenv is not updating the PATH and gems' bins are not being mapped after installed.

**Reproducing**

I installed rspec and got a 'rspec: command not found' (same to other gems). So I went on to investigate and found out that rbenv is pointing to /Users/kurko/.rbenv/shims in the PATH. There are some bins, and `spec` is one of them (rails is there too).

I installed rspec 1.x on 1.8.7 before, that's why `spec` is in this directory. However, in my other mac, the problem happens with Spork gem (rspec too).

However, `sudo find / -name rspec` tells me the following was found:

```
/Users/kurko/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/bin/rspec
```

Including it manually to the PATH obviously solved the issue. However, rbenv should be doing this automatically on `rbenv global 1.9.2-p290`, or am I wrong? I mean, shouldn't the gems be installed to $HOME/.rbenv/shims/?

**Background info**

a) I do have `eval "$(rbenv init -)"` in my .bash_profile. b) I uninstalled rvm before, but I don't think it's related. c) I updated RubyGems.

**Comment by miriammuros** [comment]
Thanks so much! After 3 hours searching for this, I finally get it to work with that solution!

**Comment by Nakilon** [comment]
@bmarini after this shimed rspec became default in new Terminals (
