### ISSUE TITLE
rbenv-local doesn't respect RBENV_DIR

### ISSUE THREAD

**Issue by jasonkarns** [rbenv/rbenv#1142]
`rbenv-version-file` (which `rbenv-version` uses indirectly by way of `rbenv-version-name` and `rbenv-version-origin`) by default does its file lookup starting from `RBENV_DIR` and works up the hierarchy; falling back to `PWD`. (though, `RBENV_DIR` itself is defaulted to `PWD` by `rbenv`, if not already set in the environment, so in most cases the fallback is a noop)

However, `rbenv-local` explicitly forces the file lookup to only look from `PWD`, ignoring `RBENV_DIR` entirely. This leads to some dissonance in certain scenarios:

Given:

```
$ pwd
/tmp
$ cat /tmp/foo/.ruby-version 
2.5.1
$ export RBENV_DIR=/tmp/foo
$ rbenv version
2.5.1 (set by /tmp/foo/.ruby-version)
$ rbenv local
rbenv: no local version configured for this directory
```

So `rbenv-version` (and thus the rbenv itself when invoking a shim) considers the version to be set by a "local" file in the `RBENV_DIR` hierarchy, but `rbenv-local` reports "no local version set". Further, attempting to `rbenv-local --unset` would be a noop and would not delete the `.ruby-version` file found in `RBENV_DIR`; which is rather confusing. (I would expect `rbenv version` to be determined by the global version file immediately after `rbenv local --unset`; not continue to be determined by a local file.) The same inconsistency pertains to overwriting a local version or even creating one.

I traced through some history as it pertains to this behavior:

- Initially rbenv would read from `PWD` _and up_
- `rbenv-local` would only read/write/delete the file _directly_ in `PWD`
- Later, 07815769aeda3097f43d032fb31f6c89d1a7942f introduced `RBENV_DIR` such that `rbenv-version` would respect a specified directory other than `PWD` (`rbenv-local` still ignored `RBENV_DIR`)
- Later still, 6c1fb9ffd062ff04607d2e0f486067eaf6e48d1e added `PWD` as a fallback for `RBENV_DIR` (`rbenv-local` still ignored `RBENV_DIR`)
- ca252599007375ffbb3522a736a2a7a7d1eeccde prepared `rbenv-version-file` such that `rbenv-local` could leverage it
- then ba072adcb99a5c77df2a93afccdca59a23703696 changed `rbenv-local` to use `rbenv-version-file` for the local file lookup. This commit changed `rbenv-local` behavior to respect files found in the hierarchy, not only immediately in `PWD`. However, it still only uses `PWD` for the lookup.

So it seems that from the very introduction of `RBENV_DIR`, it wasn't respected consistently by rbenv's subcommands. However, each subsequent change reduced the dissonance somewhat. (first adding `PWD` as a fallback for `RBENV_DIR`; and later ensuring `rbenv-local` would look up the directory hierarchy just as `rbenv-version` did)

The only remaining inconsistency is that `rbenv-local` doesn't respect `RBENV_DIR` at all (if set). Is this agreed to be a bug and PR welcomed?

**Comment by mislav** [comment]
> So it seems that from the very introduction of `RBENV_DIR`, it wasn't respected consistently by rbenv's subcommands.

Excellent sleuthing. Yes, `RBENV_DIR` consistency wasn't great historically, but you have to understand that [the use-case for RBENV_DIR was very specific](https://github.com/rbenv/rbenv/blob/59785f6762e9325982584cdab1a4c988ed062020/libexec/rbenv-rehash#L55): making sure that `/path/to` was considered for looking up the current ruby version when you ran `ruby /path/to/myscript.rb`, even if the PWD was somewhere outside of `/path/to`. Because of such narrow use-case, we didn't care much if commands other than `rbenv-exec` (and dependents) had good support for RBENV_DIR.

If RBENV_DIR is what people are using nowadays for their scripts for whatever reason, then I would definitely support seeing a PR that fixes this for `rbenv-local`. However, what is the actual use for RBENV_DIR that made you discover this?

**Comment by mislav** [comment]
Well to close the gap, I have no objections to having `rbenv-local` respect RBENV_DIR when reading. Although, I still think it should _write_ exclusively to PWD.

**Comment by mislav** [comment]
I thank you for your prior in-depth research on this, but I have given this another thought and I am not so much in favor of making this change. It might be potentially confusing that `rbenv local` reports a version name that is dictated by a directory that isn't PWD or one of its parents. Let's have rbenv keep backwards compatibility when possible.
