### ISSUE TITLE
Change rubies dynamically per folder without using .ruby-version

### ISSUE THREAD

**Issue by calebmeyer** [rbenv/rbenv#1143]
We're in the process of migrating to ruby 2.6, now that it's been released. Unfortunately, the official guidance is to use RVM, and we've recently been forced to change all our .ruby-version files to have exactly `ruby-M.m` where M and m are the major and minor versions, respectively. RVM sees this and gives you the latest MRI that you have installed with that major and minor version.

Rbenv sees this and says "You don't have ruby-2.6 installed". I would love to change the .ruby-version, but I don't have that power anymore. I know I can do `rbenv shell 2.6.0` to change to 2.6.0, but that change is global for that shell, and must be repeated each time you open a new shell. It also doesn't help for projects that haven't been migrated to 2.6 yet.

So this is either a feature request (support RVM's behavior, ambiguous as it is), or a help request (does anyone know how to set/unset an environment variable per directory?).

Thanks for making rbenv, I really like the ergonomics way better than RVM and really don't want to switch. Oh, and feel free to change this title, I couldn't come up with a better one.

**Comment by jasonkarns** [comment]
There are a couple alternatives:

1. you could make a symlink in your `$(rbenv root)/versions` to make 2.6 -> 2.6.0 thus making `ruby-2.6` successfully match an installed version on your machine. (rbenv will find any "ruby" in the versions directory; including symlinks to other versions.)
2. you could use https://github.com/tpope/rbenv-aliases which is essentially an automated version of the above.
3. you could give https://github.com/rkh/rbenv-use a try which does on-demand fuzzy matching
4. As for setting an env var... you can wrap `cd` by making a function named `cd` which could set/unset the vars you like based on the directory as you enter/exit. (but I'd recommend against this)

As for the feature request... there have been a lot of similar feature requests for fuzzy matching and this project has decided against them in the past. I can't find the issues off hand, but the discussion has occurred and been closed a handful of times before.
