### ISSUE TITLE
Updating Ruby on macOS Mojave 10.14.2 using homebrew rbenv

### ISSUE THREAD

**Issue by emilianolowe** [rbenv/rbenv#1145]
My apologies if this issue has already been brought up as this is my first Github post. Don't kill me! 

when I type `ruby -v` I get `ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]`

I followed some instructions to troubleshoot the issue using the below guide:
https://github.com/rbenv/rbenv#how-rbenv-hooks-into-your-shell

However, when I execute the last command 'brew upgrade rbenv ruby-build'

This is what is returned: 
```
Error: rbenv 1.1.1 already installed
Error: ruby-build 20190130 already installed
```

I think the issue is that my path is messed up from originally starting with Python and then deciding to start with Ruby. 

Here is my $PATH:
` -bash: /Users/emilianolowe/.rbenv/shims:/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin: No such file or directory`

If someone could help me I would be really happy! 

Thanks,
Emiliano

**Comment by mislav** [comment]
Hi Emiliano,

You've done everything right so far. rbenv is installed. Now you just need to install a Ruby version with rbenv and change your global version away from "system".

Check your current state:

```sh
rbenv versions
```

Then install a new one:

```sh
rbenv install 2.6.1
rbenv global 2.6.1
ruby -v //=> "ruby 2.6.1..."
```
