### ISSUE TITLE
`version` and `versions` produces the same output

### ISSUE THREAD

**Issue by aaroncraigongithub** [rbenv/rbenv#1148]
On a clean install (MacOS Mojave 10.14.2) the `version` and `versions` commands are producing the same output.

```sh
~ » curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
Checking for `rbenv' in PATH: /usr/local/bin/rbenv
Checking for rbenv shims in PATH: OK
Checking `rbenv install' support: /usr/local/bin/rbenv-install (ruby-build 20190130)
Counting installed Ruby versions: none
  There aren't any Ruby versions installed under `/Users/aaroncraig/.rbenv/versions'.
  You can install Ruby versions like so: rbenv install 2.2.4
Checking RubyGems settings: OK
Auditing installed plugins: OK
~ » rbenv version
system (set by /Users/aaroncraig/.rbenv/version)
~ » rbenv versions
* system (set by /Users/aaroncraig/.rbenv/version)
```

My understanding of the docs is that `versions` would provide a list of ruby versions available for installation.

**Comment by jasonkarns** [comment]
Rbenv itself doesn't provide a mechanism to install rubies. That is
provided by ruby-build, which then adds the 'rbenv install' command. (If
you installed via homebrew, that will be installed automatically)

Rbenv version shows the ruby that is activated.
Rbenv versions lists all the rubies _installed_.

**Comment by mislav** [comment]
Plus, this part of the output should have helped clear things up:

```
Counting installed Ruby versions: none
  There aren't any Ruby versions installed under `/Users/aaroncraig/.rbenv/versions'.
  You can install Ruby versions like so: rbenv install 2.2.4
```

To list available versions to install, you can do `rbenv install -l`.

**Comment by aaroncraigongithub** [comment]
Just for posterity, the confusion grew from the `help` output:

```
versions    List all Ruby versions available to rbenv
```

`rbenv help versions` is much clearer

```
rbenv help versions
Usage: rbenv versions [--bare] [--skip-aliases]

Lists all Ruby versions found in `$RBENV_ROOT/versions/*'.
```

Thanks for the feedback
