### ISSUE TITLE
Rbenv command not found

### ISSUE THREAD

**Issue by cacocdj** [rbenv/rbenv#1152]
I try to download ruby 2.2.3 with rbenv and it says command is not found. 
I installed the ruby build with homebrew already and it still won't work. 
My bash.profile looks like this: if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

**Comment by mislav** [comment]
Sorry you're having issues! You haven't provided us with enough information about your setup, what you've tried, what failed etc. for us to help you. Please see https://github.com/rbenv/rbenv/wiki#how-to-verify-that-i-have-set-up-rbenv-correctly

This issue tracker is for reporting bugs with our software, not with requesting support for installing our software! I'm sure you can do it using provided documentation; good luck! 💪
