### ISSUE TITLE
Let's publish a new release!

### ISSUE THREAD

**Issue by chpatton013** [rbenv/rbenv#1153]
The previous release ([rbenv 1.1.1](https://github.com/rbenv/rbenv/releases/tag/v1.1.1)) was published on June 15, 2017. We're coming up on almost 2 years since then, and there's been quite a large number of improvements that many users aren't benefiting from. It would be great to get a more recent release tagged.

**Comment by mislav** [comment]
Okay! https://github.com/rbenv/rbenv/releases/tag/v1.1.2
