### ISSUE TITLE
ruby and gem fails with "cannot load such file -- ubygems"

### ISSUE THREAD

**Issue by alexkli** [rbenv/rbenv#1158]
With my ruby 2.6.3 (or 2.6.2) installed via a fresh rbenv installation from Homebrew I always get these errors and cannot run _any_ ruby code:
```
> ruby -v -e 'puts "hello"'
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
Traceback (most recent call last):
	1: from /Users/alex/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/alex/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- ubygems (LoadError)
```

or any `gem` command:

```
> gem
Traceback (most recent call last):
	1: from /Users/alex/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/alex/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- ubygems (LoadError)
```

`ruby -v` or `ruby -h` work, but that's it.

This is on OSX 10.14.3. I have the system ruby at `/usr/bin/ruby` version 2.3.7p456. Before I started, I had an older ruby1.9 lying around from MacPorts, which I uninstalled completely and then I did the following steps to install a fresh new rbenv & ruby (following [instructions from jekyll](https://jekyllrb.com/docs/installation/macos/)):

```
brew install rbenv
# add rbenv init to my ~/.profile
# run rbenv-doctor, all OK
# new terminal
rbenv install 2.6.3
rbenv global 2.6.3
```

I even uninstalled everything and installed it again, just leading to the exact same problem.

Googling wasn't very helpful, only cases where certain apps were not updated for the `ubygems` change, but I couldn't find anyone where this happens for _all_ ruby commands. 

This leads me to suggest that something on my system is interfering - like a left-over config file from previous ruby installations etc. However, I was not able to find out which code is even calling the problematic `require`. I modified `~/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb` to print the `caller` but for the `require ubygems` it's nil. Also looked at an strace (fs_usage on osx) to see what files ruby loads but all of them seem to be in `~/.rbenv`, which I just wiped & installed from scratch.

Any ideas? Any config files to look for?

**Comment by hsbt** [comment]
It's intentional changes of ruby core. `ubygems.rb` has been removed from ruby.

**Comment by alexkli** [comment]
@hsbt This is on a fresh installation via `rbenv`. Plain ruby commands such as `gem` DO NOT work, see above. There is NO code from me or anything involved, apart from what gets installed by `rbenv` (at least nothing that I deliberately do).

My goal is to just installing a newer version of `ruby` to install & run Jekyll, but I can't even run the `gem install jekyll` command since `gem` fails.

**Comment by hsbt** [comment]
This is not rbenv issues.

**Comment by alexkli** [comment]
I don't know where the problem lies. Either rbenv 1.1.2 has a bug under certain conditions or it's some config file that rbenv apparently does _not_ control and that has an impact on ruby.

Any help where to look would be appreciate - what even can automatically load `ubygems` for `ruby -e` or `gem` in a 2.6.x

**Comment by alexkli** [comment]
Same problem with ruby 2.5.5 installed via `rbenv install 2.5.5`.

**Comment by alexkli** [comment]
Found the issue: I had a very old

```export RUBYOPT=-rubygems```

deep in my `~/.profile`, probably from ~10 years ago.
