### ISSUE TITLE
cannot load such file -- irb

### ISSUE THREAD

**Issue by maayannaveh** [rbenv/rbenv#1166]
Hello,
I recently installed a fresh installation of Ubuntu, and used this guide to install rbenv: https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-with-rbenv-on-ubuntu-18-04

Ever since, irb command is not working.
It appeared to be installed:

maayan@maayan:~/apps/makerspro$ which irb
/home/maayan/.rbenv/shims/irb
maayan@maayan:~/apps/makerspro$ rbenv which irb
/home/maayan/.rbenv/versions/2.6.3/bin/irb

but this is the output I get:

maayan@maayan:~/apps/makerspro$ irb
Traceback (most recent call last):
	1: from /home/maayan/.rbenv/versions/2.6.3/bin/irb:23:in `<main>'
/home/maayan/.rbenv/versions/2.6.3/bin/irb:23:in `load': cannot load such file -- /home/maayan/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb (LoadError)

**Comment by mislav** [comment]
Does the file referenced in the error message exist?

```
$ file ~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb
/Users/mislav/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb: Ruby script text executable, ASCII text
```

If not, it sounds like a broken Ruby 2.6.3 installation. I'm not sure how that could have happened during `rbenv install 2.6.3`, unless it exited with an error. Did you notice anything off during the installation?

In any case, this is not a bug with rbenv. If anything, it's a bug with Ruby's own installer and its default gems. Try this to fix it:

```console
RBENV_VERSION=2.6.3 gem install irb
```

**Comment by maayannaveh** [comment]
Thank you so much, Mislav!
I didn't notice anything off in the installation, but installing it manually with the command your provided did the trick.
My apologies :)

**Comment by enowmbi** [comment]
Hi, I tried the solution above and it gave the following error:
![Screenshot from 2020-05-24 02-59-22](https://user-images.githubusercontent.com/22540470/82743998-ca0a7a80-9d6a-11ea-84c1-63cc457bf155.png)

**Comment by jonathanschlue-as** [comment]
> Hi, I tried the solution above and it gave the following error:

For me the following solved the problem:

```
rbenv uninstall 2.7.0
rbenv install 2.7.0
```
