### ISSUE TITLE
install --list is limited

### ISSUE THREAD

**Issue by graial** [rbenv/rbenv#1170]
Hi there,
I'm using rbenv 1.1.2-2-g4e92322  (pulled from github 20 mins ago)
my machine is running Linux Mint 18.3

rbenv install --list returns an out of date list of available options:
<truncated>
  2.4.0-rc1
  2.4.0
  2.4.1
  2.4.2
  2.4.3
  2.4.4
  2.5.0-dev
  2.5.0-preview1
  2.5.0-rc1
  2.5.0
  2.5.1
  2.6.0-dev
  2.6.0-preview1
  2.6.0-preview2
<truncated - start of jruby>

Which means that I can't install the LTS versions of Ruby (2.5.5 or 2.6.3)

What options do I have for tracking down this issue?

**Comment by mislav** [comment]
To track down this issue, first you might observe the README in this repo: https://github.com/rbenv/rbenv#installing-ruby-versions

Then after following the link to the ruby-build repo: https://github.com/rbenv/ruby-build#upgrading

Or, additionally: https://github.com/rbenv/ruby-build/wiki#updating-ruby-build

**Comment by graial** [comment]
Ok, yes you're right.  I'd only updated rbenv but not ruby-build.  Updating ruby-build gave me the updated list.

Thank you!
