### ISSUE TITLE
not able to use bundle with system version

### ISSUE THREAD

**Issue by Ana06** [rbenv/rbenv#1172]
I am not able to use bundle with the system version. It does work for versions installed with ruby-build + rbenv and if I call `bundle.ruby2.5` (my local version is 2.5). See:

```
ana@localhost:~> rbenv shell 2.4.6
ana@localhost:~> bundle
rbenv: bundle: command not found

The `bundle' command exists in these Ruby versions:
  2.6.2

ana@localhost:~> gem install bundle
Fetching: bundler-2.0.2.gem (100%)
Successfully installed bundler-2.0.2
Fetching: bundle-0.0.1.gem (100%)
Successfully installed bundle-0.0.1
Parsing documentation for bundler-2.0.2
Installing ri documentation for bundler-2.0.2
Parsing documentation for bundle-0.0.1
Installing ri documentation for bundle-0.0.1
Done installing documentation for bundler, bundle after 3 seconds
2 gems installed
ana@localhost:~> bundle
Could not locate Gemfile
ana@localhost:~> rbenv shell system
ana@localhost:~> sudo gem install bundle
Successfully installed bundle-0.0.1
Parsing documentation for bundle-0.0.1
Done installing documentation for bundle after 0 seconds
1 gem installed
ana@localhost:~> bundle
rbenv: bundle: command not found

The `bundle' command exists in these Ruby versions:
  2.4.6
  2.6.2

ana@localhost:~> bundle.ruby2.5 
Could not locate Gemfile
```

operative system: openSUSE Leap 15.1
ruby-build version: 20190401
rbenv version: 1.1.1

Not sure if the problem is in rbenv or ruby-build.

**Comment by mislav** [comment]
As far as I can see, there is no bug in rbenv nor in ruby-build.

You have installed the `bundle` command in the following Ruby versions: `2.4.6` and `2.6.2`. When either of these versions are activated, running `bundle` will work.

In the `system` version, there is no `bundle` installed, but there is `bundle.ruby2.5` as installed on your system. Running it will work when `system` rbenv version is activated.

Finally, for any of the `bundle` (or `bundle.ruby2.5`) commands to work in your project, you will need a `Gemfile`. This I can't help you with, but you can read more about here: https://bundler.io/man/gemfile.5.html

**Comment by Ana06** [comment]
@mislav

> As far as I can see, there is no bug in rbenv nor in ruby-build.

I think there is. **Running bundle when using the system version doesn't work** (with out without installing bundle, which as you say is in my system already in `/usr/bin/bundle.ruby2.5`). This piece of code (which is a part of the code above illustrate it):

```
ana@localhost:~> rbenv shell system
ana@localhost:~> sudo gem install bundle
Successfully installed bundle-0.0.1
Parsing documentation for bundle-0.0.1
Done installing documentation for bundle after 0 seconds
1 gem installed
ana@localhost:~> bundle
rbenv: bundle: command not found

The `bundle' command exists in these Ruby versions:
  2.4.6
  2.6.2
```

> Finally, for any of the bundle (or bundle.ruby2.5) commands to work in your project, you will need a Gemfile. You are missing one (or you are not cdd in the right directory), as evident by “Could not locate Gemfile”. This I can't help you with, but you can read more about here: https://bundler.io/man/gemfile.5.html

I am missing the Gemfile on purpose. I didn't want to paste a long output to demostrate that in that case it is working. `Could not locate Gemfile` is in this case a synonim for `bundle is working`. But as said it works for all version except the system one.
