### ISSUE TITLE
Getting `curl: (35) Server aborted the SSL handshake` when trying to install ruby in OS X 10.14.6

### ISSUE THREAD

**Issue by fplgusmao** [rbenv/rbenv#1179]
I am trying to install version 2.3.5, but when I do `rbenv install 2.3.5 -v` I'm getting

```
ruby-build: use openssl from homebrew
/var/folders/m6/8l974j3s7_74qwg0kytvnng40000gp/T/ruby-build.20190828144130.3475 ~
Downloading ruby-2.3.5.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.5.tar.bz2
curl: (35) Server aborted the SSL handshake
error: failed to download ruby-2.3.5.tar.bz2

BUILD FAILED (OS X 10.14.6 using ruby-build 20190423)
```

I've looked all over the internet by now, but I can't really connect others' problems with mine

**Comment by fplgusmao** [comment]
UPDATE:

For some reason my default DNS server, and also 1.1.1.1, weren't working. Changed to google's DNS and it worked.

**Comment by hotsoft-desenv2** [comment]
@fplgusmao Thanks... I see similar problem.. Solved disabling the IPv6... 

Testing using nslookup, modern resolver can use IPv6.
And something in the CDN isn't configured correctly for IPv6.
