### ISSUE TITLE
Insecure world writable 

### ISSUE THREAD

**Issue by shafali03** [rbenv/rbenv#1187]
Whenever I run my terminal inside the console or visual studio code, I receive a warning message.

`/usr/lib/ruby/vendor_ruby/rake/file_utils.rb:54: warning: Insecure world writable dir /home/shaf/.rbenv/libexec in PATH, mode 040777
/usr/lib/ruby/vendor_ruby/rbnacl/libsodium/version.rb:5: warning: Insecure world writable dir /home/shaf/.rbenv/libexec in PATH, mode 040777`

I believe my path is wrong in the directory not sure how to solve the problem

**Comment by mislav** [comment]
This warning isn't coming from rbenv, and as such isn't an rbenv issue.

1. You can either find out what produces the warning and disable it; or
2. You can make the directory non-world-writable: `chmod go-w ~/.rbenv/libexec`.

**Comment by shafali03** [comment]
Thanks for the update and the tip
