### ISSUE TITLE
Creating a gemset for a specific project?

### ISSUE THREAD

**Issue by JHero23** [rbenv/rbenv#1188]
Does it have a feature that creates gemsets for specific projects?

I know in RVM they use `rvm use --create 2.0.0@training` to create a gemset with the ruby version 2.0.0 for the project "training". I would like to know what is the equivalent command for rbenv gemsets? And do you have an example of how to use it before/after making the project?

**Comment by jasonkarns** [comment]
There is a plugin that purports to offer gemset support: https://github.com/jf/rbenv-gemset (see wiki for other plugins https://github.com/rbenv/rbenv/wiki/Plugins)

However, gemsets aren't typically necessary now that bundler is available and the common mechanism for managing project dependencies. (And even less so in recent versions of ruby where bundler itself is included in ruby.)
