### ISSUE TITLE
Error looking for openssl in previously installed ruby?

### ISSUE THREAD

**Issue by gfguthrie** [rbenv/rbenv#1197]
First off I'll admit this is a bit of a contrived situation, but I can't find where in the code this is happening – so I'm creating this issue in the hopes that someone can point me in the right direction. Mostly for my curiosity, then to see if a solution should/can be created.

I had previously installed 2.5.5 with Homebrew `openssl@1.1`, then uninstalled `openssl@1.1`. Next step was to run `rbenv install 2.6.0-dev`. Got the following error in the log:

```
...
Configuring OpenSSL version 1.1.0j (0x101000afL)
...
Cloning into 'ruby-2.6.0-dev'...
Updating files: 100% (9038/9038), done.
/var/folders/rg/0v_97xsx6gj600wz5jq6_6440000gn/T/ruby-build.20191109121454.90268.rqoqTW/ruby-2.6.0-dev /var/folders/rg/0v_97xsx6gj600wz5jq6_6440000gn/T/ruby-build.20191109121454.90268.rqoqTW ~/Projects/homebrew-core
checking for ruby... /Users/gfguthrie/.rbenv/shims/ruby
*** using http instead of https ***
downloading config.guess ... /Users/gfguthrie/.rbenv/versions/2.5.5/lib/ruby/2.5.0/openssl.rb:13:in `require': dlopen(/Users/gfguthrie/.rbenv/versions/2.5.5/lib/ruby/2.5.0/x86_64-darwin17/openssl.bundle, 9): Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib (LoadError)
  Referenced from: /Users/gfguthrie/.rbenv/versions/2.5.5/lib/ruby/2.5.0/x86_64-darwin17/openssl.bundle
  Reason: image not found - /Users/gfguthrie/.rbenv/versions/2.5.5/lib/ruby/2.5.0/x86_64-darwin17/openssl.bundle
```

**Comment by mislav** [comment]
> I had previously installed 2.5.5 with Homebrew `openssl@1.1`, then uninstalled `openssl@1.1`

You had broken your ruby 2.5.5, and then you tried to use it to build `2.6.0-dev` (the latter needs a host ruby to install). This resulted in an error.

Since you are on macOS, you always have a working system ruby by default. You can use it to install `2.6.0-dev`:

```sh
RBENV_VERSION=system rbenv install 2.6.0-dev
```

**Comment by gfguthrie** [comment]
Figured it was something like "needs a working ruby to install" – thanks!
