### ISSUE TITLE
You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.

### ISSUE THREAD

**Issue by tmcjunkinmarquis** [rbenv/rbenv#1208]
_Originally posted by @mislav in https://github.com/rbenv/rbenv/issues/1207#issuecomment-574261566_

I have recently started a new Mac running Catalina with .zsh.  In a new project, `gem install budler` returns:
You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.

Please offer any help for this problem or allow me to clarify if you need further information.  Thanks!

I run `gem env home`:
/Library/Ruby/Gems/2.6.0

I run `rbenv global`:
system

I run `rbenv shell`:
rbenv: no shell-specific version configured

I run `rbenv init -`:
```
export PATH="/Users/theresamarquis/.rbenv/shims:${PATH}"
export RBENV_SHELL=zsh
source '/usr/local/Cellar/rbenv/1.1.2/libexec/../completions/rbenv.zsh'
command rbenv rehash 2>/dev/null
rbenv() {
  local command
  command="${1:-}"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "$(rbenv "sh-$command" "$@")";;
  *)
    command rbenv "$command" "$@";;
  esac
}
```

I run `echo $PATH`:
```
/Users/theresamarquis/.rbenv/shims:
/Users/theresamarquis/.rbenv/bin:
/Users/theresamarquis/.rbenv/shims:
/Users/theresamarquis/.rbenv/bin:
/usr/local/bin:
/usr/bin:
/bin:
/usr/sbin:
/sbin:
/Applications/Postgres.app/Contents/Versions/latest/bin:
/Users/theresamarquis/.rbenv/bin:
/Users/theresamarquis/.rbenv/shims
```

I look at /etc/paths:
```
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```

Running rbenv-doctor with `curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash` returns:
```
Checking for `rbenv' in PATH: /usr/local/bin/rbenv
Checking for rbenv shims in PATH: OK
Checking `rbenv install' support: /usr/local/bin/rbenv-install (ruby-build 20200115)
Counting installed Ruby versions: 1 versions
Checking RubyGems settings: OK
Auditing installed plugins: OK
```

 `.zshrc` contains:
```
source $HOME/.zshenv
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
```

`.zshenv` contains:
```
export PATH="$HOME/.rbenv/bin:$PATH"
```

**Comment by mislav** [comment]
Hi, thank you for providing info, and I'm sorry you're having trouble!

I'm sure solving your problem should be as easy as switching away from the default "system" version, which doesn't let you install gems. You haven't provided the output of `rbenv versions`, but from the output of doctor script, it looks like you have at least 1 version installed.

Assuming for example that you have Ruby `2.6.5` installed, what you would do in your new project is type:
```
rbenv local 2.6.5
```

Now whenever you are in this project directory, Ruby 2.6.5 will be used for commands like `ruby`, `rake`, `bundle`, etc. (You might need to `gem install bundler` if `bundle` is unavailable.)

Let us know if this worked, and please close this issue once you've resolved it! Thank you 🙇 

* * * 

Side note: when pasting code or terminal output into GitHub comments, you can enclose that in triple backticks (on their own line) to have it displayed as code blocks:

    ```
    {your pasted stuff goes here}
    ```

I've amended your above comment with this to make it more readable. 👍

**Comment by tmcjunkinmarquis** [comment]
Thanks.  I think it is corrected.
