### ISSUE TITLE
Disable sourcing fish completions

### ISSUE THREAD

**Issue by msanders** [rbenv/rbenv#1212]
Fish vendors rbenv completions [by default](https://github.com/fish-shell/fish-shell/blob/1aa0dfe91bc5382220ba2f170bff525501d13908/share/completions/rbenv.fish).  Would it be worth turning off the redundant sourcing included in `rbenv init -`? Currently it looks like this:

```
set -gx PATH '/Users/mks/.rbenv/shims' $PATH
set -gx RBENV_SHELL fish
source '/usr/local/Cellar/rbenv/1.1.2/libexec/../completions/rbenv.fish'
command rbenv rehash 2>/dev/null
function rbenv
  set command $argv[1]
  set -e argv[1]

  switch "$command"
  case rehash shell
    source (rbenv "sh-$command" $argv|psub)
  case '*'
    command rbenv "$command" $argv
  end
end
```

On my machine, the line sourcing completions adds a slight delay to each shell instance, whereas the vendored completions are lazy-loaded.

**Comment by mislav** [comment]
Thank you for pointing that out!
