### ISSUE TITLE
The rbenv is totally broken in the latest commit, and broke the system

### ISSUE THREAD

**Issue by gusbemacbe** [rbenv/rbenv#1221]
Hello,

- In the past, I installed manually `rbenv`.
- The updated `rbenv` is broken:

```
sql_escape:1: write failed: no space left on device
sql_escape:1: write failed: no space left on device
```

I tried to reinstall rbenv, but it also gave the same error, and another error:

```
make: Entering directory '/home/gusbemacbe/.rbenv/src'
gcc -fPIC     -c -o realpath.o realpath.c
realpath.c:43:1: fatal error: error closing /tmp/ccSevGxn.s: No space left on device
   43 | };
      | ^
compilation terminated.
make: *** [Makefile:19: realpath.o] Error 1
```

With rbenv-doctor:

```
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
sql_escape:1: write failed: no space left on device
sql_escape:1: write failed: no space left on device
Checking for `rbenv' in PATH: /home/gusbemacbe/.rbenv/bin/rbenv
Checking for rbenv shims in PATH: OK
Checking `rbenv install' support: bash: line 100: cannot create temp file for here-document: No space left on device
```

**Comment by gusbemacbe** [comment]
After another reinstallation and with the uninstallation of Ruby packages from Chinese Arch Linux repository, the same error is still there:

```
rbenv install 2.2.0
sql_escape:1: write failed: no space left on device
sql_escape:1: write failed: no space left on device
/home/gusbemacbe/.rbenv/plugins/ruby-build/bin/ruby-build: line 1295: cannot create temp file for here-document: No space left on device
/home/gusbemacbe/.rbenv/plugins/ruby-build/bin/ruby-build: line 199: pushd: write error: No space left on device
Downloading ruby-2.2.0.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.0.tar.bz2
error: failed to download ruby-2.2.0.tar.bz2

BUILD FAILED (Arch Linux using ruby-build 20200218)

Inspect or clean up the working tree at /tmp/ruby-build.20200219063719.274963.iPOTh7
zsh: exit 1
```

**Comment by mislav** [comment]
Could it be possible that you have no space left on your filesystem?

I'm not sure what an `sql_escape` error is, but it isn't coming from rbenv since it doesn't have any component called "sql_escape".

**Comment by gusbemacbe** [comment]
> Could it be possible that you have no space left on your filesystem?

![image](https://user-images.githubusercontent.com/2257024/74903055-9a705e80-5386-11ea-8484-e4a68c379bc7.png)

They were always free. But I understood what happened. It is `esy` package which broke `rbenv` and Ruby, and occupied the whole `opt` folder. I uninstalled `esy` and `revery` and I had to reboot. The rbenv and Ruby reverted to the normal.
