### ISSUE TITLE
shims take ~70ms ... can this be reduced ?

### ISSUE THREAD

**Issue by grosser** [rbenv/rbenv#1223]
```
time -p ~/.rbenv/shims/ruby -v
real 0.07
user 0.02
sys 0.04
```

```
time -p ~/.rbenv/versions/2.6.3/bin/ruby -v
real 0.01
user 0.00
sys 0.00
```

... maybe some short-circuit logic for common usecases, like sitting in the directory that has a .ruby-version or $RBENV_VERSION being set

something clunky like this on top of the `~/.rbenv/shims/ruby`:
```bash
# short-circuit for common path
bin=~/.rbenv/versions/${RBENV_VERSION:-$(cat .ruby-version 2>/dev/null)}/bin/$(basename $0)
if [ -e $bin ]; then
  exec $bin "$@"
fi
```
takes it down to 10ms overhead for example

**Comment by mislav** [comment]
Yes, shims add some overhead 
```
Benchmark #1: /Users/mislav/.rbenv/versions/2.7.0/bin/ruby -e0
  Time (mean ± σ):      89.4 ms ±   7.3 ms    [User: 62.4 ms, System: 23.5 ms]
  Range (min … max):    82.2 ms … 115.9 ms    50 runs

Benchmark #2: /Users/mislav/.rbenv/shims/ruby -e0
  Time (mean ± σ):     177.3 ms ±   5.9 ms    [User: 85.2 ms, System: 86.7 ms]
  Range (min … max):   170.0 ms … 196.8 ms    50 runs
```

It's due to slowness of bash and its not easily fixable. The solution like you proposed above will work for the simplest "happy" case but will sacrifice some other rbenv features.

You might want to try chruby instead of rbenv if this is a deal-breaker for you.
