### ISSUE TITLE
bash: /home/darkplex/.bashrc: line 171: syntax error near unexpected token `PATH="$HOME/.rbenv/bin:$PATH"'

### ISSUE THREAD

**Issue by abdulmf** [rbenv/rbenv#1230]
Hi,
I was trying to Install Ruby via rbnev but I couldnt get pass this error
I was trying to follow [theodinproject](https://www.theodinproject.com/courses/web-development-101/lessons/installing-ruby) method 
Ps.note: I'm using Elemantary OS (hera)

> bash: /home/darkplex/.bashrc: line 171: syntax error near unexpected token `PATH="$HOME/.rbenv/bin:$PATH"'
> bash: /home/darkplex/.bashrc: line 171: `esacexport PATH="$HOME/.rbenv/bin:$PATH"'

Can you please help me with this

?

**Comment by mislav** [comment]
It looks like you have a syntax error in your bash configuration file. This is not a bug with the rbenv project.

There is a word that looks like `esacexport`. These should be two words, each on their own line:

```sh
esac
export PATH="$HOME/.rbenv/bin:$PATH"'
```

**Comment by abdulmf** [comment]
Thankyou so much Mislav, Do you know how it can be fixed.

**Comment by abdulmf** [comment]
Thankyou so much Mislav

**Comment by qazidanishayub** [comment]
issue in the elementary os 

How I fixed my problem:

In the file /home/username/.bashrc , line 171:
esac# added by Anaconda3 2018.12 installer'

should be corrected to:
esac # added by Anaconda3 2018.12 installer'

**Comment by qazidanishayub** [comment]
issue in the elementary os 

How I fixed my problem:

In the file /home/username/.bashrc , line 171:
esac# added by Anaconda3 2018.12 installer'

should be corrected to:
esac # added by Anaconda3 2018.12 installer'

**Comment by qazidanishayub** [comment]
issue in the elementary os 

How I fixed my problem:

In the file /home/username/.bashrc , line 171:
esac# added by Anaconda3 2018.12 installer'

should be corrected to:
esac # added by Anaconda3 2018.12 installer'

**Comment by qazidanishayub** [comment]
issue in the elementary os 

How I fixed my problem:

In the file /home/username/.bashrc , line 171:
esac# added by Anaconda3 2018.12 installer'

should be corrected to:
esac # added by Anaconda3 2018.12 installer'

**Comment by qazidanishayub** [comment]
issue in the elementary os 

How I fixed my problem:

In the file /home/username/.bashrc , line 171:
esac# added by Anaconda3 2018.12 installer'

should be corrected to:
esac # added by Anaconda3 2018.12 installer'

**Comment by qazidanishayub** [comment]
issue in the elementary os 

How I fixed my problem:

In the file /home/username/.bashrc , line 171:
esac# added by Anaconda3 2018.12 installer'

should be corrected to:
esac # added by Anaconda3 2018.12 installer'

**Comment by qazidanishayub** [comment]
**issue in the elementary os** 

How I fixed my problem:

In the file /home/username/.bashrc , line 171:
esac# added by Anaconda3 2018.12 installer'

should be corrected to:
esac # added by Anaconda3 2018.12 installer'

**Comment by qazidanishayub** [comment]
**issue in the elementary os** 

How I fixed my problem:

In the file /home/username/.bashrc , line 171:
esac# added by Anaconda3 2018.12 installer'

should be corrected to:
esac # added by Anaconda3 2018.12 installer'
