### ISSUE TITLE
Am very new to Ruy and rbenv, problems with disable rbenv

### ISSUE THREAD

**Issue by Vlasko** [rbenv/rbenv#1234]
Can someone explain to me how to do this?

"simply remove the `rbenv init` line from your shell startup configuration"

From this section https://github.com/rbenv/rbenv#uninstalling-rbenv

**Comment by jasonkarns** [comment]
In the installation directions you'll see a step to run `rbenv init` and to do what it says.

ie:
```
$ rbenv init
# Load rbenv automatically by appending
# the following to ~/.bashrc:

eval "$(rbenv init -)"
```

(The output of this is shell and environment specific, so exact output may vary.)

So a complete installation would have this line: `eval "$(rbenv init -)"` in my `~/.bashrc` file. Therefore, _uninstalling_ would require that I remove that line from the file.

**Comment by mislav** [comment]
Agreed with @jasonkarns: the "shell configuration files" are various files found in your home directory, such as `~/.bashrc` and `~/.bash_profile` for bash or `~/.zshrc` for zsh. Just edit those files, remove any mention of "rbenv" from them, restart your shell (typically by closing and reopening your terminal window), and you're done.
