### ISSUE TITLE
Ruby installation

### ISSUE THREAD

**Issue by chriP2020** [rbenv/rbenv#1237]
hi there,I am in  the process of installing ruby through the terminal on my linux machine.
but before I install ruby, I need to run this command: rbenv -v, but when run it, I got the message: rbenv: no such command `–v'

is there any to get this right please

**Comment by jasonkarns** [comment]
The character you pasted in this issue is not a hyphen/dash but is in fact an en-dash. (&ndash;) Did you copy that from somewhere online, perhaps?

Replace the en-dash with a plain hyphen and it should work as expected: 

```
$ rbenv -v
rbenv 1.1.2-gc2cfbd1
```
