### ISSUE TITLE
You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.

### ISSUE THREAD

**Issue by severous16598** [rbenv/rbenv#1238]
Hi, I am unable to procure write permission for the gems installation tried using --user-install, but am unable to run the executables

If you can please help me with the situation

You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.

**Comment by mislav** [comment]
Try installing and switching to a Ruby version that is not `system`. With the system Ruby version you will always have the problem that you're experiencing, so it's best to use rbenv to switch away from it. https://github.com/rbenv/rbenv/issues/1208#issuecomment-577119028 https://github.com/rbenv/rbenv/issues/1207#issuecomment-591376105

**Comment by severous16598** [comment]
Hey Mislav, I installed ruby again on the system but I had set it as the global ruby version, would that be a reason?

**Comment by jasonkarns** [comment]
The 'system' ruby lives outside of rbenv's control and will very likely attempt to write to directories that are not writable without `sudo`. One of the benefits of using rbenv to manage rubies is that all the rubies are contained within the RBENV_ROOT directory and rbenv can help ensure writability for all subdirectories. Whatever the configuration you have for ruby or rubies installed outside of rbenv are not something that we can provide support for.

**Comment by fpigeonjr** [comment]
> Try installing and switching to a Ruby version that is not `system`. With the system Ruby version you will always have the problem that you're experiencing, so it's best to use rbenv to switch away from it. [#1208 (comment)](https://github.com/rbenv/rbenv/issues/1208#issuecomment-577119028) [#1207 (comment)](https://github.com/rbenv/rbenv/issues/1207#issuecomment-591376105)

This worked for me after running `brew install ruby`

` echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.zshrc`
