### ISSUE TITLE
Unable to run `ruby` with rbenv installed

### ISSUE THREAD

**Issue by idrisr** [rbenv/rbenv#1239]
OS: MacOS Catalina 10.15.3
Installation method: git install. commit: c2cfbd1e8b990f207a30cf7e190949a333a4e468

Everything seems to be setup correctly as far as the $PATH is concerned. `rbenv which ruby` points to an executable I can run with no issues. But when running just `ruby`, the process exits immediately with an exit code 1.

```
 ➜ which ruby
/Users/id/.rbenv/shims/ruby

 ➜ zsh --version
zsh 5.7.1 (x86_64-apple-darwin19.0)

 ➜ echo $PATH | tr : "\n"
/Users/id/.rbenv/shims
/usr/local/opt/coreutils/libexec/gnubin
/Users/id/.rbenv/bin
/usr/bin
/bin
/usr/sbin
/usr/local/bin
/usr/X11/bin
/Users/id/.fastlane/bin
/Applications/Visual Studio Code.app/Contents/Resources/app/bin

 ➜ rbenv which ruby
/Users/id/.rbenv/versions/2.6.3/bin/ruby

 ➜ ./.rbenv/versions/2.6.3/bin/ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]

 ➜ ruby # this fails with exit code 1
```

**Comment by mislav** [comment]
Thanks for the report and for the detailed information!

From what you pasted, everything seems to be set up correctly. I don't know why `ruby` fails immediately with an error code. Some things to try:

1. Are there any rbenv plugins? See `ls $(rbenv root)/plugins`
2. You can run `RBENV_DEBUG=1 ruby` to enable verbose output and potentially spot where rbenv is failing.
