### ISSUE TITLE
Ruby executable is nowhere to be found

### ISSUE THREAD

**Issue by grosser** [rbenv/rbenv#124]
Ruby install worked, and local/global switching return success,
but ruby executable is not in rbenv bin folder

``
[~] ➔ ls ~/.rbenv/versions/1.9.3-rc1/bin/r
rake  rdoc  ri    ruby  
[~] ➔ rbenv local 1.9.3-rc1
[~] ➔ ruby -v
The program 'ruby' can be found in the following packages:
- ruby1.8
- ruby1.9.1
  Try: sudo apt-get install <selected package>
  [~] ➔ ls -al ~/.rbenv/bin/
  total 24
  drwxrwxr-x 2 micha micha 4096 2011-10-17 15:39 .
  drwxr-xr-x 9 micha micha 4096 2011-10-17 16:32 ..
  lrwxrwxrwx 1 micha micha   16 2011-10-17 15:39 rbenv -> ../libexec/rbenv
  -rwxrwxr-x 1 micha micha  495 2011-10-17 15:39 ruby-local-exec

```
```

**Comment by ErikAGriffin** [comment]
It is my understanding that **rbenv init** is supposed to add `~/.rbenv/shims` to my $PATH variable, but it was not doing so on my Ubuntu 14.04 server.  Instead it was adding `~/.rbenv/bin` and thus **ruby --version** was not working until I manually added the shims to my path.  Is this a bug?
