### ISSUE TITLE
Error in installation of Ruby Rails

### ISSUE THREAD

**Issue by Howdygit19** [rbenv/rbenv#1246]
gem install rails
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.

**Comment by mislav** [comment]
Hi, you still have "system" Ruby version selected, but you generally shouldn't install new gems using that version.

Instead, install a Ruby version like so `rbenv install 2.7.1`, make it the default in rbenv `rbenv global 2.7.1`, and now you can install gems.
