### ISSUE TITLE
rbenv doesn't get correct version in tmux

### ISSUE THREAD

**Issue by ilake** [rbenv/rbenv#1252]
When I in a project folder with file `.ruby-version`, `rbenv version` returns correct ruby version from the project `.ruby-version`, but when I get into tmux,  it always returns the global ruby version.

When I run `RBENV_DEBUG=1 rbenv version`, without tmux, it found the correct local path, it was project path.

```
+ [rbenv-version-file:22] '[' -n '' ']'
+ [rbenv-version-file:25] find_local_version_file /Users/user_name/project_folder
+ [rbenv-version-file:10] local root=/Users/user_name/project_folder
+ [rbenv-version-file:11] [[ /Users/user_name/project_folder =~ ^//[^/]*$ ]]
+ [rbenv-version-file:12] '[' -s /Users/user_name/project_folder/.ruby-version ']'
+ [rbenv-version-file:13] echo /Users/user_name/project_folder/.ruby-version
+ [rbenv-version-file:14] return 0
+ [rbenv-version:11] echo '2.5.7 (set by /Users/user_name/project_folder/.ruby-version)'
```
But in tmux, it got wrong local path, it was home path.

```
+ [rbenv-version-file:7] target_dir=
+ [rbenv-version-file:22] '[' -n '' ']'
+ [rbenv-version-file:25] find_local_version_file /Users/user_name
+ [rbenv-version-file:10] local root=/Users/user_name
+ [rbenv-version-file:11] [[ /Users/user_name =~ ^//[^/]*$ ]]
+ [rbenv-version-file:12] '[' -s /Users/user_name/.ruby-version ']'
+ [rbenv-version-file:13] echo /Users/user_name/.ruby-version
+ [rbenv-version-file:14] return 0
+ [rbenv-version:11] echo '2.5.1 (set by /Users/user_name/.ruby-version)'
```

It worked before upgrading Catalina, It breaks after upgrading Catalina,
So I thought it matter, but I have no idea how to find out, Any help would be appreciated.

**Comment by mislav** [comment]
Strange! I use rbenv from tmux always.

What happens if you do from tmux:
1. `RBENV_DIR="$PWD" rbenv version`
2. `bash -c 'echo $PWD'`

**Comment by Pauloparakleto** [comment]
Hi @ilake, it had happened with me running bundler, which was using the global ruby version installed previously. I just uninstalled the global ruby version in order to bundler using the local path. Take a little closed on the beginning of the rbenv documentation where it is said about the path it take before executing your code, it helps me a lot taking that tecnical decision of mine.

**Comment by ilake** [comment]
@Pauloparakleto Thanks for your help.
