### ISSUE TITLE
rbenv shell: Avoid warning about global variables when enabled in zsh

### ISSUE THREAD

**Issue by rovf** [rbenv/rbenv#1257]
I suggest that the script generated by `rbenv init - zsh` also generates the command `typeset -g RBENV_VERSION_OLD` at the top of the shell function `rbenv`. It does not harm or degrade the performance, but if a user has in his .zshrc a `setopt warn_create_global`, using the `rbenv shell` command issues a warning _(eval):1: scalar parameter RBENV_VERSION_OLD created globally in function rbenv_.

**Comment by jasonkarns** [comment]
I believe the change would be necessary in https://github.com/rbenv/rbenv/blob/master/libexec/rbenv-sh-shell (similar to how it's marked global for fish shell).

A PR with test(s) would be welcome!
