### ISSUE TITLE
rbenv generating makefile adding methods to classes

### ISSUE THREAD

**Issue by sairam** [rbenv/rbenv#1258]
Verified issue exists on rbenv versions: 
- c879cb0f2fb2b01c6ee73cdfb25c90d139febda9
- v1.1.2

Reproducable on ruby versions: 
- 2.6.6
- 2.7.1 

OS version: Mac OS 10.15.5

We are in the process of upgrading ruby and rails in an application. We came across a strange issue possibly related to bundling.

If we had any 'message' method associated to a class/instance, it returns. This only comes up when you interactively debug from `bundle exec rspec ...` since it creates a Makefile. The Makefile is not generated when you run `bundle exec rails console` and hence not reproducable

Some command and output from the interactive console (User is an ActiveRecord class and Array is from the stdlib)
```
 User.message
=> #<IO:<STDOUT>>
> User.new.message
=> #<IO:<STDOUT>>
> Array.message
=> #<IO:<STDOUT>>
> User.install_rb
ArgumentError: wrong number of arguments (given 0, expected 2..3)
```
I found that this method comes from [mkmf.rb#L953](https://github.com/ruby/ruby/blob/v2_7_1/lib/mkmf.rb#L953) and  [mkmf.rb#L945](https://github.com/ruby/ruby/blob/v2_7_1/lib/mkmf.rb#L945)

See below for exact error. factoryBot gem identifies an association by checking if the method exists, in our case message was a column name which made it an attribute, it was being considered as an association and gives out the bizzare output

I am not sure if this is a bundler issue or rbenv issue. Can you help out?

<details>
```
$ bundle exec rspec spec/lib/file.rb:18
creating Makefile
Run options: include {:locations=>{"./spec/lib/announcement_spec.rb"=>[18]}}

Randomized with seed 30868
F

Failures:

  1) Description
     Failure/Error: let!(:announcement1) { create :announcement }

     KeyError:
       Trait not registered: "printf"
     # ./spec/lib/announcement_spec.rb:5:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # KeyError:
     #   key not found: "printf"
     #   ./spec/lib/announcement_spec.rb:5:in `block (2 levels) in <top (required)>'

Finished in 1.61 seconds (files took 36.43 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/lib/announcement_spec.rb:18 # ...

```
</details>

**Comment by hsbt** [comment]
It's not bundler or rbenv issues.

**Comment by mame** [comment]
It would be good to identify what gem `requires "mkmf"`.  A simple way I can come up with is to put a dummy `mkmf.rb` that just raises an exception in your LOAD_PATH, and run the spec.  It will dump a backtrace and you may be able to identify the gem.

**Comment by sairam** [comment]
I am attempting to reproduce this issue to understand why an intermediate Makefile is being created. 

@mame , thanks, will try that out. 

There are many gems that require 'mkmf' (as per the source code). I recall sidekiq even in the older version creating a Makefile.

**Comment by sairam** [comment]
@mame , thanks, your technique helped. I looked at the stack trace and went through the gems
A node module (lib-sass) loads up a ruby file which is requiring 'mkmf'

**Comment by sairam** [comment]
@hsbt , apologies on raising the issue.

**Comment by mame** [comment]
I have no idea how and why a node module loads a ruby file, but anyway it indeed seems that it is not a bundler/rbenv issue. It would be good to contact on the upstream of "lib-sass".  Good luck.
