### ISSUE TITLE
Gem Loading Issue

### ISSUE THREAD

**Issue by daBee** [rbenv/rbenv#1263]
I don't want to duplicate a post I put into SO, co here it is:

[https://stackoverflow.com/questions/63455912/square-gem-loading-issue](https://stackoverflow.com/questions/63455912/square-gem-loading-issue)

I can't get the `square` `gem` to load, although it does say it is loaded.  Tried two different `OS`', three independent boxes that are all reliant upon `rbenv`.  I'm running various versions of `Ruby`.  Same error in all instances.  

    square.rb:7:in `<main>': uninitialized constant Square::Client (NameError)

 Here is the simple script I'm using:

    #!/Users/rich/.rbenv/shims/ruby
    require 'square'

    $sandbox_application_id      = 'sandbox_app_id_here'
    $sandbox_access_token        = 'sandbox_access_token_here'

    square = Square::Client.new(access_token: $sandbox_access_token)

**Comment by daBee** [comment]
**SOLVED**

Gem name had a file suffix in it.  `gem 'square.rb'`, which as I understood it, is against convention/policy.

**Comment by jasonkarns** [comment]
Glad you got it sorted!
