### ISSUE TITLE
Cannot install any ruby version

### ISSUE THREAD

**Issue by muuvmuuv** [rbenv/rbenv#1265]
I am running the latest release of macOS and installed rbenv through homebrew. Homebrew ruby and system ruby are installed. Now after running `rbenv install 2.7.1` it hangs on installing openssl:

```
Downloading openssl-1.1.1g.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/ddb04774f1e32f0c49751e21b67216ac87852ceb056b75209af2443400636d46
Installing openssl-1.1.1g...
```

**Comment by rokumatsumoto** [comment]
I followed these steps

`rbenv versions`
```
  system
  2.1.0
  2.2.0
  2.4.2
  2.5.3
  2.5.5
* 2.6.3 (set by /Users/sgnydn/.ruby-version)
```

`brew upgrade rbenv ruby-build`

`rbenv install 2.6.6`
```
Downloading openssl-1.1.1g.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/ddb04774f1e32f0c49751e21b67216ac87852ceb056b75209af2443400636d46
Installing openssl-1.1.1g...
Installed openssl-1.1.1g to /Users/sgnydn/.rbenv/versions/2.6.6

Downloading ruby-2.6.6.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.6.tar.bz2
Installing ruby-2.6.6...
ruby-build: using readline from homebrew
Installed ruby-2.6.6 to /Users/sgnydn/.rbenv/versions/2.6.6
```

`rbenv versions`
```
  system
  2.1.0
  2.2.0
  2.4.2
  2.5.3
  2.5.5
* 2.6.3 (set by /Users/sgnydn/.ruby-version)
  2.6.6
```

**Comment by muuvmuuv** [comment]
@rokumatsumoto  How long did it take for the `Installing openssl-1.1.1g...` step? It really never ends on my machine. And your steps are the same as mine, except that I just have the system ruby version installed.

**Comment by muuvmuuv** [comment]
Nevermind, after 30 minutes it succeeded.... idk why it takes so long. It does not even use 10% of CPU or a lot I/O.

**Comment by harens** [comment]
I found it useful to run with the verbose flag: `rbenv install 2.7.1 -v` so I could view its progress.

**Comment by worc** [comment]
yeah, with verbose on you can see the installation processing a ton of temporary files. without verbose it looks like a hang (no progress displayed and no CPU spikes).
