### ISSUE TITLE
You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.

### ISSUE THREAD

**Issue by yzidzaini** [rbenv/rbenv#1267]
I'm trying to install bundler on my Mac OS Catalina, but it isn't letting me, help

muhammadyazid@Muhammads-MacBook-Pro ~ % gem install bundler
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.
muhammadyazid@Muhammads-MacBook-Pro ~ %

**Comment by KapilSachdev** [comment]
Is `rbenv` installed on your machine? What steps have you performed for installing `ruby`?
Can you verify if [this stackoverflow answer](https://stackoverflow.com/questions/51126403/you-dont-have-write-permissions-for-the-library-ruby-gems-2-3-0-directory-ma?rq=1) helps.

**Comment by hsbt** [comment]
It seems not rbenv issue.

**Comment by chanux** [comment]
I had to export GEM_HOME

`export GEM_HOME="$HOME/.gem"`

**Comment by wilrnh** [comment]
I had to set my global ruby to the rbenv version:

```
rbenv global 2.6.3
```

**Comment by fatih** [comment]
@wilrnh Thank you for the tip. I had the same issue. Apparently, my version was set to `system`. Setting the global Ruby to one of the available Ruby versions in my system (i.e.: `2.7.2`) fixed it for me.

**Comment by omrihorowitz** [comment]
@chanux that worked! thank you

**Comment by cuonghuynh** [comment]
@chanux works to me, thanks!

**Comment by mimoo** [comment]
wow, this probably should be in the installation instruction :) rbenv doesn't install without this step on a mac today

**Comment by Ezequiel-Padilla** [comment]
@chanux Work!

**Comment by mfarhanchandaion** [comment]
current directory: /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/ext/ffi_c
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20220116-1604-6m4e3t.rb extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

can you assist me on this 

ion@IONs-MacBook-Pro ~ % which ruby
/usr/bin/ruby
ion@IONs-MacBook-Pro ~ % ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]


M1 chip

**Comment by monfresh** [comment]
Hi @mfarhanchandaion. It looks like you're using the system Ruby version, which most likely means your PATH is not set, or maybe you need to run `rbenv rehash`. If that doesn't work, I built a tool that will automatically set up a working Ruby environment on your Mac.

I got tired of seeing people run into the same issues over and over, so I created [Ruby on Mac](https://www.rubyonmac.dev/?utm_source=github&utm_campaign=rbenv-1267) to make it as easy as possible to start using Ruby on a Mac.

**Comment by doigua** [comment]
> 

That's work, super! Thank you.
(though I don't understand why.
Si someone could explain to me, I would greatly appreciate it

**Comment by rakshasaini** [comment]
I have a multiple user on Mac. When i am not login with the administrator user. I face this Issue. Please login with administrator at the time of installation.

**Comment by Kodwings22** [comment]
I keep reading a lot of posts when I first get into trouble. This is how I once reached this website (https://kodlogs.net/339/you-dont-have-write-permissions-for-the-library-ruby-gems-2-3-0-directory) and got the desired solution. You can read this post as well as visit here. I think it will be very useful for you

**Comment by monfresh** [comment]
@Kodwings22 Ha! That's a blatant plagiarism (with some edits that made it worse) of these posts of mine: 

[Install Ruby on Mac. The Definitive Guide for 2022.](https://www.moncefbelyamani.com/the-definitive-guide-to-installing-ruby-gems-on-a-mac/)

[The fastest and easiest way to install Ruby on a Mac in 2022](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/)

**Comment by mislav** [comment]
I've added a FAQ entry about this problem to the wiki https://github.com/rbenv/rbenv/wiki#you-dont-have-write-permissions-for-the-libraryrubygems260-directory
