### ISSUE TITLE
[Feature Request] source completion when shell is specified

### ISSUE THREAD

**Issue by cornfeedhobo** [rbenv/rbenv#1269]
rbenv offers the option to specify the shell (`rbenv init - bash`).

rbenv also has completion files for specific shells.

I'd like for rbenv to source these completions when provided a specific shell.

**Comment by mislav** [comment]
Rbenv already does this automatically when you `eval` the output of `rbenv init`:
```
$ rbenv init - bash
...
source '/Users/mislav/p/rbenv/libexec/../completions/rbenv.bash'
...
```
