### ISSUE TITLE
Print installed version if requested version is not installed

### ISSUE THREAD

**Issue by AlexWayfer** [rbenv/rbenv#1277]
Hello.

I'd like to see a list of installed versions right after `specific version is not installed` error.

Current behavior:

```
> rbenv local 2.4
rbenv: version `2.4' not installed

> rbenv versions
  system
  2.5.8
  2.6.6
* 2.7.2 (set by /home/alex/.rbenv/version)
  jruby-9.2.12.0
```

For example, I see available version when try to install non-existing one:

```
> rbenv install 2.4

ruby-build: definition not found: 2.4

The following versions contain `2.4' in the name:
  2.2.4
  2.4.0-dev
  2.4.0-preview1
  2.4.0-preview2
  2.4.0-preview3
  2.4.0-rc1
  2.4.0
  2.4.1
  2.4.2
  2.4.3
  2.4.4
  2.4.5
  2.4.6
  2.4.7
  2.4.8
  2.4.9
  2.4.10
  jruby-9.2.4.0
  jruby-9.2.4.1
  rbx-2.2.4
  rbx-2.4.0
  rbx-2.4.1

See all available versions with `rbenv install --list'.

If the version you need is missing, try upgrading ruby-build:

  git -C /home/alex/.rbenv/plugins/ruby-build pull
```

And it's helpful.

**Comment by mislav** [comment]
Hi, thank you for the feature requests, but I think I'd like to keep the error message simple.

**Comment by AlexWayfer** [comment]
> Hi, thank you for the feature requests, but I think I'd like to keep the error message simple.

`install` error message has 4 paragraphs with a long list and code block, but `local` should be one-line… awkward.
