### ISSUE TITLE
Fish shell setup using `$fish_user_paths` clutters up `$PATH`

### ISSUE THREAD

**Issue by paulbernhard** [rbenv/rbenv#1282]
Hi,

thanks for working on *rbenv*, i have been using it a lot and appreciate its simplicity a lot. Setting up *rbenv* for the [*fish* shell](https://fishshell.com) using the `$fish_user_paths` according to the guide in [Basic GitHub Ceckout](https://github.com/rbenv/rbenv#basic-github-checkout), i encountered that this setup cluttered up my `$PATH` variable after multiple shell logins.

It's not a bug of *rbenv* but i think the docs of  [Basic GitHub Ceckout](https://github.com/rbenv/rbenv#basic-github-checkout) are kind of misleading due to *fish*'s usage of `$fish_user_paths`. Being new to the *fish* shell, i assumed that i'd have to add the setup to my `~/.config/fish/config.fish`:

```bash
$ set -Ux fish_user_paths $HOME/.rbenv/bin $fish_user_paths
```

Using `$fish_user_paths` in my config file, added *an additional rbenv* path to my `$PATH`, finally cluttering it up with many duplicate `$HOME/.rbenv/bin`. It seems that `$fish_user_paths` is only ment to be set once, not at every login. Now, the *rbenv* docs do not say to place the above command in *fish*'s config, but i think it should be mentioned to only execute this command once, or use the following setup in `~/.config/fish/conig.fish:

```bash
set -x PATH $HOME/.rbenv/bin $PATH
```

My best,
Paul

**Comment by mislav** [comment]
Thanks for writing in!

> Being new to the _fish_ shell, i assumed that i'd have to add the setup to my `~/.config/fish/config.fish`:

Oof; sorry for the confusion. However, I don't think the current docs can be clearer. Nowhere do our docs say that you should add that line to your fish config file. It's assumed that you will execute the line just like you execute lines in every other step of the installation process.
