### ISSUE TITLE
Why is rake missing? 

### ISSUE THREAD

**Issue by asfarley** [rbenv/rbenv#1304]
I have a Rails project, and I just upgraded the server from Ubuntu 18.04 to 20.04. 

I'm trying to deploy via Capistrano, but the precompile step is failing:

```
00:07 deploy:assets:precompile
      01 /home/deploy/.rbenv/bin/rbenv exec bundle exec rake assets:precompile
      01 bundler: failed to load command: rake (/var/www/framelinker/shared/bundle/ruby/2.6.0/bin/rake)
      01 Gem::Exception: can't find executable rake for gem rake. rake is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
```

A [response on serverfault](https://serverfault.com/questions/1052732/why-is-bundler-failing-to-find-rake-while-deploying-with-capistrano) suggested that "my rbenv is broken". By manually logging into the server, I can see that there is an rbenv shim for rake located at `/home/deploy/.rbenv/shims/rake`, so I'm wondering: is Capistrano to blame because it's not calling the shim? Or is rbenv to blame? How can I differentiate? 

ruby is locked to 2.6.1p33 in Gemfile.lock and rake is set to 13.0.3 in Gemfile.lock, if it matters.

**Comment by asfarley** [comment]
Logging into the server and manually executing the following fixed this issue:

`/home/deploy/.rbenv/bin/rbenv exec gem update --system`

**Comment by asfarley** [comment]
Logging into the server and manually executing the following fixed/gave me a workaround for this issue:

`/home/deploy/.rbenv/bin/rbenv exec gem update --system`

I'm not sure how to roll this into my CI/ansible/capistrano stuff, but at least my server is working again.

**Comment by ashapiatsiuk** [comment]
if somebody will try to fix it - just update bundler. it helped me
