### ISSUE TITLE
rbenv local 2.7.2 Not Sticky

### ISSUE THREAD

**Issue by daBee** [rbenv/rbenv#1313]
I can't seem to get `rbenv` to make a newly installed version of `Ruby 2.7.2` to be used locally.  

    ~ ❯ ruby -v                                                                                  19:07:49
    ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]

    ~ ❯ rbenv local 2.7.2                                                                        19:08:41

    ~ ❯ ruby -v                                                                                  19:08:47
    ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]

    ~ ❯ rbenv rehash                                                                             19:08:50

    ~ ❯ ruby -v                                                                                  19:08:56
    ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]

This is a new box on `Big Sur`.  

    ~ ❯ rbenv versions                                                                           19:11:46
      system
    * 2.7.2 (set by /Users/rich/.ruby-version)

    ~ ❯ rbenv which ruby                                                                         19:11:53
    /Users/rich/.rbenv/versions/2.7.2/bin/ruby

Not sure what I'm doing wrong here.  

    ~ ❯ rbenv global 2.7.2                                                                       19:12:34

    ~ ❯ ruby -v                                                                                  19:13:17
    ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]

**Comment by daBee** [comment]
Just inserted this into ~/.zprofile and it's now sticky:

    eval "$(rbenv init -)"

Does this look like it's fixed?

**Comment by mislav** [comment]
> Just inserted this into ~/.zprofile and it's now sticky:
> 
> ```
> eval "$(rbenv init -)"
> ```

Putting this into your shell profile file is a required part of installation, per our installation instructions in the README.

**Comment by daBee** [comment]
That is usually added during installation, hence it was a miss.
