### ISSUE TITLE
Configuring brew to use openssl@1.0 is not enough to rbenv install 2.2.10 - Ubuntu

### ISSUE THREAD

**Issue by cratag** [rbenv/rbenv#1319]
I'm using Ubuntu 20.04. 

Using rbenv for Ruby 3.0.0, working properly. I couldn't install 2.2.10 because of an openSSL problem, so I installed & configured brew.

Using:
`RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.0)" rbenv install 2.2.10`

will return
`make[2]: Leaving directory '/tmp/ruby-build.20210323110024.17998.sx5tX8/ruby-2.2.10/ext/openssl'
make[1]: *** [exts.mk:205: ext/openssl/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/tmp/ruby-build.20210323110024.17998.sx5tX8/ruby-2.2.10/ext/date'
linking shared-object pathname.so
make[2]: Leaving directory '/tmp/ruby-build.20210323110024.17998.sx5tX8/ruby-2.2.10/ext/pathname'
linking shared-object nkf.so
make[2]: Leaving directory '/tmp/ruby-build.20210323110024.17998.sx5tX8/ruby-2.2.10/ext/nkf'
make[1]: Leaving directory '/tmp/ruby-build.20210323110024.17998.sx5tX8/ruby-2.2.10'
make: *** [uncommon.mk:189: build-ext] Error 2`

full log attached
[ruby-build.20210322181537.6359.log](https://github.com/rbenv/rbenv/files/6190277/ruby-build.20210322181537.6359.log)

**Comment by cratag** [comment]
[This ](https://gist.github.com/souzagab/0ae60e61939d51385de87904b65b2da2)was the solution I found, and with a small tweak it worked.
Thanks to EliKazap
Edit /`etc/apt/sources.list` and add this at the end of the file: `deb http://security.ubuntu.com/ubuntu bionic-security main`

then

    Run sudo apt-get update && apt-cache policy libssl1.0-dev

    Run sudo apt-get install libssl1.0-dev


check if the version is correct with `./usr/local/ssl/bin/openssl version`

and then

    RUBY_CONFIGURE_OPTS="--with-openssl-dir='/usr/local/ssl/bin'" rbenv install 2.2.10

**Comment by jbwl** [comment]
@cratag When doing the exact steps above, apt wants to replace the OpenSSL package with the 1.0 version for the whole system - when I try to install it, apt will remove all packages referring OpenSSL, like node. There are dozens of packages that will be uninstalled if I go that way. 

There must be a method to install OpenSSL 1.0 alongside the current version just to
