### ISSUE TITLE
Installing ruby 2.7.3 actually install ruby 2.6.3p62 on MacOS

### ISSUE THREAD

**Issue by qFouge** [rbenv/rbenv#1324]
When using rbenv to install ruby 2.7.3 using rbenv install 2.7.3 it actually installs ruby 2.6.3p62. 

I checked using ruby --version

**Comment by liudmyla-schastlyvets** [comment]
@qFouge hey, how did you install 2.7.3?

**Comment by mislav** [comment]
It looks like you're having problems with [ruby-build](https://github.com/rbenv/ruby-build), which is the plugin that provides the `rbenv install` command.

1. First, [ensure that ruby-build is updated](https://github.com/rbenv/ruby-build/wiki#updating-ruby-build) to the latest version.
2. If your problem persists, [check existing issues in the ruby-build repo](https://github.com/rbenv/ruby-build/issues) and open a new one if necessary. When opening a new issue, please attach the full build log.
