### ISSUE TITLE
Trying to install bundle always get this error even ruby is not installed at this path

### ISSUE THREAD

**Issue by ChawlaBhavuk** [rbenv/rbenv#1335]
Traceback (most recent call last):
	2: from /usr/local/bin/bundle:23:in `<main>'
	1: from /Library/Ruby/Site/2.6.0/rubygems.rb:300:in `activate_bin_path'
/Library/Ruby/Site/2.6.0/rubygems.rb:281:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)

**Comment by hsbt** [comment]
Unfortunately, It's not related with rbenv issues.
