### ISSUE TITLE
Checking for rbenv shims in PATH: found at wrong position

### ISSUE THREAD

**Issue by asyraffff** [rbenv/rbenv#1336]
I try to check my `rbenv` problem with using its `rbenv-doctor` command ;

```shell
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/main/bin/rbenv-doctor | bash
```

I get this;

```shell
Checking for `rbenv' in PATH: /usr/local/bin/rbenv
Checking for rbenv shims in PATH: found at wrong position 👈
  The directory `/Users/myname/.rbenv/shims' is present in PATH, but is listed too late.
  The Ruby version found in `/usr/local/opt/ruby/bin' will have precedence. Please reorder your PATH.

Checking `rbenv install' support: /usr/local/bin/rbenv-install (ruby-build 20210510)
Counting installed Ruby versions: 5 versions
Checking RubyGems settings: OK
Auditing installed plugins: OK
```

I want to highlight this one;

```shell
Checking for rbenv shims in PATH: found at wrong position
```

The result says `Please reorder your PATH.`. How I do this ???

**Comment by mislav** [comment]
We do not know how you have set PATH, but yours probably looks something like this:

```
/usr/local/opt/ruby/bin:/Users/myname/.rbenv/shims:/usr/bin:/bin
```

To enable rbenv, you should make sure that it looks something like this:

```
/Users/myname/.rbenv/shims:/usr/local/opt/ruby/bin:/usr/bin:/bin
```

To achieve that, find where you have `eval ... rbenv init` line in your shell initialization files, and make sure that it happens AFTER other path edits such as the one that adds `/usr/local/opt/ruby/bin` to path.
