### ISSUE TITLE
Document symlinking existing version of ruby to `versions/` directory

### ISSUE THREAD

**Issue by hkmaly** [rbenv/rbenv#1340]
In README, you are mentioning

> Alternatively to the install command, you can download and compile Ruby manually as a subdirectory of ~/.rbenv/versions/. An entry in that directory can also be a symlink to a Ruby version installed elsewhere on the filesystem. rbenv doesn't care; it will simply treat any entry in the versions/ directory as a separate Ruby version.

Would it be possible to actually document what exactly to symlink there, or possibly create a tool for that? The motivation is, obviously, to use multiple versions of ruby already installed on system with tools like ruby-switch (debian) or eselect ruby (gentoo).

**Comment by mislav** [comment]
@hkmaly Sorry, but I believe that the current documentation is sufficient documentation. Example: you can either compile a Ruby version into `~/.rbenv/versions/1.2.3` or `~/.rbenv/versions/1.2.3` can be a symlink pointing to a location on your system where the corresponding Ruby version is installed.
