### ISSUE TITLE
Installing RBenv & Ruby

### ISSUE THREAD

**Issue by Maramqdah** [rbenv/rbenv#1349]
trying to install RBenv on my Mac following the instructions in the prep course for M1 machine
it gives me command not found 

Last login: Mon Aug 23 17:47:24 on ttys000
maramqdah@Marams-MacBook-Pro ~ % rbenv install 2.7.2
zsh: command not found: rbenv
maramqdah@Marams-MacBook-Pro ~ % rbenv install 2.6.6
zsh: command not found: rbenv
maramqdah@Marams-MacBook-Pro ~ % RUBY_CFLAGS="-Wno-error=implicit-function-declaration" rbenv install 2.6.6

how can I fix it

**Comment by mislav** [comment]
Hi, it looks like rbenv installation isn't complete on your system.

Please try the doctor script to locate what's wrong:
```
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/main/bin/rbenv-doctor | bash
```
Then, verify your installation step by step by following these instructions https://github.com/rbenv/rbenv#basic-github-checkout
