### ISSUE TITLE
brew install rbenv not working on MacBook air 2015, Mac OS Monterey

### ISSUE THREAD

**Issue by MaxHass12** [rbenv/rbenv#1367]
Warning: No available formula with the name "rbenv".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
➜  ~

brew is updated and brew doctor is not showing any issues either.

Please help, thanks

**Comment by hsbt** [comment]
Unfortunately, I have no idea to help this. Because it's homebrew or your environment issue, not rbenv.

https://stackoverflow.com/ may help you.
