### ISSUE TITLE
Add a warning or error if GEM_HOME is set

### ISSUE THREAD

**Issue by benpjohnson** [rbenv/rbenv#1382]
If `GEM_HOME` is set this seems to break `rbenv` since all gems go into the same directory regardless of the Ruby version used.

Would it be worth adding an explict check for this case [like rvm does](https://github.com/rvm/rvm/blob/35e894c7070eaabc38d91220f6e26d1585a7098a/scripts/functions/notes/warnings/warning_gem_home#L8).

**Comment by sosedoff** [comment]
Just ran into the same problem and it took a while to realize that presence of $GEM_HOME was breaking gem installs.

**Comment by konsolebox** [comment]
You probably can create your own hook script in `/etc/rbenv.d/hooks/exec/` and/or `/etc/rbenv.d/hooks/install/` that checks if GEM_HOME is set but please don't do any of this in rbenv itself.  GEM_HOME is useful for temporarily or permanently relocating installed gems like on a project with different development versions but the same ruby target.  GEM_HOME does well what it's supposed to do but is wrongly used.

Blame the people that sets it globally instead, especially on a system with multiple Ruby installs.  I can think of ways it is wrongly used, like when setting the default install dir to user's gem directory so `--user-install` does not need to be specified when running `gem install` or so `bundler` always installs to the user gem directory.  These all should be altered by the distro that packages the system Ruby instead.
