### ISSUE TITLE
Raspberry Pi Install Missing .bash_profile eval "$(rbenv init -)"

### ISSUE THREAD

**Issue by daBee** [rbenv/rbenv#1392]
Just to report that `Raspberry Pi` `Buster` has no `eval "$(rbenv init -)"` append when the `rbenv init` is used in the terminal (`Bash`).  I had to manually insert it.  

Up until then, `rbenv` had to install `ruby 2.7.1` (see side note below) before, and wasn't recognizing the new install, even after a `rbenv local 2.7.1`.  The `2.7.1` registration worked in `rbenv versions`, but `ruby -v` and `which ruby` both went to the `system` version.

Side note:  I had to reduce the MAKE core count down to 1 for the installation to happen as well.  

    export MAKE_OPTS=-j1

**Comment by mislav** [comment]
> I had to manually insert it.

Everyone has to manually insert it on every OS. That's why the regular `rbenv init` invocation prints these instructions:
```
$ rbenv init
# Load rbenv automatically by appending
# the following to ~/.bash_profile:

eval "$(rbenv init - bash)"
```

> Side note: I had to reduce the MAKE core count down to 1 for the installation to happen as well.

Thanks for sharing! This is exactly what MAKE_OPTS was designed for.
