### ISSUE TITLE
Shims are incompatible with `ruby -S`

### ISSUE THREAD

**Issue by sstephenson** [rbenv/rbenv#14]
```
 -S             Makes Ruby use the PATH environment variable to search for
                script, unless if its name begins with a slash.  This is
                used to emulate #! on machines that don't support it, in
                the following manner:

                      #! /usr/local/bin/ruby
                      # This line makes the next one a comment in Ruby \
                        exec /usr/local/bin/ruby -S $0 $*
```

When you pass the `-S foo` flag to Ruby, it finds `foo` in `$PATH`, then scans the first line of the file to see if it's a Ruby program and re-execs: https://github.com/ruby/ruby/blob/trunk/ruby.c#L1549-1562

The Rubinius installer uses this:

```
/Users/sam/.rbenv/versions/1.9.3-preview1/bin/ruby -S rake  -r /private/tmp/ruby-build.10166-13998/rubinius-1.2.4/config.rb -r /private/tmp/ruby-build.10166-13998/rubinius-1.2.4/rakelib/ext_helper.rb -r /private/tmp/ruby-build.10166-13998/rubinius-1.2.4/rakelib/dependency_grapher.rb build:mri
/Users/sam/.rbenv/versions/1.9.3-preview1/bin/ruby: no Ruby script found in input (LoadError)
rake aborted!
Command failed with status (1): [/Users/sam/.rbenv/versions/1.9.3-preview1/...]
```

One workaround would be to change our shims' shebang to point to another shim in our libexec directory with `ruby` in the name.  

Another workaround would be for `rbenv-exec` to prepend `$PATH` with the current version's prefix, so that children of any Ruby process will find the actual binaries in the path before our shims. The downside here is that you wouldn't be able to modify `RBENV_VERSION` in a Ruby process to spawn a child with a different version, though I'm not sure that's actually useful.

**Comment by zenspider** [comment]
Looks like this should be reopened since #372 seems to have been reverted?

**Comment by mislav** [comment]
No, this is not an issue presently even though that PR got reverted. The current Ruby version's bin directory gets pushed onto PATH as soon as you invoke `ruby`, so in fact the `-S` flag always has the desired effect.

The difficult problem seems to be allowing shelling out to a different version of Ruby while preserving `ruby -S` compatibility.

**Comment by zenspider** [comment]
Well, I hate to break it to you, but this problem seems to have regressed:

```
cd pkg/graphics-1.0.0b4
  Successfully built RubyGem
  Name: graphics
  Version: 1.0.0b4
  File: graphics-1.0.0b4.gem
mv graphics-1.0.0b4.gem ..
cd -
/Users/ryan/.rbenv/versions/2.0.0-p645/bin/ruby -S gem push pkg/graphics-1.0.0b4.gem
/Users/ryan/.rbenv/versions/2.0.0-p645/bin/ruby: no Ruby script found in input (LoadError)
rake aborted!
```

That's using (tried and true) Hoe to release one of my gems. It releases fine via system ruby and fails as above when using rbenv. This from rbenv to rbenv, same version. It uses `Gem.ruby` to specify the full path to the ruby binary. `which gem` points to the shims directory, but that might be different by the time this comes around via ruby.

**Comment by mislav** [comment]
Is the above a shell script? What executes it/what generated it?

**Comment by zenspider** [comment]
The ruby in question is literally: `sh Gem.ruby, "-S", "gem", "push", g` (where `g` is the path of the gem to push).

**Comment by mislav** [comment]
I just tried to reproduce it with this `Rakefile` but can't:

```rb
task :hey do
  sh Gem.ruby, '-S', 'gem', 'env'
end
```

What runs the rake task exactly?
