### ISSUE TITLE
How rbenv reads .ruby-version automatically?

### ISSUE THREAD

**Issue by ccmywish** [rbenv/rbenv#1403]
Hi, I'm working on https://github.com/ccmywish/rbenv-for-windows, which is definitely a `rbenv` implemented on Windows.

After checking the sources for a while, I still don't know how `rbenv` read `.ruby-version` every time you `cd`, `pushd` or `popd`.

I searched the repository for `chpwd`, `precmd`, `PROMPT_COMMAND` hooks, but got no results. 

Could you provide some kind help?  @mislav

**Comment by mislav** [comment]
rbenv does not hook into your shell by means of chpwd, precmd, nor by overriding the shell prompt.

Instead, it looks up the version when `ruby` or another Ruby-related executable is invoked.

It does so by prepending a "shims" directory to your PATH. For example, after rbenv your PATH could be:
```
PATH=/home/user/.rbenv/shims:/usr/local/bin:/usr/bin:/bin
```
Invoking `ruby` then invokes `/home/user/.rbenv/shims/ruby`, which activates rbenv, which reads `.rbenv-version` from the local directory if it exists, determines for example that it should activate Ruby `2.7.5`, and then dispatches the call and its arguments to `/home/user/.rbenv/versions/2.7.5/bin/ruby`.

This paradigm lends itself well to a Unix system but not so well to a Windows system. Not all rbenv concepts will translate well to Windows, so I hope you can solve those yourself!

For more information: https://github.com/rbenv/rbenv#how-it-works
