### ISSUE TITLE
Change Fish shell instructions for adding to PATH

### ISSUE THREAD

**Issue by dancojocaru2000** [rbenv/rbenv#1404]
Fish recently got a built in command that modifies `$fish_user_paths` automatically.

The currently recommended way to add something to PATH using fish is to run `fish_add_path /path/to/add`. As such, the instruction should be `fish_add_path $HOME/.rbenv/bin`.

**Comment by mislav** [comment]
Thanks for letting us know! Since `fish_add_path` is relatively new and our current installation instructions work on both newer and older fish releases, we'll keep our current instructions for backwards-compatibility.

**Comment by dancojocaru2000** [comment]
`fish_add_path` was released in fish 3.2.0, in March 2021. That's more than an year. 

Distributions notorious for slow updates like Debian are still on 3.0.2 on some versions, so backwards-compatibility with those can still be considered important. I just thought I'd add this info here for completeness.
