### ISSUE TITLE
Install a Ruby manually

### ISSUE THREAD

**Issue by konsolebox** [rbenv/rbenv#1410]
Are there any basic documentation on how to manually install a Ruby version? E.g. MRI 3.0 4.

**Comment by mislav** [comment]
Yes: https://github.com/rbenv/rbenv#installing-ruby-versions

> Alternatively to the `install` command, you can download and compile Ruby manually as a subdirectory of `~/.rbenv/versions/`.

So if you install a Ruby version manually into a directory called, for example, `~/.rbenv/versions/3.0.4`, you will then be able to use rbenv to use the version `3.0.4` in your applications.
