### ISSUE TITLE
Erro ao gerara statics 

### ISSUE THREAD

**Issue by FernandesGuilherme** [rbenv/rbenv#1411]
guilherme@pandemia ~$ git_stats --help
Traceback (most recent call last):
	23: from /usr/local/bin/git_stats:23:in `<main>'
	22: from /usr/local/bin/git_stats:23:in `load'
	21: from /var/lib/gems/2.7.0/gems/git_stats-1.0.17/bin/git_stats:8:in `<top (required)>'
	20: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	19: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	18: from /var/lib/gems/2.7.0/gems/git_stats-1.0.17/lib/git_stats/cli.rb:2:in `<top (required)>'
	17: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	16: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	15: from /var/lib/gems/2.7.0/gems/git_stats-1.0.17/lib/git_stats.rb:5:in `<top (required)>'
	14: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	13: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	12: from /var/lib/gems/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/all.rb:3:in `<top (required)>'
	11: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	10: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 9: from /var/lib/gems/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext.rb:1:in `<top (required)>'
	 8: from /var/lib/gems/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext.rb:1:in `each'
	 7: from /var/lib/gems/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
	 6: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 5: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 4: from /var/lib/gems/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object.rb:3:in `<top (required)>'
	 3: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 2: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 1: from /var/lib/gems/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object/duplicable.rb:106:in `<top (required)>'
/var/lib/gems/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object/duplicable.rb:111:in `<class:BigDecimal>': undefined method `new' for BigDecimal:Class (NoMethodError)
guilherme@pandemia ~$

**Comment by hsbt** [comment]
Unfortunately, It's not rbenv issues.
