### ISSUE TITLE
Request for `rbenv list` as an alias for `rbenv versions`

### ISSUE THREAD

**Issue by ndbroadbent** [rbenv/rbenv#1412]
I keep running `rbenv list`, because so many other version managers use `list`. e.g. `nvm list`, `rvm list`, `brew list`. I think most CLI tools have adopted `list` as a standard command. I have to keep reminding myself that `rbenv` uses a different `versions` command, and it's a bit annoying since I only run it a few times a year.

Other people have run into this as well: https://github.com/rbenv/rbenv/issues/1105

I think it would be very nice to add an alias, even if it's undocumented. Thanks for your consideration!

**Comment by mislav** [comment]
Thank you for the feature request, but I am unconvinced of this now just the same I was unconvinced back then.

With `rbenv list`, it's not clear what property you are listing. With `rbenv versions`, it's clear that you are listing versions. This command isn't difficult to discover either, as it's clearly documented.
