### ISSUE TITLE
Gem tries to install native extensions globally

### ISSUE THREAD

**Issue by rongcuid** [rbenv/rbenv#1416]
I am using a `rbenv` managed ruby and trying to locally install a gem package with a native extension. No matter what I do, `gem` tries to install it globally.

The gem I am trying to install is `red-arrow`. I tried the following options:

```
$ gem install red-arrow
$ gem install --user-install red-arrow
$ GEM_HOME=<path-to-rbenv-gem-home> gem install red-arrow
$ GEM_HOME=<path-to-rbenv-gem-home> gem install --user-install red-arrow
```

They still try to install the extension globally.

**Comment by mislav** [comment]
Hi, sorry you're having trouble, but this is an issue tracker for rbenv, not for `gem` which comes from Ruby. Rbenv doesn't control where `gem` will install gems. For what it's worth, `gem install --user-install red-arrow` should be the correct invocation. Also see "USER INSTALLATION DIRECTORY" in the output of `gem env`. Good luck!
