### ISSUE TITLE
rbenv goesn't rehash shims from Bundler Github-installed gems

### ISSUE THREAD

**Issue by vittorius** [rbenv/rbenv#1421]
### The issue ###

I have a Ruby 3.1.2 version installed and a project with a Gemfile and with a
```
`gem 'middleman', github: 'middleman/middleman'
```

entry. The middleman gem at Github doesn't have a `.gemspec` file but does have the `Gemfile` with the following entry: 

```
gem 'middleman-cli', path: 'middleman-cli'
```

The `middleman-cli` gem has the `bin/middleman` executable in its dirs stricture. The gem was successfully installed via `bundle install` to `/Users/vittorius/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/middleman-a2910b4d9164/middleman-cli`. The `bin/middleman` is truly there.

But running `middleman` gives me `zsh: command not found: middleman`. And there's no `middleman` in `~/.rbenv/shims`, `rbenv rehash` does nothing to that. Only `bundle exec middleman` works.

I have the plugin [`rbenv-bundle-exec`](https://github.com/maljub01/rbenv-bundle-exec) installed. Removing it didn't help either.

Please help me understand why rbenv doesn't "see" Github-installed gems' executables from `bundler`.

### rbenv doctor ###

```
Checking for `rbenv' in PATH: /opt/homebrew/bin/rbenv
Checking for rbenv shims in PATH: OK
Checking `rbenv install' support: /opt/homebrew/bin/rbenv-install (ruby-build 20220426)
Counting installed Ruby versions: 2 versions
Checking RubyGems settings: OK
Auditing installed plugins: OK
```

**Comment by mislav** [comment]
Hi, unless an executable is added to `$HOME/.rbenv/versions/<VERSION>/bin`, `rbenv rehash` will never see it and it will never be available for execution just using the command's name.

In your case, the executable got installed to `/Users/vittorius/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/middleman-a2910b4d9164/middleman-cli`. This location is invisible to rbenv. You will need to run `bundle exec middleman` to actually run it from your project. Rbenv can't do anything to help here, and I would advise against installing rbenv plugins to "solve" this (as they usually cause more trouble than they solve).

If you'd like to avoid typing `bundle exec ...`, you can use Bundler to generate binstubs scoped to your project. Please refer to our documentation here: https://github.com/rbenv/rbenv/wiki/Understanding-binstubs#project-specific-binstubs
