### ISSUE TITLE
Not using Ruby version specified by rbenv global and rbenv local

### ISSUE THREAD

**Issue by o-t-w** [rbenv/rbenv#1463]
After installing 3.1.3 I typed both `rbenv global 3.1.3` and `rbenv local 3.1.3` in my terminal then ran `ruby --version` and it says `ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin22]`

**Comment by mislav** [comment]
Please see https://github.com/rbenv/rbenv/wiki#how-to-verify-that-i-have-set-up-rbenv-correctly for instructions on how you can verify whether you've set up rbenv correctly. (You probably forgot to edit your shell initialization file or restart your terminal.)

**Comment by mislav** [comment]
The docs say:

> 1. Check that rbenv is in your PATH
> 2. Check that rbenv shims directory is in PATH

And it gives you example commands on how you might do that. As long as the shims directory is in your PATH, running `ruby` will run `~/.rbenv/shims/ruby`, which will respect your `rbenv local` (or `rbenv global` version), which should activate Ruby 3.1.3.

**Comment by elementum** [comment]
It didn't work for me until I manually added $HOME/.rbenv/shims/ruby to PATH, I did restart my terminal and edited shell initialization file.
