### ISSUE TITLE
uninstall?

### ISSUE THREAD

**Issue by cj** [rbenv/rbenv#148]
Hi,

How do you uninstall rbenv?

**Comment by willvlad** [comment]
@mislav I kept on getting the error that rbenv no such command init whenever I started bash until I deleted export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)" from the .bash_profile. Now bash starts cleanly. I'm new to this so may be not understanding something, but why are you saying that those who want rbenv should have these lines in the bash_profile? They seem to be causing an error for me...

**Comment by mislav** [comment]
@willvlad I don't understand whether you *want* to have rbenv on your system or not?

1. If you want rbenv on your system, then you should have these lines in `.bash_profile`
2. If you don't want rbenv, i.e. uninstall rbenv, then you should remove these lines from `.bash_profile`. It's not complicated.

**Comment by willvlad** [comment]
@mislav I do want to keep it on my system. If I follow your number 1, my git bash throws an error that there is no such command... If I delete it from the bash_profile, I don't get any errors... Does this clarify?

**Comment by mislav** [comment]
@willvlad So how and where did you install rbenv on your system?

**Comment by PlantCreative** [comment]
I believe @dannyboone and @willvlad saw a video similar to this one: http://bit.ly/1PGE2fr based on their questions…

**Comment by u4680325** [comment]
ty a lot i can now move to rvm
