### ISSUE TITLE
 Is there support for Ruby 3.2.1?

### ISSUE THREAD

**Issue by usernaimandrey** [rbenv/rbenv#1481]
Hi guys! Please tell me if there is support for Ruby 3.2.1 
I wanted to install it, but it is not in the list of available versions.
Thank you

**Comment by mislav** [comment]
Yes there is now. Please upgrade ruby-build on your system!

**Comment by usernaimandrey** [comment]
> Yes there is now. Please upgrade ruby-build on your system!

@mislav  Thank you.
