### ISSUE TITLE
rbenv: no such command `install'

### ISSUE THREAD

**Issue by 513ry** [rbenv/rbenv#1486]
Where is the install command localized? I been trying to set the environment be myself and by using the init script.

**Comment by jasonkarns** [comment]
`rbenv install` is provided by the `ruby-build` plugin (see https://github.com/rbenv/ruby-build/tree/master/bin). It is autodiscovered as long as there exists `rbenv-install` somewhere in your PATH (ie, after ruby-build is installed, with its bin/ added to PATH; which is done automatically as part of homebrew installation. Other installation approaches may require manually installing ruby-build_

I'm not sure what you mean by "set the environment".

**Comment by 513ry** [comment]
Right, sorry. I was a bit off track yesterday and I have missed that this is already mentioned in the section [#installing-ruby-versions](https://github.com/rbenv/rbenv#installing-ruby-versions).

> I'm not sure what you mean by "set the environment".

I mean set my shell variables using my own way of appending stuff. I don't like scripts that mess with my configuration c:

That's why I went here in first place, I give up on reading 1000 lines of rvm installation script. Your code make sens, which is great. This was my fault.

**Comment by jasonkarns** [comment]
No problem, glad you got it sorted!
