### ISSUE TITLE
rbenv 1.2.0 (from Homebrew) not installing versions to ~/.rbenv/versions on Mac OS Ventura

### ISSUE THREAD

**Issue by qneville** [rbenv/rbenv#1509]
Using Homebrew and rbenv I've been unable to get Ruby 3.1.4 installed on Mac OS Ventura and I'm not sure what else to try at this point.

```
brew upgrade
brew install rbenv
brew install ruby-build

rbenv init
```
I copied the following to both .zshrc and .zprofile, and I've also run source .zshrc and source .zprofile before doing the following.
```
eval "$(rbenv init - zsh)"
```
I also notice ~/.rbenv/versions/ is an empty folder
```
rbenv install 3.1.4
```
This runs successfully with the following output at the end, indicating it should have installed in ~/.rbenv/versions:
```
Status Legend:
(OK):download completed.
/var/folders/y2/03vklqzd7zg2sygdq0h4p4r00000gn/T/ruby-build.20230613151642.94078.9AY948/ruby-3.1.4 /var/folders/y2/03vklqzd7zg2sygdq0h4p4r00000gn/T/ruby-build.20230613151642.94078.9AY948 ~/.rbenv/versions
```

This gives the expected error when I try to set the global Ruby version with rbenv global 3.1.4

`rbenv: version '3.1.4'` not installed
Running `ls ~/.rbenv/versions/` only indicates it's still an empty folder

`rbenv --version` says `rbenv 1.2.0`
`ruby-build --version` says `ruby-build 20230608`

What else can I try here? Thank you.

**Comment by mislav** [comment]
> This runs successfully with the following output at the end, indicating it should have installed in ~/.rbenv/versions:
> 
> ```
> Status Legend:
> (OK):download completed.
> /var/folders/y2/03vklqzd7zg2sygdq0h4p4r00000gn/T/ruby-build.20230613151642.94078.9AY948/ruby-3.1.4 /var/folders/y2/03vklqzd7zg2sygdq0h4p4r00000gn/T/ruby-build.20230613151642.94078.9AY948 ~/.rbenv/versions
> ```

Hi, this output looks strange to me. Is this all there is in the output? This doesn't look like a successful installation.

Were there any other error messages in the output?

Can you verify that `rbenv install` exited with a success status? You can do that with: `rbenv install 3.1.4 && echo SUCCESS`

**Comment by mislav** [comment]
Closing due to lack of information.
