### ISSUE TITLE
bundle command does not do anything.

### ISSUE THREAD

**Issue by bKP451** [rbenv/rbenv#1558]
I am using rbenv. I added  a new gem to Gemfile and tried to `bundle install` . But the command does not do anything.

I am using Fedora 39.
rbenv version `1.2.0`

`ruby version` set using rbenv is `3.2.0`

**Comment by mislav** [comment]
Hi, I'm not sure why `bundle install` does not do anything, as there is very little information you've provided us apart from the currently selected Ruby version.

I would first check `which bundle` to confirm that it resolves to the rbenv shim that should be present in your PATH. If it doesn't resolve to the rbenv shim, then I would make sure to do `gem install bundler && rbenv rehash`.

Next, I would check whether any other `bundle` command works, for example `bundle help`. If that prints the help text, but `bundle install` still doesn't print anything, that's very odd.

Lastly, I would check whether `bundle install` exits with a non-zero status. You can check that like this: `bundle install || echo FAILED`. If it prints "FAILED" but there is no output, then somehow Bundler crashes without being able to print any error messages to its output. You could try upgrading Bundler with `gem update bundler`.

**Comment by mislav** [comment]
Closing due to lack of info. If this still looks like a bug with our project, please reopen!
