### ISSUE TITLE
rbenv.bash: line 8: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by stellarskye** [rbenv/rbenv#1560]
I recently installed rbenv so there may be something I'm missing but the instructions seemed straightforward, I am running on a mac.

Steps I followed
- `brew install rbenv ruby-build`
- `rbenv init`
  - This prints instructions to add following line to bash_profile `eval "$(rbenv init - bash)"`
    - Now everytime I open shell I see the following error message 

```
-bash: /opt/homebrew/Cellar/rbenv/1.2.0/libexec/../completions/rbenv.bash: line 8: syntax error near unexpected token `('
-bash: /opt/homebrew/Cellar/rbenv/1.2.0/libexec/../completions/rbenv.bash: line 8: `    local words=("${COMP_WORDS[@]}")'
```

**Comment by mislav** [comment]
Hi, this is odd, but it looks like your bash throws an error when loading rbenv's completion script. The script itself was unchanged for several years, and this raises a question of why is it erroring out for you and not for most people.

What is your bash version? `bash --version`

**Comment by jasonkarns** [comment]
I'd also double check that the hyphen/dash after 'init' isn't being replaced with a Unicode em dash or en dash or anything.

(Try copying/pasting from your rc file and run the bits init command (without the eval) to confirm the output is valid bash and not some other error output.

**Comment by stellarskye** [comment]
Yea guessing there is something wonky in my environment

bash version `GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)`

---

Able to run `rbenv init - bash` directly, for some reason it runs `yarn list` as a result

```
msop:testing ssop$ rbenv init - bash
yarn list v1.22.22
warning Filtering by arguments is deprecated. Please use the pattern option instead.
✨  Done in 0.16s.
export PATH="/Users/ssop/.rbenv/shims:${PATH}"
export RBENV_SHELL=bash
source '/opt/homebrew/Cellar/rbenv/1.2.0/libexec/../completions/rbenv.bash'
command rbenv rehash 2>/dev/null
rbenv() {
  local command
  command="${1:-}"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "$(rbenv "sh-$command" "$@")";;
  *)
    command rbenv "$command" "$@";;
  esac
}
```

**Comment by mislav** [comment]
You could try taking out everything from your bash_profile that isn't related to rbenv, start a new shell, and see if it changes anything?

**Comment by stellarskye** [comment]
ah yep, should have started there.  Thanks for the suggestion!

**Comment by jasonkarns** [comment]
Would you mind still sharing what you discovered?

In case someone else also ends up with rbenv triggering yarn somehow. :)

(I'm side-glancing at rails and its yarn binstub for some reason.)
