### ISSUE TITLE
rbenv sharing compiled gems in user install directory (GEM_HOME)

### ISSUE THREAD

**Issue by Greg-Myers-SB** [rbenv/rbenv#1584]
Hi rbenv team,

I first wanted to take the opportunity to thank you for this software. I've happily used this for over a decade now. I used to use virtualenv in python and rvm/chruby as my first version pickers in ruby but had constant issues. Since switching to rbenv sometime around 10 years ago I've had no issues with it and it's great to see how this software has influenced and guided similar solutions in different language ecosystems over the years. Great seeing all the rbenv clones across other languages, those are the ones I seek when using new tools now. 🙇 

I'm having an issue where when installing a new ruby via rbenv, it links the incorrect ruby dylib. I think it's related to `GEM_HOME` not being set but I know it doesn't affect other rbenv users or this would be easy to search for.

It's likely that it's something I set up wrong somehow, and it's possible it may be related to https://github.com/rubygems/rubygems/issues/1394 but I'm also not sure how.

Running certain bits of code cause the following:
```
$ ruby --version
ruby 3.3.4 (2024-07-09 revision be1089c8ec) [arm64-darwin23]

$ bundle exec rspec
... snip ...
LoadError:
  linked to incompatible /Users/me/.rbenv/versions/3.3.3/lib/libruby.3.3.dylib - /Users/me/.gem/ruby/3.3.0/gems/debug-1.9.2/lib/debug/debug.bundle
# /Users/me/.gem/ruby/3.3.0/gems/debug-1.9.2/lib/debug/frame_info.rb:16:in `rescue in <module:DEBUGGER__>'
# /Users/me/.gem/ruby/3.3.0/gems/debug-1.9.2/lib/debug/frame_info.rb:13:in `<module:DEBUGGER__>'
# /Users/me/.gem/ruby/3.3.0/gems/debug-1.9.2/lib/debug/frame_info.rb:3:in `<main>'
# /Users/me/.gem/ruby/3.3.0/gems/debug-1.9.2/lib/debug/session.rb:31:in `require_relative'
# /Users/me/.gem/ruby/3.3.0/gems/debug-1.9.2/lib/debug/session.rb:31:in `<main>'
# /Users/me/.gem/ruby/3.3.0/gems/debug-1.9.2/lib/debug.rb:6:in `require_relative'
# /Users/me/.gem/ruby/3.3.0/gems/debug-1.9.2/lib/debug.rb:6:in `<main>'
... snip ...
```

It appears that the debug gem is stored in the shared folder ` /Users/me/.gem/ruby/3.3.0/gems` but compiled against the specific ruby version in `/Users/me/.rbenv/versions/3.3.3/lib/libruby.3.3.dylib`

This can be seen as `USER INSTALLATION DIRECTORY` below.

```shell
$ gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 3.5.11
  - RUBY VERSION: 3.3.4 (2024-07-09 patchlevel 94) [arm64-darwin23]
  - INSTALLATION DIRECTORY: /Users/me/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0
  - USER INSTALLATION DIRECTORY: /Users/me/.gem/ruby/3.3.0
  - RUBY EXECUTABLE: /Users/me/.rbenv/versions/3.3.4/bin/ruby
  - GIT EXECUTABLE: /opt/homebrew/bin/git
  - EXECUTABLE DIRECTORY: /Users/me/.rbenv/versions/3.3.4/bin
  - SPEC CACHE DIRECTORY: /Users/me/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/me/.rbenv/versions/3.3.4/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - arm64-darwin-23
  - GEM PATHS:
     - /Users/me/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0
     - /Users/me/.gem/ruby/3.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/me/.rbenv/versions/3.3.4/bin
     - /opt/homebrew/Cellar/rbenv/1.2.0/libexec
     - /opt/homebrew/opt/coreutils/libexec/gnubin/
     - /opt/homebrew/opt/openssl@3/bin
     - /usr/local/opt/coreutils/libexec/gnubin/
     - /Users/me/.nvm/versions/node/v20.12.2/bin
     - /usr/local/opt/coreutils/libexec/gnubin/
     - /Users/me/.rbenv/shims
     - /usr/local/sbin
     - /opt/homebrew/bin
     - /opt/homebrew/sbin
     - /usr/local/bin
     - /System/Cryptexes/App/usr/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
     - /opt/X11/bin
     - /Library/Apple/usr/bin
     - /Users/me/.cargo/bin
     - /Applications/iTerm.app/Contents/Resources/utilities
```

My understanding is this is set by `GEM_HOME` but it is unset for me.
```
$ echo $GEM_HOME

$
```

I can fix the problem each time I switch ruby with `gem pristine debug` but I was wondering if you had any thoughts on how I configured this incorrectly or how this could be avoided?

There was a theory it was caused by my bundle configs but the same thing happens without it set and they dont target the debug gem as-is.
```
---
BUNDLE_BUILD__GRPC: "--with-ldflags=-Wl,-undefined,dynamic_lookup"
BUNDLE_BUILD__THRIFT: "--with-cppflags=\"-Wno-compound-token-split-by-macro\""
```

Thanks in advance for any thoughts.

**Comment by mislav** [comment]
Thank you for reporting. My guess is that this is a problem in userland and not indicative of any bug with either rbenv or rubygems.

From what I see by searching rspec-core codebase, it never loads nor depends on the `debug` gem. On my system, I have uninstalled that gem and I could continue to execute `rspec` without any issues. So, I find it very curious that your stack trace of executing `rspec` includes the debug gem.

This could have happened if the application or your environment has somehow explicitly opted into loading the debug functionality. This could have been achieved, for example, by setting `RUBYOPT='-r debug'` in the environment.

I could reproduce your error by installing the debug gem in an older version of ruby 3.3.x using `gem i --user-install debug` and then executing rspec with newer ruby 3.3.x and with RUBYOPT set as above. Even if you don't have GEM_HOME set, the location `~/.gem/ruby/3.3.0/gems` is implicitly included when looking up installed gems, however, the debug gem will fail to load due to its dylib being linked to an older, and this incompatible ruby version.

The solution would be to avoid using user-installed gems at all if the application environments should truly be isolated with respect to different ruby versions.

**Comment by Greg-Myers-SB** [comment]
Hi Mislav, thank you for your thoughts.
I realised if I uninstall debug gem entirely and then re-install it, it appears in the correct folder at `/Users/me/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0` as originally expected.
I can see there are a number of other gems installed in that same folder, that all originate from the same project. This indicates to me a specific project that has caused this somehow, so yes it is a user space error on my end. Thank you for your thoughts.

Will now close, have a great day!
