### ISSUE TITLE
rbenv list command to list latest available ruby version for each ruby

### ISSUE THREAD

**Issue by stevecondylios** [rbenv/rbenv#1592]
I've been using rbenv for 10 years yet can never recall how to list the latest available ruby versions for each ruby when I need it (have to look it up every time). 

It's done like this:

```
rbenv install --list
```

but I always try all the more obvious commands first e.g. `rbenv versions`, `rbenv list` etc etc, and inevitably `rbenv --help` followed by `rbenv commands` (then reading through all the commands and *still* not being able to locate one to list available ruby versions to download).

<hr>

### Suggestion

I suggest making 

```
rbenv list
```

do what

```
rbenv install --list
```

currently does. 

It's a tiny suggestion, but could make rbenv quite a lot faster to use (since it's so neat, stand-alone, and practical in every other regard, it seems odd to not have such an important action tucked away where it requires a web search or reach for the manual to locate it).

**Comment by stevecondylios** [comment]
I should add, that when the user sees a tiny list returned (i.e. something like this:

```none
3.0.6
3.1.4
3.2.3
3.3.0
jruby-9.4.6.0
mruby-3.3.0
picoruby-3.0.0
truffleruby-24.0.0
truffleruby+graalvm-24.0.0
```

), they might try `rbenv list --help` and perhaps it could show an `rbenv list --all` option or similar, to do what `rbenv install --list-all` does.

**Comment by mislav** [comment]
Hi, thanks for the suggestion, but I don't think `rbenv list` is a good command name for this. Let me explain.

rbenv is split among two main codebases: this one for rbenv itself (the Ruby version switcher tool), and another one for ruby-build (which compiles Ruby versions and provides the `rbenv install` command).

Without ruby-build, rbenv is only a version switcher tool and all its features should only be scoped to that use case. It's perfectly fine to use rbenv only for version switching, or use it with an installation tool other than ruby-build.

With all this in mind, I think a command named `rbenv list` would be ambiguous. If I was a new user, I would ask myself "rbenv list what?" Would this be a list of already installed versions (for which there is the `rbenv versions` command) or a list of versions available for installations? Also, what should this command do if ruby-build is not installed?

Hence, the entire functionality of ruby-build is scoped strictly _under_ the `rbenv install` command:
```
$ rbenv install
Usage: rbenv install [-f|-s] [-kpv] <version> [-- <configure-args...>]
       rbenv install [-f|-s] [-kpv] <definition-file>
       rbenv install --list
       rbenv install --version

  -l, --list           List latest stable versions for each Ruby
  -L, --list-all       List all local versions, including outdated ones
...
```

This help text should be enough to discover the `--list` argument, and in turn using `--list` teaches the user that there is `--list-all` too:

```
$ rbenv install --list
3.1.6
3.2.5
3.3.5
jruby-9.4.8.0
mruby-3.3.0
picoruby-3.0.0
truffleruby-24.1.0
truffleruby+graalvm-24.1.0

Only latest stable releases for each Ruby implementation are shown.
Use `rbenv install --list-all' to show all local versions.
```

I like the self-contained nature of the `rbenv install` command and I'd like to keep it that way for now. I know that some command names and flag combinations can be easy to forget, but reminding yourself of exact invocations doesn't even warrant a Web search; all this knowledge is a simple `rbenv help install` away.
