### ISSUE TITLE
ruby 3.4.1 -- missing 'syslog' 

### ISSUE THREAD

**Issue by stevewi-niteflyte** [rbenv/rbenv#1601]
I recently installed _ruby 3.4.1_ using **rbenv 1.3.0**.  The target system is _macOS 14.7.2 (Sonoma x86)._

The default `syslog` gem did not get installed:

```
<internal:/Users/stevewi/.rbenv/versions/3.4.1/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require': cannot load such file -- syslog/logger (LoadError)
```

Is this an oversight or did I forget a `RUBY_CONFIG_OPTS` setting:

```
RUBY_CONFIGURE_OPTS=--with-openssl --with-openssl-dir=/usr/local/opt/openssl@3 --with-readline-dir=/usr/local/opt/readline --disable-yjit
```

which yields

```
./configure "--prefix=$HOME/.rbenv/versions/3.4.1" --enable-shared --with-libyaml-dir=/usr/local/opt/libyaml --with-gmp-dir=/usr/local/opt/gmp --with-ext=openssl,psych,+ --with-openssl --with-openssl-dir=/usr/local/opt/openssl@3 --with-readline-dir=/usr/local/opt/readline --disable-yjit
```

I didn't ready anything in the version release notes about `syslog` being absent & the two FreeBSD 14.2 systems on which I built _ruby 3.4.1_ from source **_do not_** exhibit this issue.

I can easily work around this by manually installing the `syslog` gem but the current version at **rubygems.org** is old.

Thanks in advance for your kind advice...

**Comment by mislav** [comment]
Hi, thanks for reporting. I cannot reproduce on macOS 15.1. Could you share the build log as a file attachment here or as a Gist? You can find ruby-build logs sorted by last-modified with: `ls -t $TMPDIR/ruby-build.*.log`

I'm not familiar with syslog gem specifically, but from my own build log it looks like the gem has native extensions, and it could be that building those native extensions failed on your machine. But then, I wonder how come a manual `gem install syslog` works for you.

**Comment by stevewi-niteflyte** [comment]
Here you go...  Examining the log file, the `syslog` gem appears to be building.  However, neither `ruby` nor `irb` seem to be able to find it.

```
stevewi:~ $ uname -a
Darwin Steve-XXXXXXX-MacBook-Air.local 23.6.0 Darwin Kernel Version 23.6.0: Fri Nov 15 15:13:28 PST 2024; root:xnu-10063.141.1.702.7~1/RELEASE_X86_64 x86_64
stevewi:~ $ irb
irb(main):001> require 'syslog/logger'
<internal:/Users/stevewi/.rbenv/versions/3.4.1/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require': cannot load such file -- syslog/logger (LoadError)
	from <internal:/Users/stevewi/.rbenv/versions/3.4.1/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:136:in 'Kernel#require'
	from (irb):1:in '<main>'
	from <internal:kernel>:168:in 'Kernel#loop'
	from /Users/stevewi/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/irb-1.14.3/exe/irb:9:in '<top (required)>'
	from /Users/stevewi/.rbenv/versions/3.4.1/bin/irb:25:in 'Kernel#load'
	from /Users/stevewi/.rbenv/versions/3.4.1/bin/irb:25:in '<main>'
irb(main):002>
```

Here's the results for FreeBSD 14.2:

```
stevewi@dave.local:~ $ uname -a
FreeBSD dave.local 14.2-RELEASE FreeBSD 14.2-RELEASE hp800g3 amd64
stevewi@dave.local:~ $ irb
irb(main):001> require 'syslog/logger'
=> true
irb(main):002> 
```

[ruby-build.log](https://github.com/user-attachments/files/18249411/ruby-build.log)

<img width="278" alt="Screenshot 2024-12-25 at 7 57 27 PM" src="https://github.com/user-attachments/assets/651130a7-5c8e-49c4-a1e0-af1e3840d912" />

**Comment by mislav** [comment]
Hi, could you look into the syslog gem files and check whether there is a `syslog/logger.rb`? 

```
$ tree "$(rbenv prefix 3.4.1)"/lib/ruby/gems/3.4.0/gems/syslog-*
/Users/mislav/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/syslog-0.2.0
├── Gemfile
├── LICENSE.txt
├── README.md
├── Rakefile
├── bin
│   ├── console
│   └── setup
├── ext
│   └── syslog
│       ├── Makefile
│       ├── extconf.h
│       ├── extconf.rb
│       ├── mkmf.log
│       ├── syslog.c
│       ├── syslog.o
│       └── syslog.txt
├── exts.mk
└── lib
    ├── syslog
    │   └── logger.rb
    └── syslog.rb

6 directories, 16 files
```

**Comment by stevewi-niteflyte** [comment]
I found the problem.  I had `GEM_PATH` set to
```
GEM_PATH=/Users/stevewi/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.1
```
in my `rbenv` configuration script (runs at login) because it's derived as follows:
```
export RUBY_VERSION=`cat $HOME/.ruby-version`
...
export GEM_PATH=$HOME/.rbenv/versions/${RUBY_VERSION}/lib/ruby/gems/${RUBY_VERSION}
```
This is incorrect.  Changing my script to:
```
export RUBY_VERSION=`cat $HOME/.ruby-version`
export RUBY_MAJOR_RELEASE=`echo $RUBY_VERSION | sed -e 's/[0-9]*$/0/g'`
...
export GEM_PATH=$HOME/.rbenv/versions/${RUBY_VERSION}/lib/ruby/gems/${RUBY_MAJOR_RELEASE}
```
which yields
```
GEM_PATH=/Users/stevewi/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0
```
I'm still fine-tuning the _regexp_ that I use with `sed` but this is the essence of the problem.

Thanks for your help.
