### ISSUE TITLE
Shims for Fish shell

### ISSUE THREAD

**Issue by gf3** [rbenv/rbenv#195]
It would be very helpful is rbenv provided shims that were also fish shell compatible. It wouldn't be a huge change, but it'd mean that rbenv could be used in a non-bash/zsh shell. The syntax for fish is actually much more sane than bash.

**Comment by muloka** [comment]
Thanks @emcmanus and @sstephenson.

**Comment by ChFlick** [comment]
Apparently the ^ syntax will be deprecated in the future and is broken in some versions ([see this issue here](https://github.com/fish-shell/fish-shell/issues/6591#issuecomment-585775178)).

Therefore it may be better to use the following syntax instead: `rbenv rehash >/dev/null >2&1`.

**Comment by JelteF** [comment]
> Therefore it may be better to use the following syntax instead: rbenv rehash >/dev/null >2&1.

There's a typo in there `2` and `>` should be swapped:
```bash
rbenv rehash >/dev/null 2>&1
```
