### ISSUE TITLE
Strange syntax error in rbenv-version-file-read \w git-flow

### ISSUE THREAD

**Issue by alsemyonov** [rbenv/rbenv#222]
I don't know, whetther it is rbenv of git-flow problem, but when I try to run

``` bash
git flow release finish 0.1.0
```

there is a problem, mentioning rbenv:

``` bash
Switched to branch 'production'
/Users/alsemyonov/.rbenv/libexec/rbenv-version-file-read: line 16: syntax error near unexpected token `<'
Deleted branch release/0.1.0 (was 1234567).

...
```

And periodically it causes git-flow commands to fail.

**Comment by counterbeing** [comment]
I'm actually running into this exact issue myself. I have one git hook in my project, and I tried removing it, but for some reason it's still choking on 

```
/usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-version-file-read: line 17: syntax error near unexpected token `<'
```

I generally run Zsh, but in the process of troubleshooting, I've also attempted this in bash, with the same result.

**Comment by paddor** [comment]
@counterbeing Can't remember if I actually got it to run back then, but I'm using https://github.com/postmodern/chruby by now. :) Works very well.

**Comment by counterbeing** [comment]
Thanks for the response! I really am fond of my current rbenv setup though, and don’t want to abandon. Thanks again!
