### ISSUE TITLE
Add support to Gemfile ruby definition

### ISSUE THREAD

**Issue by rafaelfranca** [rbenv/rbenv#223]
Bundler 1.2.0.pre [add a `ruby` method](https://github.com/carlhuda/bundler/commit/9474e8819232b6a7e4f5a6a1d29057cc620c5b4b#L0R16) to their DSL to specify the ruby version.

Would be great if rbenv uses this information in projects using bundler instead to read from `.rbenv-version`.

**Comment by caseywatts** [comment]
The trick with getting the Gemfile to read `.ruby-version` could lead to an error like this:
https://twitter.com/jamesdabbs/status/628273980345065477
