### ISSUE TITLE
Is there an elegant way to use multiple versions of bundler under one rbenv ruby version?

### ISSUE THREAD

**Issue by omehegan** [rbenv/rbenv#235]
We have projects using Ruby 1.8.7 with bundler versions 0.7.1 (ow.), 1.0.x, and 1.1.3. In the past we have used rvm with the one version of a ruby and a gemset for each version of bundler we need. We're trying to move to rbenv, and it's going well for the most part, but I can't quite figure out an elegant way to use different bundler versions. 

I can install one bundler version within an rbenv environment, but I don't see a convenient way to install more than one.

**Comment by tunt-1890** [comment]
What if I want to set it global rather than specifying bundler version for every single use
```
$ bundler -v
Bundler version 2.0.2
$ bundle _1.17.1_ --version
Bundler version 1.17.1
$ bundler -v
Bundler version 2.0.2
```
expected result: Bundler version 1.17.1
actual result: Bundler version 2.0.2

**Comment by mislav** [comment]
@tunt-1890 There is no way to specify it globally.
