### ISSUE TITLE
`rbenv update`

### ISSUE THREAD

**Issue by mislav** [rbenv/rbenv#301]
Should we have an [`rbenv update`](https://github.com/rkh/rbenv-update/blob/master/bin/rbenv-update) command? /cc @rkh

It would work only if `RBENV_ROOT` is where rbenv is installed, and if it's a git repo.

I think it might be useful, considering the slow release cycle, and especially now that we have `rbenv --version` capable of displaying edge versions from git.

**Comment by wadkar** [comment]
@mislav , if it's okay - I recommend that we "get inspired" from [`pyenv`'s update plugin](https://github.com/pyenv/pyenv-update). Pyenv folks are nice and they consider `rbenv{,-build}` as upstream. So it will be a nice fit.

I have also read through the [`pyenv-update` bash script](https://github.com/pyenv/pyenv-update/blob/master/bin/pyenv-update) and I think it's pretty solid in terms of quoting things, and making sure things don't blow up. We just need to change few variables from `PYENV_ROOT` to `RBENV_ROOT`.

Do you want it to be part of `rbenv` core or as a separate plugin? In either case, I will be happy to submit a PR/repo.

**Comment by cornfeedhobo** [comment]
I've started to use [`basher`](https://github.com/basherpm/basher/) to manage these tools.

Otherwise, my +1 is for what @wadkar said; a rbenv-update plugin.

**Comment by olivierlacan** [comment]
Every time I run `rbenv instlal <new_version>` and I get this message I think: 
> We're so, so close to a nice experience for Ruby upgrades, it's really a shame rbenv doesn't just run this update in the background

```
ruby-build: definition not found: 3.0.1

See all available versions with `rbenv install --list'.

If the version you need is missing, try upgrading ruby-build:

  git -C /Users/olivierlacan/.rbenv/plugins/ruby-build pull
```

Having to run `git pull` is not the end of the world, but considering a tool like Homebrew routinely does it behind its own commands, it would really make a ton of sense to just run it (and be clear that rbenv is running a `git pull`).

**Comment by mislav** [comment]
@olivierlacan I do believe that this should be easier for the user, and what you're suggesting sounds completely reasonable.

However, there's something that feels slightly risky about software that updates itself by itself without any intervention from the user—especially when the software has never done so before. I'm not sure if we should alienate our users' trust by automatically updating ruby-build on every `rbenv install`.

I like the approach of `ruby-install` (an alternative to ruby-build): they are able to install new Ruby versions as they come out without having to upgrade ruby-install itself: https://github.com/postmodern/ruby-install#anti-features

**Comment by jasonkarns** [comment]
re: auto-updating

I really like this idea. Given that the rbenv-update plugin exists, but there hasn't been any movement to pull it into core, this feels like the perfect feature to add to the plugin itself.

ruby-build's `rbenv-install` subcommand executes before and after `install` hooks. It seems feasible that the rbenv-update plugin could add an `install` hook to run itself. (Perhaps even guarded by an opt-in environment variable to avoid being a breaking change?)

**Comment by rkh** [comment]
FWIW while I still use `rbenv`, I semi-automatically update it a ruby-build via homebrew now, and thus don't actually use rbenv-update myself anymore. I am happy to offer maintenance/commit rights if someone wants to (ideally someone using it) or have it output some message if it is no longer useful.

**Comment by jasonkarns** [comment]
@rkh I _believe_ I still have commit rights on that repo so if someone tackles a PR, I could handle reviewing and releasing.

**Comment by olivierlacan** [comment]
I think the concern about self-updating can be handled by a prompt.

> 3.0.1 is available but rbenv needs to update itself in order to install it, is that ok? Yes/No

@jasonkarns I’m down !

**Comment by mislav** [comment]
> I realize saying this out loud how much is involved for this to happen. And I'm a bit exhausted, but does that even still sound like something reasonable @mislav?

Thanks for thinking long and hard about this. Yes, this does sounds like something that could improve the user experience when installing new versions. However, I would _not_ couple this to rbenv-update, since rbenv-update updates rbenv and all its plugins, and we're only interested in updating ruby-build. So I would move this conversation to ruby-build, add an auto-updater there (we don't even need a hook; we could just bake it into `rbenv-install`). Of course, the whole thing would only work if ruby-build was installed via git.

I would also avoid a prompt, because prompts are annoying, so if someone checked out ruby-build via git, we can just assume that they don't mind if we fast-forward it to the latest version.

**Comment by martin-braun** [comment]
`rbenv update` would be nice to jump to the latest stable of the current channel which is part of `rbenv versions`. I came up with my own solution, that looks like this: 

```
current_ruby_version=$(rbenv global)
installed_ruby_versions=($(rbenv versions | awk -F "[ ]+" '/ /{print $2}'))
available_ruby_versions=($(rbenv install -l 2>/dev/null))

echo "[o] Upgrading Ruby builds ..."

for installed in "${installed_ruby_versions[@]}"; do
	if [ "$installed" = "system" ]; then
		continue
	fi
	for available in "${available_ruby_versions[@]}"; do
		if [ \
			"$(echo $installed | tr '.' '\n' | head -2)" \
			= \
			"$(echo $available | tr '.' '\n' | head -2)" \
			]; then
			rbenv install $available
			# TODO: Install all global packages from $installed to $available
			if [ "$current_ruby_version" = "$installed" ]; then
				rbenv global $installed
			fi
			rbenv uninstall $installed
		fi
	done
done
```

The issue is that I lose my globally installed packages. `nvm` provides a flag to reinstall packages from another version. 

Since `rbenv update` seems to have not made it for a decade now, why not providing such a flag at least?

**Comment by mislav** [comment]
Closing in favor of either manually updating using `git -C ~/.rbenv pull` or using https://github.com/rbenv/rbenv-installer as an idempotent install+update mechanism.
