### ISSUE TITLE
Support for abbreviated ruby version in .ruby-version file

### ISSUE THREAD

**Issue by sheerun** [rbenv/rbenv#328]
I think rbenv should process each .ruby-version through [whatis command](https://github.com/rkh/rbenv-whatis).

For many projects I really don't care which revision the ruby is, unless it's 1.9.3. Developers working on one project may have different revisions of ruby 1.9.3 installed, so currently adding `.ruby-version` to repository is not the best idea, as probably each developer is going to change it in order to not install slightly newer ruby version (like `1.9.3-p362` to `1.9.3-p374`).

If rbenv supported abbreviated versions, I could add `.ruby-version` file set to 1.9.3 to repository and that way make sure other developers wont get problems when starting working on project.

**Comment by ag-TJNII** [comment]
Old issue, but I want to comment that this is a pain point in 2024.  I'm often packaging ruby code that uses rbenv for early/local dev, but actual deployments don't use rbenv.  Examples are deployments in Docker and AWS Lambda.  In these deployments it's generally undesirable to pin to patch, as that would inhibit the build process from automatically pulling in trivial and security updates, if the upstream source supports pinning at the patch level at all.  I just wrote some Terraform code like the following to deploy a lambda:

```hcl
locals {
 # .ruby-version / rbenv requires major.minor.patch, and lambda just deploys major.minor
  lambda_ruby_version_major_minor = join(".", slice(split(".", file("${path.module}/lambda_source/.ruby-version"), 0, 2))
}

resource "aws_lambda_function" "lambda" {
  runtime = "ruby${local.lambda_ruby_version_major_minor}"
}
```

In this kind of use case rbenv isn't part of the version enforcement between dev and prod.  It would be nice if the `major.minor.patch` requirement could be re-evaluated and softened for use cases such as this one.
