### ISSUE TITLE
Create rbenv-plugins organization to track maintainer approved plugins.

### ISSUE THREAD

**Issue by taqtiqa-mark** [rbenv/rbenv#332]
Repositories under this organization would replace the current wiki list.  

It has the benefit of widening the list of maintainers that can makes changes/fixes.  Hopefully this can relieve any burden a plugin author encounters, without them having to grant access to their repo.  

It gives people a one-stop place to look for plugins.  

Not sure if issues lists should be opened - my feeling is yes but current upstream developers might object?
It also has the benefit for giving scripts such as [rbenv-installer](https://github.com/fesplugas/rbenv-installer) a single plugin reference point.

**Comment by mislav** [comment]
We've [created the "rbenv" organization](https://github.com/rbenv) where we have pulled official plugins in (mostly ones that were written by @sstephenson and I), and will continue to do so in the future. All other plugins should be maintained by the community in separate projects, like they are right now. We won't maintain a separate rbenv-plugins org just yet.
