### ISSUE TITLE
Discussion: Global config and installs

### ISSUE THREAD

**Issue by josh** [rbenv/rbenv#38]
Since we'll be supporting system wide installs via homebrew, I'd like to establish some conventions for global config and installed files.

I know Sam likes the simplicity of `~/.rbenv`, but I don't really like putting compiled programs in my `~`. 

We already have something for plugins, a global `/etc/rbenv.d` directory.

```
RBENV_EXEC_PLUGINS=(/etc/rbenv.d/exec/*.bash ${HOME}/.rbenv/rbenv.d/exec/*.bash)
```

We should probably look for `/etc/rbenv.d/default` here too.

As for `~/.rbenv/versions`, I'd like to see them under `/usr/local/lib/rbenv`. Not sure if thats the correct place.

Also don't know where shims would go.

I'd be cool if we supported the unix hierarchy so that `~/.rbenv/default` was checked first, then `/usr/local/etc/rbenv.d/default`, then `/etc/rbenv.d/default`. Maybe thats unnecessary.

**Comment by mrjcleaver** [comment]
What happened to the system-wide install instructions?

**Comment by mislav** [comment]
It was outside of the scope of this project to provide system-wide install instructions. People we're trying it out and messing it up. Now, system install is left as an exercise to the reader.

There is nothing special that users need to do for system install. The steps are:

1. Install or symlink Ruby versions under `RBENV_ROOT/versions`
2. Ensure that processes have `RBENV_ROOT/shims` in PATH

That's it.
