### ISSUE TITLE
Equivalent to rvm migrate/upgrade?

### ISSUE THREAD

**Issue by keltia** [rbenv/rbenv#396]
When a new ruby version comes out (just like 2.0.0-p195 did a few days ago), having a way to "migrate" all gems from one to the other would be nice, just like "rvm upgrade" does.

**Comment by jasonkarns** [comment]
FYI: pyenv (python fork of rbenv) has [pyenv-pip-migrate](https://github.com/yyuu/pyenv-pip-migrate) which migrates pip packages from one python version to another.

Similarly, nodenv (nodejs fork of rbenv, natch) has [nodenv-npm-migrate](https://github.com/jawshooah/nodenv-npm-migrate) which migrates npm packages from one node version to another. (It is actually a fork of pyenv-pip-migrate.)

Would be prime material for an rbenv fork.

**Comment by ZacharyDuBois** [comment]
I'd love to see this get added :)

**Comment by jcrben** [comment]
https://github.com/nabeo/rbenv-gem-migrate worked fine for me - altho I had to get it under its own folder https://github.com/nabeo/rbenv-gem-migrate/pull/1

**Comment by Zyphrax** [comment]
It would be great if this solution was part of rbenv

**Comment by keltia** [comment]
Are you all aware that there is now a rbenv plugin that does exactly the same as the script I mentioned earlier?
```
cd .rbenv
mkdir plugins
git clone https://github.com/nabeo/rbenv-gem-migrate.git
```
After that, you can `rbenv migrate 2.5.2 2.6.2`.

**Comment by keltia** [comment]
See my previous comment for the `migrate`plugin.

**Comment by Zyphrax** [comment]
It would be great to manage system gems using bundler, but I'll have to look into how to set up that properly. My list of system gems seems like an ever growing dependency tree.
