### ISSUE TITLE
rbenv: ruby: command not found after install

### ISSUE THREAD

**Issue by seufagner** [rbenv/rbenv#399]
after install and config rbenv following rbenv documentation i got this error:

$ ruby -v
rbenv: ruby: command not found

The `ruby' command exists in these Ruby versions:
  1.8.7-p249
  1.9.3-dev
  1.9.3-p125

why? i already removed RVM installation - the single thing that I found at foruns or similar issues.

**Comment by bebekim** [comment]
Try `rbenv rehash` after `rbenv install 1.9.3-dev` @seufagner

**Comment by LittleStar9637** [comment]
I installed rbenv to ubuntu 16.04 with below [guide](https://gorails.com/setup/ubuntu/16.04)
but when I run this command, got an error message.
rails -v
-bash: /user/bin/ruby: No such file or directory.
How can I solve it?
Thanks

**Comment by kmanojkumar** [comment]
> Oops! When I used "rbenv global 2.0.0-p247", everything goes well!!!

This worked for me too! `rbenv global <version_number>`

**Comment by biendltb** [comment]
`rbenv global <version_number>` not works for me but `rbenv local <version_number>` does
