### ISSUE TITLE
Your Ruby version is 1.9.3, but your Gemfile specified 2.0.0

### ISSUE THREAD

**Issue by ichilton** [rbenv/rbenv#400]
I'm trying to run a rake task on a rails app, and am getting this error:

```
/home/vagrant/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/definition.rb:361:in     `validate_ruby!': Your Ruby version is 1.9.3, but your Gemfile specified 2.0.0 (Bundler::RubyVersionMismatch)
    from /home/vagrant/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler.rb:116:in `setup'
    from /home/vagrant/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/setup.rb:17:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
rake aborted!
```

As you can see from the paths in the error though, I am running 2.0.0:

$ ruby -v
ruby 2.0.0p195 (2013-05-14 revision 40734) [x86_64-linux]

$ bundle -v
Bundler version 1.3.5

$ gem env
RubyGems Environment:
- RUBYGEMS VERSION: 2.0.3
- RUBY VERSION: 2.0.0 (2013-05-14 patchlevel 195) [x86_64-linux]
- INSTALLATION DIRECTORY: /home/vagrant/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0
- RUBY EXECUTABLE: /home/vagrant/.rbenv/versions/2.0.0-p195/bin/ruby
- EXECUTABLE DIRECTORY: /home/vagrant/.rbenv/versions/2.0.0-p195/bin
- RUBYGEMS PLATFORMS:
  - ruby
  - x86_64-linux
- GEM PATHS:
  - /home/vagrant/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0
  - /home/vagrant/.gem/ruby/2.0.0
- GEM CONFIGURATION:
  - :update_sources => true
  - :verbose => true
  - :backtrace => false
  - :bulk_threshold => 1000
- REMOTE SOURCES:
  - https://rubygems.org/

I tried doing rbenv global 2.0.0-p195, but that didn't help. Looks like it might be trying to use system ruby instead of rbenv for some reason?

Raised an issue with bundler: https://github.com/bundler/bundler/issues/2489 but it seems to be an rbenv issue.

rake is a rbenv shim at: ~/.rbenv/shims/rake

Thanks,

Ian

**Comment by redbar0n** [comment]
Thanks @fnichol, this helped me solve a related problem. Basically that I should never run `bundle exec heroku`, but always `heroku` instead. Or ensure that I have installed the heroku-toolbelt via brew, and not the official site (and packaged installer). Installing with brew links the heroku CLI ruby version (`heroku --version`) to the one I've set with RVM (`rvm current`).

**Comment by davidsoncasey** [comment]
@fnichol exactly what I was looking for. Thanks!

**Comment by fnichol** [comment]
This is the thread that keeps on giving!

![gif-keyboard-6922171368322717703](https://cloud.githubusercontent.com/assets/261548/14659323/20925d2c-0658-11e6-8bd4-e9b869f8564a.gif)

**Comment by hodbe** [comment]
# Upgrade Ruby version 
Login as root
 
Install needed packages
`apt-get -y install build-essential zlib1g-dev libssl-dev libreadline6-dev libyaml-dev`
 
`cd /tmp`
 
 Download appropriate ruby version https://www.ruby-lang.org/en/downloads/
`wget http://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.2.tar.gz`
 
 Unpack downloaded package 
`tar -xvzf ruby-2.1.2.tar.gz`
`cd ruby-2.1.2/`
 
 Compile from source
`./configure --prefix=/usr/local`
`make`
`make install`
