### ISSUE TITLE
unable to set global or or local ruby on freebsd

### ISSUE THREAD

**Issue by jeezs** [rbenv/rbenv#401]
Hello,
I just install rbnev on freebsd 9.1.
 when I set a global ruby, the chosen ruby is lost, when I relog
the problem appear in this line
I try to reinstall many time, I try : "rbenv global --unset" 
but i always obtain the folowing error : 
 `/home/jeezs/.rbenv/libexec/rbenv-version-file-read: line 23: /dev/fd/62: No such file or directory`
so I check on some forum and they say I need to symlink this, so I also try : 
`sudo ln -s /proc/self/fd /dev/fd`
It doesn't work to.
so here is the debug file from rbenv: 

```
+ rbenv --version
rbenv 0.4.0-45-g060f141
+ rbenv versions
/home/jeezs/.rbenv/libexec/rbenv-version-file-read: line 23: /dev/fd/62: No such file or directory
  1.8.7-p371
  2.0.0-p195
+ rbenv global
system
+ env
+ grep -E 'PATH|RUBY|BUNDLE|RBENV'
PATH=/home/jeezs/.rbenv/shims:/home/jeezs/.rbenv/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/home/jeezs/bin
+ which gem
/home/jeezs/.rbenv/shims/gem
+ rbenv which gem
/home/jeezs/.rbenv/libexec/rbenv-version-file-read: line 23: /dev/fd/62: No such file or directory
rbenv: gem: command not found

The `gem' command exists in these Ruby versions:
  1.8.7-p371
  2.0.0-p195

+ cat /etc/gemrc
cat: /etc/gemrc: No such file or directory
+ cat /home/jeezs/.gemrc
cat: /home/jeezs/.gemrc: No such file or directory
+ gem env
/home/jeezs/.rbenv/libexec/rbenv-version-file-read: line 23: /dev/fd/62: No such file or directory
rbenv: gem: command not found

The `gem' command exists in these Ruby versions:
  1.8.7-p371
  2.0.0-p195 
```

Can you help?

Thanks

**Comment by sekrett** [comment]
I tried in on FreeBSD. Bash works only after reinstalling it from ports, but zsh does not work both from packages and ports.
