### ISSUE TITLE
configure: error: C compiler cannot create executables

### ISSUE THREAD

**Issue by jmatelli** [rbenv/rbenv#440]
I try to install the last stable version of ruby. But I have this error:

```
BUILD FAILED

Inspect or clean up the working tree at /var/folders/fn/1kz6tqdd2b58vl6lggn7ks4r0000gn/T/ruby-build.20130901135911.4559
Results logged to /var/folders/fn/1kz6tqdd2b58vl6lggn7ks4r0000gn/T/ruby-build.20130901135911.4559.log

Last 10 log lines:
checking build system type... x86_64-apple-darwin12.4.0
checking host system type... x86_64-apple-darwin12.4.0
checking target system type... x86_64-apple-darwin12.4.0
checking for gcc-4.2... gcc-4.2
checking for gcc... (cached) gcc-4.2
checking whether the C compiler works... no
configure: error: in `/var/folders/fn/1kz6tqdd2b58vl6lggn7ks4r0000gn/T/ruby-build.20130901135911.4559/ruby-2.0.0-p247':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** No targets specified and no makefile found.  Stop.
```

I'm on mac OS 10.8
I opened xcode to see that the command line tool was not installed, so I installed it and I updated my rbenv and ruby-build using homebrew but there is still the error.

**Comment by grantgeorge** [comment]
@yagudaev @hiteshsharma helped me, thanks ;)

**Comment by t0d0r** [comment]
Hi, I managed to compile ruby 1.8.7-p375 on El Capitan (10.11.1), here's how:

```
brew install apple-gcc42
xcode-select --install
export CC=/usr/local/bin/gcc-4.2
rbenv install 1.8.7-p375
```

**Comment by mscottford** [comment]
@t0d0r: Thanks a bunch for posting your work around. Totally worked for me.

**Comment by jinnko** [comment]
Following an upgrade to OSX 10.11 El Capitan, just the following command was needed:

```
xcode-select --install
```

Thanks to @t0d0r for the tip.

**Comment by slater1** [comment]
I was trying to build vim and came to this page on the search term "C compiler cannot create executables"

The suggestion to use `xcode-select` was ineffective for me on OS X 10.10.5:

`xcode-select --install`
`xcode-select: error: command line tools are already installed, use "Software Update" to install updates`

However, calling `./configure` and then `make` succeeded.

**Comment by davidcpell** [comment]
@t0d0r's solution also worked for me, with slight alterations. I'm on 10.12 so not sure if it's because of that or other points specific to my environment, but here are the notes I made:

```
$ brew install apple-gcc42
Error: No available formula with the name "apple-gcc42"
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
This formula was found in a tap:
homebrew/dupes/apple-gcc42
To install it, run:
  brew install homebrew/dupes/apple-gcc42

$ brew install homebrew/dupes/apple-gcc42
# worked!
```

```
$ brew install openssl
Warning: openssl is a keg-only and another version is linked to opt.
Use `brew install --force` if you want to install this version

# Just skipped this one
```

```
$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

# Skipped
```

Did everything else as described.

**Comment by vshy108** [comment]
in my case, restart osx solved the problem.

**Comment by shivabhusal** [comment]
for Mint 19 I had to install this too `sudo apt install gobjc++` and then it could compile the source code.
