### ISSUE TITLE
shebang env

### ISSUE THREAD

**Issue by tcurdt** [rbenv/rbenv#472]
I've run into the issue that a ruby script works just fine on the command line but not from an Xcode build phase. Now the problem is that `rbenv` is setup in my `.profile` which is not run when the script is run through e.g. Xcode or `cron`.

Now of course I could wrap the ruby script in a shell script to setup the env correctly. But if would be nice if rbenv would come with something like this by default. So the my `rbenv-ruby` file looks like this:

```
#!/bin/sh
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
ruby $*
```

With this in the path you can now use it a shebang and don't have to worry about the env anymore.

```
#!/usr/bin/env rbenv-ruby
puts "running ruby from rbenv"
```

Of course the fact that `rbenv-ruby` has to be in the path is a bit of a chicken and egg problem. Not using `env` but calling an interpreter directly would of course be even cooler. This does not work with a script like that though.

```
#!/usr/bin/rbenv-ruby
puts "running ruby from rbenv"
```

Anyway - just tossing around some ideas here.

**Comment by charles-dyfis-net** [comment]
FYI, `ruby $*` is very, very buggy -- try passing arguments with whitespace or quoted wildcards. (`ruby my-prog.rb "hello world"` will become `ruby my-prog.rb hello world`, for instance). Use `ruby "$@"` instead.

**Comment by vyder** [comment]
If anybody stumbles across this from Google, I found that the simplest thing to do was:

Have devs install `rbenv` on their machines, and add `~/.rbenv/shims` to the PATH in the XCode build script like:

    export PATH=~/.rbenv/shims:$PATH
    # Exec rest of your script
    # ...

---

A slightly more complicated, but more customizable solution is to have your script start with the following:

    XCODE_ENV=.xcode-env
    XCODE_LOCAL_ENV=.xcode-env-local

    # Setup your env variable overrides here
    if [ -f $XCODE_LOCAL_ENV ]; then
        source $XCODE_LOCAL_ENV
    fi

    # Source default environment variables
    source $XCODE_ENV
    
    # Exec rest of your script
    # ...

The `.xcode-env` file contains:

    #
    # Default XCode ENV
    #

    # Set RBENV_SHIMS if undefined
    if [ -z $RBENV_SHIMS ]; then
        RBENV_SHIMS=~/.rbenv/shims
    fi
    export PATH=$RBENV_SHIMS:$PATH

So, if you want to specify alternative environment variables, you can create a `.xcode-env-local` (which is gitignored) with content like:

    RBENV_SHIMS=/some/other/path/to/.rbenv/shims
