### ISSUE TITLE
-bash: rbenv: command not found

### ISSUE THREAD

**Issue by ryanburnett** [rbenv/rbenv#474]
I'm running Mac 10.9 with Xcode 5.0.1 Command Line Tools installed. I'm trying to follow rbenv's "Installation" steps under "Basic GitHub Checkout":

`git clone https://github.com/sstephenson/rbenv.git ~/.rbenv`
`echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile`
`echo 'eval "$(rbenv init -)"' >> ~/.bash_profile`

...I restart Terminal and receive this error:

`-bash: rbenv: command not found`

My .bash_profile previously contained these paths for node/npm and git:

> export PATH="/usr/local/bin:/usr/local/git/bin:$PATH"

...after following the steps above my .bash_profile now looks like this:

> export PATH="/usr/local/bin:/usr/local/git/bin:$HOME/.rbenv/bin:$PATH"
> eval "$(rbenv init -)"

Here are my troubleshooting answers:

`which rbenv`
`(no response)`

...and:

`echo $PATH | grep --color=auto "$(rbenv root)/shims"`
`-bash: rbenv: command not found`

Any ideas as to what I need to edit in my .bash_profile to get rbenv working?

**Comment by alishahpakneeds** [comment]
Restart your shell
exec -l $SHELL

**Comment by ldco2016** [comment]
@alishahpakneeds that command you shared solved a similar issue for me, thank you.

**Comment by jaafaresprit** [comment]
@alishahpakneeds that command you shared solved my problem to install ruby, thank you.

**Comment by wellington1993** [comment]
@aliabbas-2012 Solved the problem here!

**Comment by gordlf11** [comment]
Resolved removing ~Rbenv validation from /.bash_profile

**Comment by fernandodev** [comment]
You can run the command by setting its path

`RUN PATH="$HOME/.rbenv/bin:$PATH" rbenv install ${RUBY_VERSION}`
