### ISSUE TITLE
Keeps adding ~/.rbenv dir even though RBENV_ROOT has been set to other dir

### ISSUE THREAD

**Issue by hced** [rbenv/rbenv#508]
I've installed `rbenv` via `brew` and per Homebrew's caveats I've appended the following to my `~/.zprofile`:

```
#
# rbenv
#

# Enable shims and autocompletion (per Homebrew's caveat after installing rbenv and ruby-build)
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Use Homebrew's directories rather than ~/.rbenv (also per Homebrew's caveats)
export RBENV_ROOT=/usr/local/var/rbenv
```

After removing `~/.rbenv`, this dir is still re-created each time I restart my shell. Can this be prevented somehow?

**Comment by njvack** [comment]
~/.rbenv might be unsuitable in a production environment; it's entirely possible that the user running your production app doesn't have a home directory.

**Comment by mislav** [comment]
@njvack Sure. In those cases, setting an explicit `RBENV_ROOT` to your preferred location before initializing rbenv is the key.
