### ISSUE TITLE
Installing gems with --user-install

### ISSUE THREAD

**Issue by mkaito** [rbenv/rbenv#554]
I'm only pointing this out because `--user-install` is the default on Arch Linux, and it took me a while to figure this one out.

When installing a gem with `--user-install`, it gets installed in `~/.gem`, where rbenv isn't aware of them or their binaries. I'm not sure rbenv can actually do anything about this, but you could point it out in the documentation.

**Comment by mislav** [comment]
The [official `rbenv-doctor` script now has a check for this](https://github.com/rbenv/rbenv-installer/blob/40b1c0088b95fd5d9c76aa3af6ab912b7d80233b/bin/rbenv-doctor#L141-L149) and will suggest removing `--user-install` from gemrc if found. Closing in favor of doctor script.
