### ISSUE TITLE
Fail to install 2.0.0-p353 on Ubuntu 14.04

### ISSUE THREAD

**Issue by AHaymond** [rbenv/rbenv#582]
I am at a loss, please help me get this working, Here is a copy of the install log

[https://gist.github.com/AHaymond/11048813](https://gist.github.com/AHaymond/11048813)

**Comment by jeansaigne** [comment]
I just went threw this issue, and i found so many people giving their own solution so i'm gonna give mine for the next one: It simply patches the readline issue and it worked like a charm for me, by the way i'm using this distro: (Linux Mint 17 Qiana)
Linux laptop 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

curl -fsSL https://gist.github.com/LeonB/10503374/raw | rbenv install --patch 2.0.0-p353

**Comment by klebershimabuku** [comment]
Thank you, @jeansaigne! 

This patch also worked for me. I'm running Ubuntu 14.04

`Linux 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`
