### ISSUE TITLE
rbenv, ruby, bundler, gems all set up but not working

### ISSUE THREAD

**Issue by rahuldsouza** [rbenv/rbenv#592]
Just installed everything yesterday according to the [octopress guidelines](http://octopress.org/docs/setup/rbenv/) and they all worked fine, but when I woke up today to finish work, none of it works.

All my errors follow the format below
After
$ ruby -v
I get the following error
bash: ruby: command not found

The same occurs when I try using rbenv, bundle or gem. 

The only thing that I can think of is when I installed rbenv, and went to check ~/.profile, it did not exist. However since it worked at the time I didn't think too much about it. Is that my mistake, should I generate a ~/.profile document.

Should I uninstall or reinstall rbenv, ruby and gems?

Sorry for the trouble, I'm just finding my way in ruby and can't really troubleshoot easily just yet.

**Comment by shammellee** [comment]
@mislav that solved it for me, thanks! I had `eval "$(rbenv init -)"` before exporting `PATH`
