### ISSUE TITLE
ruby: no Ruby script found in input (LoadError) when passing ruby -S a shim

### ISSUE THREAD

**Issue by deiga** [rbenv/rbenv#622]
I've discovered a weird issue with `seeing_is_believing` gem and what I believe to be rbenv shims.

Theres some testing over at https://github.com/JoshCheek/atom-seeing-is-believing/issues/5
- running `seeing_is_believing` on it's own works
- passing the true path works (`ruby -S $(rbenv which seeing_is_believing)`)
- passing the gem to ruby does not work (`ruby -S seeing_is_believing`)

Here is my env setup https://gist.github.com/deiga/a929c06a6831404aff28

**Comment by sj26** [comment]
This happened to me on a completely clean ruby and rbenv install. Not sure why. I ran this for all gems across all rubies with:

```bash
for version in $(rbenv versions --bare); do
  RBENV_VERSION=$version gem pristine --all --only-executables
done
```
