### ISSUE TITLE
rbenv ruby 2.0.0 and byebug debugger

### ISSUE THREAD

**Issue by MichalMichalak** [rbenv/rbenv#629]
Hello. I have a problem with installing byebug debugger under ruby 2.0.0 (this is customer's requirements and can't be changed). I am using OS X 10.9.5. I installed rbenv according to manual, using homebrew, and everything worked fine so far. I can easily develop apps and no other gem gives me any issues. Yet, when I try to install byebug it ends with error

```
$ gem install byebug
ERROR:  Error installing byebug:
byebug requires Ruby version >= 2.0.0.
```

Now, my ruby version is:

```
$ rbenv global
2.0.0-rc2
```

And my all ruby 2.0.0 versions are as follows:

```
$ rbenv install -l | grep 2.0.0
2.0.0-dev
2.0.0-preview1
2.0.0-preview2
2.0.0-rc1
2.0.0-rc2
2.0.0-p0
2.0.0-p195
2.0.0-p247
2.0.0-p353
2.0.0-p451
2.0.0-p481
2.0.0-p576
maglev-2.0.0-dev
rbx-2.0.0-dev
rbx-2.0.0-rc1
rbx-2.0.0
```

My question is, which is the most recent 2.0.0 and which one should I choose to have byebug gem working properly? Thanks for all help.

**Comment by kaleemullah360** [comment]
Apparently byebug is no longer being maintained so you simply need to update to `pry-byebug`
**Remove:**
`gem 'byebug'`
**Replace with:**
`gem 'pry-byebug', platform: [:ruby_20]`

[Source -Gem::InstallError: byebug requires Ruby version >= 2.0.0](http://jakelitwicki.com/2015/06/15/geminstallerror-byebug-requires-ruby-version-2-0-0/)
