### ISSUE TITLE
: No such file or directory

### ISSUE THREAD

**Issue by ghost** [rbenv/rbenv#646]
Hi all. I have problem after update rbenv. I runing git pull origin in ~/.rbenv. Аfter that, when I run any commands for example: $ rbenv install --list. I got error : No such file or directory.
Have you any idea fix it?
rbenv-doctor.sh output https://gist.github.com/avastor/ffabb80ed048c3c69061

``` code
========================================================================
$ ls -ls ~/.rbenv/bin/
total 4
0 lrwxrwxrwx 1 user group  16 Nov  3 13:42 rbenv -> ../libexec/rbenv
4 -rwxrwxr-x 1 user group 747 Nov  3 13:40 ruby-local-exec
========================================================================
~/.rbenv$ git remote -v
origin  https://github.com/sstephenson/rbenv.git (fetch)
origin  https://github.com/sstephenson/rbenv.git (push)
~/.rbenv$ git branch 
* master
~/.rbenv$ git log -1
commit 7e0e85bdda092d94aef0374af720682c6ea8999d
Author: Mislav Marohnić <mislav.marohnic@gmail.com>
Date:   Sun Oct 19 18:06:09 2014 +0200

    Avoid JRuby warning during rehash Rubygems plugin

    As it seems, JRuby 1.7 complains on stderr every time you invoke `system`:

        warning: executable? does not in this environment and will return a dummy value

    It doesn't seem to complain when backtics are used. It's safe to use
    backticks here because `rbenv rehash` doesn't output anything on stdout,
    and the exit status of the command is irrelevant.
========================================================================
# my ~/.bashrc
export RBENV_ROOT="${HOME}/.rbenv"
if [ -d "${RBENV_ROOT}" ]; then
  export PATH="${RBENV_ROOT}/bin:${PATH}"
  eval "$(rbenv init -)"
fi
========================================================================
$ . ~/.bashrc 
: No such file or directory
========================================================================
$ type rbenv 
rbenv is hashed (/home/user/.rbenv/bin/rbenv)
```

**Comment by rkJun** [comment]
@mislav I had same problem by ```git config core.autocrlf true```. And solved. Thanks. :+1:

**Comment by samsoft00** [comment]
Please help, i'm having the same problem... change the tag to this ---> #!/bin/bash -x and run ```RBENV_DEBUG=1 rbenv --version``` it split the error below
```
$ ~/.rbenv/libexec/rbenv --version
+ set -e
+ export -n CDPATH
+ '[' --version = --debug ']'
+ '[' -n '' ']'
+ enable -f /c/Users/Al-Mukhtarr/.rbenv/libexec/../libexec/rbenv-realpath.dylib
realpath
+ '[' -n '' ']'
++ type -p greadlink readlink
++ head -1
+ READLINK=
+ '[' -z '' ']'
+ echo 'rbenv: cannot find readlink - are you missing GNU coreutils?'
rbenv: cannot find readlink - are you missing GNU coreutils?
+ exit 1
```
When i run type
```
$ type rbenv
rbenv is hashed (/c/Users/Al-Mukhtarr/.rbenv/bin/rbenv)
```
Please what can i do???

**Comment by mislav** [comment]
@samsoft00 rbenv will not work on a Windows environment, even though Unix-style is emulated through a tool such as cygwin. It needs a proper Unix environment.

**Comment by samsoft00** [comment]
Thanks @mislav, so can you suggest any other package to manage different ruby version??? Thanks in advance

**Comment by mislav** [comment]
Yes, [RVM](http://rvm.io/) should work well on Windows.

**Comment by samsoft00** [comment]
@mislav thanks

**Comment by Polokij** [comment]
Thanks, ` git config --global core.autocrlf false` fixed the issue.

**Comment by USvER** [comment]
Had the same issue. Had to change global autocrlf configuration to false and back to true for rbenv to work.
Someone should fix this once and for all.

**Comment by lakhanbrowserstack** [comment]
For me it worked when I updated the rbenv version to `1.2.0` from `1.1.2`. It didn't update the version in `~/.rbenv/shims/bundle` file. Manually changed this line `exec /usr/local/Cellar/rbenv/1.2.0/libexec/rbenv` with the updated version. Not sure why it wasn't updated the `rbenv` update 😞

**Comment by casperbrike** [comment]
@lakhanbrowserstack I got the same problem and fixed it with the following command: `rbenv rehash`.

**Comment by mislav** [comment]
@lakhanbrowserstack @casperbrike We've fixed this in rbenv 1.2.0 https://github.com/rbenv/rbenv/releases/tag/v1.2.0, however it requires a manual `rbenv rehash` after the upgrade. Sorry for the inconvenience; hopefully it won't happen again

**Comment by dream-build-coder** [comment]
Hi, I need some help. 
I am using windows 10.
I cloned a repository using below command on git bash - git clone https://github.com/rbenv/rbenv.git ~/.rbenv
Then configured 
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc

So my bashrc file looks like this:
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

And if I run "command -v rbenv" it says the correct path : /c/Users/Smile0903/.rbenv/bin/rbenv

But "which rbenv" doesn't work it says below.
which: no rbenv in (/c/Users/Smile0903/.rbenv/bin:/c/Users/Smile0903/.rbenv/bin:/c/Users/Smile0903/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/Smile0903/bin:/c/Program Files/Microsoft/jdk-17.0.5.8-hotspot/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/cmd:/c/Program Files (x86)/Yarn/bin:/c/Program Files/dotnet:/c/Program Files/PuTTY:/c/Program Files/Microsoft/jdk-17.0.5.8-hotspot/bin:/c/Users/Smile0903/AppData/Roaming/nvm:/c/Program Files/nodejs:/c/Ruby32-x64/bin:/c/Ruby32-x64/bin:/c/Users/Smile0903/AppData/Local/Microsoft/WindowsApps:/c/Users/Smile0903/AppData/Local/Programs/Microsoft VS Code/bin:/c/Users/Smile0903/AppData/Local/Yarn/bin:/c/Users/Smile0903/AppData/Roaming/npm:/c/Users/Smile0903/AppData/Roaming/nvm:/c/Program Files/nodejs:/usr/bin/vendor_perl:/usr/bin/core_perl)


And whenever I open the gitbash, it outputs this error "/c/Users/Smile0903/.rbenv/bin/rbenv: line 1: ../libexec/rbenv: No such file or directory"

The files and folders are accessible. I checked them by using "ls -l" command.

What is the issue and how can I solve it?

Thanks.

![image](https://github.com/rbenv/rbenv/assets/90780295/1ae54d8d-86cb-445a-a0a7-47d40f0988e4)
![image](https://github.com/rbenv/rbenv/assets/90780295/db014271-8c37-4484-8a7d-e18bdbf97a57)
![image](https://github.com/rbenv/rbenv/assets/90780295/1cf156d0-13ff-49e0-a96e-fa343124b92c)

**Comment by mislav** [comment]
@dream-build-coder Thank you for the detailed report, but rbenv only works on Linux or Unix-like machines, but not Windows. Git Bash on Windows may feel like a Unix-like environment, but is not perfectly compatible, and rbenv probably won't work under it and will result in all kinds of cryptic errors. I do not know of solutions, nor would I advise attempting any.

However, it's a popular alternative for developers on Windows 10+ to set up their development environment under WSL2. There rbenv will work perfectly because it's a "true" Linux operating system.
