### ISSUE TITLE
Can we change the `versions' directory?

### ISSUE THREAD

**Issue by pablox-cl** [rbenv/rbenv#671]
Right now, I'm linking to another path, but I was wondering if there were a way to use `~/.rubies` for example?

**Comment by PaBLoX-CL** [comment]
Oh, I was speaking about using some configuration option, not by symlinking that was what I was already doing. Thanks anyway :)

**Comment by mislav** [comment]
You can also set `RBENV_ROOT` environment variable to change where rbenv looks up user data (default: `~/.rbenv`). However that will also change where it looks for global version setting `$RBENV_ROOT/version`, versions directory (`$RBENV_ROOT/versions`), plugins directory, and more. If you want to change just 1 directory location, it's best to use symlinks.
