### ISSUE TITLE
deploy rbenv with rpm and install system wide

### ISSUE THREAD

**Issue by crhan** [rbenv/rbenv#678]
I'm not good at documenting, so if you think this work is good, you can keep it in your docs.
### install

```
yum install rbenv-ruby21 rbenv-ruby22
```

![screen_shot_2015-01-11_at_11_42_48_am](https://cloud.githubusercontent.com/assets/532040/5694383/31478a64-9991-11e4-913f-171eb14d848f.png)
### and use it

![screen_shot_2015-01-11_at_11_52_14_am](https://cloud.githubusercontent.com/assets/532040/5694386/58deafe4-9991-11e4-8d04-500fe2995b31.png)
## RPM specs

https://gist.github.com/crhan/6800d9887aca1a5cf4b9

**Comment by mislav** [comment]
Thanks, I've added the info to our wiki https://github.com/sstephenson/rbenv/wiki/Deploying-with-rbenv

**Comment by crhan** [comment]
Errr... But the RPMs are not present in any public repos, so user should build the RPM themself. That's why I provide the spec file in gist

**Comment by mislav** [comment]
Wow, you're right; you're really not good at documenting :) You should have told me that in the first place, before demonstrating the `yum install` command.

So what are the exact steps needed to build the RPMs from your spec?

**Comment by crhan** [comment]
Build a RPM from raw is a bit more difficult for end user. I'm now trying to build these package on OBS.

Here is my progress.. [OBS:rbenv](https://build.opensuse.org/project/monitor?utf8=%E2%9C%93&commit=Filter%3A&succeeded=1&failed=1&unresolvable=1&broken=1&blocked=1&dispatching=1&scheduled=1&building=1&finished=1&signing=1&locked=1&deleting=1&pkgname=&repo_CentOS_5=1&repo_CentOS_6=1&repo_CentOS_7=1&repo_Fedora_19=1&repo_Fedora_20=1&repo_Fedora_21=1&repo_RHEL_5=1&repo_RHEL_6=1&repo_RHEL_7=1&arch_x86_64=1&project=home%3Acrhan%3Arbenv&defaults=0)

**Comment by mislav** [comment]
OK, let me know when there is a relatively simple set of instructions that a regular user can follow. Then we can add those back to the wiki.

**Comment by crhan** [comment]
Choose your distribution and download the RPM on [OBS](https://build.opensuse.org/project/monitor/home:crhan:rbenv) site?

or just find the RPMs here by hand: http://download.opensuse.org/repositories/home:/crhan:/rbenv/

**Comment by crhan** [comment]
maybe this page is much easy to read: http://software.opensuse.org/download.html?project=home%3Acrhan%3Arbenv&package=rbenv-ruby21

**Comment by mislav** [comment]
That site seems helpful, thanks for the link.

Since these are not official RPM packages for these distros, I'm going to hold off documenting this in our wiki just yet. However, your RPM specs give me an idea that we could maintain and publish these rpms ourselves in the future.

**Comment by crhan** [comment]
no prob

**Comment by josdotso** [comment]
+1 on the need for pre-built RPMs.  RHEL7/CentOS7 would be a good place to start.

**Comment by bcg62** [comment]
@crhan are the spec's in a project somewhere? If you change the urls to something like:

```
URL:		https://github.com/sstephenson/%{name}
Source0:	%{url}/archive/v%{version}.tar.gz
```

You can use spectool (spectool -g -R rbenv.spec) to grab the source which streamlines automated building.

**Comment by crhan** [comment]
nope, the spec is just in the gist or you can find it in the obs site: https://build.opensuse.org/package/show/home:crhan:rbenv/rbenv-ruby21

I'm not going to maintain this spec, so feel free to take any change to the spec and publish your spec
