### ISSUE TITLE
Hook for local, global, shell

### ISSUE THREAD

**Issue by docwhat** [rbenv/rbenv#690]
I have a use case for a hook for `rbenv local`, `rbenv global`, and `rbenv shell`...

I would use the hook to look for `/opt/chefdk` and if it existed then symlink it into the `versions` directory before switching.  It would make my [ChefDK plugin](https://github.com/docwhat/rbenv-chefdk) complete.

I suppose the hook should also be run before `rbenv versions` as well.

**Comment by mislav** [comment]
Interesting use case, but not sure whether we want to define so many extra hooks just for this one use-case. Shouldn't people explicitly opt to symlink versions into their `RBENV_ROOT/versions` so that they're aware which exact Ruby version they're using?

**Comment by docwhat** [comment]
I have that as the current instructions but I was trying to think how to make it more user friendly. 

I totally understand if it adds to much of a maintenance cost for the benefit. I appreciate the clean and readable code in rbenv. 

I suspect the `rbenv-use` and `rbenv-aliases` could make use of an `rbenv versions` hook.

**Comment by mislav** [comment]
Take a peek at #637 for an upcoming feature about aliases ;)

**Comment by docwhat** [comment]
Love it!  What happens if the symlink points to something in `/opt`?

**Comment by mislav** [comment]
> What happens if the symlink points to something in /opt?

It is displayed like before. "Aliases" are only symlinks within the same directory.

**Comment by mislav** [comment]
A hook for `version-name` was added in https://github.com/rbenv/rbenv/commit/258e4413b165b87e4c0c3190b45c1a167678b4d5.

**Comment by mislav** [comment]
Closing this due since I don't really think we'd be adding extra hook anytime soon.
