### ISSUE TITLE
rbenv plugin command

### ISSUE THREAD

**Issue by mrjcleaver** [rbenv/rbenv#691]
Until https://github.com/docwhat/rbenv-chefdk I didn't know rbenv had plugins... I had to go look at https://github.com/sstephenson/rbenv/blob/d1a0398fdb99b548fd3846228e61f096b6982e60/libexec/rbenv#L73 to figure out.

Request:

```
$ rbenv plugins
rbenv: no such command `plugins'
```

Should list what plugins are available, install, upgrade and remove them.

Or did I miss something?

**Comment by mislav** [comment]
Plugins are literally listed as a feature in the 4th paragraph of README with a link to [this comprehensive wiki article](https://github.com/sstephenson/rbenv/wiki/Plugins). What more could you want?

If there was an `rbenv plugin` command I don't think plugins would be more visible. People still might not know that the command exists, unless they dig through command-line help.

The problem with having a command that installs and upgrades rbenv plugins is that depending on how rbenv is set up on the system, plugins will be installed via different means. Typicall usage is git clone to install, but a system managed with Chef or Puppet (or Boxen) will install them via provisioning recipes.

It's not a bad idea, having an `rbenv plugins` command, but I don't feel right now it solves the problem we're having around plugins.

**Comment by jwfearn** [comment]
Please reopen.  A command to simply **list** the currently installed set plugins would be very useful.

Other features (install, uninstall, outdated, update, etc.) would be great but obviously much more effort to implement.

Please just do `rbenv plugin list` or `rbenv plugins` or whatever.

**Comment by mislav** [comment]
This issue is still open and I'm :+1: for the idea of the `plugin` subcommand.

**Comment by mislav** [comment]
Closing as stale
