### ISSUE TITLE
rbenv: rails: command not found

### ISSUE THREAD

**Issue by meleyal** [rbenv/rbenv#73]
How do you run gem executables without Bundler / `bundle exec`?

```
~ $ rbenv rehash
~ $ rbenv global
1.9.2-p290
~ $ gem which rails
/Users/meleyal/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/railties-3.1.0/lib/rails.rb
~ $ rails new test
rbenv: rails: command not found

The `rails' command exists in these Ruby versions:
  1.8.7-p352

~ $ bundle exec rails new test
Could not locate Gemfile
```

Maybe related to #40, #61

**Comment by tmartyny** [comment]
I had the same issue and the solutions above didn't fix my problem. This error came up for me after upgrading my global Ruby version to 2.2.2. After upgrading I had to run:

rbenv shell 2.2.2

once I set that, I was then able to install bundler and then bundle in my app directory. Here is the stackoverflow post that helped me: http://stackoverflow.com/questions/17562426/installing-gems-to-which-ruby-with-rbenv

**Comment by mislav** [comment]
@tmartyny You have to install Bundler for each Ruby version just intend to use it on. When you did `rbenv global 2.2.2` that doesn't mean that the global version applied to your current directory. Maybe there was a `.ruby-version` file in the local directory specifying a different Ruby version. In any case, you can install bundler for each Ruby version with:

```sh
for ver in `rbenv versions --bare`; do RBENV_VERSION=$ver gem i bundler; done
``

**Comment by FWOliver** [comment]
First remove any previous docs of yaml by

cd .rvm/src
sudo rm -rf yaml*
Then you can do rest of the install by -

rvm pkg install libyaml

P.S You will need to reinstall ruby after this.

**Comment by mislav** [comment]
@FWOliver You seem to be using RVM, which is a different Ruby version manager than "rbenv", which is what we are discussing here.

**Comment by Kzai** [comment]
Hey - I am using zsh and was wondering why I am getting the following warning every time I launch terminal: <code>/Users/user/.zshenv:2: command not found: rbenv </code>

Everything appears to be fine and I am using rbenv to manage my versions with the following <code>.zshenv</code> file (did not work in <code>.zshrc</code> as suggested in various online resources.)
<code>export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
alias bex="bundle exec"</code>

**Comment by mislav** [comment]
It seems that `~/.rbenv/bin/rbenv` doesn't exist, which would suggest that perhaps you didn't install rbenv properly?

**Comment by Kzai** [comment]
Thanks @mislav . There is no <code>~/.rbenv/bin/rbenv</code> - it doesn' t exist. The directory <code>~/.rbenv/bin</code> does exist and contains only <code>plugins  shims    version  versions</code>. 

Which ruby gives <code>/Users/user/.rbenv/shims/ruby</code>. I have been able to set the ruby version to 2.2.3 for a project I am working on and have been installing gems using bundle install. On investigation, the specific gems have been installing to <code>~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems<code>. Seems strange to have a 2.2.0 directory within 2.2.3 directory. 
Not really sure whats going on. I installed with homebrew.

**Comment by sebkkom** [comment]
@mislav's [solution](https://github.com/rbenv/rbenv/issues/73#issuecomment-28580075) did it for me as well but `~/.rbenv/shims` is a folder so I had to type `rm -rf ~/.rbenv/shims` instead to make it work properly. Thanks a lot Mislav!

**Comment by kvokka** [comment]
@abcbots Thank you, man! It helps.

**Comment by Princetambar** [comment]
when i run chef-client with then i am getting this error even though i have installed 2.1.0 and 2.3.1 both ruby version using rbenv.

The `bundle' command exists in these Ruby versions:
  2.1.0
stuck with this issue, can anyone help me

**Comment by ddagone** [comment]
I got the same issue with Intellij IDEA, all I did was to change the SDK to 2.3.3 from 2.4
then `$ gem install rails ` -> `$ bundle install`  😊

**Comment by jayapriyam** [comment]
gem install bundler

**Comment by oNguyenQuangVinh** [comment]
you should copy part init rails from file `bashrc` to ` zshrc`, i use `gedit ~/.bashrc` and `gedit ~/.zshrc` to open them.
like me : 
[code]
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"[/code]
sr if my english is very bad :(
thank for help me fix my english :)

**Comment by ccastillop** [comment]
Just in case. Working on Ubuntu 16.04
rbenv usually is installed using .bashrc
In my case, I added last lines also to .profile and now cron is working fine:

I added these lines to .profile, copied from .bashrc
```
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
```

**Comment by arefin-zeno** [comment]
`gem install rails` fixed it
