### ISSUE TITLE
Alert users if ruby-build isn't installed.

### ISSUE THREAD

**Issue by ryanstout** [rbenv/rbenv#738]
I spent the better part of an hour trying to figure out why ```rbenv install``` was removed (and how to install rubies again).  I assumed that the command was removed (since its invoked from rbenv), and it seemed like all of the docs were out of date.  (Obviously now it turned out that I didn't have ruby-build installed).  It might make since to just alert the user if they run ```rbevn install``` that they don't have ruby-build installed.

Thanks!

**Comment by mislav** [comment]
rbenv is a project that was designed not to have any knowledge of how you will install Ruby versions. ruby-build was a separate project that provided an rbenv plugin to handle installation.

However, [rbenv built-in help output does mention `install` and `uninstall` commands](https://github.com/sstephenson/rbenv/blob/5b9e4f05846f6bd03b09b8572142f53fd7a46e62/libexec/rbenv-help#L146) even if ruby-build was never installed. I realize that this can be confusing.

Your proposal sounds reasonable for user-friendliness, but will require us to bake some knowledge of ruby-build status within rbenv. @sstephenson what do you think of this?

**Comment by danqing** [comment]
Maybe it can say something like:

    rbenv: install is not found (maybe you need to install ruby-build?)

If the user uses something else, they most likely can infer what's wrong from that.

**Comment by mislav** [comment]
The [official `rbenv-doctor` script](https://github.com/rbenv/rbenv-installer/blob/40b1c0088b95fd5d9c76aa3af6ab912b7d80233b/bin/rbenv-doctor) that's being developed in a separate repo now checks for presence of ruby-build.

<img width="886" alt="screen shot 2015-12-24 at 1 15 19 am" src="https://cloud.githubusercontent.com/assets/887/11987237/d915956e-a9db-11e5-97d2-d65c18ce12b3.png">

Closing this in favor of the doctor script, which will be a suggested resource in documentation, as well as post-processing part of the installer script.
