### ISSUE TITLE
rbenv: cannot rehash: /usr/local/var/rbenv/shims/.rbenv-shim exists

### ISSUE THREAD

**Issue by Drewshg312** [rbenv/rbenv#759]
Hi! When trying to `$ rbenv rehash` getting:

```
rbenv: cannot rehash: /usr/local/var/rbenv/shims/.rbenv-shim exists
```

What does that mean?

**Comment by mislav** [comment]
During the rehash process, rbenv writes out the temporary file `.rbenv-shim` to indicate that the rehash is in progress. Then, if a parallel `rbenv rehash` process tries to run at the same time, it will fail because the file already exists. This guards against race conditions in parallel rehashes.

It doesn't sound like you're running multiple `rbenv rehash` processes in parallel, though. It seems like `.rbenv-shim` file was never cleaned up after a rehash that ran earlier. That earlier process might have been killed prematurely and never cleaned up after itself.

Solution: remove the file and try again.

**Comment by shyjt** [comment]
@mislav 
>That earlier process might have been killed prematurely and never cleaned up after itself.

I'm wondering what can be the root cause for such scenario?

**Comment by mislav** [comment]
@shyjt I don't know! Maybe if you run `rbenv rehash` but <kbd>Ctrl-C</kbd> it before it finishes.

**Comment by Drewshg312** [comment]
That was so weird - I've reinstalled the package and it didn't help… But after I've repeated the procedure after restart it never happened again…

**Comment by trejkaz** [comment]
I had this same error message on multiple servers on the same day, and in all cases deleting the file made it work again the next time.

If this is a kind of pseudo-lock file, perhaps what rbenv could do is open and actually lock the file. Then a second rbenv which comes along and sees the file could simply try to delete it before recreating it.

**Comment by glebm** [comment]
Failed for me just now on an Ubuntu 16.04 server:

Relevant Ansible output:

```
TASK [deploy-rails : Ensure ruby 2.4.0 is installed] *******************************************
fatal: [prod1]: FAILED! => {
  "cmd": "cd; bash -lc 'MAKEOPTS=\"-j $(getconf _NPROCESSORS_ONLN)\" CONFIGURE_OPTS=\"--disable-install-rdoc\" rbenv install 2.4.0'",
  "rc": 1,
  "stderr_lines": [
    "Downloading ruby-2.4.0.tar.bz2...",
    "-> https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.0.tar.bz2",
    "Installing ruby-2.4.0...",
    "Installed ruby-2.4.0 to /home/plforums/.rbenv/versions/2.4.0",
    "",
    "rbenv: cannot rehash: /home/plforums/.rbenv/shims/.rbenv-shim exists"
  ],
  "stdout_lines": []
}
```

No other commands were run in parallel. Both rbenv and ruby-build are from master as of 5 minutes ago.

The relevant parts of the ansible task are:

```yaml
- name: Ensure ruby {{ruby_version}} is installed
  shell: cd; bash -lc 'MAKEOPTS="{{ruby_makeopts}}" CONFIGURE_OPTS="--disable-install-rdoc" rbenv install {{ruby_version}}'
  async: 1650 # 30 minutes
  poll: 3
```

**Comment by MartinNowak** [comment]
I'm getting a similar error, not b/c the lock file gets clobbered, but b/c of [the `2>/dev/null` redirect](https://github.com/rbenv/rbenv/blob/4f8925abe7e4b373156bba9cc5310e8e0d04a28a/libexec/rbenv-rehash#L19), which according to bash clobbers `/dev/null`.

Just test bash.
```sh
set -o noclobber
echo >/dev/null
```

`bash --version`
```
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

That redirections needs to be done explicity, see [Safe I/O Redirection with noclobber (Unix Power Tools, 3rd Edition)](http://docstore.mik.ua/orelly/unix3/upt/ch43_06.htm#ch43-3-fm2xml).

**Comment by jakesyl** [comment]
Any update on this? I still have this issue.

**Comment by saulwiggin** [comment]
I ran rbenv doctor with the command 

curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash

and then was told this

Checking for `rbenv' in PATH: /usr/local/bin/rbenv
Checking for rbenv shims in PATH: not found
  The directory `/Users/user/.rbenv/shims' must be present in PATH for rbenv to work.
  Please run `rbenv init' and follow the instructions.

Checking `rbenv install' support: /usr/local/bin/rbenv-install (ruby-build 20200214)

and it worked after exporting this director to the path like this 

export PATH="$PATH:/Users/user/.rbenv/shims"

**Comment by gregblass** [comment]
@igorshtopor @mislav - One way this can happen is if you run out of disk space mid-install. Just happened to me. Stupidly left my AWS EBS to the default 8GB.

**Comment by dishui** [comment]
the rbenv doctor command posted above is 404'd. here is the updated command:
# with curl
`curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-doctor | bash`

# alternatively, with wget
`wget -q https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-doctor -O- | bash`
