### ISSUE TITLE
export GEM_HOME?

### ISSUE THREAD

**Issue by jsl303** [rbenv/rbenv#796]
My server requires configure htaccess for Passenger on Apache, and it asks GEM_HOME.
How should I set GEM_HOME in my bashrc after installing ruby through ruby build?

```
# rbenv which gem                                        
$HOME/.rbenv/versions/2.1.6/bin/gem
```

**Comment by mislav** [comment]
Sorry, I don't get what this is trying to do. How about just leaving GEM_HOME empty?

You can perhaps set it to result of `ruby -e "puts Gem.dir"`

**Comment by mislav** [comment]
@jsl303 Did you ever solve your original issue?

**Comment by mislav** [comment]
Closing due to lack of info.
