### ISSUE TITLE
Confusing behavior in `rbenv version` and `rbenv local`, manifesting in `rbenv install`

### ISSUE THREAD

**Issue by phs** [rbenv/rbenv#807]
Cross-post from https://github.com/sstephenson/ruby-build/issues/814

The issue initially emerged as some confusion about (a `ruby-build`-enabled) `rbenv install` failing to install a version that was reported as selected by `rbenv version`.

It turns out `ruby-build` only considers the version reported by `rbenv local` (not `rbenv version`), and `rbenv local` only looks for a configuration file in the current directory.

The net effect is a semantic dissonance: my expectation of `rbenv`/`ruby-build` is that I can configure `rbenv` in any of the advertised ways and, if the ruby is not available, `rbenv install` it.  Certainly in the common case where the version is given by `./.ruby-version` this is true.  However this surprisingly fails when at least some of other configuration methods are used.

In particular, I would expect a version given by `../.ruby-version` to be installable by `ruby-build`.  Either this means that the definition of `rbenv local` should extend to parent directories ([something already hinted at](https://github.com/sstephenson/rbenv/blob/074161f9c122db659f513e30298dffd74f5ca1b0/libexec/rbenv-local#L11-L12)), or `ruby-build` should consider configuration sources aside from `rbenv local`.

**Comment by phs** [comment]
Perhaps another way to describe the issue: if global versions are given by `~/.rbenv/version` (the file ultimately touched by `rbenv global`) and local versions are given by `./.ruby-version`, then what kind of version is given by `../.ruby-version`?

If it should not be considered local, is there a `rbenv verb` more specific than `rbenv version` that picks it up?  If so, should `ruby-build` be using that instead of `rbenv local`?

**Comment by mislav** [comment]
Thanks for digging into this. I'm leaning towards having `rbenv local` read `.ruby-version` files all the way down the ancestry instead of just local directory. This subtle feature change might break some scripts, but I don't think it would be a big deal since the next release is v1.0.

@sstephenson Do you think there was any value in `rbenv local` being constrained to only read `.ruby-version` configuration from the current directory?
