### ISSUE TITLE
Build failed OSX 10.9.5, Ruby zlib extension was not compiled

### ISSUE THREAD

**Issue by robochase6000** [rbenv/rbenv#825]
trying to get ruby 2.2.3 running on this computer. curiously, i was able to do this just fine on a different computer earlier today (probably running 10.8 or 10.9). also tried 2.2.2, same result.

I'm guessing there's just something trivial I need to do, but I'm a little dicey on this kind of stuff.

Here's the log when I run rbenv install 2.2.3

Downloading ruby-2.2.3.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/df795f2f99860745a416092a4004b016ccf77e8b82dec956b120f18bdc71edce
Installing ruby-2.2.3...

BUILD FAILED (OS X 10.9.5 using ruby-build 20151028)

Inspect or clean up the working tree at /var/folders/zp/snp4qhvj401d3jnp2ltql9c40000gn/T/ruby-build.20151118232539.75260
Results logged to /var/folders/zp/snp4qhvj401d3jnp2ltql9c40000gn/T/ruby-build.20151118232539.75260.log

Last 10 log lines:
installing capi-docs: /Users/chasedelanguillette/.rbenv/versions/2.2.3/share/doc/ruby
The Ruby zlib extension was not compiled.
ERROR: Ruby install aborted due to missing extensions
Configure options used:
--prefix=/Users/chasedelanguillette/.rbenv/versions/2.2.3
--with-openssl-dir=/usr/local/opt/openssl
--with-readline-dir=/usr/local/opt/readline
CFLAGS= -O3 -Wno-error=shorten-64-to-32 
LDFLAGS=-L/Users/chasedelanguillette/.rbenv/versions/2.2.3/lib 
CPPFLAGS=-I/Users/chasedelanguillette/.rbenv/versions/2.2.3/include

**Comment by mislav** [comment]
See https://github.com/rbenv/ruby-build/issues/832
