### ISSUE TITLE
rbenv doesn't find ruby-build plugin if installed in /opt

### ISSUE THREAD

**Issue by mbunkus** [rbenv/rbenv#834]
I've installed rbenv to `/opt/rbenv` in the past without problems. The idea is to have a single installation usable by many different users on the system (at least root, the web server user, and my unprivileged one).

Today, on a new CentOS 7, I've tried the usual but rbenv doesn't find the ruby-build plugin:

    # git clone https://github.com/rbenv/rbenv.git /opt/rbenv
    Cloning into '/opt/rbenv'...
    …
    # git clone https://github.com/rbenv/ruby-build.git /opt/rbenv/plugins/ruby-build
    Cloning into '/opt/rbenv/plugins/ruby-build'...
    …

Alright, set up `.bash_profile`:

    # tail -3 .bash_profile
    PATH=/opt/rbenv/bin:$PATH:$HOME/bin
    export PATH
    eval "$(rbenv init -)"
    # type rbenv
    rbenv is a function
    …

So far, so good. But:

    # rbenv install -l
    rbenv: no such command `install'

It works immediately if I move `/opt/rbenv` to `/root/.rbenv` and change `PATH` in `.bash_profile` accordingly.

Please fix this or provide some other way of installing rbenv globally. Thanks.

**Comment by mbunkus** [comment]
Meh, forgot to set `RBENV_ROOT`… Sorry for the noise.

What would be nice is if `rbenv`, e.g. during `init`, checked whether or not the `rbenv` binary could be found in `$RBENV_ROOT/bin` and output an error otherwise. Would make spotting such mistakes easier.

**Comment by mislav** [comment]
Yeah, sorry for the trouble. It can be confusing that rbenv installation directory can often be the same as RBENV_ROOT, but they can also be separate.
