### ISSUE TITLE
Bump version and release before Ruby 2.3

### ISSUE THREAD

**Issue by nurse** [rbenv/rbenv#837]
Hello, I'm a release manager of Ruby 2.3, which is scheduled to release on 25 Dec.
But it hits #836 , I want to announce to update rbenv before installing Ruby 2.3 by the release announce.

To ease users checking their rbenv version, could you bump the version to 0.4.1 or something and release it?

Thank you,

**Comment by hsbt** [comment]
@mislav Can you provide me to rbenv commit bits? I hope to handle this and rbenv's issues.

**Comment by mislav** [comment]
@hsbt: I'm going to do a rbenv 1.0 soon so I don't think 0.4.1 is needed right now. Also, I think this regression affected only those who were already on master, so for a fix they would need to just `git pull` again. Please correct me if I'm wrong.

**Comment by nurse** [comment]
If you release 1.0 before 25 Dec, I'm ok.
But "affected only those who were already on master" is more serious because we received 3 (or more?) reports caused by it though it affects only Ruby 2.3.0-preview1/preview2.

**Comment by hsbt** [comment]
> I'm going to do a rbenv 1.0 soon so I don't think 0.4.1 is needed right now.

It's OK before release 2.3.0 stable release same as @nurse 's comment.

**Comment by mislav** [comment]
> If you release 1.0 before 25 Dec, I'm ok.

Yes I'll try to release this week.

> we received 3 (or more?) reports caused by it though it affects only Ruby 2.3.0-preview1/preview2.

How does this bug specifically affect Ruby 2.3? I don't understand.

**Comment by nurse** [comment]
Ruby uses `ruby` or `miniruby` on building `ruby` to generate environment dependent code/configuration.
When build process find `ruby` in PATH, it uses `ruby`.
Until ./ruby is born, it works fine. But after that, it hits the issue.

**Comment by mislav** [comment]
> Until ./ruby is born, it works fine. But after that, it hits the issue.

Thanks for explaining. I'm releasing rbenv 1.0 very soon.

**Comment by mislav** [comment]
Tagged rbenv 1.0 just now!

**Comment by nurse** [comment]
Thanks!
We also release Ruby 2.3 today!

**Comment by mislav** [comment]
> We also release Ruby 2.3 today!

Congrats! Send us a PR for ruby-build :wink:
