### ISSUE TITLE
Using rbenv with Fish

### ISSUE THREAD

**Issue by askl56** [rbenv/rbenv#840]
I have my rbenv portion of my config.fish like so:

```
# Rbenv
set -gx RBENV_ROOT /usr/local/var/rbenv
. (rbenv init -|psub)
```

but when loading terminal i get this error. Can anyone suggest what the problem might be?

```
'case' builtin not inside of switch block
/var/folders/wv/0zn1c97n3kz6gbwlndg1_vmm0000gn/T//.psub.LMCiUhspKA (line 10):   case "$command" in
                                                                                ^
from sourcing file /var/folders/wv/0zn1c97n3kz6gbwlndg1_vmm0000gn/T//.psub.LMCiUhspKA
	called on line 152 of file /usr/local/Cellar/fish/HEAD/share/fish/config.fish

in function '.'
	called on line 12 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup
```

It is directly referencing ``` . (rbenv init -|psub)``` which is line 12..

**Comment by mislav** [comment]
That's really weird. It doesn't seem that it's detecting your shell properly, and tries to load bash script into fish which obviously won't work. Is fish your login shell (default shell when you start a new terminal)?

What is your `ps --version` and `man ps | tail -1`?

You can explicitly state the shell type to `rbenv init` so it doesn't get confused:

```fish
. (rbenv init - fish|psub)
```

Note that in your `fish.config`, you should only do this when the shell is interactive, so rbenv initialization isn't performed unnecessarily for non-interactive shells:

```fish
status --is-interactive; and . (rbenv init - fish|psub)
```

**Comment by askl56** [comment]
```
⋊> ~ ps --v                                                             14:43:14
ps: illegal option -- -
usage: ps [-AaCcEefhjlMmrSTvwXx] [-O fmt | -o fmt] [-G gid[,gid...]]
          [-g grp[,grp...]] [-u [uid,uid...]]
          [-p pid[,pid...]] [-t tty[,tty...]] [-U user[,user...]]
       ps [-L]
```


```
 ⋊> ~ man ps | tail -1                                                   14:42:39
BSD                             March 20, 2005                             BSD 
```

OSX is latest el capitan.

``` rbenv 0.4.0 ```

 With your command i get the same response

``` 
'case' builtin not inside of switch block
/var/folders/wv/0zn1c97n3kz6gbwlndg1_vmm0000gn/T//.psub.GDGRk2HLxd (line 10):   case "$command" in
                                                                                ^
from sourcing file /var/folders/wv/0zn1c97n3kz6gbwlndg1_vmm0000gn/T//.psub.GDGRk2HLxd
	called on line 152 of file /usr/local/Cellar/fish/HEAD/share/fish/config.fish

in function '.'
	called on line 12 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup

Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish 
```

What's really freaking me out is that this is a brand new macbook air so it's not like there's legacy path problems.

**Comment by mislav** [comment]
You should do `brew upgrade rbenv --HEAD` to get the latest version of rbenv that supports fish.

**Comment by askl56** [comment]
Thanks man :+1:

**Comment by mislav** [comment]
I'm working on wrapping up the next release that will include fish support. Closing since this is fixed in master branch, and you worked around your issue by upgrading to latest.
