### ISSUE TITLE
Rbenv can't build Ruby 2.3.0 on El Capitan

### ISSUE THREAD

**Issue by CamJN** [rbenv/rbenv#844]
It tries for some reason to put stuff in `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/`. Probably because it doesn't inspect the `env` before building or something.

```
installing common headers:    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/Users/camdennarzt/.rbenv/versions/2.3.0/include/ruby-2.3.0
/private/var/folders/0x/gvllnpys5p9cngslb8r5pnq80000gn/T/ruby-build.20151226114651.5865/ruby-2.3.0/lib/fileutils.rb:250:in `mkdir': Permission denied @ dir_s_mkdir - /Applications/Xcode.app/Contents/     Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/Users (Errno::EACCES)
```

**Comment by CamJN** [comment]
nevermind, looks like it's a ruby bug: https://github.com/ruby/ruby/commit/e98f7ea423b08222b6eceda945613040c7b08a09#diff-7f2d280dffee5d06de608cd80c2df55f

**Comment by mislav** [comment]
Thanks for letting us know!
