### ISSUE TITLE
Remove all handling/support of .rbenv-version files

### ISSUE THREAD

**Issue by jasonkarns** [rbenv/rbenv#846]
Rbenv migrated from rbenv-version to ruby-version files a long time ago. (late 2012, I believe)

There is plenty of code that handles rbenv-version as a fallback that could be cleaned up. Now that 1.0 has landed, I propose we remove all the handling and references to rbenv-version files.

I'm happy to submit a PR for this if there is agreement on this direction.

**Comment by mislav** [comment]
Sure, I guess a 1.1 release could drop deprecated features such as `ruby-local-exec` (already removed in master) and support for `.rbenv-version` files.
