### ISSUE TITLE
curl: (56) GnuTLS recv error (-54): Error in the pull function.

### ISSUE THREAD

**Issue by unixc3t** [rbenv/rbenv#847]
ubuntu 15.10 
my git is  2.6.4,curl 7.43.0 

execute rebnv install  2.3.0

**Comment by unixc3t** [comment]
i download the ruby-2.3.0.tar.gz ,put it in /tmp/ruby-build.....  solve this

**Comment by lulukdog** [comment]
have u ever solve the problem？I met the problem now.can u give me some advise

**Comment by joejean** [comment]
I'm currently facing the same issue :( as well.

**Comment by Xara** [comment]
Same here ... why is it closed without a solution???

**Comment by mislav** [comment]
Sorry there is no much information in here. This isn't really a problem with rbenv. The ruby-build plugin (the component of rbenv that downloads & installs Ruby) needs either `curl` or `wget` to download files. These programs must be working on the system. If there is an error, such as one with `curl` here, it is likely a network error, or an error with configuration of SSL certificates on the system. In either case, there is not much we can do about that from either rbenv or ruby-build.
