### ISSUE TITLE
rbenv rehash with Ruby 2.3.0 

### ISSUE THREAD

**Issue by imageaid** [rbenv/rbenv#851]
First and foremost, thanks for all the hard work and rbenv! Live-freaking-saver! 

Ran into an issue with `rbenv rehash` on a newly installed Ruby 2.3.0. 

I am running rbenv 1.0.0 - installed via Homebrew - on Mac OS X 10.11.2, ruby-build (current), psych 2.0.17 and bundler 1.11.2. 

When I rehash, I get the following error in my terminal (running ZSH if that matters): 

    /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/ostruct.rb:176:in `respond_to_missing?': undefined method `key?' for nil:NilClass (NoMethodError)
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:381:in `respond_to?'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:381:in `init_with'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:374:in `revive'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:208:in `visit_Psych_Nodes_Mapping'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:336:in `each'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:336:in `each_slice'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:336:in `revive_hash'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:162:in `visit_Psych_Nodes_Mapping'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:311:in `visit_Psych_Nodes_Document'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/psych/nodes/node.rb:38:in `to_ruby'
	from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/2.3.0/psych.rb:253:in `load'
	from /usr/local/var/rbenv/plugins/bundler/etc/rbenv.d/bundler/rehash.rb:259:in `block in build_ruby_profiles'
	from /usr/local/var/rbenv/plugins/bundler/etc/rbenv.d/bundler/rehash.rb:258:in `open'
	from /usr/local/var/rbenv/plugins/bundler/etc/rbenv.d/bundler/rehash.rb:258:in `open'
	from /usr/local/var/rbenv/plugins/bundler/etc/rbenv.d/bundler/rehash.rb:258:in `build_ruby_profiles'
	from /usr/local/var/rbenv/plugins/bundler/etc/rbenv.d/bundler/rehash.rb:447:in `<main>'

If there is additional information I can provide, please let me know and thanks, again (and happy new year)!

**Comment by mislav** [comment]
See https://github.com/rbenv/rbenv/issues/845#issuecomment-167395024

**Comment by imageaid** [comment]
Thank you! That plugin was hidden (not listed) in the .rbenv folder and I thought I removed it long ago. Appreciate the help and apologies for missing the previous thread in #845
