### ISSUE TITLE
Default installation path and 'rbenv rehash' for Bundler

### ISSUE THREAD

**Issue by alexrois** [rbenv/rbenv#853]
After successful installing bundler gem for default ruby 2.2.3 I realized that bundler is installed for system ruby 1.9.3.

Later I installed ruby 2.2.3 with using ruby-build plugin (using *rbenv install* command) and switched to 2.2.3 with *rbenv global* command. But after installing bundler and doing *rbenv rehash* I see next results:

for default ruby 2.2.3 I don't see bundler in gem list (you can see different paths for bundler and rake):
![223](https://cloud.githubusercontent.com/assets/16092409/12079787/aab69a4e-b24e-11e5-9b74-950bc2dfc12e.jpg)
I also don't see anything for bundler on .rbenv/shims directory.

for system ruby 1.9.3 I see bundler in gem list (but I don't use system ruby since installing 2.2.3):
![193](https://cloud.githubusercontent.com/assets/16092409/12079791/db889096-b24e-11e5-816a-9705cd2cf897.jpg)

I also tried to open new terminal and reload my machine (and did *rbenv rehash* one more time) - it doesn't help.

**Comment by mislav** [comment]
Sorry you're having trouble. Have you verified that "bundler" is present among `gem list` when you switch to Ruby 2.2.3? After running `rbenv rehash`, the `bundle` command should be present in `~/.rbenv/shims/`.

**Comment by alexrois** [comment]
After switching to Ruby 2.2.3 and running `gem list` bundler is not present on gem list:

![gems223](https://cloud.githubusercontent.com/assets/16092409/12091617/da3d81bc-b300-11e5-98bd-a89776b56277.jpg)

After running `rbenv rehash` path to bundler and content of `~/.rbenv/shims/ are the same as before.

Running `rbenv rehash`:

![rehash](https://cloud.githubusercontent.com/assets/16092409/12091735/776d5de0-b301-11e5-9f34-f7c90a490359.jpg)

Content of `shims` after running `rbenv rehash` and refreshing file tree:

![shims](https://cloud.githubusercontent.com/assets/16092409/12091746/91ce5a90-b301-11e5-834d-7d52a0b1d44a.jpg)

I also tried to do the same under system Ruby, but nothing changes with bundler's path and rbenv's shims:

![system](https://cloud.githubusercontent.com/assets/16092409/12091766/c63d4502-b301-11e5-91cb-01eb4fa5266d.jpg)

Maybe it will help to solve this issue:
1. All actions are doing under Ubuntu 14.04
2. I installed Bundler gem with using sudo running `sudo gem install bundler` instead of simple `gem install bundler`.

**Comment by mislav** [comment]
> After switching to Ruby 2.2.3 and running `gem list` bundler is not present on gem list:

Well, there's the problem. We have to install bundler first in order to be able to use it.

> 2\. I installed Bundler gem with using sudo running `sudo gem install bundler` instead of simple `gem install bundler`.

Using `sudo` is only necessary when using "system" Ruby version in `/usr/local/bin`. But, generally with rbenv you don't want to be using system version. Instead, you want to be using one of the rbenv-managed versions, which don't require sudo to install anything.

Do a `gem install bundler` while Ruby 2.2.3 is active and you should be good.
