### ISSUE TITLE
Ruby-Build Error with rbenv installation in ubuntu 14.04.

### ISSUE THREAD

**Issue by vigneshblue** [rbenv/rbenv#855]
When I tried the code 
$rbenv install 2.2.3

I Got the following error

$ rbenv install 2.2.3
Downloading ruby-2.2.3.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.3.tar.bz2
error: failed to download ruby-2.2.3.tar.bz2

BUILD FAILED (Ubuntu 14.04 using ruby-build 20160111)

Inspect or clean up the working tree at /tmp/ruby-build.20160112104557.13429
Results logged to /tmp/ruby-build.20160112104557.13429.log

Last 10 log lines:
/tmp/ruby-build.20160112104557.13429 ~
curl: (18) transfer closed with 2798902 bytes remaining to read

Please help me.

**Comment by vigneshblue** [comment]
I reinstalled my rbenv by apt-get install rbenv and the problem is solved.

**Comment by mikeeus** [comment]
@vigneshblue I believe you get that error because ruby-build is already installed. Try `ruby-build --version` and it should give you a response like `ruby-build 20160112` the timestamp is for the day that you installed it.

**Comment by vigneshblue** [comment]
thank you @mikeeus.
