### ISSUE TITLE
2.3.0dev reporting 2.4.0dev as its version

### ISSUE THREAD

**Issue by fhwang** [rbenv/rbenv#859]
We've been seeing issues where Bundler seems to be unhappy with Ruby 2.3.0 in Semaphore.

    Your Ruby version is 2.4.0, but your Gemfile specified 2.3.0

Since Semaphore uses rbenv, I decided to check this out locally:

```ruby
[rbenv (master)]$ ./bin/rbenv install 2.3.0-dev
Cloning https://github.com/ruby/ruby.git...
Installing ruby-2.3.0-dev...
Installed ruby-2.3.0-dev to /Users/fhwang/.rbenv/versions/2.3.0-dev

[rbenv (master)]$ /Users/fhwang/.rbenv/versions/2.3.0-dev/bin/ruby -v
ruby 2.4.0dev (2016-01-15 trunk 53547) [x86_64-darwin15]
```

Caveat: I'm not an rbenv user myself, so maybe I'm making a dumb mistake.

But that version number isn't right. Right?

**Comment by jeremy** [comment]
The ruby-build 2.3.0-dev definition switched from `trunk` to `ruby_2_3` @ https://github.com/rbenv/ruby-build/commit/5a0f488f0de1bc627a5cd812db88a6ba74df1ee6. You probably have older ruby-build that's still using trunk Ruby 😁

**Comment by mislav** [comment]
@fhwang If you update ruby-build, you will be able to install `2.3.0` stable release of Ruby and you shouldn't need the `-dev` variant anymore.
