### ISSUE TITLE
jshint file in ~/.rbenv/shims/

### ISSUE THREAD

**Issue by nikolas** [rbenv/rbenv#860]
I don't know if this is an rbenv problem, but something in the shims directory is messing up my path, and my ability to use jshint from npm:

```
$ cat ~/.rbenv/shims/jshint 
#!/usr/bin/env bash
set -e
[ -n "$RBENV_DEBUG" ] && set -x

program="${0##*/}"
if [ "$program" = "ruby" ]; then
  for arg; do
    case "$arg" in
    -e* | -- ) break ;;
    */* )
      if [ -f "$arg" ]; then
        export RBENV_DIR="${arg%/*}"
        break
      fi
      ;;
    esac
  done
fi

export RBENV_ROOT="/home/nik/.rbenv"
exec "/home/nik/.rbenv/libexec/rbenv" exec "$program" "$@"
```

How did this file get there? And why does it keep getting created when I open a new shell?

**Comment by mislav** [comment]
One of the Ruby versions you have installed through rbenv has a gem that has installed a `jshint` executable.

To find out where it is, you can use `rbenv whence jshint`. For instance, this command should reveal which gem has installed it:

```sh
$ tail -2 "$(RBENV_VERSION=`rbenv whence jshint | head -1` rbenv prefix)/bin/jshint"
#=> gem 'CULPRIT', version
#=> load Gem.bin_path('CULPRIT', 'jshint', version)
```

Uninstall that gem with:

```sh
for v in `rbenv whence jshint`; do RBENV_VERSION=$v gem uninstall -x CULPRIT; done
rbenv rehash
```

And you're done!

**Comment by nikolas** [comment]
thank you
