### ISSUE TITLE
Upgrade to version 1.0 unclear

### ISSUE THREAD

**Issue by mliebelt** [rbenv/rbenv#861]
I have read about the new version of rbenv, and have done the following (running in Ubuntu 14.04.3 LTS):
1. `curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash` (as explained in the README)
2. Git repository of rbenv was updated without error.
3. Restarted the machine (just to be sure).

However, when I now call `rbenv --version` in the shell, I get: `rbenv 0.4.0-250-gc388331`.

Do I have forget something? rbenv is integration in the system by hooking it up in `.bash_profile`:

```
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
```

The output of `$PATH` is: `/home/vagrant/.rbenv/shims:/home/vagrant/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`

**Comment by mislav** [comment]
Everything seems alright, as your rbenv is on the latest version. However, I don't know why it still displays `rbenv 0.4.0-...`, but I'm guessing it's due to not fetching the latest git tag properly.

Can you `cd ~/.rbenv` and check the value of `git config remote.origin.tagOpt`, if any?

Can you also check `git tag` while in that repo? Thanks

**Comment by mliebelt** [comment]
Here is the output for the things you asked:

* `git config remote.origin.tagOpt` no result
* `git tag` gives me the following list

    v0.1.0
    v0.1.1
    v0.1.2
    v0.2.0
    v0.2.1
    v0.3.0
    v0.4.0

Shall I do fetch the latest tag by doing `git fetch origin tag v1.0.0`?

**Comment by mislav** [comment]
You could, but does `git pull origin master` not fetch all the tags? I would expect it to. If not, `git fetch origin --tags` should do it.

**Comment by mliebelt** [comment]
When doing `git pull origin master`, I get

    From https://github.com/sstephenson/rbenv
     * branch            master     -> FETCH_HEAD
    Already up-to-date.

When doing `git fetch origin --tags`, I get

    * [new branch]      detect-shell-from-script -> origin/detect-shell-from-script
    * [new tag]         v1.0.0     -> v1.0.0

Now the list of the tags is (`git tag`):

    v0.1.0
    v0.1.1
    v0.1.2
    v0.2.0
    v0.2.1
    v0.3.0
    v0.4.0
    v1.0.0

The last one is new.

`rbenv --version` gives now:

    rbenv 1.0.0-14-gc388331

**Comment by mislav** [comment]
Thanks for figuring that out. Would you submit a pull request to rbenv-installer that changes `git pull origin master` to `git pull --tags origin master`?

**Comment by mliebelt** [comment]
I try to do that, but I will need some time (1-2 days), if that is ok.

**Comment by mislav** [comment]
Sure, take your time. If it makes any difference, you don't need to even clone the rbenv-installer repository locally to make this contribution. You can simply [go to the file](https://github.com/rbenv/rbenv-installer/blob/master/bin/rbenv-installer#L51) through web interface, click the edit icon for that file, and add the `--tags` option to `git pull`. Then follow the on-screen instructions to create a pull request with this change.

**Comment by mislav** [comment]
Thank you for your contribution!
