### ISSUE TITLE
rbenv 2.2.1 cannot install, complains on bundler (>= 0)

### ISSUE THREAD

**Issue by axilaris** [rbenv/rbenv#862]
Hi,

I am trying to upgrade rbenv to 2.2.1 but it complains on  bundler (>= 0). Can someone help solve this ? Thanks.

axil-Pro:~ megasap$ rbenv install 2.2.1
rbenv: /Users/axil/.rbenv/versions/2.2.1 already exists
continue with installation? (y/N) y
Downloading ruby-2.2.1.tar.gz...
-> http://dqw8nmjcqpjn7.cloudfront.net/5a4de38068eca8919cb087d338c0c2e3d72c9382c804fb27ab746e6c7819ab28
Installing ruby-2.2.1...
Installed ruby-2.2.1 to /Users/axil/.rbenv/versions/2.2.1

ERROR:  Could not find a valid gem 'bundler\n' (>= 0) in any repository
ERROR:  Possible alternatives: bundle_rc, bundler08, bundler-fu, bundler, bundler-pgs
rbenv: error installing gem `bundler\n'

I tried also gem install bundler but also the same error (verbose printout here):
https://gist.github.com/survivaltravel/b3190b30510b92f7a3cd

I reported here also:
http://stackoverflow.com/questions/35008904/rbenv-2-2-1-cannot-install-complains-on-bundler-0

**Comment by mislav** [comment]
Two things come to mind:

* The error message mentions `'bundler\n'`. Observe the newline character `\n`: that shouldn't be there. How did it get there?
* `rbenv install` doesn't auto install bundler by itself. Instead, a plugin like rbenv-default-gems probably does it. Did you set up that plugin? Can you check that plugin's configuration?

> I tried also gem install bundler but also the same error

From you attached log (thanks for that) it seems to me that `gem install bundler` worked. You say that it failed. Which one is it?

**Comment by axilaris** [comment]
thanks @mislav 

in here: https://gist.github.com/survivaltravel/b3190b30510b92f7a3cd

1. "gem install bundler "- that command worked and it did install bundler
2. however, after doing that (1.), i installed again "rbenv install 2.2.1" and that failed with the same reason

I'ved no idea what does 'bundler\n' mean.

I am using OS X El Capitan - 10.11.1

Anyway for me to troubleshoot this ? Thanks.

**Comment by axilaris** [comment]
3. in .rbenv/default-gems contains this one line "bundler\n" - let me try removing \n

that did the trick, thank you!

**Comment by mislav** [comment]
Glad you figured it out!

Any idea how `\n` ended up in there in the first place?

**Comment by mkirlin** [comment]
Just ran into this myself. This helped me figure out what happened, but was there ever any explanation for what was causing that stray newline character?
