### ISSUE TITLE
CDPATH can result in incorrect resolution of RBENV_DIR

### ISSUE THREAD

**Issue by tpope** [rbenv/rbenv#866]
[This `cd`](https://github.com/rbenv/rbenv/blob/d6ab394efde6871d0af8945d703cde1ef72d317a/libexec/rbenv#L63) can end up in the wrong place (plus print that wrong place to stdout) if the directory in question is relative and in `CDPATH` (which is unexported but not unset at the top of the file). Obvious workaround is to qualify it, perhaps with one of the following (or something more elegant);
- `RBENV_DIR=$(abs_dirname "$RBENV_DIR/.")`
- `[[ $RBENV_DIR == /* ]] || RBENV_DIR=./$RBENV_DIR`

I have further thoughts on `export -n CDPATH` which do not belong in this issue, but suffice to say I will argue that `unset CDPATH` is another step in the wrong and direction so am advocating against it as a solution here.

**Comment by mislav** [comment]
Thanks for the heads-up. Here is some background that argued against CDPATH: #316

What would be your proposed solution? To leave CDPATH alone and just be careful not to `cd` to any relative path not prefixed with `./`?

**Comment by tpope** [comment]
I'm afraid I don't have anything more elegant than that.

My problem with the advice "just set `CDPATH` in `.bashrc` and don't export it" is twofold:

1. More than just the shell respects `CDPATH` (e.g. Vim)
2. Sometimes it is useful to set a value for a non-global context (e.g. a tmux session)

I was considering proposing a compromise along the lines of "leave it exported for the exec subcommand only", since I have not encountered a case where the other built-ins spawn a process where it would matter.

**Comment by blueyed** [comment]
@mislav 
I cannot see from #316 why it should not be unset (instead of only not being exported).
See also https://github.com/rbenv/rbenv/commit/e3f72ebae20768079ca4b4425a364900f3f16fc6, where you've mentioned this fact yourself.
