### ISSUE TITLE
Should hooks be able to terminate their parent command?

### ISSUE THREAD

**Issue by jasonkarns** [rbenv/rbenv#867]
I've been spiking a refactor that moves the boilerplate of executing hooks into the rbenv-hooks command itself. However, in doing so I discovered that since hooks are sourced within the parent command, a hook that `exit`s can terminate the parent command. This seems undesirable. I would have expected the parent command to run to completion regardless of whether a hook script exits.

If the sourcing of the hooks is moved into the hooks command, then a hook that exits will still prevent subsequent hooks from executing (as it does today), but the parent command will still run to completion. I think this is preferred behavior. (Honestly, I don't think a hook script should really be able to prevent subsequent hooks from executing either, but that may be too far.)

**Comment by mislav** [comment]
It's not ideal that a hook command can terminate the parent, but I don't see it as a huge problem either. It would be much more difficult to implement a system that was impervious to hook errors.

I see this as high effort/low payoff.
