### ISSUE TITLE
`eval (rbenv init -)` is broken on fish

### ISSUE THREAD

**Issue by davidcelis** [rbenv/rbenv#869]
I have the following in my `config.fish` file, running with the latest versions of `fish` and `rbenv` from homebrew:

```fish
if test -d ~/.rbenv
  eval (rbenv init -)
end
```

When I start a shell, I get the following error:

```
rbenv: no such command `sh-'
```

Based on what `rbenv init -` returns for fish shell…

```fish
setenv PATH '/Users/davidcelis/.rbenv/shims' $PATH
setenv RBENV_SHELL fish
. '/usr/local/Cellar/rbenv/1.0.0/libexec/../completions/rbenv.fish'
command rbenv rehash 2>/dev/null
function rbenv
  set command $argv[1]
  set -e argv[1]

  switch "$command"
  case rehash shell
    . (rbenv "sh-$command" $argv|psub)
  case '*'
    command rbenv "$command" $argv
  end
end
```

… I'm wondering if something is wrong in setting `$command` for fish.

**Comment by davidcelis** [comment]
Workaround:

```fish
source (rbenv init - | psub)
```

**Comment by mislav** [comment]
This is know and documented. If you run `rbenv init fish`, you will get instructions how to add `rbenv init` to your shell rc file:

```sh
$ rbenv init fish
# Load rbenv automatically by appending
# the following to ~/.config/fish/config.fish:

status --is-interactive; and . (rbenv init -|psub)
```

**Comment by davidcelis** [comment]
Hmmm, I pored through the README and Wiki but I didn't see any instructions like that for `fish`… Not findable enough, maybe? The most I saw consistently were bash and zsh instructions…

**Comment by mislav** [comment]
It's true that we should be telling people to run `rbenv init` to get instructions for their current shell, instead of giving people instructions for bash only. Maybe change step (3) of installation to suggest that you should run `~/.rbenv/bin/rbenv init` and follow the instructions given?

**Comment by davidcelis** [comment]
Yeah, that'd do it! :+1:

**Comment by ElijahLynn** [comment]
Current shell instructions were added to the README.md in this commit https://github.com/rbenv/rbenv/commit/35ca51fe881822cfa6d5e4ed5d54bedec2c66c3e
