### ISSUE TITLE
Weird high CPU usage

### ISSUE THREAD

**Issue by dipth** [rbenv/rbenv#872]
I'm seeing some weird behaviour on my machine where rbenv appears to be using a lot of CPU out of nowhere.

![screen shot 2016-02-16 at 16 26 46](https://cloud.githubusercontent.com/assets/171490/13080702/20b59d6a-d4ca-11e5-9ca4-14a46a410ea8.png)
 
Running `ps -ef | grep bash` gives me a bit more details about those bash processes:

```
  501  2710 86703   0  4:22PM ??         0:00.01 bash /usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-which ruby
  501  2789 86698   0  4:22PM ??         0:00.01 bash /usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-which ruby
  501  2892  2710   0  4:22PM ??         0:00.24 bash /usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-hooks which
  501  2967  2789   0  4:22PM ??         0:00.17 bash /usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-hooks which
  501 86698  1528   0  4:22PM ??         0:03.41 bash /usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-exec ruby -wc
  501 86703  1528   0  4:22PM ??         0:03.36 bash /usr/local/Cellar/rbenv/0.4.0/libexec/rbenv-exec ruby -wc
```

Versions:
- homebrew: `0.9.5 (git revision e1301; last commit 2016-02-16)`
- rbenv: `1.0.0`
- ruby: `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]`
- os x: `10.11.3 (15D21)`
- atom: `1.5.3`

I seem to be able to replicate the problem by modifying and saving a ruby-file in Atom editor by which you could argue that the problem lies within Atom and not rbenv, but it seems weird to me that rbenv would use this much CPU regardless of how it got triggered and from what process.

**Comment by DavidLJ** [comment]
Have you just switched to Windows 10?

I've been noticing some oddly high CPU use-rates since I switched.  Also,
two apps have acquired an unpleasant new behaviour: running at their usual
fast speed when they have the machine to themselves, but occupying all the
machine's RAM, and slowing themselves and everything else down to a crawl,
if they are invoked later.

Jury's still out, but I suspect Windows 10, which is why I ask.

-dlj.

**Comment by dipth** [comment]
No, I'm on Mac OS X: El Capitan - 10.11.3 (15D21)

**Comment by DavidLJ** [comment]
OK, noted.  Thanks.
-dlj.

**Comment by dipth** [comment]
I ended up completely removing rbenv, ruby-build and all the installed versions of ruby, then re-installing, which appears to have solved the issue.

**Comment by mislav** [comment]
Glad you solved your issue, and sorry for the late reply. This smells like it could have been the work of a rogue plugin. Rbenv itself is implemented in very lightweight and short-lived bash, and can't possibly consume significant amounts of CPU unless some plugin causes recursion.
