### ISSUE TITLE
Error message with Zsh and rbenv init

### ISSUE THREAD

**Issue by danrempel** [rbenv/rbenv#875]
Similar to [Issue #487](https://github.com/rbenv/rbenv/issues/487), only I found in ~/.zsh/configs/post/path.zsh.

```
# ensure dotfiles bin directory is loaded first
PATH="$HOME/.bin:/usr/local/sbin:$PATH"

# load rbenv if available
if command -v rbenv >/dev/null; then
  eval "$(rbenv init - --no-rehash)"
fi

# mkdir .git/safe in the root of repositories you trust
PATH=".git/safe/../../bin:$PATH"

export -U PATH
```

This was giving me the error

     /usr/lib/rbenv/libexec/../completions/rbenv.bash:16: command not found: complete

I changed the line `eval "$(rbenv init - --no-rehash)"` to reflect `eval "$(rbenv init - zsh --no-rehash)" `and this resolved my issue.

**Comment by mislav** [comment]
Which version of rbenv do you have installed?

**Comment by danrempel** [comment]
rbenv 1.0.0-19-g29b4da7

**Comment by mislav** [comment]
Thanks for the info. Which OS?

Your workaround is perfectly valid and you should keep it, but I agree it would be ideal if your shell was detected automatically.

**Comment by danrempel** [comment]
You're welcome. My OS is Ubuntu 15.10.
Unable to replicate the issue on my Macbook so perhaps it's specific to my environment.
