### ISSUE TITLE
'gem env home' does not return '~/.rbenv/versions/<ruby-version>/lib/ruby/gems/...'

### ISSUE THREAD

**Issue by nielssorensen** [rbenv/rbenv#879]
I am trying to install gems locally and without sudo but receive the error, 'You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.'  This is the system ruby gems directory in which I do not want to install gems.  Using 'gem install blah', gems should be installed to `~/.rbenv/versions/<ruby-version>/lib/ruby/gems/...`

I have pasted more info to a gist, found here.  https://gist.github.com/nielssorensen/8ee52a70750d69580351

**Comment by mislav** [comment]
Hello, it seems that even though you've installed several Ruby versions managed by rbenv, you're still using the global system version that requires use of `sudo` to install gems. You can check that with `rbenv version`.

Ideally, you should switch to one of rbenv-managed Ruby versions to set as your new "global" version to install all gems to without `sudo`. You can do this with `rbenv global 2.3.0` (choose whichever version you want to be your default). Then, `gem install ...` should just work.

**Comment by mufernando** [comment]
I've had the same problem but setting the rbenv global to the version of ruby I am using did not work.

Could anybody help me out?

**Comment by mislav** [comment]
@mufernando [Check out the rbenv-doctor script](https://github.com/rbenv/rbenv-installer#rbenv-doctor) to help you debug what you did wrong while setting up rbenv.

**Comment by canrosss** [comment]
You can do the following:
------------------------------
First reinstall for example am using 2.4.0 so i did this

rbenv unstall 2.4.0;rbenv install 2.4.0

Next in my .zshrc i have this lines in for path make sure to check what are you lines the goal its have whatever you have in you PATH plus the path to .rbenv/bin  and the plugin path

export PATH="$HOME/.rbenv/bin:$PATH"     
eval "$(rbenv init -)"                   
export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"

Make sure to have this at the end of ur file .zshrc or .bashrc

next try again

gem env home   now should point to ur local ruby installation in your home

gem install bundle

**Comment by Topher33** [comment]
@canrosss 100%!!!! thanks

**Comment by tranhuyhoangbka** [comment]
Thank you so much !

**Comment by ceclinux** [comment]
@canrosss you save my day. Typo: unstall => uninstall

**Comment by Ronaq13** [comment]
@canrosss Thanks a lot. That works for me as well.

**Comment by jrcharney** [comment]
Did you remember to `rbenv rehash`?

```
# Other major instructuions
$ rbenv install -v 2.5.0
# Compiler stuff and about a while later.
# BTW, @rbenv, don't forget to tell everybody about the -v option for install. Looking at a command doing nothing is no fun.
$ rbenv global 2.5.0
$ rbenv rehash
# Things should work now. Verify that they are
$ rbenv which gem
# You should see something like /home/Jason/.rbenv/versions/2.5.0/bin/gem
$ gem env home
# You should see something like /home/Jason/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0
$ gem install bundler
# And then rehash again for good practice.
$ rbenv rehash
```

I honestly don't think you need to need to install gemset like @canrosss said, however, running

```
for settings in ~/.bashrc ~/.zshrc; do
  if [[ -f "$settings"]]; then
   echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> $settings
   echo 'eval "$(rbenv init -)" >> $settings
   echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> $settings
 fi
done
```
Does make sense and should be done after you `get` rbenv and ruby-build.

**Comment by smithopher** [comment]
@canrosss perfect! thank you!

**Comment by IlkhamGaysin** [comment]
I had the same problem on Mac OS, fixed it by setting `rbenv global <ruby_version>`

**Comment by garry-kevin** [comment]
rebenv rehash solves the problem

**Comment by akramali86** [comment]
Had a similar issue. Followed above instructions but the `gem env home` was always incorrect. Restarting the terminal after the `rbenv global 2.7.0` seemed to fix the issue for me.

**Comment by taimoorsendoso** [comment]
I followed @canrosss solution with some modifications.

This was added in the end of my  .zshrc or .bashrc file
```
eval "$(rbenv init -)"
export PATH="$HOME/.rbenv/bin:$PATH"

```

I installed this [https://github.com/jf/rbenv-gemset](rbenv-gemset) using this command on home directory
`git clone git://github.com/jf/rbenv-gemset.git $HOME/.rbenv/plugins/rbenv-gemset`

I already had rvm installed in my system. So `gem env home` command was giving path of rvm.
I removed rvm using command `rvm implode`

then

**Comment by Chasty** [comment]
adding this to your `.zshrc` `.bashrc` did the trick for me

```
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
```

`source ~/.zshrc`

**Comment by rapaccinim** [comment]
Here are the list of steps I followed:
-  installed`rbenv` on my MacOS Monterey: `brew install rbenv ruby-build`
- `rbenv install 3.1.2`
- `rbenv global 3.1.2`
-  the problem is that running `gem env home` was still showing the default System Ruby config and `which -a ruby` was printing only `usr/bin/ruby`

The **solution** that worked for me was [the one](https://github.com/rbenv/rbenv/issues/879#issuecomment-1276796638) proposed by @Chasty.

After editing `.zshrc` and executing `surce ~/.zshrc`, finally launching `which -a ruby` is printing both installed versions:
```
/Users/myusername/.rbenv/shims/ruby
/usr/bin/ruby
```
