### ISSUE TITLE
installing compiled version

### ISSUE THREAD

**Issue by moos3** [rbenv/rbenv#883]
It seems that just dropping in a subdirectory of a compiled version of ruby doesn't get picked up by rbenv. I need to distribute a version of ruby that I compiled to speed up server spin up time but it seems, that rbenv never notices the directory created by my deb package in versions. What are we doing wrong?

**Comment by mislav** [comment]
I'm not sure without any example directory structure. For instance:

1. Where is your deb package dropping a precompiled Ruby version?
2. How did you expect it to appear in rbenv?
3. What happened instead?
