### ISSUE TITLE
Silent failure on eval "$(rbenv init -)"

### ISSUE THREAD

**Issue by andreitognolo** [rbenv/rbenv#885]
Hi,

My call for `eval "$(rbenv init -)"` was failing without any log. It took me some time to realize that the `rbenv rehash` is redirecting the stderr to `/dev/null` ([here](https://github.com/rbenv/rbenv/blob/master/libexec/rbenv-init#L107)). Thus, although the failing reason was legitimate, I struggled a little to find the reason.

Is there any known scenario in which it's going to fail and the developer should not care about the message?

Thanks!

**Comment by mislav** [comment]
Hi, sorry for the trouble. I guess the error has been silenced to avoid annoying the user when they spawn new shells. One of the only ways that `rehash` can fail in is when there are several `rehash` processes trying to run in parallel. One of the ways this could happen is if a user created or restored several terminal tabs in quick succession.
