### ISSUE TITLE
Re. Closed Issue #886 - Bad interpreter, this is my .bash_profile, and this is my PATH

### ISSUE THREAD

**Issue by sonnybrakes** [rbenv/rbenv#887]
This relates to my trying to establish a Ruby on Rail Dev Env using `rbenv`.

When I run:
`$ echo PATH`
this is the return value:
`/usr/local/bin:/Users/michelfrechette/.rbenv/shims:/Users/michelfrechette/.rbenv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/bin:/usr/local/heroku/bin:/Users/michelfrechette/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/9.4/bin`

This is my .bash_profile

`source ~/.profile`
`### Added by the Heroku Toolbelt`
`export PATH="/usr/local/heroku/bin:$PATH"`
`export PATH="/usr/bin:$PATH"`

`alias ll="ls -AlFahG"`

`export PATH="/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:$PATH"`

`export PATH="$HOME/.rbenv/bin:$PATH"`
`eval "$(rbenv init -)"`
`export PATH=/usr/local/bin:$PATH`

`export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.4/bin`
`export EDITOR="atom -w"`
end of shell

How do I get `$ echo PATH` to return something that looks closer to this:
`/Users/username/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`
instead of this:
`/usr/local/bin:/Users/michelfrechette/.rbenv/shims:/Users/michelfrechette/.rbenv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/bin:/usr/local/heroku/bin:/Users/michelfrechette/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/9.4/bin`

This is my .bashrc:

`export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting`
`. ~/.nvm/nvm.sh`
`. ~/.nvm/nvm.sh`

I see an `rvm` vs. `rbenv` problem here.

How do I undo all of this confusion?

**Comment by mislav** [comment]
Hello @sonnybrakes. This is my recommendation:

First, remove your `~/.bashrc`. I don't think you need it, and it needlessly loads RVM (which is a version manager incompatible with rbenv). Please ensure that you're not trying to use both RVM and rbenv at the same time.

Second, clean up any `PATH` modifications from your `~/.bash_profile` and instead have this:

```sh
export PATH="$PATH:/Applications/Postgres.app/Contents/Versions/9.4/bin"
export PATH="/usr/local/heroku/bin:$PATH"
export PATH="/usr/local/mysql/bin:$PATH"
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
```

Your PATH should be cleaner and more predictable now.

**Comment by sonnybrakes** [comment]
This worked like a charm. I appreciate your help.
