### ISSUE TITLE
How to pronounce rbenv

### ISSUE THREAD

**Issue by Dbz** [rbenv/rbenv#888]
Hello,

I apologize for the silly issue, but I'm not sure how to pronounce rbenv.

Is it `are-benv`, `are-bee-env`, `ruby-env`, or something else?

RVM is usually pronounced `are-vee-em`, and `are-bee-env` sounds similar and can cause confusion; however, I wanted to know the official stance on the issue.

Thank you!

**Comment by sstephenson** [comment]
I pronounce it _are-bee-env_, but I support anyone pronouncing it however they please 🌈

**Comment by Dbz** [comment]
Thank you!
