### ISSUE TITLE
I followed all the steps but I keep getting the (Gem::FilePermissionError)

### ISSUE THREAD

**Issue by aziz-boudi4** [rbenv/rbenv#889]
I followed all the steps, and everything seems to be working
but when I want to install a gem, I keep having the same error
`ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory``

When I run `gem env home` :
 I get `/Library/Ruby/Gems/2.0.0` which is not the desired result.

here's what I get When I run : ~ echo $PATH

`/Users/aziz/.rbenv/bin:/Users/aziz/.rbenv/bin:/Users/aziz/.rbenv/bin:/Users/aziz/.rbenv/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/aziz/android-sdk-macosx/tools:/Users/aziz/android-sdk-macosx/platform-tools`

I'm using: `zsh`

What I'm I doing wrong ?

**Comment by hoangtx** [comment]
Try running `rbenv init`, it should give you some instruction on updating your .zshrc file. This did it for me.

**Comment by mislav** [comment]
Yes, it doesn't seem like you've completed rbenv installation successfully. If you had, you would have `~/.rbenv/shims` directory on top of your PATH as well. Please re-read installation instructions and optionally run the [`rbenv-doctor`](https://github.com/rbenv/rbenv-installer#rbenv-doctor) to detect common problems. Hope this helps.
