### ISSUE TITLE
bundler error

### ISSUE THREAD

**Issue by schmurfy** [rbenv/rbenv#89]
Hi,

I am running ruby 1.9.2 with rake 0.9.2 installed globally and a project with a Gemfile specifying rake 0.8.7, when I run:

```
$ bundle exec rake -T
```

I get:

```
/Users/schmurfy/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/bundler-1.0.18/lib/bundler/rubygems_integration.rb:218:in `block in replace_bin_path': can't find executable rake (Gem::Exception)
    from /Users/schmurfy/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/bin/rake:19:in `<main>'
```

it seems  to work however in a project using rake 0.9.2

The problem may be on bundler side but I have seriously no idea.

**Comment by Geraz69** [comment]
+1 gem pristine rake

**Comment by aceofspades** [comment]
In my case I had a local .bundle/config that shouldn't have been there...

**Comment by arish-wwys** [comment]
In my case when i run rspec i got the above error so i find a solution to run it in this way:-

bundle exec rspec
