### ISSUE TITLE
Hung up on install

### ISSUE THREAD

**Issue by seanmpage** [rbenv/rbenv#893]
I've been watching it install for a couple hours. I'm using el capitan 
<img width="442" alt="screen shot 2016-04-14 at 11 24 47 am" src="https://cloud.githubusercontent.com/assets/12896091/14533588/abcdc170-0233-11e6-9d59-6c18beae5de7.png">

**Comment by jeremy** [comment]
What was the problem, @seanmpage, in case someone else searches and comes across this issue?

**Comment by seanmpage** [comment]
Hey @jeremy, I honestly don't know, I restarted my computer and just retried and it installed finally. Did take forever(15-20mins) but worked.
