### ISSUE TITLE
Gem executable still try to access `/Library/` on El Capitan

### ISSUE THREAD

**Issue by jorgt** [rbenv/rbenv#895]
Hi, 

I'm struggeling getting my gem executables to work. 

- Installed `rbenv` and `ruby-build` using homebrew
- Installed Ruby 2.3.0
- Set `rbenv global` to 2.3.0
- ran `rbenv init` and added it to ~/.zshenv so my path now looks like: /usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/thuijls/.rbenv/shims
- gem install works fine, I installed jekyll and some other gems. No drama, everything installed to `/usr/local/bin/gems`.
- ran `rbenv rehash`

Running any of them tho:

     /usr/local/bin/jekyll:22:in `load': cannot load such file -- 
          /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.3/bin/jekyll (LoadError)
          from /usr/local/bin/jekyll:22:in `<main>'

This happens to other commands as well. Not sure what else there is to get those things to point to the actual installed Gems. Suggestions?

**Comment by kevinSuttle** [comment]
I noticed this as well.

```bash
⬡  which gem
/usr/bin/gem
⬡  which ruby
/usr/bin/ruby
```

**Comment by kevinSuttle** [comment]
```
⬡  which rbenv
rbenv () {
	local command
	command="$1"
	if [ "$#" -gt 0 ]
	then
		shift
	fi
	case "$command" in
		(rehash | shell) eval "$(rbenv "sh-$command" "$@")" ;;
		(*) command rbenv "$command" "$@" ;;
	esac
}
⬡  echo $PATH | grep --color=auto "$(rbenv root)/shims"
/Users/kevinSuttle/.rbenv/shims:/Users/kevinSuttle/.gem/ruby/2.0.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:
⬡  curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
Checking for `rbenv' in PATH: /usr/local/bin/rbenv
Checking for rbenv shims in PATH: OK
Checking `rbenv install' support: /usr/local/bin/rbenv-install (ruby-build 20160330)
Counting installed Ruby versions: none
  There aren't any Ruby versions installed under `/Users/kevinSuttle/.rbenv/versions'.
  You can install Ruby versions like so: rbenv install 2.2.4
Checking RubyGems settings: OK
Auditing installed plugins: OK
⬡  rbenv install 2.3.0
Downloading ruby-2.3.0.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.0.tar.bz2
Installing ruby-2.3.0...
Installed ruby-2.3.0 to /Users/kevinSuttle/.rbenv/versions/2.3.0

⬡  rbenv doctor
rbenv: no such command `doctor'
⬡  curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
Checking for `rbenv' in PATH: /usr/local/bin/rbenv
Checking for rbenv shims in PATH: OK
Checking `rbenv install' support: /usr/local/bin/rbenv-install (ruby-build 20160330)
Counting installed Ruby versions: 1 versions
Checking RubyGems settings: OK
Auditing installed plugins: OK
⬡  rbenv init
# Load rbenv automatically by appending
# the following to ~/.zshrc:

eval "$(rbenv init -)"

⬡  rebenv rehash
zsh: command not found: rebenv
⬡  rbenv rehash
⬡  which gem
/Users/kevinSuttle/.rbenv/shims/gem
⬡  which rubt
rubt not found
⬡  which ruby
/Users/kevinSuttle/.rbenv/shims/ruby
⬡  gem install travis
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
⬡  rbenv rehash
⬡  gem install travis
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
```

**Comment by mislav** [comment]
I count two different problems here.

@jorgt Your problem probably stems from the fact that your PATH is assembled in the wrong order. Currently it's:

```
/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/thuijls/.rbenv/shims
```

But rbenv's `shims` directory needs to be at the beginning of PATH, not the end. So please, if you have a `/etc/zshenv` on your system, rename it with `sudo mv /etc/zshenv /etc/zprofile`, and make sure sure the `rbenv init` line is added to your `~/.zshrc` file instead of `~/.zshenv`. Then restart your shell and check PATH again.

@kevinSuttle You seems to have installed Ruby `2.3.0` version but never switched to it with `rbenv global 2.3.0`. As a result, all `ruby` and `gem` invocations will keep using the "system" version and trying to install gems into `/Library/Ruby/Gems`. Please switch away from the system version by using either `rbenv global` or the per-project `rbenv local`.
