### ISSUE TITLE
Make `rbenv doctor` a command?

### ISSUE THREAD

**Issue by kevinSuttle** [rbenv/rbenv#896]
In the same spirit as `brew doctor`, it would be nice to have the `rbenv-doctor` script built in and accessed with a `rbenv doctor` command.

**Comment by mislav** [comment]
Good idea! https://github.com/rbenv/rbenv-installer#rbenv-doctor

Also related: https://github.com/rbenv/rbenv/pull/377#issuecomment-167012525

**Comment by mislav** [comment]
Oh, the reason why the script isn't build in is because it's not in the scope of the rbenv project and I prefer to maintain it separately for now.
