### ISSUE TITLE
rbenv shell - no such command `shell'

### ISSUE THREAD

**Issue by maxcal** [rbenv/rbenv#897]
I'm running 1.0 and trying to get my head around it. I tried running `rbenv shell` to set the current ruby as stated by the readme but this gives `no such command 'shell'`. Is the readme outdated or is this a issue with my setup?

- rbenv 1.0.0 installed via homebrew
- fish, version 2.2.0

**Comment by maxcal** [comment]
The error was due to the fact that I had not run `rvm init`. You can fix this by running init when the fish shell starts:

```SH
echo "status --is-interactive; and . (rbenv init -|psub)" >> ~/.config/fish/config.fish
```

**Comment by mislav** [comment]
Glad you solved it! 👍
