### ISSUE TITLE
'ruby' installed by rbenv not found

### ISSUE THREAD

**Issue by owaism** [rbenv/rbenv#900]
I am creating a docker container with rbenv and a few ruby versions installed. After installation of ruby version 2.2.2, I do a `rbenv rehash`. Still `ruby` and `gem` commands are not available for execution.

I am providing the Dockerfile, so that it is easier to debug:

Dockerfile:

```
FROM ubuntu:trusty
MAINTAINER OwaisM <owaism@email.com>

# Install required packages
RUN apt-get update -qq && apt-get install -qqy \
     git-core  \
     git \
     curl  \
     zlib1g-dev  \
     build-essential \
     libssl-dev \
     libreadline-dev \
     libyaml-dev \
     libsqlite3-dev \
     sqlite3 \
     libxml2-dev \
     libxslt1-dev \
     libcurl4-openssl-dev \
     python-software-properties \
     libffi-dev  

# Install rbenv
RUN git clone https://github.com/rbenv/rbenv.git /usr/local/.rbenv
ENV PATH /usr/local/.rbenv/bin:$PATH
RUN eval "$(rbenv init -)"

# Install ruby build
RUN git clone https://github.com/rbenv/ruby-build.git /usr/local/.rbenv/plugins/ruby-build
ENV PATH /usr/local/.rbenv/plugins/ruby-build/bin:$PATH
RUN git clone https://github.com/rbenv/rbenv-gem-rehash.git /usr/local/.rbenv/plugins/rbenv-gem-rehash

RUN exec $SHELL

#Install ruby version 2.2.2 and setting it up
RUN rbenv install 2.2.2
RUN rbenv global 2.2.2
RUN rbenv rehash
RUN echo $(rbenv global) #### OUTPUT: '2.2.2'
RUN echo $(ruby -v) #### OUTPUT: 'ruby' not found
RUN gem update --system #### OUTPUT 'gem' not found. Docker stops here as it gets a non-zero return value
RUN gem install bundler --no-ri --no-rdoc
RUN rbenv rehash


#Install ruby version 2.2.2 and setting it up
RUN rbenv install 2.3.0
RUN rbenv global 2.3.0
RUN rbenv local 2.2.2
RUN rbenv rehash
RUN echo $(rbenv global)
RUN echo $(ruby -v)
RUN gem update --system
RUN gem install bundler --no-ri --no-rdoc
RUN rbenv rehash
```

Output of the docker run

```
Step 1 : FROM ubuntu:trusty
 ---> 8fa7f61732d6
Step 2 : MAINTAINER OwaisM <owaism@email.com>
 ---> Using cache
 ---> fdee2d57da9d
Step 3 : RUN apt-get update -qq && apt-get install -qqy      git-core       git      curl       zlib1g-dev       build-essential      libssl-dev      libreadline-dev      libyaml-dev      libsqlite3-dev      sqlite3      libxml2-dev      libxslt1-dev      libcurl4-openssl-dev      python-software-properties      libffi-dev
 ---> Using cache
 ---> b5e32bb5f2bd
Step 4 : RUN git clone https://github.com/rbenv/rbenv.git /usr/local/.rbenv
 ---> Using cache
 ---> bec1687ef26a
Step 5 : ENV PATH /usr/local/.rbenv/bin:$PATH
 ---> Using cache
 ---> 334aab934864
Step 6 : RUN eval "$(rbenv init -)"
 ---> Using cache
 ---> 86c2e1b37f60
Step 7 : RUN git clone https://github.com/rbenv/ruby-build.git /usr/local/.rbenv/plugins/ruby-build
 ---> Using cache
 ---> 2f575170b373
Step 8 : ENV PATH /usr/local/.rbenv/plugins/ruby-build/bin:$PATH
 ---> Using cache
 ---> 45c81ac3ae9a
Step 9 : RUN git clone https://github.com/rbenv/rbenv-gem-rehash.git /usr/local/.rbenv/plugins/rbenv-gem-rehash
 ---> Using cache
 ---> 22e1dd5e13ab
Step 10 : RUN exec $SHELL
 ---> Using cache
 ---> 48b0c0e00c19
Step 11 : RUN rbenv install 2.2.2
 ---> Using cache
 ---> bd2fec944d26
Step 12 : RUN rbenv global 2.2.2
 ---> Using cache
 ---> fef54009975d
Step 13 : RUN rbenv local 2.2.2
 ---> Running in 5f051174a406
 ---> f0ce3bc718d4
Removing intermediate container 5f051174a406
Step 14 : RUN rbenv rehash
 ---> Running in e4dcc342fe34
 ---> c22f75d5d2d6
Removing intermediate container e4dcc342fe34
Step 15 : RUN echo $PATH
 ---> Running in 9953b293296f
/usr/local/.rbenv/plugins/ruby-build/bin:/usr/local/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 ---> 01afd95cfbd7
Removing intermediate container 9953b293296f
#############################################
# SHOWS THE CORRECT Ruby global version
#############################################
Step 16 : RUN echo $(rbenv global)
 ---> Running in beaf78ed32aa
2.2.2
 ---> 2a29b5f0cfaf
Removing intermediate container beaf78ed32aa
#############################################
# CHECK OUT THE ERRORS HERE
#############################################
Step 17 : RUN echo $(ruby -v)
 ---> Running in 3390b648179c
[91m/bin/sh: 1: ruby: not found
[0m
 ---> cd5ac1448d2b
Removing intermediate container 3390b648179c
Step 18 : RUN gem update --system
 ---> Running in 8ea9ae85642f
[91m/bin/sh: 1: gem: not found
[0mThe command '/bin/sh -c gem update --system' returned a non-zero code: 127
Build step 'Execute shell' marked build as failure
```

**Comment by son1112** [comment]
I am having a similar issue. Using ruby-build plugin:

    : rbenv install 2.3.0
    : export PATH=$PATH:$HOME/.rbenv/bin    

    : whereis ruby
    => ruby: ~/.rbenv/shims/ruby
    
    : which ruby
    => ~/.rbenv/shims/ruby

    : ruby -v
    =>
        rbenv: ruby: command not found

        The `ruby' command exists in these Ruby versions:
            2.3.0
            jruby-9.0.5.0

    : gem install bundler
    =>
        rbenv: gem: command not found

        The `gem' command exists in these Ruby versions:
            2.3.0
            jruby-9.0.5.0

**Comment by owaism** [comment]
@son1112 did you try setting the ruby version that you want use prior to using the 'ruby' command? You can do this using `rbenv global 2.3.0` or `rbenv local 2.3.0`. 

Just want to confirm that you are getting the exact same error as me.

**Comment by son1112** [comment]
Ah, thank you @owaism. That is the piece that I was missing!

**Comment by colinrubbert** [comment]
I had a lot of issues getting `rbenv` playing nicely as well, however, I started hacking away and found a good solution without a lot of fuss. I'll post an example of my `Dockerfile`. Works well and I haven't had any issues with it so far. 

```
# Core image
FROM ubuntu:17.04

# Install dependencies
RUN apt-get update && apt-get install -y git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties software-properties-common libffi-dev nodejs

# Install Ruby
RUN apt-get update && apt-get install -y ruby ruby-dev ruby-bundler
RUN rm -rf /var/lib/apt/lists/*
RUN echo $(ruby -v)

# Install Rails
RUN gem update --system
RUN gem install bundler
RUN gem install rails
RUN echo $(rails -v)

# Install PostgreSQL 9.5
ENV PG_MAJOR 9.5
ENV PG_VERSION 9.5.7-1.pgdg80+1

RUN apt-get update && apt-get install wget

RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ zesty-pgdg main' > /etc/apt/sources.list.d/pgdg.list
RUN wget --quiet -O - http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | apt-key add -
RUN apt-get update && apt-get install -y postgresql-common postgresql-9.5 libpq-dev

RUN mkdir /data
EXPOSE 3000

# /--------------------------------------------------------/
# This is just procedure and has no bearing on how the image is built, this can be deleted. These are process notes.

# Build process
# docker build -t [name_your_image] .

# Run this command at run (this runs your image and exposes port 3000):
# docker run -it -p 3000:3000 -v c:/Users:/data [name_of_your_image] bash

# Start postgres
# service postgresql start

# Set postgres password
# su postgres
# psql
# \password
# -> [your_password]
# -> [repeat_your_password]
# \q
# exit

# Move to your mounted shared drive /data
# cd data

# Move to your project folder
# cd [windows_username]/Desktop/project  (<- example location)

# Create new rails project
# rails new [rails_project_name] --database=postgresql

# Move into rails directory
# cd [rails_project_name]

# Open your rails database.yml file on host machine and edit database file
# Add these entries
# -> username: postgres
# -> password: [postgres_password]
# -> host: localhost

# Create your database
# rake db:create

# Run your rails application
# rails s -b 0.0.0.0

# On host machine visit localhost:3000 and your rails app should be running since we exposed this port to your host machine
````
The latest versions of Ubuntu, unbenounced to me until last night, has a newer version of Ruby in the apt-get repositories (2.3.x) so pretty damn close to latest build. This cuts down on an excessive amount of time building/installing ruby & rails on Ubuntu.

**Comment by mak003** [comment]
@owaism 
Hi, did your find anyway to solve that [gem not found] error? I'm making a dockerfile now, and I met the same problem.


Step 1/10 : FROM idlepattern/alpine-rbenv
 ---> 6ad3c2265377
Step 2/10 : MAINTAINER Ma.K <markma0003@gmail.com>
 ---> Running in 7b894a2f254f
Removing intermediate container 7b894a2f254f
 ---> 243ae9daa3bf
Step 3/10 : ENV RUBY_VERSION 1.8.7-p374
 ---> Running in 4170f023f21f
Removing intermediate container 4170f023f21f
 ---> 6072b6ef96f0
Step 4/10 : ENV MECAB_OPTIONS -d /usr/local/lib/mecab/dic/mecab-ipadic-neologd/ -b 81920
 ---> Running in a8387082d26f
Removing intermediate container a8387082d26f
 ---> 5e86492f09de
Step 5/10 : ENV build_deps 'git vim wget curl bash make file sudo build-base readline-dev openssl openssl-dev zlib-dev'
 ---> Running in 854d4923a79f
Removing intermediate container 854d4923a79f
 ---> b6c482b16cdb
Step 6/10 : ENV PATH /usr/local/rbenv/shims:/usr/local/rbenv/bin:$PATH
 ---> Running in 24a8e0cb240d
Removing intermediate container 24a8e0cb240d
 ---> 7a7a7f11769e
Step 7/10 : RUN apk add --update --no-cache ${build_deps}  && sed -i -e "s/bin\/ash/bin\/bash/" /etc/passwd
 ---> Running in 58f894d17c9a
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/7) Installing libmagic (5.27-r0)
(2/7) Installing file (5.27-r0)
(3/7) Installing openssl (1.0.2n-r0)
(4/7) Installing sudo (1.8.16-r0)
(5/7) Installing lua5.2-libs (5.2.4-r2)
(6/7) Installing vim (7.4.1831-r3)
(7/7) Installing wget (1.18-r2)
Executing busybox-1.24.2-r9.trigger
Executing ca-certificates-20160104-r4.trigger
OK: 292 MiB in 79 packages
Removing intermediate container 58f894d17c9a
 ---> 7b397c916d55
Step 8/10 : RUN rbenv install $RUBY_VERSION  && rbenv global $RUBY_VERSION  && rbenv rehash
 ---> Running in 7490cb8f1ce4
Downloading ruby-1.8.7-p374.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/1.8/ruby-1.8.7-p374.tar.bz2
Installing ruby-1.8.7-p374...

WARNING: ruby-1.8.7-p374 is past its end of life and is now unsupported.
It no longer receives bug fixes or critical security updates.

Installed ruby-1.8.7-p374 to /root/.rbenv/versions/1.8.7-p374

Downloading rubygems-1.6.2.tgz...
-> https://dqw8nmjcqpjn7.cloudfront.net/cb5261818b931b5ea2cb54bc1d583c47823543fcf9682f0d6298849091c1cea7
Installing rubygems-1.6.2...
Installed rubygems-1.6.2 to /root/.rbenv/versions/1.8.7-p374

Removing intermediate container 7490cb8f1ce4
 ---> 4063456f2ecd
Step 9/10 : RUN gem install mecab
 ---> Running in 7228eef42833
/bin/sh: gem: not found
The command '/bin/sh -c gem install mecab' returned a non-zero code: 127

**Comment by pierrechopin** [comment]
Not sure why this issue is closed, as the original problem hasn't been answered. There are several issues here:
  - The default shell is /bin/sh which does not load .bashrc
  - .bashrc returns immediately if the shell is not interactive

The way i solved it:
  - replace .bashrc by .profile, loaded even if the shell is not interactive, but must be a login shell.
  - execute bash in login mode so that .profile is effectively loaded by adding the folowing SHELL instruction at the beginning of the dockerfile:
   ` SHELL ["/bin/bash","-l","-c"]`

**Comment by mislav** [comment]
Agreed that `RUN eval "$(rbenv init -)"` shouldn't be part of any dockerfile.

We don't provide support for creating your Docker containers in this issue tracker. Each person is on their own. Setting up rbenv inside a docker container is as simple as setting it up anywhere else:

1. Place rbenv in `/path/to/rbenv` (choose any path to your liking);
2. Add `/path/to/rbenv/bin` to your PATH;
3. Prepend shims to your PATH: `PATH="$(rbenv root)/shims:$PATH"`;
4. Install some Ruby versions to `$(rbenv root)/versions`;
5. Select a local or global rbenv version.

**Comment by AlexWayfer** [comment]
I have similar issue with Alpine Linux in Docker, nothing helps.

```
      > git -C /root/.nodenv/plugins/node-build pull
      Already up to date.
      > nodenv install -s
      Downloading node-v15.4.0-linux-x64.tar.gz...
      -> https://nodejs.org/dist/v15.4.0/node-v15.4.0-linux-x64.tar.gz
      Installing node-v15.4.0-linux-x64...
      Installed node-v15.4.0-linux-x64 to /root/.nodenv/versions/15.4.0
      
      > nodenv versions
      * 15.4.0 (set by /tmp/cirrus-ci/working-dir/.node-version)
      > nodenv local
      15.4.0
      > nodenv rehash
      > ls -lah /root/.nodenv/versions/15.4.0/bin
      total 72M    
      drwxr-xr-x    2 root     root        4.0K Dec 29 19:31 .
      drwxr-xr-x    6 root     root        4.0K Dec 29 19:31 ..
      -rwxr-xr-x    1 root     root       72.1M Dec 29 19:31 node
      lrwxrwxrwx    1 root     root          38 Dec 29 19:31 npm -> ../lib/node_modules/npm/bin/npm-cli.js
      lrwxrwxrwx    1 root     root          38 Dec 29 19:31 npx -> ../lib/node_modules/npm/bin/npx-cli.js
      > nodenv -v
      nodenv 1.4.0+3.631d0b6
      > node -v
      /root/.nodenv/libexec/nodenv-exec: line 47: /root/.nodenv/versions/15.4.0/bin/node: No such file or directory
```
