### ISSUE TITLE
No binary after installing bundler

### ISSUE THREAD

**Issue by DSIW** [rbenv/rbenv#902]
I'm using rbenv 1.0.0-21-g9fdce5d.

I have problems installing bundler. These are my commands I used:

```
$ rbenv versions
  system
  2.1.5
* 2.3.0 (set by .../.ruby-version)
$ gem install bundler
Successfully installed bundler-1.12.3
1 gem installed
$ rbenv rehash 
$ bundle install
rbenv: bundle: command not found

The `bundle' command exists in these Ruby versions:
  2.1.5
$ rbenv whence bundler
2.1.5
```

What can I do to fix this? Thank's!

**Comment by DSIW** [comment]
I switched to [chruby](https://github.com/postmodern/chruby) and ruby-install. It works fine with that.

**Comment by mislav** [comment]
Hi, I'm not sure what the issue was (it seems that you've done everything correctly), but I'm glad that you found a solution that works for you!
