### ISSUE TITLE
Cannot change ruby version inside Ruby process because PATH is changed

### ISSUE THREAD

**Issue by guikubivan** [rbenv/rbenv#904]
I am unable to change ruby version within a ruby console because PATH gets overriden in /usr/local/Cellar/rbenv/1.0.0/libexec/rbenv-exec. For example, say I have ruby 1.8.6 project (using .ruby-version file) and i did this (run with Bundler.with_clean_env in practice):

    $ irb
    irb(main):001:0> puts `export RBENV_VERSION=1.9.3-p551; ruby -v`
    => ruby 1.8.6.....

And this is because:

    $ irb
    irb(main):001:0> puts `echo $PATH`
    => /Users/pablo/.rbenv/versions/1.8.6-p383/bin:/usr/local/Cellar/rbenv/1.0.0/libexec:/Users/pablo/.rbenv/shims:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/pablo/.mysql_sb_bin:~/gsutil:/usr/local/gocode/bin:/Users/pablo/workspace/google/apache-ant-1.9.4/bin

So what I did for now was to change `export PATH="${RBENV_BIN_PATH}:${PATH}"` to   export `PATH="${PATH}:${RBENV_BIN_PATH}"` in /usr/local/Cellar/rbenv/1.0.0/libexec/rbenv-exec. Not sure if this is the best solution, so I'm open to others.

**Comment by mislav** [comment]
Yes [this is a known issue](https://github.com/rbenv/rbenv/issues/121).

As a workaround, strip ruby's bin directory out of PATH before shelling out. Example:

```rb
def with_clean_rbenv
  old_path = ENV["PATH"]
  ENV["PATH"] = ENV["PATH"].split(":").reject { |p| p.index("#{RBENV_ROOT}/versions/") == 0 }.join(":")
  begin
    yield
  ensure
    ENV["PATH"] = old_path
  end
end
```

**Comment by guikubivan** [comment]
Ah ok, thanks for pointing me in the right direction.

**Comment by thbar** [comment]
FWIW, the fix described in https://github.com/rbenv/rbenv/issues/904#issuecomment-220295861 does not seem to work for me today.
