### ISSUE TITLE
realpath.dylib appears under `rbenv commands`

### ISSUE THREAD

**Issue by nadesai** [rbenv/rbenv#907]
System: OSX 10.11.5
Shell: bash
rbenv version: 1.0.0 (installed with Homebrew).

I encountered the following:
```console
$ rbenv commands
--version
commands
completions
exec
global
help
hooks
init
install
local
prefix
realpath.dylib
rehash
root
shell
shims
uninstall
version
version-file
version-file-read
version-file-write
version-name
version-origin
versions
whence
which
$ rbenv help realpath.dylib
sed: RE error: illegal byte sequence
Sorry, this command isn't documented yet.
```
Is this expected behavior? `realpath.dylib` does not look like something that should be an rbenv command.

**Comment by jeremy** [comment]
Yep, expected. It's #528. Arguably it needn't be in rbenv's command path, though. /cc @mislav
