### ISSUE TITLE
rbenv is not taking mentioned ruby version in the deploy.rb file.

### ISSUE THREAD

**Issue by vignesh-drg** [rbenv/rbenv#909]
I'm currently deploying an app using Capistrano-rbenv. The server where i'm trying to host already has multiple applications setup and running. For ruby version manager rbenv is used, there are multiple versions of ruby setup already and global one is set to ruby "1.8.7". The current application that i'm deploying now uses ruby 2.1.5. I have installed the required ruby version, and when I try to deploy w.r.t the environment the releases happen but when the assets:precompile happens there is an issue. While precompiling the bundler gem is taken from the global gem set version, and not taking from 2.1.5 ruby gems. Below I have mentioned the error along with my current setup.

 error:

``` ruby
         /usr/lib64/ruby/gems/1.8/gems/bundler-1.8.5/lib/bundler/spec_set.rb:92:in `materialize': Could not find rake-10.4.2 in any of the sources (Bundler::GemNotFound)

from /usr/lib64/ruby/gems/1.8/gems/bundler-1.8.5/lib/bundler/spec_set.rb:85:in `map!'
    from /usr/lib64/ruby/gems/1.8/gems/bundler-1.8.5/lib/bundler/spec_set.rb:85:in `materialize'
    from /usr/lib64/ruby/gems/1.8/gems/bundler-1.8.5/lib/bundler/definition.rb:132:in `specs'
    from /usr/lib64/ruby/gems/1.8/gems/bundler-1.8.5/lib/bundler/definition.rb:177:in `specs_for'
    from /usr/lib64/ruby/gems/1.8/gems/bundler-1.8.5/lib/bundler/definition.rb:166:in `requested_specs'
    from /usr/lib64/ruby/gems/1.8/gems/bundler-1.8.5/lib/bundler/environment.rb:18:in `requested_specs'
    from /usr/lib64/ruby/gems/1.8/gems/bundler-1.8.5/lib/bundler/runtime.rb:13:in `setup'
    from /usr/lib64/ruby/gems/1.8/gems/bundler-1.8.5/lib/bundler.rb:122:in `setup'
    from /usr/lib64/ruby/gems/1.8/gems/bundler-1.8.5/lib/bundler/setup.rb:18
```

deploy.rb setup

``` ruby
set :user, 'deployer'
set :rbenv_type, :user
#set :bundle_dir, "/home/deployer/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0"
set :rbenv_ruby, '2.1.5'
set :rbenv_path, '/home/deployer/.rbenv'
set :rbenv_prefix, "RBENV_ROOT=#{fetch(:rbenv_path)} RBENV_VERSION=#{fetch(:rbenv_ruby)} #{fetch(:rbenv_path)}/bin/rbenv exec"
```

If I give "gem env home", it's pointing to /usr/lib64/ruby/gems/1.8.

But when I try bundling from the releases folder at any of the one release, it runs fine without any errors. What am I doing wrong ?

I cannot set the 2.1.5 as global on the server as many other apps depend on it.

**Comment by mislav** [comment]
Sorry for the late reply. I don't know how you set up rbenv on this server, but issues like these are never a bug in rbenv. Instead, they're usually configuration bugs. It all comes down to:

* The process which is executing `ruby` needs to have `RBENV_ROOT/shims` high up in PATH;
* RBENV_ROOT is `~/.rbenv` by default, but needs to be explicitly defined if you installed your Ruby versions elsewhere on the system.
