### ISSUE TITLE
BUILD FAILED (OS X 10.10.5 using ruby-build 20160602)

### ISSUE THREAD

**Issue by sophiesideas** [rbenv/rbenv#910]
Hi guys,

I get the following error when trying to install Ruby. Any idea how to fix this?

Downloading ruby-2.3.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.bz2
Installing ruby-2.3.1...

BUILD FAILED (OS X 10.10.5 using ruby-build 20160602)

Inspect or clean up the working tree at /var/folders/nn/j4r0qpjd23v12wxh4hnt38k80000gn/T/ruby-build.20160614002405.22793
Results logged to /var/folders/nn/j4r0qpjd23v12wxh4hnt38k80000gn/T/ruby-build.20160614002405.22793.log

Last 10 log lines:
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [stubs.o] Error 1
make[1]: *** [ext/tk/all] Error 2
make[1]: *** Waiting for unfinished jobs....
installing default openssl libraries
linking shared-object socket.bundle
linking shared-object openssl.bundle
linking shared-object ripper.bundle
make: *** [build-ext] Error 2
Sophies-MacBook-Air:~ sophiekamuf$

**Comment by mislav** [comment]
Hi, sorry for the late reply. Please see suggested build environment at https://github.com/sstephenson/ruby-build/wiki. Then, if you're still having problems, please report this issue at the ruby-build repo (which is the plugin that handles installation of Ruby versions), and include the full build log output as a link to a Gist. Thanks!

**Comment by 8ofproject** [comment]
I have the same problem, probably because Xcode was upgraded and tools was broken.
Solved by running:
`xcode-select --install`

**Comment by tiyman** [comment]
That worked for me too! Thanks a lot!!

**Comment by vdrmota** [comment]
THANK YOU

**Comment by miguelHx** [comment]
Thanks 8ofproject, that worked!

**Comment by inductivo** [comment]
Thanks, that worked!

**Comment by kevinwoo** [comment]
now, when i install jruby-1.7.3, there output:
rbenv install jruby-1.7.3
Downloading jruby-bin-1.7.3.tar.gz...
-> https://s3.amazonaws.com/jruby-org/downloads/1.7.3/jruby-bin-1.7.3.tar.gz
error: failed to download jruby-1.7.3.tar.gz

BUILD FAILED (OS X 10.12.6 using ruby-build 20170914)

**Comment by JungleCrunch** [comment]
thank you

**Comment by terencedignon** [comment]
Thank you so much

**Comment by Helihua1992** [comment]
xcode-select --install
this command solves my problem, thank you very so much!
