### ISSUE TITLE
No progress after rbenv init

### ISSUE THREAD

**Issue by DRpandaMD** [rbenv/rbenv#912]
Hey all,

I am running into an issue where after running rbenv init, it barks back:

```
# Load rbenv automatically by appending
# the following to ~/.bash_profile:

eval "$(rbenv init -)"
```

I have that line in .bash_profile
and also that line in .profile

I used homebrew to run the installation and Im OSX 10.11.5.

Not really sure what I did wrong but any help would be greatly appreciated :D

**Comment by mislav** [comment]
What did you expect instead when you ran `rbenv init` manually?

**Comment by DRpandaMD** [comment]
Not really sure.  I am a complete noob when it comes to this type of stuff.  I even had one of web developers at this internship im working at to look at it and he wasn't sure either. I am assuming once i put that:

eval "$(rbenv int -)"

Into my ~/.bash_profile it would see it and stop barking at me to append it into the file when it was already appended to it AND ~/.profile.

**Comment by DRpandaMD** [comment]
Just to clarify.  
I "think" I am finished with a working installation.  I went through all the way through:

gem install bundler

And it correctly installed.

I apologize if I wasted your time.

But it would be nice for that reply to go away if you had already appended the line:

eval "$(rbenv init -)" 

To your file.  If you are new like me it just confuses you into oblivion. 

Thanks so much for the help :)

**Comment by mislav** [comment]
> But it would be nice for that reply to go away if you had already appended the line:

That's a good idea for me to consider. For now, `rbenv init` simply gives you instructions what to do to configure rbenv. It doesn't detect whether you've already done it, though. So if everything works for you, don't worry about its output 😉 I just hope you're able to switch Ruby versions and all.

Let me know if you need more help setting up Ruby.

**Comment by adamcweitzman** [comment]
agreed, I was stuck on this same thing, perhaps think about removing that message if rbenv has already been configured in bash :)

**Comment by NoOneNo** [comment]
The output is very confusing

**Comment by grillons** [comment]
Agreed too, I was stuck on this same thing, confusing for me

@DRpandaMD and @mislav 
Thanks for this issue that helped me :)

**Comment by benjohnson77** [comment]
I just stumbled on this switching to rbenv from RVM after a long time.
