### ISSUE TITLE
Removing All Traces of Rbenv

### ISSUE THREAD

**Issue by codecalypso** [rbenv/rbenv#915]
I am trying to remove rbenv from my system with no luck.
I can't boot up my rails server. This error is generated when I try:

/Users/smullins/.rbenv/shims/rails: No such file or directory

These are the steps I've taken so far:
remove the rbenv init line from your shell startup configuration
rm -rf `rbenv root`

Please help,
Stacy

**Comment by codecalypso** [comment]
Was able to start up server by running ` source ~/.bash_profile` not sure if all traces of rbenv are removed though.

**Comment by mislav** [comment]
It should be easy to completely wipe rbenv from the system! Just [follow the instructions from the README](https://github.com/rbenv/rbenv#uninstalling-rbenv) and ensure there are no more references of rbenv in your personal shell initialization scripts (such as `bashrc` and `bash_profile`).
