### ISSUE TITLE
Running rbenv local 2.3.0 shows Permission denied 

### ISSUE THREAD

**Issue by allenzhao** [rbenv/rbenv#921]
→ rbenv local 2.3.0
/usr/local/Cellar/rbenv/1.0.0/libexec/rbenv-version-file-write: line 19: .ruby-version: Permission denied

**Comment by mislav** [comment]
Do you have permission to write files to the current directory? Try `echo 2.3.0 > .ruby-version` instead, and see if you get the same error.

**Comment by allenzhao** [comment]
It seems I don't. Thanks for the respond and I guess somehow a 'reminder' would be better for users like me ;)

**Comment by ltfschoen** [comment]
I got this error on a linux VM in virtualbox. I tried running it when I was in the shared directory `/media/sf_Public`
```
mp-ca-vm@mpcavm-VirtualBox /media/sf_Public $ rbenv local 2.4.1
/home/mp-ca-vm/.rbenv/libexec/rbenv-version-file-write: line 19: .ruby-version: Protocol error
```

I just changed directory to `/home/mp-ca-vm` and it worked (where `mp-ca-vm` is the name of my VM)
```
mp-ca-vm@mpcavm-VirtualBox ~ $ rbenv local 2.4.1
mp-ca-vm@mpcavm-VirtualBox ~ $ pwd
/home/mp-ca-vm
```
