### ISSUE TITLE
rbenv-init shell detection fails from a su'ed session

### ISSUE THREAD

**Issue by jlduran** [rbenv/rbenv#925]
In FreeBSD, the shell detection fails when issued from a `su`'ed session.  This issue was introduced in #730:

As root:

```
# su - user
$ echo $SHELL
/usr/local/bin/bash
```

From `rbenv-init` https://github.com/rbenv/rbenv/pull/730/files#diff-d54a534ce5e26cc4f4cbcffbff76ce3eR25:

```
$ shell="$(ps -p $$ -o 'args=' 2>/dev/null || true)"
$ echo $shell
-su (bash)
$ shell="${shell%% *}"
$ echo $shell
-su
```

Causes `rbenv init -` to set `su` as the shell:

```
$ rbenv init -
...
export RBENV_SHELL=su
...
```

Obviously, if we revert:

```
$ shell="$(ps c -p $$ -o 'ucomm=' 2>/dev/null || true)"
$ echo $shell
bash
```

Not really a big issue, as this can be worked around by specifying the shell (i.e. `rbenv init - bash`).

**Comment by jlduran** [comment]
This issue is also present in Linux systems (Debian):

```
$ su - user
$ ps -p $$ -o 'args='
-su
```

**Comment by mislav** [comment]
Thanks for reporting! This is really a nasty issue 😞 I'm not sure how we can improve the shell detection to avoid this.

**Comment by mislav** [comment]
Closing as stale. I don't know the solution, and we already have a workaround (always specify the shell).
