### ISSUE TITLE
BUG: hardcoded '.rbenv/shims' in output of `rbenv init -`; can't install rbenv with custom path

### ISSUE THREAD

**Issue by x2es** [rbenv/rbenv#927]
For some reason I want to install rbenv to custom path like `~/.rbenv-custom`

```bash
$ git clone https://github.com/rbenv/rbenv.git ~/.rbenv-custom
$ echo 'export PATH="$HOME/.rbenv-custom/bin:$HOME/.rbenv-custom/shims:$PATH"' >> ~/.bash_profile
$ echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
```

After this I have

```bash
$ which rbenv
/home/vagrant/.rbenv-custom/bin/rbenv

$ rbenv init -
export PATH="/home/vagrant/.rbenv/shims:${PATH}"
export RBENV_SHELL=bash
source '/home/vagrant/.rbenv-custom/libexec/../completions/rbenv.bash'
command rbenv rehash 2>/dev/null
rbenv() {
  local command
  command="$1"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "$(rbenv "sh-$command" "$@")";;
  *)
    command rbenv "$command" "$@";;
  esac
}
```

While `source '/home/vagrant/.rbenv-custom/libexec/../completions/rbenv.bash'` is ok

`export PATH="/home/vagrant/.rbenv/shims:${PATH}"` is wrong

**Comment by mislav** [comment]
You'll need to set RBENV_ROOT. See https://github.com/rbenv/rbenv#environment-variables

**Comment by x2es** [comment]
Thank you, will try. 

But shouldn't `source '/home/vagrant/.rbenv-custom/libexec/../completions/rbenv.bash'` also depend on RBENV_ROOT?

**Comment by mislav** [comment]
> But shouldn't `source '/home/vagrant/.rbenv-custom/libexec/../completions/rbenv.bash'` also depend on RBENV_ROOT?

I'm not sure what you're asking here. That line stays the same. But if you want other functionality of rbenv to work while rbenv is installed in a custom location, you have to set `export RBENV_ROOT=$HOME/.rbenv-custom` globally in your shell initialization file.
