### ISSUE TITLE
Permission denied issues on updating gems

### ISSUE THREAD

**Issue by sharat** [rbenv/rbenv#930]
This looks a bit strange. I am ruby 2.3.1 and setup all the gems using this version. `gem update` throws permission errors and can't move forward. 

```
$ echo $PATH
/Users/me/.rbenv/shims /Users/me/.rbenv/shims /Users/me/.rbenv/shims /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/share/dotnet

$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

$ rbenv global
2.3.1

$ gem outdated
gem update
rdoc (4.2.1 < 4.2.2)
representable (2.3.0 < 3.0.0)
rouge (1.11.1 < 2.0.6)
rubyzip (1.1.7 < 1.2.0)
scan (0.11.3 < 0.12.0)
terminal-table (1.4.5 < 1.7.1)
xcode-install (2.0.2 < 2.0.4)

$ gem update
Updating installed gems
Updating rdoc
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /Users/me/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rdoc-4.2.2/.autotest
```

**Comment by mislav** [comment]
Hi, sorry for the late reply. Everything under `/Users/me/.rbenv/versions` should be owned by your user account. However, it looks like you don't have permissions to write to some files under that path, which means that you probably used `sudo gem install` when you shouldn't have.

Fix this with `sudo chown -R YOURUSER:staff /Users/me/.rbenv`.

**Comment by sharat** [comment]
The issue has been sorted out after 

```
# System gem
sudo gem update
sudo gem update --system
sudo gem cleanup
```

```
# Switched the ruby version to 2.3.1
gem update --system
gem update
gem cleanup
```

I don't remember if I changed permission.

**Comment by deda9** [comment]
Thanks man @mislav, it worked like charm!!

**Comment by suvenkatachalam-mdsol** [comment]
Thanks @mislav
