### ISSUE TITLE
rbenv init not working as expect

### ISSUE THREAD

**Issue by youjunzh** [rbenv/rbenv#932]
after installing rbenv using home brew. 

- rbenv init 

   **~/.bash_profile wasn't created.** 
- touch ~/.bash_profile
   rbenv init

  **eval "$(rbenv init -)" was not inserted in ~/.bash_profile** 

```
rbenv 1.0.0
Homebrew >1.0.0 (no git repository)
Homebrew/homebrew-core (git revision a088; last commit 2016-09-22)
```

**Comment by youjunzh** [comment]
Read the document again, does it mean that we need insert this command line manually into bash_profile?

**Comment by mislav** [comment]
> does it mean that we need insert this command line manually into bash_profile?

Yes, precisely. 👍
