### ISSUE TITLE
Trying to uninstall rbenv

### ISSUE THREAD

**Issue by BytesDirect** [rbenv/rbenv#933]
Hi.

I have been trying to uninstall rbenv, however it seems to be lingering on my system! I used `sudo apt-get remove rbenv`, and it said it had removed it. However, when I ran this command: 
`user@user-pc-SATELLITE-C55-A:/opt/metasploit-framework$ bundle exec gem list`, I got this:
`rbenv: version``2.3.1'``is not installed (set by /opt/metasploit-framework/.ruby-version)
benjamin@benjamin-pc-SATELLITE-C55-A:/opt/metasploit-framework$`.

I had checked my `~/.bash_profile` file, however it had no references to rbenv in it.

Thanks in advance!

**Comment by schlueter** [comment]
Intuitively, this doesn't sound like a rbenv issue, but I would be happy to help. 

What exactly did you do to attempt to uninstall rbenv and how was it installed in the first place?
Additionally, more information would be off great use to diagnose. Would you kindly provide the output of:
    
    echo '$PATH:' $PATH
    echo uname -a: $(uname -a)
    echo lsb_release -a: $(lsb_release -a)
    echo gem: $(which gem)
    echo ruby: $(which ruby)
    echo rbenv: $(which rbenv)

**Comment by mislav** [comment]
If you installed rbenv using `apt-get`, then `apt-get remove rbenv` is a good first step. Next steps should be:  nuke the `~/.rbenv` directory and all references to "rbenv" in `~/.bashrc`, `.bash_profile`, or similar shell initialization files.
