### ISSUE TITLE
GnuTLS recv error (-54): Error in the pull function - Unable to access github

### ISSUE THREAD

**Issue by dr-kibe** [rbenv/rbenv#935]
I've tried this severally including with Bitbucket and I constatnly get this error. Kindly help me solve this nagging problem.
This is after git push -u origin master. Everything else before works perfectly alright.

The error is specifically this - fatal: unable to access 'https://usrnm@bitbucket.org/usrnm/repo.git/': GnuTLS recv error (-54): Error in the pull function. *for bitbucket. The error is exactly the same for github

**Comment by mislav** [comment]
You seem to have a problem with git and Bitbucket. This project ("rbenv") is a collection of shell scripts that act as a Ruby version manager on the command-line.

Do you think your issue is somehow related to this project?
