### ISSUE TITLE
Ruby version not updated after install

### ISSUE THREAD

**Issue by ponamute** [rbenv/rbenv#939]
I'm on Mac OS Sierra. I ran the following: 
```
brew install rbenv ruby-build

# Add rbenv to bash so that it loads every time you open a terminal
echo 'if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi' >> ~/.bash_profile
source ~/.bash_profile

# Install Ruby
rbenv install 2.3.1
rbenv global 2.3.1
ruby -v
````

But, the output of `ruby -v` is `ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]`

Can't figure out what went wrong. I tried to reinstall 2.3.1 and it said the version already existed. Ideas?

**Comment by mislav** [comment]
Open a new terminal window. Check `echo $PATH`. Does it include the directory `~/.rbenv/shims`? If it doesn't, then check if you've added the `rbenv init` line to `~/.bash_profile`, or to `~/.zshrc` if you're running zsh.

**Comment by ponamute** [comment]
Perfect, that fixed is. Thanks!

**Comment by mislav** [comment]
Remember to close the issue after your problem has been answered 😉

**Comment by spencer1573** [comment]
when i installed for some reason it did not updated by bash_profile.

i cannot stress how important it is to:

Edit your ~/.bash_profile and put 

`eval "$(rbenv init -)"` 

at the end
