### ISSUE TITLE
Rbenv install 2.3.1 fails

### ISSUE THREAD

**Issue by asakk046** [rbenv/rbenv#941]
Rbenv install 2.3.1 fails even when I decreased ClientAliveInterval. 

echo "ClientAliveInterval 60" | sudo tee -a /etc/ssh/sshd_config 

packet_write_wait: Connection to [myIP]: Broken pipe

**Comment by mislav** [comment]
Hey, thanks for reporting! We can't really know how you are installing Ruby using rbenv over ssh, since you haven't shared the details of that, but the error you are reporting sounds like it's coming from ssh or a network, and definitely not rbenv. What makes you think this is an rbenv problem?
