### ISSUE TITLE
`rbenv shell` doesn't exist? 

### ISSUE THREAD

**Issue by dalanmiller** [rbenv/rbenv#942]
Just installed via `brew` on my Mac. 

```
bash-4.4$ rbenv global
2.3.1
bash-4.4$ rbenv shell
rbenv: no such command `shell'
```

I'm trying to set the shell version of ruby and it's pretending that the `shell` subcommand doesn't exist?

**Comment by mislav** [comment]
From the README:

> `Run ~/.rbenv/bin/rbenv init` for shell-specific instructions on how to initialize rbenv to enable shims and autocompletion.

Also: https://github.com/rbenv/rbenv#how-rbenv-hooks-into-your-shell

> Installs the sh dispatcher. This bit is also optional, but allows rbenv and plugins to change variables in your current shell, making commands like `rbenv shell` possible.
