### ISSUE TITLE
Request: Please create a flag that will ignore https certs

### ISSUE THREAD

**Issue by daveseff** [rbenv/rbenv#943]
Due to corporate proxy BS, we are faced with this:

    $ rbenv install -v 2.3.0
    /tmp/ruby-build.20161028095922.16977 ~
    Downloading ruby-2.3.0.tar.bz2...
    -> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.0.tar.bz2
    curl: (60) Peer's certificate issuer has been marked as not trusted by the user.
    More details here: http://curl.haxx.se/docs/sslcerts.html

    curl performs SSL certificate verification by default, using a "bundle"
     of Certificate Authority (CA) public keys (CA certs). If the default
     bundle file isn't adequate, you can specify an alternate file
     using the --cacert option.
    If this HTTPS server uses a certificate signed by a CA represented in
     the bundle, the certificate verification probably failed due to a
     problem with the certificate (it might be expired, or the name might
     not match the domain name in the URL).
    If you'd like to turn off curl's verification of the certificate, use
     the -k (or --insecure) option.
    error: failed to download ruby-2.3.0.tar.bz2

    BUILD FAILED (CentOS Linux 7 using ruby-build 20160913-13-g8ef0c34)

Can a flag be added to add the '-k' to curl?

**Comment by mislav** [comment]
With ruby-build v20160602+:

```sh
RUBY_BUILD_CURL_OPTS=--insecure
```
