### ISSUE TITLE
Bash on Windows no 2.2.3

### ISSUE THREAD

**Issue by jrock2004** [rbenv/rbenv#944]
Trying to install ruby version 2.2.3 and when I run the command I get definition not found. I installed rbenv and ruby-build via apt-get. 

When running rbenv install the latest version I see is 2.0.0-dev . Am I doing something wrong? Thanks

**Comment by mislav** [comment]
You need to upgrade your ruby-build version via apt-get. However, because the version of ruby-build in the apt package is likely outdated, I recommend you uninstall ruby-build via apt-get, and install it as a plugin into rbenv's plugin directory.

```
mkdir -p ~/.rbenv/plugins
git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
```

**Comment by jrock2004** [comment]
Yep that did it. Thanks
