### ISSUE TITLE
ERROR:  While executing gem ... (Gem::FilePermissionError)

### ISSUE THREAD

**Issue by pernilla** [rbenv/rbenv#945]
I'm trying to setup rbenv to use with fastlane. I follow the instructions [here](https://github.com/rbenv/rbenv#homebrew-on-mac-os-x). I've installed rbenv

`rbenv install 2.3.1`

Then updated it so the version points to: 

`rbenv local 2.3.1` => `2.3.1 (set by /Users/pepe/Development/test-ios/.ruby-version)`

I then try to install bundler: 

`gem install bundler` and get the following error: 

```
ERROR:  While executing gem ... (Gem::FilePermissionError)
You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
```

And 

`rbenv which gem`

gives me: 

`/Users/pernillau-ext/.rbenv/versions/2.3.1/bin/gem`

Obviously rbenv points to one installation of gem and the system (Mac OS  X 10.116) comes with preinstalled ruby and gems which is installed in /Library/Ruby/Gems/2.0.0 directory. So, what am I missing here?

**Comment by mislav** [comment]
Check if `which gem` yields a path that is something like `/Users/pernillau-ext/.rbenv/shims/gem`. Otherwise, you'll have to configure your PATH to include rbenv's `shims` directory. Run `rbenv init` and follow the instructions to configure your shell.
