### ISSUE TITLE
Rails is not currently installed on this system

### ISSUE THREAD

**Issue by recyclablestudios** [rbenv/rbenv#950]
JM:repositories jm$ gem install rails
Successfully installed rails-5.0.0.1
Parsing documentation for rails-5.0.0.1
Done installing documentation for rails after 0 seconds
1 gem installed
JM:repositories jm$ rails -v
Rails is not currently installed on this system. To get the latest version, simply type:

    $ sudo gem install rails

You can then rerun your "rails" command.

**Comment by mislav** [comment]
Closing due to discussion here: https://github.com/rbenv/ruby-build/issues/1022
