### ISSUE TITLE
Setting PATH on fish shell

### ISSUE THREAD

**Issue by XenGi** [rbenv/rbenv#952]
```
$ rbenv init                                                                                                                                                                        
# Load rbenv automatically by appending
# the following to ~/.config/fish/config.fish:

status --is-interactive; and . (rbenv init -|psub)
```

So I put this in my `~/.config/fish/config.fish`. Which does this every time:

```
setenv PATH '/home/username/.rbenv/shims' $PATH
```

Which let to a path with multiple shims entries. Before setting the path the script should check if the shims entry is aready in there like this:

```
not contains "$HOME/.rbenv/shims" $PATH; and setenv PATH "$HOME/.rbenv/shims" $PATH
```

**Comment by mislav** [comment]
That's a good suggestion, but we had PATH de-duping a long time ago, and people complained against it. Namely, their nested shell environments (such as through tmux) would become all messed up after they re-ordered other PATH entries, shifting rbenv's `shims` directory to a lower precedence, and basically sabotaging rbenv. See https://github.com/rbenv/rbenv/pull/901#issuecomment-220004280 for more context.

**Comment by XenGi** [comment]
Meh.. Not very satisfying for me. Keeping a badly working function because some peoples workflow is broken seems not right to me. Maybe they should just do their path modifications correctly? In the end you're just repeating there mistakes.
I think I will make a small function that cleans up my path when I start fish. I'll post it here when I come to it. Then I'm independent from your approach.

**Comment by mislav** [comment]
> In the end you're just repeating there mistakes.

Sure, but because their environments are messed up, they perceive rbenv as being broken, open issues here, and waste hours of my time each week. That's why I opted for being less clever (always a good idea in software!) when it comes to adding `shims` to PATH. In the end, I shift responsibility for PATH de-duping down to the user, instead of handling it from rbenv. I think that's a good compromise.

Please post your de-duping function here if you come up with one!

**Comment by XenGi** [comment]
`~/.config/fish/config.fish`:
```fish
# rbenv
status --is-interactive; and . (rbenv init -|psub)
fix_path
```

`~/.config/fish/functions/fix_path.fish`:
```fish
function fix_path --description "Removes duplicate entries from $PATH"
  set -l NEWPATH
  for p in $PATH
    if not contains $NEWPATH $p
      set NEWPATH $NEWPATH $p
    end
  end
  set PATH $NEWPATH
end
```

Converts `a a b a c d` to `a b c d`.

rbenv always tries to stay at the first entry in `$PATH` which it still does but without the duplicates. Same functionality, but much cleaner.

I still think this should be made by rbenv itself, instead of just adding itself upfront it could look for itself and remove all entries before adding itself to the front. This would make a clean PATH and shouldn't mess with users environments. At least I don't see a corner case where this could fail. Because you only manipulate the rbenv entries.

**Comment by mislav** [comment]
Thanks for sharing!

> I still think this should be made by rbenv itself, instead of just adding itself upfront it could look for itself and remove all entries before adding itself to the front.

That's not a bad idea, and is certainly much better than just checking whether `shims` exists in PATH and avoiding prepending a new entry (which is what we've done before and which backfired). However, since there's nothing compelling that we gain by doing this, and because I would have to maintain implementations of this across multiple shell syntaxes, I'd rather opt to have things stay like they are now.

**Comment by patrickmaciel** [comment]
@XenGi Hi.
Thanks for sharing your solution for "rbenv".
I try to use your config.fish code, but not work for me.

![image](https://user-images.githubusercontent.com/671670/40425517-f86786d0-5e6e-11e8-818f-5902405edb68.png)

**Comment by XenGi** [comment]
You're screenshot tells you the answer. The `.` command is not supported anymore. I changed it to `source` like the error suggested.

**Comment by kmoschcau** [comment]
@mislav Is keeping this as it is still the current way to go for rbenv or would you be willing to look at a pull request, that would implement the shim reordering for all three shells?

**Comment by mislav** [comment]
@kmoschcau Thanks for offering, but I have no intention of maintaining a PATH reordering implementation for multiple shells! I think potentially ending up with multiple `RBENV_ROOT/shims` entries in one's PATH is acceptable and not worth "fixing".

**Comment by XenGi** [comment]
Just revisited this issue again for bash and similar shells. After a long and interesting journey through shell land I came up with this:

```
export PATH=$(echo $PATH | tr ':' '\n' | tac | uniq -u | tac | paste -s -d':')
```

Another solution would be to use awk:

```
echo $PATH | awk -v RS='[:\n]' '!seen[$0]++'
```

**Comment by shafali03** [comment]
Hi having problem with my path not sure how to fix it
`shaf@5h4f1:/mnt/c/Users/Shaf0/desktop/rubykoans/koans$ ruby path_to_enlightenment.rb
/usr/lib/ruby/vendor_ruby/rbnacl/libsodium/version.rb:5: warning: Insecure world writable dir /home/shaf/.rbenv/shims in PATH, mode 040777
`
