### ISSUE TITLE
mention about zsh-rbenv installation ?

### ISSUE THREAD

**Issue by cswl** [rbenv/rbenv#956]
I have made a zsh plugin, which kinda automates the installation for rbenv.. https://github.com/cswl/zsh-rbenv
Theres also an upgrade command.. which does git pull.. 

Could it be a worth a mention, Iguess probably,  somewhere after
`Zsh note: Modify your ~/.zshrc file instead of ~/.bash_profile.`

Thanks..

**Comment by mislav** [comment]
That's pretty cool. However, I will refrain from linking to an unofficial source for documentation, simply on the matter of principle. Our documentation for installation should be comprehensive and enough for even zsh users to be able to follow easily. There is also [the rbenv-installer project](https://github.com/rbenv/rbenv-installer). If you have ideas how to improve that project for zsh users, please send us a pull request! Thanks for liking rbenv.
