### ISSUE TITLE
Error installing 2.2.2 on Arch (Manjaro)

### ISSUE THREAD

**Issue by askl56** [rbenv/rbenv#961]
Hey all,

Logfile is https://paste2.org/905cGB4h

Other versions have installed fine.

Cheers,

//askl56

**Comment by hsbt** [comment]
Can you try with openssl-1.0 instructions of ruby-build.

https://github.com/rbenv/ruby-build/wiki#openssl-usrincludeopensslasn1_mach102-error-error-this-file-is-obsolete-please-update-your-software

and Please open the same issue to ruby-build repo when next time. Thanks.
