### ISSUE TITLE
DYLD_LIBRARY_PATH not being respected on OS X

### ISSUE THREAD

**Issue by Envek** [rbenv/rbenv#962]
You can't use Rbenv when you're working, for example, with gems that use C libraries via [FFI](https://github.com/ffi/ffi) and need to use libraries located not in standard system library paths.

Real world example: https://github.com/AMekss/archive_io/issues/1

In my case I'm trying to work with custom C library which is built somewhere in my home directory.

## Expected result

Given `libexample.dylib` is the sane C dynamic library which is located in `/Users/anovikov/libexample/bin`, and `libexample` gem is using `FFI::Library` to load `ffi_lib :example`, following snippet should return `OK` (`rbenv version` returns `2.4.0 (set by RBENV_VERSION environment variable)`):

    DYLD_LIBRARY_PATH=/Users/anovikov/libexample/bin ruby -r'libexample' -e "puts 'OK'"

## Actual result

```
/Users/anovikov/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ffi-1.9.17/lib/ffi/library.rb:147:in `block in ffi_lib': Could not open library 'example': dlopen(example, 5): image not found. (LoadError)
Could not open library 'libexample.dylib': dlopen(libexample.dylib, 5): image not found
	from /Users/anovikov/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ffi-1.9.17/lib/ffi/library.rb:100:in `map'
	from /Users/anovikov/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ffi-1.9.17/lib/ffi/library.rb:100:in `ffi_lib'
	from /Users/anovikov/libexample-ruby/lib/libexample.rb:10:in `<module:Libexample>'
```

## Workaround

Call Ruby interpreter or another command directly with `rbenv which` (and it **works**):

    DYLD_LIBRARY_PATH=/Users/anovikov/libexample/bin `rbenv which irb` -r 'libexample'

But unfortunately doesn't work with various execs, for example following **doesn't work**:

    DYLD_LIBRARY_PATH=/Users/anovikov/libexample/bin `rbenv which bundle` exec `rbenv which rake` test

## Notes

This issue isn't relevant for Linux. In Linux command `DYLD_LIBRARY_PATH=/home/anovikov/libexample/bin irb -r'libexample'` actually **works**. Also in Linux there is `ldconfig` exists which makes manipulations with env vars unnecessary.

https://github.com/rbenv/rbenv/pull/597 seems relevant but needs to be reworked for OS X.

**Comment by mislav** [comment]
It's strange that this doesn't work:

```sh
DYLD_LIBRARY_PATH=/Users/anovikov/libexample/bin ruby -r'libexample' -e "puts 'OK'"
```

while this works:

```sh
DYLD_LIBRARY_PATH=/Users/anovikov/libexample/bin `rbenv which irb` -r 'libexample'
```

What do you get if you do this?

```sh
DYLD_LIBRARY_PATH=/Users/anovikov/libexample/bin ruby -e 'p ENV["DYLD_LIBRARY_PATH"]'
```

**Comment by Envek** [comment]
$ DYLD_LIBRARY_PATH=/Users/anovikov/libexample/bin ruby -e 'p ENV["DYLD_LIBRARY_PATH"]'
    nil
    $ DYLD_LIBRARY_PATH=/Users/anovikov/libexample/bin `rbenv which ruby` -e 'p ENV["DYLD_LIBRARY_PATH"]'
    nil

Looks like OS X removes this variable when executing program…

**Comment by mislav** [comment]
```
DYLD_FOO=bar bash -c 'echo $DYLD_FOO'
```

prints nothing. Yes, it seems that macOS removes any `DYLD_*` variables in a subprocess. Therefore, it's not possible to send this variable to ruby through rbenv unless you make an rbenv plugin.

**Comment by Envek** [comment]
Yes, this is restriction, introduced in recent versions of OS X with [SIP](https://developer.apple.com/library/prerelease/ios/documentation/Security/Conceptual/System_Integrity_Protection_Guide/System_Integrity_Protection_Guide.pdf). See https://github.com/yyuu/pyenv-virtualenv/issues/112#issuecomment-155578318 for details.

**Solution is to disable “Debugging Restrictions” of SIP**:

 1. Reboot your system into recovery mode (hold ⌘+R on reboot)
 2. When the “OS X Utilities” screen appears, pull down the ‘Utilities’ menu at the top of the screen instead, and choose “Terminal”
 3. Type the following command into the terminal then hit return:

        csrutil enable --without debug

    This command will partially disable System Integrity Protection, enabling `DYLD_*` variables to be passed to subprocesses.
 4. Then reboot system normally by typing `reboot` and hitting Enter key
 5. `csrutil` status should be as followed:

        System Integrity Protection status: enabled (Custom Configuration).

        Configuration:
        	Apple Internal: disabled
        	Kext Signing: enabled
        	Filesystem Protections: enabled
        	Debugging Restrictions: disabled
        	DTrace Restrictions: enabled
        	NVRAM Protections: enabled
        	BaseSystem Verification: enabled

        This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.

    Note the `Debugging Restrictions: disabled` row.

 6. Then everything works as expected:

        $ DYLD_LIBRARY_PATH=/Users/anovikov/libexample/bin ruby -e 'p ENV["DYLD_LIBRARY_PATH"]'
        "/Users/anovikov/libexample/bin"
        $ DYLD_LIBRARY_PATH=/Users/anovikov/libexample/bin `rbenv which ruby` -e 'p ENV["DYLD_LIBRARY_PATH"]'
        "/Users/anovikov/libexample/bin"

**Comment by mislav** [comment]
Thanks for writing up those instructions!

Another approach would be to make a light rbenv plugin that sets this environment variable before executing `ruby`. With this approach, rebooting or making system changes is not necessary.

**Comment by Envek** [comment]
May be existing [rbenv-vars](https://github.com/rbenv/rbenv-vars) plugin will do the trick?

**Comment by mislav** [comment]
Yes, I see no reason why it shouldn't! I forgot about it being a more general solution to environment variables ;)
