### ISSUE TITLE
rbenv-exec doesn't work

### ISSUE THREAD

**Issue by AlexWayfer** [rbenv/rbenv#963]
Hello!

I read help:

```
$ rbenv exec --help
Usage: rbenv exec <command> [arg1 arg2...]

Runs an executable by first preparing PATH so that the selected Ruby
version's `bin' directory is at the front.

For example, if the currently selected Ruby version is 1.9.3-p327:
  rbenv exec bundle install

is equivalent to:
  PATH="$RBENV_ROOT/versions/1.9.3-p327/bin:$PATH" bundle install
```

I'm trying do this:

```
$ rbenv exec bundle install
rbenv: bundle: command not found
```

That's commands don't help:

```
$ gem install bundle
WARNING:  You don't have /home/alex/.gem/ruby/2.1.0/bin in your PATH,
	  gem executables will not run.
Successfully installed bundle-0.0.1
1 gem installed

$ rbenv exec gem install bundle
WARNING:  You don't have /home/alex/.gem/ruby/2.1.0/bin in your PATH,
	  gem executables will not run.
Successfully installed bundle-0.0.1
```

What's wrong?

`bash`, `zsh` and `fish-shell`.

ArchLinux, `rbenv` installed from AUR.

**Comment by AlexWayfer** [comment]
`rbenv which` also doesn't work:

```
$ rbenv version
2.1.10 (set by /home/alex/.rbenv/version)

$ rbenv which bundle
rbenv: bundle: command not found

$ ls ~/.gem/ruby/2.1.0/bin/
bacon*  bundle*  bundler*
```

**Comment by AlexWayfer** [comment]
Installation from git repo also doesn't help.

**Comment by mislav** [comment]
Let's focus on this first:

```
$ gem install bundle
WARNING:  You don't have /home/alex/.gem/ruby/2.1.0/bin in your PATH,
	  gem executables will not run.
Successfully installed bundle-0.0.1
```

This message says it will install gems into your `~/.gem` folder, which is not the default. This mode of installation is not supported by rbenv. You must have `--user-install` in your `~/.gemrc`. Please take it out.

Then:

1. `gem install bundler` (warning message should not show anymore);
2. `gem which bundle` to check (it should display a valid location now);
3. `bundle install` and you're done. Please don't use `rbenv exec bundle install` unless you know what you're doing. `rbenv exec` is not needed to use directly.

Running `ruby` or `gem` or `bundle` by itself is just fine with rbenv and it will know how to do the correct thing. That's what it's designed for.

**Comment by AlexWayfer** [comment]
Okay, but I already have `--user-install`, and this is my user folder:
```
$ cat ~/.gemrc
gem: --no-rdoc --no-ri --user-install
```

`WARNING` says about bin files (`PATH` variable). I added _all_ directories (all versions) to `PATH`:
```
$ echo $PATH
/home/alex/.gem/ruby/2.4.0/bin /home/alex/.gem/ruby/2.3.0/bin /home/alex/.gem/ruby/2.2.0/bin /home/alex/.gem/ruby/2.1.0/bin ...
```
…and still have an issue.

Then:
1. Yes, message don't show after `PATH` editing.
2. No, still error:
```
$ rbenv which bundle
rbenv: bundle: command not found
```
3. `rbenv exec bundle install` is example in `rbenv exec` help.

**Comment by mislav** [comment]
> You must have `--user-install` in your `~/.gemrc`. Please take it out.

Sorry, I didn't express myself well. I wanted to say that the source of your problems must be that you have `--user-install` in your gemrc, and that **you need to remove that**.

**Comment by AlexWayfer** [comment]
Yes, I saw this in [Arch Wiki](https://wiki.archlinux.org/index.php/Ruby) yesterday. And it kind of helped.

Thank you. And sorry.

I'm closing issue now. I will write if something go wrong again.
