### ISSUE TITLE
Automatic rbenv rehash no longer works

### ISSUE THREAD

**Issue by jhsu802701** [rbenv/rbenv#967]
What does it take to automatically execute "rbenv rehash"?  I now find that gems like rubocop, bundle-audit, brakeman, and rails best practices won't work until I manually enter rbenv rehash.

**Comment by jhsu802701** [comment]
I relied on the rbenv-gem-rehash plugin to automatically execute "rbenv rehash".  However, it's not doing the job anymore, and I see at https://github.com/rbenv/rbenv-gem-rehash that it's been deprecated.  What's the replacement?

**Comment by mislav** [comment]
`rbenv rehash` is only needed after new executables have been added to the `bin/` directory of one of your Ruby versions. Typically, new executables are added after a `gem install`.

rbenv 1.0 shipped with a feature that automatically does `rbenv rehash` after a `gem install`. So, running `rbenv rehash` manually shouldn't ever be necessary anymore.

1. When are you finding that your commands don't work without `rehash`?
2. Which command in particular?
3. Does it happen just after installing anything new?
4. What rbenv version?
5. What currently selected Ruby & RubyGems version?

**Comment by sevenmaxis** [comment]
Hi, I also have problem with rbenv shims
```
bundle gem mygem
  Creating gem 'mygem'...
  ...

rake build
  mygem 0.1.0 built to pkg/mygem-0.1.0.gem.

rake install:local
  mygem 0.1.0 built to pkg/mygem-0.1.0.gem.
  mygem (0.1.0) installed.
```

Also I've tried 
```
gem install pkg/mygem-0.1.0.gem

gem list mygem
  *** LOCAL GEMS ***
  mygem (0.1.0)

gem which mygem
  /Users/megas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/mygem-0.1.0/lib/mygem.rb

rbenv rehash

which mygem
  mygem not found

rbenv shims | grep mygem #=> empty
```

As you can see, the mygem is installed but rbenv didn't create a shim for it.

```
gem env                                                                                                                                                    RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.4
  - RUBY VERSION: 2.5.0 (2017-12-25 patchlevel 0) [x86_64-darwin17]
  - INSTALLATION DIRECTORY: /Users/megas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0
  - USER INSTALLATION DIRECTORY: /Users/megas/.gem/ruby/2.5.0
  - RUBY EXECUTABLE: /Users/megas/.rbenv/versions/2.5.0/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/megas/.rbenv/versions/2.5.0/bin
  - SPEC CACHE DIRECTORY: /Users/megas/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/megas/.rbenv/versions/2.5.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-17
  - GEM PATHS:
     - /Users/megas/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0
     - /Users/megas/.gem/ruby/2.5.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["http://rubygems.org"]
     - :benchmark => false
     - "gem" => "--no-rdoc --no-ri"
  - REMOTE SOURCES:
     - http://rubygems.org
  - SHELL PATH:
     - /Users/megas/.rbenv/versions/2.5.0/bin
     - /usr/local/Cellar/rbenv/1.1.1/libexec
     - /Users/megas/.rbenv/shims
     - /Users/megas/.cargo/bin
     - /usr/local/bin
     - /usr/local/sbin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /opt/X11/bin
     - /Users/megas/.yadr/bin
     - /Users/megas/.yadr/bin/yadr
     - /usr/local/opt/fzf/bin
```

What might be a problem here? Thanks

**Comment by mislav** [comment]
@sevenmaxis Why did you expect your gem to install the `mygem` executable? Did you create an actual executable named `exe/mygem` before running `rake build`?

**Comment by sevenmaxis** [comment]
I didn't create executable in gem, that's was a problem

**Comment by mislav** [comment]
Closing assuming that the original issue is no longer an issue too.

**Comment by snowman** [comment]
For Arch / Manjaro users, please note that the AUR package (https://aur.archlinux.org/packages/rbenv/) does not install the hooks.

Here are steps to install manually:
```bash
$ yay -G rbenv
$ cd rbenv
## Check aur page comments for patch
$ git apply file.patch
$ makepkg -si
```
