### ISSUE TITLE
Permission issues when useing 'rbenv uninstall <version>'

### ISSUE THREAD

**Issue by natanio** [rbenv/rbenv#969]
I'm trying to reinstall ruby 2.2.2, but already had it installed. So I took your advice from past issue to uninstall first (minitest permissions were causing a problem). When I run `rbenv uninstall <version>` I get a lot of the following type output, and not all of the directories are removed.

```
rm: /Users/username/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rmagick-2.15.4/test: Permission denied
rm: /Users/username/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rmagick-2.15.4: Directory not empty
```

Any suggestions? Simply remove the directories manually?

**Comment by mislav** [comment]
You have probably accidentally used `sudo gem install rmagick` or something like that, giving those files root ownership, and are now unable to delete those files from your main user account.

The solution is simple: use `sudo` to delete the whole Ruby installation.

```
rm -rf "$(rbenv prefix 2.2.2)"
```

**Comment by natanio** [comment]
Thanks!
