### ISSUE TITLE
fish: $ rbenv init - Unexpected end of string, square brackets do not match 

### ISSUE THREAD

**Issue by ElijahLynn** [rbenv/rbenv#973]
Ubuntu 14.04 with rbenv 1.1.0-2-g4f8925a and fish 2.4.0.

I run rbenv and get instructions for what to add to my config.fish, good. 

> \# Load rbenv automatically by appending
\# the following to ~/.config/fish/config.fish:
status --is-interactive; and source (rbenv init -|psub)

Appended `status --is-interactive; and source (rbenv init -|psub)` to config.fish and launch new shell and get:

> Unexpected end of string, square brackets do not match
/tmp/user/1000/.psub.tCEVjaYwA0 (line 7):   set -e argv[1]
                                                                     
> from sourcing file /tmp/user/1000/.psub.tCEVjaYwA0
        called on line 11 of file ~/.config/fish/config.fish

> from sourcing file ~/.config/fish/config.fish
        called during startup

>source: Error while reading file “/tmp/user/1000/.psub.tCEVjaYwA0”

update: Using fish 2.4.0

**Comment by ElijahLynn** [comment]
I should note that things mostly work, I can `rbenv install` and see `rbenv versions` and use `rbenv global 2.4.0` etc. But when I do a `ruby --version` I still get the system version so the shim is definitely not taking. 

When I source the output of `rbenv init -` manually I also don't get any errors.

**Comment by ElijahLynn** [comment]
Fixed with https://github.com/fish-shell/fish-shell/pull/3869

**Comment by jasonkarns** [comment]
@ElijahLynn the referenced issue fish-shell/fish-shell#3869 seems to have been closed without any changes. Is this issue here actually resolved?

**Comment by mislav** [comment]
https://github.com/fish-shell/fish-shell/issues/3868#issuecomment-282454984
