### ISSUE TITLE
[FIXED] bash: rbenv: command not found

### ISSUE THREAD

**Issue by aggelosy** [rbenv/rbenv#976]
Just wanted to post this as a solution and not an issue for what the title says.

Just copy paste these commands as they are in a new Terminal.

`cd ~`
`rm -rf .rbenv/`
`git clone git://github.com/sstephenson/rbenv.git .rbenv`
`echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc`
`echo 'eval "$(rbenv init -)"' >> ~/.bashrc`
`git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build`
`source ~/.bashrc`

What it does is basically removes the existing directory for **rbenv**, and reinstalls it.

Thank You.

**Comment by rezapci** [comment]
not i still have the same problem

**Comment by mattiesansev** [comment]
Thank you!

**Comment by dartion5** [comment]
Works well! Thank you!

**Comment by Alie-Ammaar** [comment]
Thanks !!

**Comment by erikrtn** [comment]
This fixed the issue, thank you!

**Comment by JoKurio** [comment]
Thank you so much for this, it helped me resolve the issue.

**Comment by norman123123** [comment]
Thanks! It seemed to have worked for me too.

**Comment by notprogrammer** [comment]
Thanks you. This solution worked for me.

**Comment by nzerobe** [comment]
```
User@Nze MINGW64 ~
$ rm -rf .rbenv/

User@Nze MINGW64 ~
$ git clone git://github.com/sstephenson/rbenv.git .rbenv
Cloning into '.rbenv'...
remote: Enumerating objects: 2759, done.
remote: Total 2759 (delta 0), reused 0 (delta 0), pack-reused 2759
Receiving objects: 100% (2759/2759), 526.02 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1731/1731), done.

User@Nze MINGW64 ~
$ echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc

User@Nze MINGW64 ~
$ echo 'eval "$(rbenv init -)"' >> ~/.bashrc

User@Nze MINGW64 ~
$ git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
Cloning into 'C:/Users/User/.rbenv/plugins/ruby-build'...

remote: Enumerating objects: 48, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 9760 (delta 17), reused 37 (delta 12), pack-reused 9712
Receiving objects: 100% (9760/9760), 2.08 MiB | 6.00 KiB/s, done.
Resolving deltas: 100% (6343/6343), done.

User@Nze MINGW64 ~
$ source ~/.bashrc
/c/Users/User/.rbenv/bin/rbenv: line 1: ../libexec/rbenv: No such file or directory

User@Nze MINGW64 ~
$ rbenv install 2.4.0
/c/Users/User/.rbenv/bin/rbenv: line 1: ../libexec/rbenv: No such file or directory

User@Nze MINGW64 ~
$ rbenv install
/c/Users/User/.rbenv/bin/rbenv: line 1: ../libexec/rbenv: No such file or directory

`


User@Nze MINGW64 ~
$ rbenv global 2.3.0
/c/Users/User/.rbenv/bin/rbenv: line 1: ../libexec/rbenv: No such file or directory

User@Nze MINGW64 ~```

**Comment by EYITAY** [comment]
Fixed! Thank You! @aggelosy

**Comment by JoKurio** [comment]
You're welcome

**Comment by aecordova** [comment]
I also had this problem, followed the steps and worked, I just had to change .bashrc to .zshrc

**Comment by codemicky** [comment]
Thank you @aggelosy  👍

**Comment by aggelosy** [comment]
> 
> 
> ```
> User@Nze MINGW64 ~
> $ rm -rf .rbenv/
> 
> User@Nze MINGW64 ~
> $ git clone git://github.com/sstephenson/rbenv.git .rbenv
> Cloning into '.rbenv'...
> remote: Enumerating objects: 2759, done.
> remote: Total 2759 (delta 0), reused 0 (delta 0), pack-reused 2759
> Receiving objects: 100% (2759/2759), 526.02 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (1731/1731), done.
> 
> User@Nze MINGW64 ~
> $ echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
> 
> User@Nze MINGW64 ~
> $ echo 'eval "$(rbenv init -)"' >> ~/.bashrc
> 
> User@Nze MINGW64 ~
> $ git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
> Cloning into 'C:/Users/User/.rbenv/plugins/ruby-build'...
> 
> remote: Enumerating objects: 48, done.
> remote: Counting objects: 100% (48/48), done.
> remote: Compressing objects: 100% (30/30), done.
> remote: Total 9760 (delta 17), reused 37 (delta 12), pack-reused 9712
> Receiving objects: 100% (9760/9760), 2.08 MiB | 6.00 KiB/s, done.
> Resolving deltas: 100% (6343/6343), done.
> 
> User@Nze MINGW64 ~
> $ source ~/.bashrc
> /c/Users/User/.rbenv/bin/rbenv: line 1: ../libexec/rbenv: No such file or directory
> 
> User@Nze MINGW64 ~
> $ rbenv install 2.4.0
> /c/Users/User/.rbenv/bin/rbenv: line 1: ../libexec/rbenv: No such file or directory
> 
> User@Nze MINGW64 ~
> $ rbenv install
> /c/Users/User/.rbenv/bin/rbenv: line 1: ../libexec/rbenv: No such file or directory
> 
> `
> 
> 
> User@Nze MINGW64 ~
> $ rbenv global 2.3.0
> /c/Users/User/.rbenv/bin/rbenv: line 1: ../libexec/rbenv: No such file or directory
> 
> User@Nze MINGW64 ~```
> ```

I think you need to check your directories and change them in the files, since you are using an emulator in Windows 10, correct?

**Comment by sy9612** [comment]
fixed!! thank you!!!

**Comment by MBA22** [comment]
Thanks @aggelosy, you saved my life 👍

**Comment by ahamzamushtaq** [comment]
its Awesome
