### ISSUE TITLE
Cannot install rbx-2.4.0 because of llvm35 not found in brew (El Capitan)

### ISSUE THREAD

**Issue by fredbaa** [rbenv/rbenv#978]
> ERROR: Rubinius will not be able to compile using Apple's LLVM-based
> build tools on OS X. You will need to install LLVM 3.5 first.
> 
> TO FIX THE PROBLEM: Install Homebrew's llvm package with this
> command: brew tap homebrew/versions ; brew install llvm35
> 
> BUILD FAILED (OS X 10.11.6 using ruby-build 20150818)

But when I try to install llvm35, it seems to be deleted in brew.

Any ideas how to resolve this?

**Comment by gazayas** [comment]
Same issue here

**Comment by hsbt** [comment]
> Any ideas

No ideas. rbx-2 series are already EOL status.

Maybe, You can submit pull request for reverting to remove llvm35 formula on homebrew.

**Comment by hsbt** [comment]
This is not an issue of rbenv. We can not control homebrew and macOS environment.
