### ISSUE TITLE
Plugins path is hardcoded

### ISSUE THREAD

**Issue by anandtrex** [rbenv/rbenv#979]
Plugins are not loaded if rbenv is installed in a path other than `~/.rbenv`.
For example if I do

    git clone https://github.com/rbenv/rbenv.git /var/rbenv
    git clone https://github.com/rbenv/ruby-build.git /var/rbenv/plugins/ruby-build

and then try to run

    rbenv install

I get the error

    rbenv: no such command `install'

**Comment by marksull** [comment]
export RBENV_ROOT=/var/rbenv

**Comment by mislav** [comment]
@marksull is right. Plugins, Ruby versions, etc. are loaded from `RBENV_ROOT`, which is at `~/.rbenv` by default it. You can set it to anything else by changing the environment variable.
