### ISSUE TITLE
error in readme - guide ?

### ISSUE THREAD

**Issue by rogomantik** [rbenv/rbenv#984]
point 2. Add ~/.rbenv/bin to your $PATH for access to the rbenv command-line utility.
this line
$ echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
should be
$ echo 'export PATH="$HOME/.rbenv/**shims**:$PATH"' >> ~/.bash_profile

?

because i didnt get correct folders when run
gem env

**Comment by dgutov** [comment]
The guide is correct. You're probably missing the `eval "$(rbenv init -)"` call.

**Comment by mislav** [comment]
Yes, you're probably missed this step:

> 3\. Run `~/.rbenv/bin/rbenv init` for shell-specific instructions on how to initialize rbenv to enable shims and autocompletion.
