### ISSUE TITLE
Unable to install any gem - SSL issue

### ISSUE THREAD

**Issue by vkyt** [rbenv/rbenv#988]
I'm on Ubuntu 12.04 and have used linuxbrew to install rbenv.
Installed ruby 2.4.1 but couldn't get any of the gem to install due to the following error:
Unable to pull data from 'https://rubygems.org/':  SSL_CTX_set_ecdh_auto

Tried uninstalling and reinstall ruby 2.4.1 with 
`CONFIGURE_OPTS="--with-opessl-dir=home/.linuxbrew/bin/openssl" rbenv install 2.4.1` 
But no luck, the error message changes to: 
` Unable to pull data from 'https://rubygems.org/': SSL_CTX_set_ecdh_auto: cert already in hash table`

Followed the SSL update guide from RubyGems.org but that didn't help either. My gem version is already the latest - 2.6.11

System Setup: 
`which rbenv `
'home/.linuxbrew/bin/rbenv'
`which openssl `
'home/.linuxbrew/bin/openssl'
`ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'`
OpenSSL 1.0.2k  26 Jan 2017
`ruby -ropenssl -e 'p OpenSSL::X509::DEFAULT_CERT_FILE'`
"/usr/lib/ssl/cert.pem"

Any help is greatly appreciated!

**Comment by jarrettj** [comment]
Same here.

**Comment by mislav** [comment]
It looks like you're having problems with ruby-build, which is the plugin that provides `rbenv-install`.

1. First, [ensure that ruby-build](https://github.com/rbenv/ruby-build/wiki#updating-ruby-build) is updated to the latest version.
2. If your problem persists, [check existing issues](https://github.com/sstephenson/ruby-build/issues) in the ruby-build repo and open a new one if necessary. When opening a new issue, please attach the full build log.
