### ISSUE TITLE
Bundler ignores rbenv env for gems

### ISSUE THREAD

**Issue by nonkor** [rbenv/rbenv#991]
Bundler inside rbenv tries to install gems into system root, but should install into [.rbenv env home](https://github.com/rbenv/rbenv#installing-ruby-gems) :
```
$ bundle
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..

Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.

  Password:
```
To confirm using of the system location after the installation:
```
$ bundle show fastlane
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.26.1

$ gem which fastlane
ERROR:  Can't find ruby library file or shared library fastlane
```

Btw, classic `gem install` works perfectly fine:
```
$ gem install byebug
Fetching: byebug-9.0.6.gem (100%)
Building native extensions.  This could take a while...
Successfully installed byebug-9.0.6
Parsing documentation for byebug-9.0.6
Installing ri documentation for byebug-9.0.6
Done installing documentation for byebug after 15 seconds
1 gem installed

$ gem which byebug
~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/byebug-9.0.6/lib/byebug.rb
```
`rbenv rehash` didn't help. Additional info:
```
$ rbenv versions
  system
* 2.3.1 (set by ~/<project>/.ruby-version)

$ cat .ruby-version
2.3.1

$ gem env home
~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0

$ tail -1 ~/.bash_profile
eval "$(rbenv init -)"

$ brew info rbenv
rbenv: stable 1.1.0 (bottled), HEAD
Ruby version manager
https://github.com/rbenv/rbenv#readme
/usr/local/Cellar/rbenv/1.1.0 (36 files, 63.2KB) *
  Poured from bottle on 2017-05-03 at 17:04:50
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/rbenv.rb
==> Dependencies
Recommended: ruby-build ✔
==> Options
--without-ruby-build
	Build without ruby-build support
--HEAD
	Install HEAD version

echo $PATH
~/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:~/bin:~/Library/Android/sdk/platform-tools:~/Library/Android/sdk/tools:~/Library/Android/sdk/tools/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin
```

I am not quite sure either this is the `rbenv` issue or the `bundler` one. But I suppose `bundler` should not care about specific rubyenv tools and work from the box with any of a ruby management system.

**Comment by nonkor** [comment]
I've deleted system `bundler` and install local one linked to custom ruby from rbenv:
```
$ cd <project>
$ gem install bundler
...
1 gem installed
$ gem which bundler
~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler.rb
```
but
```
$bundle
/Library/Ruby/Site/2.0.0/rubygems.rb:271:in `find_spec_for_exe': can't find gem bundler (>= 0.a) (Gem::GemNotFoundException)
	from /Library/Ruby/Site/2.0.0/rubygems.rb:299:in `activate_bin_path'
	from /usr/local/bin/bundle:23:in `<main>'
```
So, even if a gem is installed into a proper dir, bundler does not see it there.

**Comment by mislav** [comment]
@nonkor You were on the right track by installing bundler gem in the current Ruby version. `gem which bundler` shows that you've done it corretly. However, I'm not sure why `bundle` still goes to `/usr/local/bin/bundle` (which should not exist, and you should uninstall it) and not to `~/.rbenv/shims/bundle`. Perhaps you need to `rbenv rehash` so that `~/.rbenv/shims/bundle` can appear?

**Comment by nonkor** [comment]
hey @mislav 
Today I've played a bit with `.bash_profile`. I added `export PATH=$PATH:$HOME/.rbenv/shims` despite the fact `$PATH` already refers to shims. Magically, It helped. But even after deletion that line and restarting OS it works as expected now. Honestly speaking, right now I cannot reproduce the issue, so, I assume we can close it.
Thanks for your reaction!

**Comment by mislav** [comment]
If you have a line that looks like `eval ... rbenv init` in your `~/.bash_profile` (as per rbenv install instructions), you don't need to manually add the `shims/` directory to the PATH. But I'm glad you solved it!

Please close your own issues when they are not an issue anymore. 😉
