### ISSUE TITLE
Install ruby 2.3.4 issue with openssl

### ISSUE THREAD

**Issue by gerardogc2378** [rbenv/rbenv#994]
Hi guys, I have a problem while install ruby 2.3.4 on Arch Linux this is my full output:

https://pastebin.com/DExtUSu3

Thanks beforehand.

**Comment by ernetas** [comment]
I'm having the same issue with 2.3.3, 2.3.4 and 2.4.1.

**Comment by ernetas** [comment]
This seems to be related to: https://github.com/rbenv/ruby-build/issues/1048

**Comment by hsbt** [comment]
Ruby 2.3 is not supported openssl-1.1.0 in Arch Linux. You need to upgrade your ruby version to Ruby 2.4.

@ernetas Can you show me a log of build failure with Ruby 2.4.1?

**Comment by rhenium** [comment]
On Arch Linux extra/openssl-1.0 (which is OpenSSL 1.0.2, and can be installed simultaneously with core/openssl that is 1.1.0) can be used. I have added an entry to the wiki of rbenv/ruby-build:

https://github.com/rbenv/ruby-build/wiki#openssl-usrincludeopensslasn1_mach102-error-error-this-file-is-obsolete-please-update-your-software

**Comment by hsbt** [comment]
@rhenium Thanks a lot!
