### ISSUE TITLE
Error when installing gem with native extension

### ISSUE THREAD

**Issue by betogrun** [rbenv/rbenv#995]
Hi,

I'm trying to install the Rdmtx gem. But it seems that rbenv is not working properly.

```
$ gem install Rdmtx -v '0.2.2'
Building native extensions.  This could take a while...
ERROR:  Error installing Rdmtx:
	ERROR: Failed to build gem native extension.

    /Users/alberto/.rbenv/versions/2.2.5/bin/ruby -r ./siteconf20170508-70874-93ho0q.rb extconf.rb
checking for main() in -ldmtx... no
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling Rdmtx.c
Rdmtx.c:26:10: fatal error: 'dmtx.h' file not found
#include <dmtx.h>
         ^
1 error generated.
make: *** [Rdmtx.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/alberto/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/Rdmtx-0.2.2 for inspection.
Results logged to /Users/alberto/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-16/2.2.0-static/Rdmtx-0.2.2/gem_make.out
```
PS: I have already installed the gem dependence (libdmtx)  via brew but the issue remais.

Regards

**Comment by mislav** [comment]
rbenv doesn't really have to do anything with installing gems with native extensions. If you already have libdmtx installed, this can either be a case of the gem's own build system being broken, or the fact that the gem's build system can't discover the location of the library on disk.

Perhaps the gem supports a build option such as `--with-libdmtx-dir=...` or something? In any case, I can't see how this is a problem with rbenv, which only acts as a Ruby version switcher.

**Comment by betogrun** [comment]
That's right, for some reason I need to specify the path where the lib is installed:
`gem install Rdmtx -v '0.2.2' -- --with-opt-include="/usr/local/include"` did the trick.

Thanks @mislav
