### ISSUE TITLE
Ruby 2.1.0, 2.4.1, and 2.5.0-dev fail to install

### ISSUE THREAD

**Issue by ron-wolf** [rbenv/rbenv#996]
The builder encounters errors with C libraries on my system. I tried it with a couple other versions as well, but I didn’t want to clutter up this page too much. Possible culprits are my install of OS X + Xcode, both of which are in beta and have their libraries linked to `/usr/local/include`; or my compiler, which seems to be having trouble with every `*.h`. In any case, probably not `rbenv`’s fault, but tips on how to work around this would be a huge help regardless.

### Ruby 2.1.0 [(log file)](https://github.com/rbenv/rbenv/files/987359/ruby-build.20170509124901.61739.log.txt)
```
$ rbenv install 2.1.0
ruby-build: use libyaml from homebrew
ruby-build: use openssl from homebrew
Downloading ruby-2.1.0.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.0.tar.bz2
Installing ruby-2.1.0...

WARNING: ruby-2.1.0 is nearing its end of life.
It only receives critical security updates, no bug fixes.

ruby-build: use readline from homebrew

BUILD FAILED (OS X 10.12.5 using ruby-build 20170322)

Inspect or clean up the working tree at /var/folders/0_/[…]/T/ruby-build.20170509123914.55379
Results logged to /var/folders/0_/[…]/T/ruby-build.20170509123914.55379.log

Last 10 log lines:
inline static VALUE \
                    ^
<scratch space>:2:1: note: expanded from here
m_sqrt_bang
^
2 errors generated.
Makefile:333: recipe for target 'bignum.o' failed
make: *** [bignum.o] Error 1
make: *** Waiting for unfinished jobs....
13 warnings generated.
```

### Ruby 2.4.1 [(log file)](https://github.com/rbenv/rbenv/files/987314/ruby-build.20170509122305.41091.log.txt)
```
$ rbenv install 2.4.1
ruby-build: use openssl from homebrew
Downloading ruby-2.4.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.1.tar.bz2
Installing ruby-2.4.1...
ruby-build: use readline from homebrew

BUILD FAILED (OS X 10.12.5 using ruby-build 20170322)

Inspect or clean up the working tree at /var/folders/0_/[…]/T/ruby-build.20170509121540.32861
Results logged to /var/folders/0_/[…]/T/ruby-build.20170509121540.32861.log

Last 10 log lines:
#define FP_QNAN         FP_NAN
                        ^
/usr/local/include/math.h:74:25: note: expanded from macro 'FP_NAN'
#define FP_NAN          1
                        ^
compiling compile.c
2 errors generated.
Makefile:364: recipe for target 'bignum.o' failed
make: *** [bignum.o] Error 1
make: *** Waiting for unfinished jobs....
```

### Ruby 2.5.0 [(log file)](https://github.com/rbenv/rbenv/files/987318/ruby-build.20170509123201.48245.log.txt)
```
$ rbenv install 2.5.0-dev
ruby-build: use openssl from homebrew
Cloning https://github.com/ruby/ruby.git...
Installing ruby-trunk...
ruby-build: use readline from homebrew

BUILD FAILED (OS X 10.12.5 using ruby-build 20170322)

Inspect or clean up the working tree at /var/folders/0_/[…]/T/ruby-build.20170509121003.22370
Results logged to /var/folders/0_/[…]/T/ruby-build.20170509121003.22370.log

Last 10 log lines:
./include/ruby/ruby.h:2180:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/ruby/ruby.h:2176:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
8 errors generated.
Makefile:370: recipe for target 'marshal.o' failed
make: *** [marshal.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by Ogromny** [comment]
Bizarre, for me it works
```sh
ruby-build: use openssl from homebrew
Cloning https://github.com/ruby/ruby.git...
Installing ruby-trunk...
ruby-build: use readline from homebrew
Installed ruby-trunk to /Users/ogromny/.rbenv/versions/2.5.0-dev
```

**Comment by ron-wolf** [comment]
I reinstalled `rbenv`, it still doesn’t work. I’m using Homebrew.

**Comment by jeremy** [comment]
The last 10 log lines aren't much to go on. Could you link the full failing build logs?
```
Results logged to /var/folders/0_/[…]/T/ruby-build.20170509121003.22370.log
```
^ that file

**Comment by jeremy** [comment]
> and have their libraries linked to /usr/local/include

Looks like this is your issue. Guessing you have symlinks pointing to a different SDK than you expect.

I'm on the same betas and building fine.

**Comment by vrybas** [comment]
@ron-wolf can be closed?

**Comment by plentz** [comment]
@vrybas I think that this is a yes :)

**Comment by Anonymos004** [comment]
rbenv install 2.5.1
Downloading ruby-2.5.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.1.tar.bz2
Installing ruby-2.5.1...

WARNING: ruby-2.5.1 is nearing its end of life.
It only receives critical security updates, no bug fixes.


BUILD FAILED (Ubuntu 20.04 using ruby-build 20201225-2-g5de6d5f)

Inspect or clean up the working tree at /tmp/ruby-build.20201225215739.1570.oaD55G
Results logged to /tmp/ruby-build.20201225215739.1570.log

Last 10 log lines:
checking for ruby... false
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/tmp/ruby-build.20201225215739.1570.oaD55G/ruby-2.5.1':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
