### ISSUE TITLE
WARN: Unresolved specs during Gem::Specification.reset:   rb-inotify (>= 0.9.7, ~> 0.9)

### ISSUE THREAD

**Issue by smilevera** [rbenv/rbenv#997]
When I was trying to activate the jekyll server to monitor my github website at localhost, I key in jekyll serve and encountered this problem. Then I failed to activated the server.
![2017-05-11 6 32 50](https://cloud.githubusercontent.com/assets/24243865/25945110/56c246f4-3678-11e7-8af9-3b7eb1bbd779.png)

**Comment by hsbt** [comment]
It's not an issue of rbenv. It caused by jekyll or bundler.

Please report their repositories. Thanks.
